### ISSUE TITLE
Compile successfully but no katago file fould

### ISSUE THREAD

**Issue by KhiemDuyNguyen** [lightvector/KataGo#101]
![Screenshot from 2020-01-14 16-30-06](https://user-images.githubusercontent.com/37052526/72388397-710b4580-36eb-11ea-9a89-9f160dff505f.png)

Can anyone help me with this? Thank you.

**Comment by KhiemDuyNguyen** [comment]
![Screenshot from 2020-01-14 17-06-45](https://user-images.githubusercontent.com/37052526/72390417-4b346f80-36f0-11ea-9138-d8fca04213ce.png)

**Comment by lightvector** [comment]
Did you forget to run "make" after running "cmake <various arguments>"?

**Comment by KhiemDuyNguyen** [comment]
Yes I did forget it, sorry for stupid question.

**Comment by lightvector** [comment]
Okay, cool, no worries. :)
If you have any more questions, just ask. Once you get it working, please close this issue. Thanks!
