### ISSUE TITLE
katago 1.3 made the vedio card eject error.

### ISSUE THREAD

**Issue by l1t1** [lightvector/KataGo#102]
i run a test using following command, but only one game played, then my monitor became balck, but the computer still running, i use mstsc  visit the machine, and found my vedio card reports an error, 
i set maxVisits = 100
in D:\gtp_example.cfg
```
D:\tool\go_gui\gogui-twogtp -white "D:\KataGo13\katago gtp -model D:\KataGo13\g170e.gz -config D:\gtp_example.cfg" -black "D:\sai\sai --gtp -w D:\sai\sai240.gz --noponder -v 800"  -games 20 -sgffile katago170e_sai240 -auto -komi 7.5
```
btw when i set maxVisits = 1600 yesterday, all 20 games palyed without error

**Comment by l1t1** [comment]
my work command at https://github.com/sai-dev/sai/issues/98
and the error info
![2020-01-15_135333](https://user-images.githubusercontent.com/23301704/72409331-62329a80-37a0-11ea-9c71-6c5428038168.png)

**Comment by l1t1** [comment]
windows event shows related with sai, closed
日志名称:          Application
来源:            Application Error
日期:            2020/1/15 13:51:36
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           PC
描述:
错误应用程序名称: sai.exe，版本: 0.0.0.0，时间戳: 0x5e021b39
错误模块名称: ucrtbase.DLL，版本: 10.0.14393.2990，时间戳: 0x5caeb96f
异常代码: 0x40000015
错误偏移量: 0x000000000006e01f
错误进程 ID: 0x10f4
错误应用程序启动时间: 0x01d5cb6760d2cf2d
错误应用程序路径: D:\sai\sai.exe
错误模块路径: C:\Windows\system32\ucrtbase.DLL
报告 ID: 16e63a5a-375b-11ea-ade7-70208405d212
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-01-15T05:51:36.000000000Z" />
    <EventRecordID>1088170</EventRecordID>
    <Channel>Application</Channel>
    <Computer>PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>sai.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>5e021b39</Data>
    <Data>ucrtbase.DLL</Data>
    <Data>10.0.14393.2990</Data>
    <Data>5caeb96f</Data>
    <Data>40000015</Data>
    <Data>000000000006e01f</Data>
    <Data>10f4</Data>
    <Data>01d5cb6760d2cf2d</Data>
    <Data>D:\sai\sai.exe</Data>
    <Data>C:\Windows\system32\ucrtbase.DLL</Data>
    <Data>16e63a5a-375b-11ea-ade7-70208405d212</Data>
  </EventData>
</Event>

**Comment by lightvector** [comment]
I'm guessing that your video card driver is unstable somehow, or its prone to overheating, or something. It might not have anything to do with either SAI or KataGo, except for the fact that maybe they use it intensely and cause the driver to display the instability.

**Comment by l1t1** [comment]
but, how to explain that  after i reboot the computer, the match can play a game, then same problem occurs?

**Comment by lightvector** [comment]
I don't know. Maybe your video card driver is buggy and gets into a bad state, which is fixed by rebooting.

**Comment by l1t1** [comment]
> I don't know. Maybe your video card driver is buggy and gets into a bad state, which is fixed by rebooting.

could you get something useful from the gtp.log?
[gtp.zip](https://github.com/lightvector/KataGo/files/4075484/gtp.zip)

**Comment by lightvector** [comment]
No, nothing interesting.

**Comment by lightvector** [comment]
You can try updating your drivers. If it's due to overheating (this would explain why it would reliably work and then reliably fail later, most kinds of errors would make it not work at all even at the start) then you might configuring both bots to run at a lower intensity and much slower (lower threads and everything) and seeing if that helps.

**Comment by l1t1** [comment]
use default gtp_example.cfg and sai -v 4800, works as so far
```
D:\tool\go_gui\gogui-twogtp -white "D:\KataGo131\katago gtp -model D:\KataGo13\g170e.gz -config D:\KataGo131\gtp_example.cfg" -black "D:\sai\sai --gtp -w D:\sai\sai240.gz --noponder -v 4800 -l sai.log"  -games 2 -sgffile katago170e_sai240 -auto -komi 7.5
```

**Comment by l1t1** [comment]
video card crashed again , the computer slowed down before it occured.
```
D:\tool\go_gui>D:\tool\go_gui\gogui-twogtp -white "D:\KataGo131\katago gtp -model D:\KataGo13\g170e.gz -config D:\KataGo131\gtp_example.cfg" -black "D:\tool\lee
la15\leelaz --gtp -w D:\tool\leela15\lz250.gz --noponder -v 1600 -l sai.log"  -games 2 -sgffile katago170e_lz250 -auto -komi 7.5
White program died
```
White program died <--katago

sgf
```
(;FF[4]CA[UTF-8]AP[gogui-twogtp:1.4.9]
KM[7.5]PB[Leela Zero]PW[KataGo]DT[2020-01-19]
C[Black command: D:\\tool\\leela15\\leelaz --gtp -w D:\\tool\\leela15\\lz250.gz --noponder -v 1600 -l sai.log
White command: D:\\KataGo131\\katago gtp -model D:\\KataGo13\\g170e.gz -config D:\\KataGo131\\gtp_example.cfg
Black version: 0.17
White version: 1.3.1
Result[Black\]: W+6.5
Result[White\]: ?
Host: PC
Date: January 19, 2020 10:46:04 AM CST]
;B[dp];W[dd];B[cc];W[dc];B[cd];W[de];B[bf];W[qd];B[pp])
```

**Comment by lightvector** [comment]
Unfortunately, I'm still not sure there's anything for KataGo to do here. This seems to me to be some sort of instability in your GPU drivers or your hardware when it comes under heavy load, maybe KataGo triggers more than it due to the particular architecture of the neural net that it tries to run. Sorry about that!

If you have more information about the error or you find workarounds, or you find someone technically-skilled to help you debug in-person and they find a bug, feel free to reply back, and I can reopen and see what I can do.
