### ISSUE TITLE
Max moves in analysis

### ISSUE THREAD

**Issue by TFiFiE** [lightvector/KataGo#103]
Could you add an argument to `lz-analyze` and `kata-analyze` that caps the number of moves for which stats are shown?

**Comment by lightvector** [comment]
This seems like it would be a very frontend/UI-side option. Shouldn't such
an option be a feature request for the relevant front-end program (Lizzie,
GoReviewPartner, Sabaki, etc) that is missing such an option, rather than a
feature request for KataGo? It seems to me that adding an argument to these
GTP extensions to do this might already require individual changes those
user-facing tools anyways, to make use of the new argument.

**Comment by TFiFiE** [comment]
I just want to be able to get a quick, succinct running evaluation of a position without needing a front end.

**Comment by lightvector** [comment]
What if it was a config option?

**Comment by TFiFiE** [comment]
Wouldn't it be weird then to have the minimum and maximum be set in different ways?

**Comment by lightvector** [comment]
Oh, I see what you're getting at. Yeah, I forgot there's already a
"minmoves" argument.

Are they actually the minimum and maximum of the same thing though? Mostly
I implemented minmoves for bare compatibility - in Leela Zero does it
actually also simply display 0-visit moves if you ask for too many and not
affect the search, or does it actually affect the search and cause it to
try to explore the minimum number of moves requested by some minimal amount?

And similarly if I were to implement a "maxmoves" argument in KataGo, is
your intent that it would affect only the display, or that it would affect
the search itself by preventing any further exploration of new moves if the
maxmoves value was hit?

It would be strange if one of "minmoves" had or was intended to have an
effect on the search but the other was purely display.

Also, should I really be dictating new arguments to add to lz-analyze? My
inclination if adding it would be to add it to kata-analyze alone, and add
it to lz-analyze if and only if Leela Zero added it to lz-analyze.

Thanks!

**Comment by lightvector** [comment]
Anyways, whatever. I went ahead and just added it. Out as part of [v1.3.1 release](https://github.com/lightvector/KataGo/releases/tag/v1.3.1)
:)

**Comment by lightvector** [comment]
Documented here, `maxmoves`: https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md
