### ISSUE TITLE
suggest to start katago without config file

### ISSUE THREAD

**Issue by l1t1** [lightvector/KataGo#104]
now it cannot run as
```
C:\katago131>katago gtp -model ..\g170e.txt.gz
PARSE ERROR:
             Required argument missing: config

Brief USAGE:
   gtp  [-override-version <VERSION>] -model <FILE> -config <FILE> [--]
        [-version] [-h]

For complete USAGE and HELP type:
   gtp -help
```
it must run as
```
C:\katago131>katago gtp -model ..\g170e.txt.gz -config gtp_example.cfg
KataGo v1.3.1
Using OpenCL Device 0: Intel(R) HD Graphics 4400 (Intel(R) Corporation) OpenCL 1.2
Loaded tuning parameters from: ./KataGoData/opencltuning/tune_gpuIntelRHDGraphics4400_x19_y19_c128_mv8.txt
Loaded model ..\g170e.txt.gz
GTP ready, beginning main protocol loop
genmove b
= Q4
```
as you wrote in the release note,

>your GTP config - defaults are built into KataGo directly and you can just use those directly 
could you just omit it in future release?

**Comment by lightvector** [comment]
I'm not planning to make the config possible to completely omit, since there are many parameters that are currently genuinely the user's choice and not easily settable to defaults (for example, what rules to use, or how many visits to cap to, or which GPUs to use, etc). Perhaps in the future more can be automated, but not right now.

**Comment by lightvector** [comment]
And just in case you misread the release notes - the release did NOT say that you could completely omit the config. It simply said that you could delete a large number of parameters from the config (everything from the `Root move selection and biases` section and all sections below it too).
