### ISSUE TITLE
Does the results of kata-analyze always had been sorted?

### ISSUE THREAD

**Issue by yzyray** [lightvector/KataGo#105]
I noticed there is "order" in kata-analyze output format,when i using pipeline communication get these output infos ,it needs to be sorted by "order" or already had been sorted ? 
As i noticed, it had been sorted,but not for sure.

**Comment by lightvector** [comment]
It is always sorted in KataGo currently, but I would say that any users should NOT rely on it - it is NOT absolutely promised by the protocol.

KataGo is simply mirroring lz-analyze's semantics, which I found actually not too long ago that these originally derive from https://github.com/SabakiHQ/Sabaki/blob/84815c94250b95f20b2fefad837ebbb2f393f665/docs/guides/engine-analysis-integration.md

(with the lz- and kata- prefixes indicating that these extend the original Sabaki extension command with a few more fields).

**Comment by yzyray** [comment]
> It is always sorted in KataGo currently, but I would say that any users should NOT rely on it - it is NOT absolutely promised by the protocol.
> 
> KataGo is simply mirroring lz-analyze's semantics, which I found actually not too long ago that these originally derive from https://github.com/SabakiHQ/Sabaki/blob/84815c94250b95f20b2fefad837ebbb2f393f665/docs/guides/engine-analysis-integration.md
> With the lz- and kata- prefixes indicating that these extend the original Sabaki extension command with a few more fields. The original command semantics does not appear to promise anything about the sorting either.

Thank you!I'll sort results by order in my GUI.

**Comment by lightvector** [comment]
Closing. Feel free to reply back if you have other quetions.
