### ISSUE TITLE
About kata-genmove_analyze

### ISSUE THREAD

**Issue by fangzhch74** [lightvector/KataGo#107]
I've tried new command kata-genmove_analyze in ver1.3.1
Why play Q16 instead of Q4 of order 0?
Is there any relationship between play position and info move lines?

Thank you.

kata-genmove_analyze
=
info move Q4 visits 116 utility -0.115235 winrate 0.443583 scoreMean -0.734005 scoreStdev 22.8435 scoreLead -0.734005 scoreSelfplay -0.95698 prior 0.214653 lcb 0.439767 utilityLcb -0.12592 order 0 pv Q4 Q16 R17 Q17 R16 R14 R15 Q15 S14 C17 info move Q16 visits 79 utility -0.116342 winrate 0.442886 scoreMean -0.735952 scoreStdev 22.762 scoreLead -0.735952 scoreSelfplay -0.921316 prior 0.203945 lcb 0.439294 utilityLcb -0.126399 order 1 pv Q16 Q4 C3 D3 C4 C6 C5 D5 B6 C17 info move Q3 visits 41 utility -0.130945 winrate 0.43665 scoreMean -0.852465 scoreStdev 22.8339 scoreLead -0.852465 scoreSelfplay -1.18262 prior 0.101664 lcb 0.429884 utilityLcb -0.14989 order 2 pv Q3 Q16 R6 C17 C16 D17 F17 info move R16 visits 40 utility -0.128352 winrate 0.437739 scoreMean -0.810398 scoreStdev 22.7794 scoreLead -0.810398 scoreSelfplay -1.13127 prior 0.0909118 lcb 0.431248 utilityLcb -0.146525 order 3 pv R16 Q4 P16 C17 C16 D17 info move R4 visits 32 utility -0.133959 winrate 0.435284 scoreMean -0.844459 scoreStdev 22.8771 scoreLead -0.844459 scoreSelfplay -1.21824 prior 0.0829205 lcb 0.427023 utilityLcb -0.157092 order 4 pv R4 Q16 O3 C17 D17 C16 C14 info move Q17 visits 31 utility -0.128607 winrate 0.437638 scoreMean -0.814625 scoreStdev 22.7224 scoreLead -0.814625 scoreSelfplay -1.13756 prior 0.0736137 lcb 0.429114 utilityLcb -0.152473 order 5 pv Q17 Q4 R14 C17 C16 D17 info move C3 visits 7 utility -0.152235 winrate 0.427001 scoreMean -1.04976 scoreStdev 22.8069 scoreLead -1.04976 scoreSelfplay -1.42812 prior 0.0248123 lcb 0.384583 utilityLcb -0.271004 order 6 pv C3 C4 D3 F3 info move P16 visits 5 utility -0.145905 winrate 0.429703 scoreMean -0.928202 scoreStdev 22.8236 scoreLead -0.928202 scoreSelfplay -1.31559 prior 0.0169167 lcb 0.350979 utilityLcb -0.366332 order 7 pv P16 R17 R15 info move Q15 visits 5 utility -0.14019 winrate 0.432207 scoreMean -0.896112 scoreStdev 22.9236 scoreLead -0.896112 scoreSelfplay -1.23012 prior 0.0167427 lcb 0.348387 utilityLcb -0.374886 order 8 pv Q15 R17 P17 Q16 info move Q5 visits 4 utility -0.161366 winrate 0.42293 scoreMean -1.02894 scoreStdev 22.9002 scoreLead -1.02894 scoreSelfplay -1.55252 prior 0.0160561 lcb 0.338361 utilityLcb -0.398159 order 9 pv Q5 R3 P3 info move P4 visits 4 utility -0.143638 winrate 0.43103 scoreMean -0.940784 scoreStdev 22.8943 scoreLead -0.940784 scoreSelfplay -1.3636 prior 0.0148292 lcb 0.249842 utilityLcb -0.650964 order 10 pv P4 Q16 R4 info move R15 visits 4 utility -0.137486 winrate 0.433532 scoreMean -0.857441 scoreStdev 22.8649 scoreLead -0.857441 scoreSelfplay -1.22112 prior 0.0107711 lcb 0.309128 utilityLcb -0.485816 order 11 pv R15 Q4 Q17 info move P3 visits 3 utility -0.14738 winrate 0.429387 scoreMean -0.954802 scoreStdev 22.7089 scoreLead -0.954802 scoreSelfplay -1.4166 prior 0.0103072 lcb 0.252152 utilityLcb -0.643635 order 12 pv P3 Q16 R4 info move F17 visits 3 utility -0.140148 winrate 0.432644 scoreMean -0.947566 scoreStdev 22.6976 scoreLead -0.947566 scoreSelfplay -1.32848 prior 0.00839262 lcb -0.271904 utilityLcb -2.11288 order 13 pv F17 Q17 Q4 info move C14 visits 2 utility -0.155016 winrate 0.426119 scoreMean -1.08708 scoreStdev 22.7327 scoreLead -1.08708 scoreSelfplay -1.55187 prior 0.0103841 lcb -0.573881 utilityLcb -2.8 order 14 pv C14 Q16 info move P17 visits 2 utility -0.153435 winrate 0.426072 scoreMean -0.957317 scoreStdev 22.3858 scoreLead -0.957317 scoreSelfplay -1.34128 prior 0.00906859 lcb -0.573928 utilityLcb -2.8 order 15 pv P17 R4 info move R5 visits 2 utility -0.155467 winrate 0.425636 scoreMean -1.0094 scoreStdev 22.7501 scoreLead -1.0094 scoreSelfplay -1.48934 prior 0.00872921 lcb -0.574364 utilityLcb -2.8 order 16 pv R5 Q16 info move R3 visits 2 utility -0.151344 winrate 0.427573 scoreMean -1.0235 scoreStdev 22.9175 scoreLead -1.0235 scoreSelfplay -1.46132 prior 0.00734191 lcb -0.572427 utilityLcb -2.8 order 17 pv R3 Q16 info move R17 visits 1 utility -0.167205 winrate 0.421215 scoreMean -1.16352 scoreStdev 22.4956 scoreLead -1.16352 scoreSelfplay -1.83822 prior 0.00730631 lcb -0.578785 utilityLcb -2.8 order 18 pv R17
play Q16

showboard
= MoveNum: 3 HASH: 671ADCF6EC380018C138D3BA9914B60A
   A B C D E F G H J K L M N O P Q R S T
19 . . . . . . . . . . . . . . . . . . .
18 . . . . . . . . . . . . . . . . . . .
17 . . . . . . . . . . . . . . . . . . .
16 . . . X1. . . . . . . . . . . X3. . .
15 . . . . . . . . . . . . . . . . . . .
14 . . . . . . . . . . . . . . . . . . .
13 . . . . . . . . . . . . . . . . . . .
12 . . . . . . . . . . . . . . . . . . .
11 . . . . . . . . . . . . . . . . . . .
10 . . . . . . . . . . . . . . . . . . .
 9 . . . . . . . . . . . . . . . . . . .
 8 . . . . . . . . . . . . . . . . . . .
 7 . . . . . . . . . . . . . . . . . . .
 6 . . . . . . . . . . . . . . . . . . .
 5 . . . . . . . . . . . . . . . . . . .
 4 . . . O2. . . . . . . . . . . . . . .
 3 . . . . . . . . . . . . . . . . . . .
 2 . . . . . . . . . . . . . . . . . . .
 1 . . . . . . . . . . . . . . . . . . .
Next player: White
Rules: {"hasButton":false,"ko":"POSITIONAL","komi":7.5,"scoring":"AREA","suicide":true,"tax":"NONE","whiteHandicapBonus":"0"}
B stones captured: 0
W stones captured: 0

**Comment by lightvector** [comment]
KataGo will randomly sometimes make a move that is different than the one it believes to be the best, so that it plays more variety and doesn't always play exactly the same game every time. This is particularly true in the opening when many moves are almost equal in value.

**Comment by fangzhch74** [comment]
> KataGo will randomly sometimes make a move that is different than the one it believes to be the best, so that it plays more variety and doesn't always play exactly the same game every time. This is particularly true in the opening when many moves are almost equal in value.

Thank you very much.
The output seems a little difference from  LeelaZero engine that the play position always at the first line. Is it possible always moving the order 0, that seems more friendly as user interface.

**Comment by lightvector** [comment]
I do not want or plan to make that change. For an analysis tool, I think it would be informative to know the moments where KataGo chose an alternative move due to temperature randomization - changing the played move to order 0 would obscure this information.

Closing this issue, feel free to reply back if you have other questions!
