### ISSUE TITLE
[Question] Do shrunk weights for smaller boards work correctly?

### ISSUE THREAD

**Issue by y-ich** [lightvector/KataGo#110]
I have a question for you.

KataGo uses a 19x19 weight for smaller boards using a mask feature.

I converted the weight for smaller boards by changing poslen in model.py for each smaller board and removing mask.
It seems work normally.
Do you think that it works correctly?
Or does restoring a checkpoint with different poslen cause confusion of weight values?

Smaller weight and no masks boost performance very much.
It is very attractive.

Thank you.

**Comment by lightvector** [comment]
Yes this will work correctly. The weights themselves do not intrinsically care about the board size - the only care about in terms of what they were trained to be *good* at, and KataGo's C++ engine also avoids masking in some cases where a fixed board size is used.

**Comment by y-ich** [comment]
Thank you for your explanation!
