### ISSUE TITLE
g170 config question

### ISSUE THREAD

**Issue by barrtgt** [lightvector/KataGo#113]
I'm curious what was the thread count and batch size you used for self-play and gatekeeping? Thanks.

**Comment by lightvector** [comment]
I used cpp/configs/gatekeeper2a.cfg, cpp/configs/gatekeeper2b.cfg, cpp/configs/selfplay8a.cfg, cpp/configs/selfplay8b.cfg, cpp/configs/selfplay8b20.cfg at various stages in the run, all in https://github.com/lightvector/KataGo/tree/master/cpp/configs.

These should be okay settings (possibly could still be tuned better) for 2xV100 and 8xV100 cloud machines.

**Comment by barrtgt** [comment]
Great. Much appreciated.
