### ISSUE TITLE
Very slow enough to take more than a minute.

### ISSUE THREAD

**Issue by mc-mong** [lightvector/KataGo#118]
Very slow enough to take more than a minute.

katago-v1.3.2-cuda10.1-windows-x64.zip

2020-02-02 19:39:58+0900: GTP Engine starting...
2020-02-02 19:39:58+0900: KataGo v1.3.2
2020-02-02 19:39:58+0900: Using 8 CPU thread(s) for search
2020-02-02 19:39:58+0900: nnRandSeed0 = 6129657175884853758
2020-02-02 19:39:58+0900: After dedups: nnModelFile0 = g170e-b15.gz useFP16 auto useNHWC auto
2020-02-02 19:40:04+0900: Loaded neural net with nnXLen 19 nnYLen 19
2020-02-02 19:40:04+0900: Loaded model g170e-b15.gz
2020-02-02 19:40:04+0900: GTP ready, beginning main protocol loop
2020-02-02 19:40:04+0900: Controller: name
2020-02-02 19:40:04+0900: = KataGo
2020-02-02 19:40:04+0900: Controller: version
2020-02-02 19:40:04+0900: = 1.3.2
2020-02-02 19:40:04+0900: Controller: protocol_version
2020-02-02 19:40:04+0900: = 2
2020-02-02 19:40:04+0900: Controller: list_commands
2020-02-02 19:40:04+0900: = protocol_version
name
version
known_command
list_commands
quit
boardsize
rectangular_boardsize
clear_board
komi
play
undo
kata-get-rules
kata-set-rule
kata-set-rules
genmove
genmove_debug
search_debug
clear_cache
showboard
fixed_handicap
place_free_handicap
set_free_handicap
time_settings
time_left
final_score
final_status_list
loadsgf
lz-genmove_analyze
kata-genmove_analyze
lz-analyze
kata-analyze
stop
2020-02-02 19:40:04+0900: Controller: komi 0
2020-02-02 19:40:04+0900: = 
2020-02-02 19:40:04+0900: Controller: boardsize 19
2020-02-02 19:40:04+0900: = 
2020-02-02 19:40:04+0900: Cuda backend: Found GPU GeForce GTX 1060 3GB memory 3221225472 compute capability major 6 minor 1
2020-02-02 19:40:04+0900: Cuda backend: Model version 8 useFP16 = true useNHWC = false
2020-02-02 19:40:04+0900: Controller: clear_board
2020-02-02 19:40:04+0900: = 
2020-02-02 19:40:04+0900: Controller: play B D4
2020-02-02 19:40:04+0900: = 
2020-02-02 19:40:04+0900: Controller: lz-genmove_analyze W 100

No longer after the above message.

**Comment by lightvector** [comment]
What is taking more than a minute? Do you mean the "lz-genmove_analyze W 100" is very slow?

**Comment by mc-mong** [comment]
> 
> 
> What is taking more than a minute? Do you mean the "lz-genmove_analyze W 100" is very slow?

More than 40 minutes...
 -------------------------------------------
gtp_example.cfg

maxVisits = 1000

**Comment by mc-mong** [comment]
> 
> 
> What is taking more than a minute? Do you mean the "lz-genmove_analyze W 100" is very slow?

katago-v1.3.1-cuda10.1-windows-x64.zip

Leave it within 10 seconds.
------------------------------------------
gtp_example.cfg

maxVisits = 1000

**Comment by lightvector** [comment]
Thanks. I pushed an update to the release right now that might fix your problem involving automatic use of cudaUseFP16, you can try re-downloading and see if it fixes your problem: https://github.com/lightvector/KataGo/releases/tag/v1.3.2 - please let me know!

Also on GTX1060 I recommend you also try the OpenCL version. With the recent performance improvement of OpenCL, there is a chance that OpenCL version will be faster anyways for you. If you do try it, please know that on the first start up it will take a while to tune - I recommend BEFORE running it in Sabaki or Lizzie or anything else, you FIRST run it on the command line directly with:
`katago benchmark -config YOUR_GTP_CONFIG.cfg -model YOUR_MODEL_FILE.txt.gz`

**Comment by mc-mong** [comment]
gtp_example_b15.cfg

maxVisits = 11000

---------------------------------------------------

C:\baduk\Katago-opencl>katago benchmark -config gtp_example_b15.cfg -model g170e-b15.gz
2020-02-02 23:38:58+0900: Loading model and initializing benchmark...
2020-02-02 23:38:58+0900: nnRandSeed0 = 959346610040786134
2020-02-02 23:38:58+0900: After dedups: nnModelFile0 = g170e-b15.gz useFP16 auto useNHWC auto
2020-02-02 23:39:04+0900: Found OpenCL Platform 0: NVIDIA CUDA (NVIDIA Corporation) (OpenCL 1.2 CUDA 10.1.120)
2020-02-02 23:39:04+0900: Found 1 device(s) on platform 0 with type GPU or Accelerator
2020-02-02 23:39:04+0900: Found OpenCL Device 0: GeForce GTX 1060 3GB (NVIDIA Corporation)
2020-02-02 23:39:04+0900: Using OpenCL Device 0: GeForce GTX 1060 3GB (NVIDIA Corporation) OpenCL 1.2 CUDA
2020-02-02 23:39:04+0900: Loaded tuning parameters from: ./KataGoData/opencltuning/tune6_gpuGeForceGTX10603GB_x19_y19_c192_mv8.txt
2020-02-02 23:39:04+0900: Loaded neural net
2020-02-02 23:39:04+0900: OpenCL backend: Model version 8

Testing using 600 visits. If you have a good GPU, you might increase this using "-visits N" to get more accurate results.
 If you have a weak GPU and this is taking forever, you can decrease it instead to finish the benchmark faster.

You are currently using the OpenCL version of KataGo.
If you have a strong GPU capable of FP16 tensor cores (e.g. RTX2080), downloading or compiling the Cuda version of KataGo and setting cudaUseFP16=true and cudaUseNHWC=true may give a large performance boost.

Your GTP config is currently set to use numSearchThreads = 8
Testing different numbers of threads:

numSearchThreads =  1: 10 / 10 positions, visits/s = 212.51 nnEvals/s = 195.97 nnBatches/s = 195.97 avgBatchSize = 1.00 (28.2 secs) (EloDiff baseline)
numSearchThreads =  2: 10 / 10 positions, visits/s = 224.40 nnEvals/s = 208.34 nnBatches/s = 208.23 avgBatchSize = 1.00 (26.8 secs) (EloDiff +14)
numSearchThreads =  4: 10 / 10 positions, visits/s = 344.89 nnEvals/s = 318.75 nnBatches/s = 159.46 avgBatchSize = 2.00 (17.5 secs) (EloDiff +162)
numSearchThreads =  6: 10 / 10 positions, visits/s = 433.60 nnEvals/s = 403.14 nnBatches/s = 135.31 avgBatchSize = 2.98 (14.0 secs) (EloDiff +239)
numSearchThreads =  8: 10 / 10 positions, visits/s = 482.59 nnEvals/s = 442.68 nnBatches/s = 110.75 avgBatchSize = 4.00 (12.6 secs) (EloDiff +271)
numSearchThreads = 12: 10 / 10 positions, visits/s = 561.74 nnEvals/s = 515.68 nnBatches/s = 73.27 avgBatchSize = 7.04 (10.9 secs) (EloDiff +315)
numSearchThreads = 16: 10 / 10 positions, visits/s = 596.45 nnEvals/s = 553.29 nnBatches/s = 49.75 avgBatchSize = 11.12 (10.3 secs) (EloDiff +324)
numSearchThreads = 24: 10 / 10 positions, visits/s = 596.80 nnEvals/s = 563.27 nnBatches/s = 39.08 avgBatchSize = 14.41 (10.4 secs) (EloDiff +298)

Based on some test data, each speed doubling gains perhaps ~250 Elo by searching deeper.
Based on some test data, each thread costs perhaps 7 Elo if using 800 visits, and 2 Elo if using 5000 visits (by making MCTS worse).
So APPROXIMATELY based on this benchmark, if you intend to do a 5 second search:
numSearchThreads =  1: (baseline)
numSearchThreads =  2:   +14 Elo
numSearchThreads =  4:  +162 Elo
numSearchThreads =  6:  +239 Elo
numSearchThreads =  8:  +271 Elo
numSearchThreads = 12:  +315 Elo
numSearchThreads = 16:  +324 Elo (recommended)
numSearchThreads = 24:  +298 Elo

If you care about performance, you may want to edit numSearchThreads in gtp_example_b15.cfg based on the above results!
If you intend to do much longer searches, you can try slightly higher numSearchThreads if you still see clear speedups.
If you intend to do short or fixed-visit searches, use lower numSearchThreads for better strength, high threads will weaken strength.
If interested see also other notes about performance and mem usage in the top of gtp_example_b15.cfg

**Comment by mc-mong** [comment]
cuda version 1.3.2

gtp_example_b15.cfg

maxVisits = 11000

-----------------------------------

C:\baduk\Katago>katago benchmark -config gtp_example_b15.cfg -model g170e-b15.gz
2020-02-02 23:53:21+0900: Loading model and initializing benchmark...
2020-02-02 23:53:21+0900: nnRandSeed0 = 6790671016764914608
2020-02-02 23:53:21+0900: After dedups: nnModelFile0 = g170e-b15.gz useFP16 auto useNHWC auto
2020-02-02 23:53:26+0900: Loaded neural net
2020-02-02 23:53:26+0900: Cuda backend: Found GPU GeForce GTX 1060 3GB memory 3221225472 compute capability major 6 minor 1
2020-02-02 23:53:26+0900: Cuda backend: Model version 8 useFP16 = false useNHWC = false

Testing using 600 visits. If you have a good GPU, you might increase this using "-visits N" to get more accurate results.
 If you have a weak GPU and this is taking forever, you can decrease it instead to finish the benchmark faster.

Your GTP config is currently set to cudaUseFP16 = auto and cudaUseNHWC = auto

Your GTP config is currently set to use numSearchThreads = 8
Testing different numbers of threads:

numSearchThreads =  1: 10 / 10 positions, visits/s = 228.16 nnEvals/s = 211.93 nnBatches/s = 211.93 avgBatchSize = 1.00 (26.3 secs) (EloDiff baseline)
numSearchThreads =  2: 10 / 10 positions, visits/s = 237.42 nnEvals/s = 222.09 nnBatches/s = 221.97 avgBatchSize = 1.00 (25.3 secs) (EloDiff +9)
numSearchThreads =  4: 10 / 10 positions, visits/s = 310.50 nnEvals/s = 288.67 nnBatches/s = 144.64 avgBatchSize = 2.00 (19.4 secs) (EloDiff +97)
numSearchThreads =  6: 10 / 10 positions, visits/s = 345.44 nnEvals/s = 325.63 nnBatches/s = 108.94 avgBatchSize = 2.99 (17.5 secs) (EloDiff +127)
numSearchThreads =  8: 10 / 10 positions, visits/s = 365.82 nnEvals/s = 337.73 nnBatches/s = 82.87 avgBatchSize = 4.08 (16.6 secs) (EloDiff +139)
numSearchThreads = 12: 10 / 10 positions, visits/s = 342.11 nnEvals/s = 319.43 nnBatches/s = 41.49 avgBatchSize = 7.70 (17.9 secs) (EloDiff +95)
numSearchThreads = 16: 10 / 10 positions, visits/s = 393.22 nnEvals/s = 365.35 nnBatches/s = 31.84 avgBatchSize = 11.47 (15.6 secs) (EloDiff +132)
numSearchThreads = 24: 10 / 10 positions, visits/s = 400.69 nnEvals/s = 377.67 nnBatches/s = 21.35 avgBatchSize = 17.69 (15.5 secs) (EloDiff +105)

Based on some test data, each speed doubling gains perhaps ~250 Elo by searching deeper.
Based on some test data, each thread costs perhaps 7 Elo if using 800 visits, and 2 Elo if using 5000 visits (by making MCTS worse).
So APPROXIMATELY based on this benchmark, if you intend to do a 5 second search:
numSearchThreads =  1: (baseline)
numSearchThreads =  2:    +9 Elo
numSearchThreads =  4:   +97 Elo
numSearchThreads =  6:  +127 Elo
numSearchThreads =  8:  +139 Elo (recommended)
numSearchThreads = 12:   +95 Elo
numSearchThreads = 16:  +132 Elo
numSearchThreads = 24:  +105 Elo

If you care about performance, you may want to edit numSearchThreads in gtp_example_b15.cfg based on the above results!
If you intend to do much longer searches, you can try slightly higher numSearchThreads if you still see clear speedups.
If you intend to do short or fixed-visit searches, use lower numSearchThreads for better strength, high threads will weaken strength.
If interested see also other notes about performance and mem usage in the top of gtp_example_b15.cfg

**Comment by lightvector** [comment]
Okay, seems like you should use the OpenCL version. There is no problem any more, everything is good now?

**Comment by lightvector** [comment]
Closing this for now. Feel free to reply back if in fact your problem is not solved yet.
