### ISSUE TITLE
recent changes in the benchmarks of katago?

### ISSUE THREAD

**Issue by objt-ba** [lightvector/KataGo#125]
The first time you start KataGo it performs a kind of benchmark/optimization, and saves it to a text file.
I collected these config files for a number of different GPUs, (even though the GPU may not be the only factor).

As I am about to upgrade to a more recent KataGo version, I now wonder if I have to recreate those. (e.g. due to new factors in the file format, or a different benchmark procedure, or changes in the naming of the files).

Thank you in advance

**Comment by objt-ba** [comment]
Aha ! - found it.
```
// the new file details
-rw-r--r-- 1 root root 639 Feb  7 22:53 tune6_gpuGeForceGTX1080Ti_x19_y19_c256_mv8.txt

// the old file details
-rw-r--r-- 1 root root 570 Nov 24 23:01 tune_gpuGeForceGTX1080Ti_x19_y19_c256_mv5.txt

```
Apparently both filesize and filename are different now.
Case closed. :)

**Comment by lightvector** [comment]
Yep I made it also change the filename so that old and new versions don't
fight depending on which was most recently run.

>
