### ISSUE TITLE
Playing too fast

### ISSUE THREAD

**Issue by luckydrq** [lightvector/KataGo#126]
Hi, 
   First of all, thanks for creating this program! It's awsome!
   Recently, i let katago play against [leela-zero](https://github.com/leela-zero/leela-zero) several times  on my personal computer and katago loses all the games. I've noticed that katago plays really fast and seems that it doesn't need time to think(not even a second) while leela takes 20 ~ 70 seconds before generating the next move. Here is some information:

## OS
Windows 10 Pro(x64)

## Hardware
- GPU: NVIDIA GeForce RTX 2060(6GB)
- CPU: Intel Core i5-9400F
- RAM: 16GB(DDR4 2666 MHz 8GB x2)

### leela-zero
- version: v0.17 (latest)
- GPU support: yes
- network weights file: https://zero.sjeng.org/best-network

### katago
- version: v1.3.2 (latest)
- GPU support: yes
- neural nets file: [g170-b20c256x2-s1913382912-d435450331.txt.gz](https://github.com/lightvector/KataGo/releases/download/v1.3.2/g170-b20c256x2-s1913382912-d435450331.txt.gz)

Also i install CUDA and CUDANN.

### sabaki
- version: v0.43.3(latest, doesn't matter for this issue)

PS: i don't know what's the difference between `network weights` and `neural nets`. Are they the same thing?

### sabaki configure
![image](https://user-images.githubusercontent.com/1474688/74096162-0a384b00-4b36-11ea-9df2-c4dee9b0f7f8.png)

### leela-zero
None. I just follow the docs, download binary files and the recommended weights file and set up in sabaki as shown above.

### katago
I modified the [gtp_example.cfg](https://github.com/lightvector/KataGo/blob/master/cpp/configs/gtp_example.cfg) with 3 lines.
```
numSearchThreads = 24  // 6 -> 24
cudaUseFP16 = true  // auto -> true
cudaUseNHWC = true // auto -> true
```

benchmark:

![image](https://user-images.githubusercontent.com/1474688/74096288-e7a73180-4b37-11ea-956b-137c68710eea.png)

## Help
I think i've used the most powful config for both leela-zero and katago but must have missed something there. Can you give me some advices? I want to config katago as strong as all i got to fit it. Thanks! Best wishes!

**Comment by luckydrq** [comment]
I use katago to play against some other AI, and it beats them. So i am not saying it's not strong, but it is just not strong enough from what the docs describe.

**Comment by af990m** [comment]
You should edit this line 
“maxVisits = 500”  
in  the file gtp_example.cfg，
or add "-v 500" as the command line arguments for leelaz

**Comment by lightvector** [comment]
I'm assuming this solves the problem? Let me know if not, happy to answer questions, otherwise I'll close this issue in perhaps a few days. Thanks!

**Comment by luckydrq** [comment]
@af990m @lightvector Thanks for reply! 

Yes, like @af990m said, config the field `maxVisits` will let katago take more time to "think" and do be stronger. But what's the fittest value for me?  It seems that leela-zero doesn't need the field to be set explictly.

**Comment by lightvector** [comment]
If you're relying on GTP time controls that are sent by your client (Canadian or absolute time) you can just comment out that field entirely. That value is a max, you can just have no maximum if you want KataGo to just use the full amount of time it wants to use.

**Comment by lightvector** [comment]
Going ahead and closing this. Please reply back if commenting out max visits did not solve the problem of making KataGo have no limit for thinking.
