### ISSUE TITLE
Implementing support for command "kgs-time_settings"

### ISSUE THREAD

**Issue by sbbdms** [lightvector/KataGo#128]
Hi!
I am doing some tests with KataGo on KGS, and I find a problem.

Firstly I comment and disable maxVisits & maxPlayouts & maxTime in the GTP setting, lagBuffer is default value (1.0) and then:
(1) KataGo can manage its time properly under Canadian time setting. For example when the time setting is 5:00+10/5:00, KataGo uses its time sufficiently, usually around 29 secs per move.
(2) KataGo can manage its time according to the main time. For example when the time setting is absolute 30 mins, KataGo plays 5 secs per move. When the main time is absolute 90 mins, KataGo plays 20 secs per move.
(3) KataGo cannot manage its time properly when there's little/no main time but sufficient byo-yomi. For example when the time setting is 5:00+5x0:30, KataGo always plays a move in 0.5 seconds.
I try to discomment, enable maxVisits & maxPlayouts & maxTime in the GTP setting and set a high value like maxVisits=20000, but it still cannot change KataGo's time management.
Note: KataGo doesn't have this problem in Drago with the same config file. It only happens when KataGo connects to KGS.

However, I do observe some bot accounts (Petgo2 & KataGoBot) on KGS that uses KataGo, their time setting is 0:00+20x0:20 and their KataGo uses their time sufficiently. I try the same time setting, but it still don't work well for the KataGo on my computer.
How should I adjust the setting correctly and let KataGo manage its time properly?
Thanks!

**Comment by lightvector** [comment]
I'm not sure. It depends on how KGS is reporting the time to KataGo - perhaps with byo-yomi it reports a time that makes KataGo think it has only a fixed 30 seconds for the entire game left, which of course means that KataGo will try to move as fast as possible. I haven't tried to make it run on KGS, so I'm a bit unfamiliar with what the KGS GTP client does.

You might consider asking your question in the Leela Zero Discord chat, I believe the owners of those bots are active there: https://discord.gg/fhDHgfk

**Comment by sbbdms** [comment]
I check the instruction of KgsGtp and find that KgsGtp has its own command called "kgs-time_settings". Below is the description:

> Similar to the boardsize command, you may get several time settings commands; any settings that your engine cannot play with, you should return an error. If your engine supports the kgs-time_settings command, then you will get that instead of the standard time_settings command. The reason for the KGS-specific time setting is that GTP's standard time settings has no way to describe the byo-yomi time system. This system is quite popular in tournaments and is used often on KGS. The format for the kgs-time_settings command is the same as time_settings, but another parameter is inserted as the first parameter, which describes the time system as either none, absolute, byoyomi, or canadian. For the none and absolute time systems there will be fewer than two options. If you do not support kgs-time_settings and your engine is put into a byo-yomi game, kgsGtp will tell your engine that it is an absolute time game with no byo-yomi periods and a total time equal to the main time and all of the periods.

Then I check the code in KataGo and I find there's no support for this command. So, when a byo-yomi game starts, KataGo is told that it is an absolute time game with no byo-yomi periods and a total time equal to the main time and all of the periods (I don't know why KataGo can handle Kgs' Canadian time setting though).

There's code that support this command in Leela Zero (https://github.com/leela-zero/leela-zero/blob/next/src/GTP.cpp), which starts from line 1012.
Could you please implement it to KataGo under the license? Thanks!

**Comment by lightvector** [comment]
We can't use Leela Zero's code because Leela Zero's license is incompatible with KataGo. So looks like I'll need to implement something myself.

Unless I'm missing something this also seems like stupid behavior by KGS. It's bizarre that KGS would report a byo-yomi game as an absolute time game, when instead it could report it as Canadian. GTP mandates Canadian time controls as an option, so pretty much every Go bot in existence in theory should support it, even if they don't have KGS-specific extensions. Sum up the main time and all of the byo yomi periods _except one_, and report it as a Canadian game with that main time and the final byo yomi period reported as the repeatedly refreshing Canadian time. It seems this would be a strict improvement, and let any bot understand that there *is* actually a refreshing unit of time at the end, instead of that being all the time there is.

**Comment by sbbdms** [comment]
I see that the corresponding support has implemented in the latest commit. Thank you for your work!
