### ISSUE TITLE
Where can i find the number of stones on the current board?

### ISSUE THREAD

**Issue by Grant-Tao** [lightvector/KataGo#134]
Dear @lightvector : 

I am reading your source code recent days, I am interested in the stones' number variations between different games. how can i get the stones' number  of the current board conveniently and with little computation.

thank you very much.

**Comment by lightvector** [comment]
That number isn't tracked. If you're working within KataGo's source code, you'll need to iterate over the board and count it. Why do you ask? Are you trying to modify the code for something?

**Comment by Grant-Tao** [comment]
Yes, I want to track the stone number and the searching depth.

**Comment by lightvector** [comment]
Neither of those things are measured. You'll have to edit the code yourself to do what you want.

**Comment by lightvector** [comment]
What are you trying to do in particular? Hard to help more without the context.

**Comment by Grant-Tao** [comment]
Thank you very much for your kind responds.
The overall idea is that: under certain computation limit, at the beginning of a game the player needs deeper search, and when the game goes to the end, wider search is needed. But how to control the search width is a hard to tackle.  KataGo's compulsory rollout policy can only be effective when the player has a large computing power. I guess that is why KataGo does not have a cpu-only version. 

BTW, your new version (1.3.3, 20 block 2.43G) seems less efficient than its previous one (1.3.2. 1.91G), about 10% for both opencl and cuda version. More weight parameters?

**Comment by kennychenfs** [comment]
Cpuct can decide search width.  Larger cpuct means wider.

**Comment by lightvector** [comment]
There are no changes between 1.3.3 and 1.3.2 that should significantly affect performance. Could you try posting some benchmarks from your system that demonstrate this difference? (`./katago benchmark -config YOUR_CONFIG -model MODEL FILE`) Ideally, attach the full text of the output, including where it reports the neural net configuration and such. Keep in mind that the neural net version is separate from the KataGo version, so it is necessary to distinguish and test the two separately. So there are three possible configurations worth testing.

* 1.3.3, 20 block 2.43G
* 1.3.3, 20 block 1.91G
* 1.3.2, 20 block 1.91G

**Comment by Grant-Tao** [comment]
### **Here you are:**
### 1.32 20 block 1.91G:
2020-03-08 15:21:14+0800: Loading model and initializing benchmark...
2020-03-08 15:21:14+0800: nnRandSeed0 = 6648928626843828616
2020-03-08 15:21:14+0800: After dedups: nnModelFile0 = model.txt useFP16 auto useNHWC auto
2020-03-08 15:21:18+0800: Found OpenCL Platform 0: NVIDIA CUDA (NVIDIA Corporation) (OpenCL 1.2 CUDA 10.1.0)
2020-03-08 15:21:18+0800: Found 2 device(s) on platform 0 with type GPU or Accelerator
2020-03-08 15:21:18+0800: Found OpenCL Device 0: GeForce GTX 1070 (NVIDIA Corporation)
2020-03-08 15:21:18+0800: Found OpenCL Device 1: GeForce GTX 1070 (NVIDIA Corporation)
2020-03-08 15:21:19+0800: Using OpenCL Device 0: GeForce GTX 1070 (NVIDIA Corporation) OpenCL 1.2 CUDA
2020-03-08 15:21:19+0800: Using OpenCL Device 1: GeForce GTX 1070 (NVIDIA Corporation) OpenCL 1.2 CUDA
2020-03-08 15:21:19+0800: Loaded tuning parameters from: /home/grant/.katago/opencltuning/tune6_gpuGeForceGTX1070_x19_y19_c256_mv8.txt
2020-03-08 15:21:19+0800: Loaded neural net
2020-03-08 15:21:19+0800: OpenCL backend: Model version 8
2020-03-08 15:21:19+0800: OpenCL backend: Model version 8

Testing using 600 visits. If you have a good GPU, you might increase this using "-visits N" to get more accurate results.
 If you have a weak GPU and this is taking forever, you can decrease it instead to finish the benchmark faster.

You are currently using the OpenCL version of KataGo.
If you have a strong GPU capable of FP16 tensor cores (e.g. RTX2080), downloading or compiling the Cuda version of KataGo and setting cudaUseFP16=true and cudaUseNHWC=true may give a large performance boost.

Your GTP config is currently set to use numSearchThreads = 16
Testing different numbers of threads: 

numSearchThreads =  1: 10 / 10 positions, visits/s = 198.23 nnEvals/s = 183.36 nnBatches/s = 183.36 avgBatchSize = 1.00 (30.3 secs) (EloDiff baseline)
numSearchThreads =  2: 10 / 10 positions, visits/s = 359.20 nnEvals/s = 322.86 nnBatches/s = 321.84 avgBatchSize = 1.00 (16.7 secs) (EloDiff +211)
numSearchThreads =  4: 10 / 10 positions, visits/s = 509.23 nnEvals/s = 478.07 nnBatches/s = 359.16 avgBatchSize = 1.33 (11.8 secs) (EloDiff +332)
numSearchThreads =  6: 10 / 10 positions, visits/s = 580.37 nnEvals/s = 535.96 nnBatches/s = 268.22 avgBatchSize = 2.00 (10.4 secs) (EloDiff +373)
numSearchThreads =  8: 10 / 10 positions, visits/s = 607.64 nnEvals/s = 572.50 nnBatches/s = 214.62 avgBatchSize = 2.67 (10.0 secs) (EloDiff +384)
numSearchThreads = 12: 10 / 10 positions, visits/s = 660.63 nnEvals/s = 615.76 nnBatches/s = 154.51 avgBatchSize = 3.99 (9.2 secs) (EloDiff +403)
numSearchThreads = 16: 10 / 10 positions, visits/s = 676.26 nnEvals/s = 634.15 nnBatches/s = 118.54 avgBatchSize = 5.35 (9.1 secs) (EloDiff +399)
numSearchThreads = 24: 10 / 10 positions, visits/s = 747.86 nnEvals/s = 709.21 nnBatches/s = 93.03 avgBatchSize = 7.62 (8.3 secs) (EloDiff +416)

Based on some test data, each speed doubling gains perhaps ~250 Elo by searching deeper.
Based on some test data, each thread costs perhaps 7 Elo if using 800 visits, and 2 Elo if using 5000 visits (by making MCTS worse).
So APPROXIMATELY based on this benchmark, if you intend to do a 5 second search: 
numSearchThreads =  1: (baseline)
numSearchThreads =  2:  +211 Elo
numSearchThreads =  4:  +332 Elo
numSearchThreads =  6:  +373 Elo
numSearchThreads =  8:  +384 Elo
numSearchThreads = 12:  +403 Elo
numSearchThreads = 16:  +399 Elo
numSearchThreads = 24:  +416 Elo (recommended)

If you care about performance, you may want to edit numSearchThreads in gtp_test.cfg based on the above results!
If you intend to do much longer searches, you can try slightly higher numSearchThreads if you still see clear speedups.
If you intend to do short or fixed-visit searches, use lower numSearchThreads for better strength, high threads will weaken strength.
If interested see also other notes about performance and mem usage in the top of gtp_test.cfg

**Comment by Grant-Tao** [comment]
### 1.3.3 20 blocks 1.91G : 
2020-03-08 15:27:56+0800: Loading model and initializing benchmark...
WARNING: Your nnMaxBatchSize is hardcoded to 10, ignoring it and assuming it is >= threads, for this benchmark.
2020-03-08 15:27:56+0800: nnRandSeed0 = 16961387910611492581
2020-03-08 15:27:56+0800: After dedups: nnModelFile0 = model.txt useFP16 auto useNHWC auto
2020-03-08 15:28:00+0800: Found OpenCL Platform 0: NVIDIA CUDA (NVIDIA Corporation) (OpenCL 1.2 CUDA 10.1.0)
2020-03-08 15:28:00+0800: Found 2 device(s) on platform 0 with type CPU or GPU or Accelerator
2020-03-08 15:28:00+0800: Found OpenCL Device 0: GeForce GTX 1070 (NVIDIA Corporation) (score 11000102)
2020-03-08 15:28:00+0800: Found OpenCL Device 1: GeForce GTX 1070 (NVIDIA Corporation) (score 11000102)
2020-03-08 15:28:00+0800: Using OpenCL Device 0: GeForce GTX 1070 (NVIDIA Corporation) OpenCL 1.2 CUDA
2020-03-08 15:28:00+0800: Using OpenCL Device 1: GeForce GTX 1070 (NVIDIA Corporation) OpenCL 1.2 CUDA
2020-03-08 15:28:00+0800: Loaded tuning parameters from: /home/grant/.katago/opencltuning/tune6_gpuGeForceGTX1070_x19_y19_c256_mv8.txt
2020-03-08 15:28:00+0800: OpenCL backend: Model version 8
2020-03-08 15:28:00+0800: OpenCL backend: Model name: b20c256x2-s1913382912-d435450331
2020-03-08 15:28:00+0800: OpenCL backend: Model version 8
2020-03-08 15:28:00+0800: OpenCL backend: Model name: b20c256x2-s1913382912-d435450331


Testing using 800 visits.
  If you have a good GPU, you might increase this using "-visits N" to get more accurate results.
  If you have a weak GPU and this is taking forever, you can decrease it instead to finish the benchmark faster.

You are currently using the OpenCL version of KataGo.
If you have a strong GPU capable of FP16 tensor cores (e.g. RTX2080), using the Cuda version of KataGo instead may give a large performance boost.

Your GTP config is currently set to use numSearchThreads = 16
Testing different numbers of threads: 
numSearchThreads =  1: 10 / 10 positions, visits/s = 201.77 nnEvals/s = 185.04 nnBatches/s = 185.04 avgBatchSize = 1.00 (39.7 secs) (EloDiff baseline)
numSearchThreads =  2: 10 / 10 positions, visits/s = 351.26 nnEvals/s = 321.35 nnBatches/s = 320.39 avgBatchSize = 1.00 (22.8 secs) (EloDiff +197)
numSearchThreads =  4: 10 / 10 positions, visits/s = 521.16 nnEvals/s = 476.45 nnBatches/s = 356.90 avgBatchSize = 1.33 (15.4 secs) (EloDiff +334)
numSearchThreads =  6: 10 / 10 positions, visits/s = 572.94 nnEvals/s = 526.39 nnBatches/s = 263.62 avgBatchSize = 2.00 (14.1 secs) (EloDiff +362)
numSearchThreads =  8: 10 / 10 positions, visits/s = 626.52 nnEvals/s = 578.08 nnBatches/s = 216.84 avgBatchSize = 2.67 (12.9 secs) (EloDiff +389)
numSearchThreads = 12: 10 / 10 positions, visits/s = 673.16 nnEvals/s = 613.40 nnBatches/s = 151.07 avgBatchSize = 4.06 (12.0 secs) (EloDiff +404)
numSearchThreads = 16: 10 / 10 positions, visits/s = 677.86 nnEvals/s = 629.53 nnBatches/s = 116.03 avgBatchSize = 5.43 (12.0 secs) (EloDiff +394)
numSearchThreads = 24: 10 / 10 positions, visits/s = 648.31 nnEvals/s = 596.87 nnBatches/s = 73.10 avgBatchSize = 8.16 (12.7 secs) (EloDiff +351)


Based on some test data, each speed doubling gains perhaps ~250 Elo by searching deeper.
Based on some test data, each thread costs perhaps 7 Elo if using 800 visits, and 2 Elo if using 5000 visits (by making MCTS worse).
So APPROXIMATELY based on this benchmark, if you intend to do a 5 second search: 
numSearchThreads =  1: (baseline)
numSearchThreads =  2:  +197 Elo
numSearchThreads =  4:  +334 Elo
numSearchThreads =  6:  +362 Elo
numSearchThreads =  8:  +389 Elo
numSearchThreads = 12:  +404 Elo (recommended)
numSearchThreads = 16:  +394 Elo
numSearchThreads = 24:  +351 Elo

If you care about performance, you may want to edit numSearchThreads in gtp_test.cfg based on the above results!
WARNING: Your nnMaxBatchSize is hardcoded to 10, recommend deleting it and using the default (which this benchmark assumes)
If you intend to do much longer searches, configure the seconds per game move you expect with the '-time' flag and benchmark again.
If you intend to do short or fixed-visit searches, use lower numSearchThreads for better strength, high threads will weaken strength.
If interested see also other notes about performance and mem usage in the top of gtp_test.cfg

**Comment by Grant-Tao** [comment]
### 1.3.3 20 block 2.43G:

2020-03-08 15:31:53+0800: Loading model and initializing benchmark...
WARNING: Your nnMaxBatchSize is hardcoded to 10, ignoring it and assuming it is >= threads, for this benchmark.
2020-03-08 15:31:53+0800: nnRandSeed0 = 14447669931042659730
2020-03-08 15:31:53+0800: After dedups: nnModelFile0 = model.bin useFP16 auto useNHWC auto
2020-03-08 15:31:53+0800: Found OpenCL Platform 0: NVIDIA CUDA (NVIDIA Corporation) (OpenCL 1.2 CUDA 10.1.0)
2020-03-08 15:31:53+0800: Found 2 device(s) on platform 0 with type CPU or GPU or Accelerator
2020-03-08 15:31:53+0800: Found OpenCL Device 0: GeForce GTX 1070 (NVIDIA Corporation) (score 11000102)
2020-03-08 15:31:53+0800: Found OpenCL Device 1: GeForce GTX 1070 (NVIDIA Corporation) (score 11000102)
2020-03-08 15:31:53+0800: Using OpenCL Device 0: GeForce GTX 1070 (NVIDIA Corporation) OpenCL 1.2 CUDA
2020-03-08 15:31:53+0800: Using OpenCL Device 1: GeForce GTX 1070 (NVIDIA Corporation) OpenCL 1.2 CUDA
2020-03-08 15:31:53+0800: Loaded tuning parameters from: /home/grant/.katago/opencltuning/tune6_gpuGeForceGTX1070_x19_y19_c256_mv8.txt
2020-03-08 15:31:53+0800: OpenCL backend: Model version 8
2020-03-08 15:31:53+0800: OpenCL backend: Model name: g170-b20c256x2-s2430231552-d525879064
2020-03-08 15:31:53+0800: OpenCL backend: Model version 8
2020-03-08 15:31:53+0800: OpenCL backend: Model name: g170-b20c256x2-s2430231552-d525879064


Testing using 800 visits.
  If you have a good GPU, you might increase this using "-visits N" to get more accurate results.
  If you have a weak GPU and this is taking forever, you can decrease it instead to finish the benchmark faster.

You are currently using the OpenCL version of KataGo.
If you have a strong GPU capable of FP16 tensor cores (e.g. RTX2080), using the Cuda version of KataGo instead may give a large performance boost.

Your GTP config is currently set to use numSearchThreads = 16
Testing different numbers of threads: 
numSearchThreads =  1: 10 / 10 positions, visits/s = 200.60 nnEvals/s = 184.43 nnBatches/s = 184.43 avgBatchSize = 1.00 (39.9 secs) (EloDiff baseline)
numSearchThreads =  2: 10 / 10 positions, visits/s = 349.30 nnEvals/s = 319.87 nnBatches/s = 318.56 avgBatchSize = 1.00 (22.9 secs) (EloDiff +197)
numSearchThreads =  4: 10 / 10 positions, visits/s = 519.01 nnEvals/s = 478.10 nnBatches/s = 358.59 avgBatchSize = 1.33 (15.5 secs) (EloDiff +334)
numSearchThreads =  6: 10 / 10 positions, visits/s = 613.94 nnEvals/s = 557.58 nnBatches/s = 279.74 avgBatchSize = 1.99 (13.1 secs) (EloDiff +390)
numSearchThreads =  8: 10 / 10 positions, visits/s = 623.62 nnEvals/s = 569.45 nnBatches/s = 213.83 avgBatchSize = 2.66 (12.9 secs) (EloDiff +389)
numSearchThreads = 12: 10 / 10 positions, visits/s = 647.54 nnEvals/s = 598.52 nnBatches/s = 147.87 avgBatchSize = 4.05 (12.5 secs) (EloDiff +391)
numSearchThreads = 16: 10 / 10 positions, visits/s = 658.58 nnEvals/s = 600.23 nnBatches/s = 109.01 avgBatchSize = 5.51 (12.4 secs) (EloDiff +385)
numSearchThreads = 24: 10 / 10 positions, visits/s = 653.57 nnEvals/s = 609.89 nnBatches/s = 74.17 avgBatchSize = 8.22 (12.6 secs) (EloDiff +356)


Based on some test data, each speed doubling gains perhaps ~250 Elo by searching deeper.
Based on some test data, each thread costs perhaps 7 Elo if using 800 visits, and 2 Elo if using 5000 visits (by making MCTS worse).
So APPROXIMATELY based on this benchmark, if you intend to do a 5 second search: 
numSearchThreads =  1: (baseline)
numSearchThreads =  2:  +197 Elo
numSearchThreads =  4:  +334 Elo
numSearchThreads =  6:  +390 Elo
numSearchThreads =  8:  +389 Elo
numSearchThreads = 12:  +391 Elo (recommended)
numSearchThreads = 16:  +385 Elo
numSearchThreads = 24:  +356 Elo

If you care about performance, you may want to edit numSearchThreads in gtp_test.cfg based on the above results!
WARNING: Your nnMaxBatchSize is hardcoded to 10, recommend deleting it and using the default (which this benchmark assumes)
If you intend to do much longer searches, configure the seconds per game move you expect with the '-time' flag and benchmark again.
If you intend to do short or fixed-visit searches, use lower numSearchThreads for better strength, high threads will weaken strength.
If interested see also other notes about performance and mem usage in the top of gtp_test.cfg

**Comment by lightvector** [comment]
I think we talked about this more privately and worked out at least a partial understanding. I don't think there's all that much to do on KataGo's side unfortunately right now, so closing this thread. I may work further on the GPU implementation in the future when I get time.
