### ISSUE TITLE
How KataGo shows win rate in 'log.gtp'?

### ISSUE THREAD

**Issue by zyh001** [lightvector/KataGo#135]
I hope in the next version. KataGo can display the win rate of every step in the log file.I now have a study to get all the data in the game, including the relationship between the winning rate and the moku.

**Comment by lightvector** [comment]
Can't you already do this? It will require being a little clever and knowing how to use `grep` or something similar. Set logSearchInfo = true and then grep the logfile for the line of debug output where Kata logs its winrate. See here in the source code for what exactly all the numbers on this line are:
https://github.com/lightvector/KataGo/blob/master/cpp/search/searchresults.cpp#L972
