### ISSUE TITLE
free memory problem

### ISSUE THREAD

**Issue by vivwangsc** [lightvector/KataGo#140]
i very like katago; i always play go game with katago in china fox go platform. 
i run katago in ubuntu 18.04 with cuda 10.2;
when i play go game with katago one by one, I found my system memory alway run out , where a game is end , or a new game is start, katago engin do not free the memory using in previous game. that memory is very big. so my pc alway run out memory and halt.
can you  fix this little trouble,thanks a lot!

**Comment by lightvector** [comment]
Try taking a look at the comment here https://github.com/lightvector/KataGo/blob/master/cpp/configs/gtp_example.cfg#L19 about nnCacheSizePowerOfTwo.

This should normally be the bulk of the persistent memory use in KataGo. You can set it to a smaller number if desired. The table is 2 to the power of nnCacheSizePowerOfTwo many entries, and each entry is 1.5KB or 3KB depending on if you have ownership predictions enabled or not.

**Comment by vivwangsc** [comment]
Thanks for you tip;
I have 32gb memory, when play a game, system show 10g memory remain,and then i do not exit katago engin and play the go game continue, remain memory should be smaller  smaller, at last katago should run out  all the memory and due to system halt.
I suppose when  engin receive a gtp command as "clear borad" or "resign",engin should free the memory used by previous game,but it didn't do this?
my nnCacheSizePotowerOfTwo set  to 24,it ok for my play the first game.
thanks again!

**Comment by lightvector** [comment]
No, it doesn't clear the cache between games. This is intended - if you were repeatedly using KataGo to analyze a collection of games with similar openings, or you were repeatedly re-loading back to a given position in a game to try other branches, it should cache those results to make things faster. If you do want to force GTP to clear the cache, a "clear_cache" GTP command exists.

But the better option is you should simply choose a cache size that is not too large for your system to handle. Besides, having a very large cache size shouldn't have *that* much improvement on performance. 2^24 = 16 million versus using instead 8 million or 4 million probably will only have a minor effect, you can try benchmarking it.

If you do observe that the memory grows unboundedly even with a much smaller cache size, then there is something wrong that I would look into, let me know.

**Comment by lightvector** [comment]
This seems handled, and also `./katago genconfig` also now since the last few releases of KataGo provides a somewhat more convenient way to set the this value for the user automatically, so closing this issue.

**Comment by wmbr** [comment]
I have experienced a similar issue when running katago (1.8.1, OpenCL) via Sabaki (GTP).
Even with nnCacheSizePowerOfTwo = 15, the RAM usage of katago keeps slowly rising (reaching at least 4GiB). Interestingly, issuing "clear_cache" does not free up noticeable amounts of memory.

**Comment by lightvector** [comment]
Are you having it do hundreds of thousands or millions of playouts on a single turn, letting it search longer and longer? Setting the nn cache size will control how much memory is used for *caching* old results, but it will always have to use however much memory it needs to use for an ongoing search right now, which will always keep growing as the search tree keeps getting larger.

It's also possible that whatever tool you're using to inspect memory usage, or the memory allocator, for some reason, doesn't actually free memory back to the OS, or doesn't report freed stuff back to the OS, even though internally all the memory is now freed and (e.g.) would not continue growing after a cache clear and a fresh new search since the true usage is now far below the nominal amount.

It's also possible there is some sort of leak, or fragmentation, but it's been a while since I've noticed any mem leak or fragmentation issue.

**Comment by wmbr** [comment]
>  it will always have to use however much memory it needs to use for an ongoing search right now, which will always keep growing as the search tree keeps getting larger.

This memory would be freed after every move played, right?
I was testing a series of successive games separated by `clear_board` commands and the memory usage was rising continuously.

> It's also possible that whatever tool you're using to inspect memory usage, or the memory allocator, for some reason, doesn't actually free memory back to the OS, or doesn't report freed stuff back to the OS, even though internally all the memory is now freed and (e.g.) would not continue growing after a cache clear and a fresh new search since the true usage is now far below the nominal amount.

It does continue growing after `clear_cache`, so no.
