### ISSUE TITLE
suggest to save images in jpg format instead of png to cut down the size of source zip file

### ISSUE THREAD

**Issue by l1t1** [lightvector/KataGo#144]
eg
 148,237 bytes 19k.jpg
 217,673 bytes 19k.png

**Comment by lightvector** [comment]
Maybe I'll just remove some older no-longer-used images. It only saves a few percent though in total, though.

**Comment by lightvector** [comment]
Actually it saves a bit more than that, since almost all of the images can be removed. Done!

**Comment by lightvector** [comment]
(Not bothering to convert the grand total remaining *2* images to jpg, that's not much space usage anyways)
