### ISSUE TITLE
chinese-ogs rule?

### ISSUE THREAD

**Issue by trunterzx** [lightvector/KataGo#145]
Hi all!

I'm trying out the new release of KataGo.

I saw in the list of possible rules that there is a "chinese rule" and there is a "chinese-ogs rule".
Just curious, may I know what is special about the "chinese-ogs rule"?

**Comment by Hersmunch** [comment]
See https://github.com/lightvector/KataGo/blob/master/docs/GTP_Extensions.md. Amongst others there are these:

- chinese : Equivalent to {"hasButton":false,"ko":"SIMPLE", "scoring":"AREA", "suicide":false,"tax":"NONE","whiteHandicapBonus":"N"}

- chinese-ogs : Equivalent to {"hasButton":false,"ko":"POSITIONAL", "scoring":"AREA", "suicide":false,"tax":"NONE","whiteHandicapBonus":"N"}

- chinese-kgs : Equivalent to {"hasButton":false,"ko":"POSITIONAL", "scoring":"AREA", "suicide":false,"tax":"NONE","whiteHandicapBonus":"N"}

Use https://lightvector.github.io/KataGo/rules.html to get full descriptions.

**Comment by trunterzx** [comment]
Hmm so the difference is in the ko judgement... Thanks!
