### ISSUE TITLE
How to compile the latest version on MAC

### ISSUE THREAD

**Issue by dappstore123** [lightvector/KataGo#149]
How to compile the latest version on MAC？
brew install katago。version is 1.3.2。
but i want use latest version 。

**Comment by anotheros** [comment]
Clone this repo:
git clone https://github.com/lightvector/KataGo.git
Compile using CMake and make in the cpp directory:
cd KataGo/cpp
cmake . -DBUILD_MCTS=1 -DUSE_BACKEND=OPENCL or cmake . -DBUILD_MCTS=1 -DUSE_BACKEND=CUDA depending on which backend you want. Specify also -DUSE_TCMALLOC=1 if using TCMalloc. Compiling will also call git commands to embed the git hash into the compiled executable, specify also -DNO_GIT_REVISION=1 to disable it if this is causing issues for you.
make
