### ISSUE TITLE
LAMB

### ISSUE THREAD

**Issue by lukaszlew** [lightvector/KataGo#15]
I'd like to point your attention to a robust LAMB algorithm:
https://arxiv.org/pdf/1904.00962.pdf

**Comment by lightvector** [comment]
Thanks! It looks like this is not necessarily immediately relevant to this project, as it seems to be about how to improve how training scales with very large batches, which comes up in the situation when you have a very large amount of parallel compute on the neural net training side across many GPUs/TPUs and therefore need large batches to be able to optimally use the hardware, as opposed to when training is only on one or a few GPUs and batch sizes cannot be so large anyways. For Go, most of the compute cost is on the self-play side for data generation, which is also already highly parallelizable.

Nonetheless, it is interesting - thanks!

**Comment by lightvector** [comment]
Thanks! It looks like this is not necessarily immediately relevant to this
project, as it seems to be about how to improve how training scales with
very large batches, which comes up in the situation when you have a very
large amount of parallel compute on the neural net training side across
many GPUs/TPUs and therefore need large batches to be able to optimally use
the hardware, as opposed to when training is only on one or a few GPUs and
batch sizes cannot be so large anyways. For Go, most of the compute cost is
on the self-play side for data generation, which is also already highly
parallelizable.

Nonetheless, it is interesting - thanks!
