### ISSUE TITLE
Error loading or parsing model file katanetwork.bin: Could not open file - does not exist or invalid permissions?

### ISSUE THREAD

**Issue by DecrosCZ** [lightvector/KataGo#151]
Hello, could anyone help me? The title is what the Lizzie console says after i downloaded 1.3.3. with one of the latest networks, i tried all the formats .bin, .gz, .bin.gz, all of which return this error

**Comment by lightvector** [comment]
Given that you closed this, I presume it was solved, but if not, let me know if there are any remaining questions here.

**Comment by DecrosCZ** [comment]
Yea, i solved it by extracting the model file from the .bin.gz network file in the lizzie folder, is that equivalent? won't the network lose anything from its strength?

**Comment by lightvector** [comment]
If it loads correctly, and it's the model file you wanted to use, it should be fine.
