### ISSUE TITLE
More weights around 20bs191 is kindly needed

### ISSUE THREAD

**Issue by alphaladder** [lightvector/KataGo#152]
@lightvector  

The handicap games of GO are very important for our amateur players .In our QQ discusssion group , we found  that the previous s191 weight has more powerful handicap ability rather than latest s243 weights via various test games between human. Vs katago 20b, although its Elo is obvious lower than s243, thus it suggested  the weights around s191 may be valuable for handicap games .
Would you mind release several weights around 20b s191? Such as 190,192 and so on.... Very appreciated.

**Comment by lightvector** [comment]
At some point, I'll upload everything, but for now I might be able to do some point releases, sure. Let me see about that.

**Comment by alphaladder** [comment]
> At some point, I'll upload everything, but for now I might be able to do some point releases, sure. Let me see about that.

Thanks a lot. Actually,the release of 1 or 2 weights around 191 at this time may be easier for the fans who are interested in handicap game to make some comparison .

**Comment by lightvector** [comment]
Two more have been posted at https://d3dndmfyhecmj0.cloudfront.net/g170/neuralnets/index.html:

g170-b20c256x2-s1856587264-d425711436
g170-b20c256x2-s1982992896-d447159308

Does this help?

**Comment by alphaladder** [comment]
> Two more have been posted at https://d3dndmfyhecmj0.cloudfront.net/g170/neuralnets/index.html:
> 
> g170-b20c256x2-s1856587264-d425711436
> g170-b20c256x2-s1982992896-d447159308
> 
> Does this help?

@lightvector Thousands of thanks!,You are so great!

**Comment by lightvector** [comment]
Closing this since it seems handled, please reply back or open another issue if you have further requests. Enjoy!
