### ISSUE TITLE
suggest to add printsgf

### ISSUE THREAD

**Issue by kennychenfs** [lightvector/KataGo#157]
I am trying to make my computer as a server and my phone as a client to play go, but katago doesn't have the printsgf tool.  I can't get game record directly. Printsgf will be very useful.

**Comment by lightvector** [comment]
Thanks. I will look into implementing this.

**Comment by lightvector** [comment]
printsgf is implemented in master branch now, and will be included in next release.
https://github.com/lightvector/KataGo/commit/15e4288f684f77ccd78900c67dccf2b7a0afad28

**Comment by kennychenfs** [comment]
it breaks.
terminate called after throwing an instance of 'IOError'
  what():  Could not parse rules: StoneScoring

**Comment by lightvector** [comment]
Thanks, I know what the bug is. I'll push out a quick bugfix release soon.

**Comment by lightvector** [comment]
Should be fixed now: https://github.com/lightvector/KataGo/releases/tag/v1.3.5

Let me know if you find any further issues!
