### ISSUE TITLE
CL_MEM_OBJECT_ALLOCATION_FAILURE

### ISSUE THREAD

**Issue by cleinias** [lightvector/KataGo#166]
I had katago/OpenCl version 1.3.3 working on my oldish Linux system (Xeon/16GB RAM/Quadro2000 GPU)  as of a few hours ago, but now it crashes with a memory allocation failure 

`(what():  OpenCL error at /home/dwugcloud/data/kata/cpp/neuralnet/openclbackend.cpp, func err, line 1115, error CL_MEM_OBJECT_ALLOCATION_FAILURE)`

Any idea about the sudden change in behavior?

**Comment by lightvector** [comment]
Well, if it failed to allocate memory, maybe your GPU somehow ran out of memory? Do you have other things running at the same time? Games/videos/other bots/lots of other programs? Does a reboot help?

**Comment by cleinias** [comment]
Actually, this happened right after a reboot, that's why I'm puzzled, I'll do some further tests

**Comment by cleinias** [comment]
Well, it seems the issue indeed was (and remains) the reboot. That is, after a routine update that involved  the Linux kernel and the nvidia drivers, katago has stopped working with the mem allocation error. I have an older card (Quadro 2000), which requires nvidia's legacy 390xx driver, that may be the problem.  Reainstalling drivers and opencl libraries did not help. I seem to be out of luck at his point. Just for the record, here is what nvidia-smi reports:

`Sun Mar 15 13:34:21 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.132                Driver Version: 390.132                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro 2000         Off  | 00000000:03:00.0  On |                  N/A |
| 39%   74C    P0    N/A /  N/A |    322MiB /   962MiB |      5%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       922      G   /usr/lib/Xorg                                144MiB |
|    0      1430      G   /usr/bin/kwin_x11                              6MiB |
|    0      1432      G   /usr/bin/plasmashell                         152MiB |
+-----------------------------------------------------------------------------+
`
So, 640Mb of GPU's RAM available. I tried to run the tests with no X system running and almost all GPU's RAM available and got the same error. So this seems to be a bug in the driver/opencl libs

**Comment by cleinias** [comment]
On the other hand, LeelaZero seems not to have issues after the update, so I am not sure the responsibility is the driver's only

**Comment by cleinias** [comment]
Compiling katago from source solved the issue (I was using the precompiled binaries when getting the error).
