### ISSUE TITLE
analysis engine hangs forever on wrong file type .txt.gz vs .bin.gz

### ISSUE THREAD

**Issue by sanderland** [lightvector/KataGo#167]
I renamed my models to shortname.gz, and the new 1.3.3 version insists on a .txt/.bin extension. When I guessed this wrong, the analysis engine hangs forever in loading.

**Comment by lightvector** [comment]
Yes, KataGo uses the extension to determine how to load the file, please don't change it. As for hanging forever if you do change it, I may investigate that at some point. Thanks!

**Comment by sanderland** [comment]
got it, 1.3.2 was fine with it, so was a bit surprised and took me a while to figure out what was wrong.
in any case, the analysis engine is great and has made developing something on top of kata much nicer than gtp analysis.

**Comment by lightvector** [comment]
This is fixed in tip of master now, along with some improvements to some of the error messages. Thank you for the report! This will go out next release.

https://github.com/lightvector/KataGo/commit/2d05257759c5de1d5a0198f4b83b3cebc047773e

**Comment by lightvector** [comment]
Released.
