### ISSUE TITLE
[feature request] clear_search GTP command

### ISSUE THREAD

**Issue by y-ich** [lightvector/KataGo#168]
Hi.
Thank you for your great project!

When you study SGF kifus, you may go back and forth in its play sequence.
When you go back one play move, you need to "clear_cache" command as well as "undo", otherwise previously searched nodes mislead you with overestimated visit numbers.
But clear_cache clears not only search but also cache as its name.
NN Cache should work well after going back one play move.
So I think "clear_search" command, which executes only bot->clearSearch(), will work well for studying.
(Actually I already experiment and it seems work well.)

What do you think about this?

Or executing bot->clearSearch() in "undo" command may satisfy my request.

**Comment by lightvector** [comment]
Undo does already clear the search. Do you observe anything different?

**Comment by y-ich** [comment]
Really?

I am sorry my confusion.
I will confirm the behavior.

**Comment by y-ich** [comment]
I confirmed it.

My mistake was setting break point at AsyncBot::clearSearch to check it.
So I miss search->clearSearch in Search::setPosition.
