### ISSUE TITLE
feature request: merge cuda and opencl engine files

### ISSUE THREAD

**Issue by ivysrono** [lightvector/KataGo#169]
Most of users don't know whether their PCs support CUDA, so it's hard toinstall the best performance KataGo for them.

Merge engines, use cuda if possible, else use opencl.

**Comment by yishn** [comment]
No, we don't include engine binaries in Sabaki.

**Comment by lightvector** [comment]
Actually, users should use OpenCL unless they have an NVIDIA 20xx card. Even if they have CUDA, OpenCL will usually be faster.

Merging the two implementations is probably just not going to happen. The code is not written in a way that this would be easy, and even if it were, many ways of doing this could possibly result in users who only wanted to use OpenCL have the libraries and dependencies for CUDA installed in order for the executable to compile or link or run properly, which would be silly.

The only reason to use CUDA right now is the tensor cores. I'm hoping that will change if OpenCL also implements tensor cores. Then there may be no reason at all to use CUDA and everyone can just use OpenCL.

**Comment by ivysrono** [comment]
Thank you very much.
