### ISSUE TITLE
‘dwt-default_network_path-rebased ’Compile error

### ISSUE THREAD

**Issue by luckyangman** [lightvector/KataGo#175]
Error in compiling ‘dwt-default_network_path-rebased ’

**Comment by iopq** [comment]
needs a little bit more detail, like OS, compiler, what command you tried and the whole error message

**Comment by luckyangman** [comment]
![QQ20200323201743](https://user-images.githubusercontent.com/33744438/77316039-99469e80-6d43-11ea-8bbc-f7cc32e82567.png)

**Comment by lightvector** [comment]
Thanks, but keep in mind I explicitly said the feature is not tested on Windows and that is why I haven't merged yet. I will test it and fix compile when I have the time. In the meantime, there is no need for this issue.

**Comment by lightvector** [comment]
Which is to say, please be patient. When I push a branch that is explicitly _work-in-progress_ don't rush, just let me continue the work in progress. 
:)

**Comment by luckyangman** [comment]
Got it, thank you!
