### ISSUE TITLE
2019“CHINA SECURITIES Cup” The World AI Weiqi Open

### ISSUE THREAD

**Issue by poptangtwe** [lightvector/KataGo#18]
Will KataGo participate in the competition?

-----

http://sports.sina.com.cn/go/2019-05-31/doc-ihvhiews6020777.shtml?cre=tianyi&mod=pcpager_focus&loc=22&r=9&rfunc=100&tj=none&tr=9

ALLOWANCE：
Free accommodation is up to 2 people per team。 Traveling allowance is shown as below：
- Asia： 10000 Yuan for each team。
- Rest region of the world： 20000 Yuan for each team。

PRIZES：
Total bonus： 800，000 ¥ before tax。
Rank | 1 | 2 | 3 | 4 | 5-8
Prize（Yuan） | 450，000 | 150，000 | 60，000 | 40，000 | 20，000
Human-AI Pair Weiqi competition： The top eight AI teams in the preliminary competition will be paired with a human player。 The knock-out system is adopted。 The winner will be rewarded with 20，000 RMB in total。（AI team and human player is awarded 10，000 RMB each）

**Comment by lightvector** [comment]
Neat. Probably not this time around, although I entirely wouldn't rule out something like this in the future.
