### ISSUE TITLE
Have any ideas or plans to let katago participate in the world intelligent go open?

### ISSUE THREAD

**Issue by LangChuang** [lightvector/KataGo#181]
Hello! David! I'm a katago fan from China, and I also like playing go. To be honest, you are my idol!
Do you have any ideas or plans to let katago participate in the world intelligent go open? 

I think katago's level of handicap is likely to exceed fineart now. It has a strong computing power and 60b fineart. Although fineart spend a lot of money to develop, but we all guess that katago has surpassed  fineart in algorithm level.
Of course, we can use such excellent go AI, which is really a very happy thing!
Be careful of covid-19!Have a good day!

**Comment by lightvector** [comment]
Was there a reason you closed this?

When is the competition you refer to normally scheduled?

**Comment by LangChuang** [comment]
I don't know much about GitHub. I thought I could only ask about program technology, so I'll reopen it now
I'm talking about the game organized by the international go Federation. It's not UEC. Fineart won't take part in UEC, because UEC's AI is too weak
Last year's competition was held in Rizhao City, Shandong Province, China. Fineart was the champion, leelazero was the fourth (weight: 239), fineart (or alphago) is the strongest go AI we think now. Fineart is only used by Chinese go teams. We really hope that katago will get better and better and prove that katago can be used in the competition. The top three AI of that game can't be used by ordinary people. Katago is open source, And it has the most functions
If katago wants to win the world championship, it will meet fineart. Tencent is very rich, so the computing power of the computer is too strong. To beat it, it must be better than fineart in algorithm. Of course, katago also has to do its best to prepare the maximum computing power, which is very important
Because the function of katago is the most practical. If you reach the level of world champion, it's really a great thing. Everyone will choose to use katago and everyone can use it

**Comment by OmnipotentEntity** [comment]
https://www.usgo.org/news/2019/10/the-power-report-fineart-wins-computer-ai-go-tournament-hane-takes-gosei-title-shibano-wins-meijin-title/

This seems to be what @LangChuang is referring to.  It seems like last year's tournament was held from August 21-25.  It was previously mentioned in issue #18 

I haven't been able to find any English language news source or similar describing when or even if an AI tournament will be held this year.

**Comment by lightvector** [comment]
For those who stumble on this from Google search or whatever later, see https://github.com/lightvector/KataGo/issues/320 for a more detailed thread.
