### ISSUE TITLE
randomise opening

### ISSUE THREAD

**Issue by oldnewsbigfry** [lightvector/KataGo#183]
hi,

What are some good settings for randomising the opening moves?

On leelazero '-m 30' would randomise the first 30 moves, pick from top candidates.

If I wanted it to randomly pick between 3 or 4 top moves in the search for about the first 30 moves what would be some good settings?

From the config file I found these options below but I'm not sure if these are good defaults, and how long is 'early game'?

Thanks in advance for any help.

# Temperature for the early game, randomize between chosen moves with this temperature
# chosenMoveTemperatureEarly = 0.5
# Decay temperature for the early game by 0.5 every this many moves, scaled with board size.
# chosenMoveTemperatureHalflife = 19
# At the end of search after the early game, randomize between chosen moves with this temperature
# chosenMoveTemperature = 0.10
# Subtract this many visits from each move prior to applying chosenMoveTemperature
# (unless all moves have too few visits) to downweight unlikely moves
# chosenMoveSubtract = 0
# The same as chosenMoveSubtract but only prunes moves that fall below the threshold, does not affect moves above
# chosenMovePrune = 1

**Comment by lightvector** [comment]
Yes, I would also say just leave it on the default unless in actual practice you notice some issue.

**Comment by lightvector** [comment]
Nothing to address here right? And since all the defaults are working fine it's not clear to me that other users beneift from seeing this issue, so closing it. Please reply back if you do have more questions, thanks!

**Comment by kennychenfs** [comment]
How long is early game?
Or at least, is it a fixed number or decided by katago?

**Comment by lightvector** [comment]
> Decay temperature for the early game by 0.5 every this many moves, scaled with board size.
> chosenMoveTemperatureHalflife = 19
