### ISSUE TITLE
kata-analyze in Sabaki v0.50.1

### ISSUE THREAD

**Issue by knodakip** [lightvector/KataGo#184]
Hi, 

Is there a way to make kata-analyze command as default in Sabaki?
Currently when i run "Toggle analysis" it systematically uses lz-analyze command.

Also, there is no outputted lines in the side engine bar only = info move (…) is displayed
It might be very convenient to show for each move : visits, winrate, scoreMean

Sorry if this is a request to be handled on the Sabaki github side :)

Thanks

**Comment by lightvector** [comment]
Yes, this should be a Sabaki task. Recently KataGo implemented a specific protocol command to make things easier for Sabaki devs (where for technical reasons they preferred to do their engine commands/parsing a little differently that made it harder for them to use kata-analyze). This change was released by KataGo in v1.3.4 just 3 days ago, but I'm guessing there is still a bit of work for Sabaki to do to use that protocol command.

**Comment by knodakip** [comment]
Thanks for the quick reply.
