### ISSUE TITLE
Game counter in selfplay resets after changing networks

### ISSUE THREAD

**Issue by iopq** [lightvector/KataGo#185]
When I `touch`ed a network in the models folder, katago switched to it, then switched back to the previous model when that folder got moved back. To my surprise, it said "Started 100 games" which means it will play more games total than my selfplay.cfg allows it.

First of all, it's weird it did anything when I specifically called kill -STOP on the process before running other tests. But maybe it takes time to actually stop? This doesn't concern me too much.

The real issue is that that count should be cumulative, otherwise switching networks can potentially never reach the max (then what's the point of having the max value?)

**Comment by lightvector** [comment]
Thanks for the note! Sorry yes, this is a bug that I had realized not too long ago too. The very first commit of the [distributed branch](https://github.com/lightvector/KataGo/tree/distributed) or the (distributed-rebase-to-v1.3.5 branch)[https://github.com/lightvector/KataGo/tree/distributed-rebase-to-v1.3.5] that I pushed just now fixes this as a byproduct of some of the other refactors it does to the selfplay logic to prepare for distributed selfplay training.

I don't know for sure if the branch breaks something else in the process of these refactors - it hasn't been tested yet, which is partly why I've left it in a separate branch. If you need this specific bugfix but also don't mind helping to test out if this branch still works and didn't break anything, you can try it. Or you can cherry-pick the very first commit in one of those branches. Or you can just take a look at the diff from the very first commit and see how the fix works, and just add the few lines to do it without using the rest of the refactor for now. Namely, you just load the value in the selfplay.cpp main command, make an atomic counter to count games started, fetch_add the counter inside `gameLoop`, and a check inside gameLoop to break the loop if exceeding this the max.
```
const int64_t maxGamesTotal = cfg.getInt64("numGamesTotal",1,((int64_t)1) << 62);
...
std::atomic<int64_t> numGamesStarted(0);
...
int64_t gameIdx = numGamesStarted.fetch_add(1,std::memory_order_acq_rel);
...
(check and break loop)
```

Does that help? I'll merge more of the distributed branch in to master officially before too long, when I can do more testing myself.

**Comment by lightvector** [comment]
By the way, I don't know how you manage viewing the git log and exploring the revision graph to see how different branches relate, and being able to cherry-pick revisions and things like that, but in case you don't already have your own solution worked out, the following alias in my .gitconfig I've found to be very, very useful for making a good command-line display:

`glog = log --color --graph --all --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit`

**Comment by lightvector** [comment]
Just an update: this is fixed in master as of maybe a week ago, along with the further changes this week I pushed to how the self-play scripts work to accomodate the "official" synchronous loop example.
