### ISSUE TITLE
Problem Tuning

### ISSUE THREAD

**Issue by ZeMannFred** [lightvector/KataGo#189]
Hello, 
I tried to install Katago on Sabaki, I arrived on the tuning section with tuning done but F4 (to toggle analysis doesn't work)

I viewed a video with explication which said to use a benchmark command and in the end, I have this error : 
Uncaught exception: Could not create file: C:\Program Files\Sabaki\katago/KataGoData/opencltuning/tune6_gpuIntelRUHDGraphics620_x19_y19_c256_mv8.txt
and that stop, so I don't know what to do.

Regards and thanks for your work

PS: I used a windows 10 with katago-v1.3.5-opencl-windows-x64.zip

**Comment by lightvector** [comment]
Windows often restricts permissions of programs to write to subdirectories for Program Files unless they are running with admin privileges, so KataGo is probably not being allowed to store its tuning data.

You could run KataGo with admin privileges but that seems ugly. So try putting KataGo in a different place, entirely outside of the Program Files directory. If that works with the benchmark command, then you should be good to go, just make sure to update your Sabaki paths to point to the new location.

**Comment by ZeMannFred** [comment]
Ok thanks, this is the solution. It works !
