### ISSUE TITLE
Overfitting again

### ISSUE THREAD

**Issue by michito744** [lightvector/KataGo#192]
Hello, thank you for developing.

I use KataGo 30block (g170).
It's very strong compared to the g104 and can select a good choice of moves.

However, there are rare cases of overfitting, and there is always a phase where a move that is not difficult for humans is overlooked.
It tends to occur in a clearly dominant phase and is easy to spot if the procedure is slightly different.

Example: 58th 10-dan title 2nd match:

Move247, g170 can't find correct move248.
![2020-04-10](https://user-images.githubusercontent.com/53891655/78974042-0d5ab200-7b4c-11ea-8ca1-2f4f9552b29f.png)

Evaluation
![2020-04-10 (1)](https://user-images.githubusercontent.com/53891655/78974157-5a3e8880-7b4c-11ea-871a-180719ed8907.png)

If it is actually embarked upon, it is assessed correctly.
![2020-04-10 (2)](https://user-images.githubusercontent.com/53891655/78974189-63c7f080-7b4c-11ea-8b9f-c377ddbaf867.png)

Move245: g170 can find move P4. Why!?
![2020-04-10 (3)](https://user-images.githubusercontent.com/53891655/78974207-72160c80-7b4c-11ea-8466-ee27a4f5a7e8.png)

**Comment by isty2e** [comment]
There are certainly many blind spots (both policy-originated and value-originated) in KataGo, but it is not necessarily because of overfitting. It is more like a consequence of underexploration, which may or may not be resolved as training progresses. An example of overfit networks would be something like ELF.

**Comment by michito744** [comment]
Does providing examples of the blind spots you found help to strengthen KataGo?

**Comment by michito744** [comment]
Does providing examples of the blind spots I found help to strengthen KataGo?

**Comment by isty2e** [comment]
Not likely now, since the self-play and training are still purely zero. Later when we go distributed, KataGo might start self-playing starting from blind positions.

**Comment by lightvector** [comment]
I'm pretty sure the final net of this run actually handles this particular position reasonably well now, so I'm going ahead and closing this issue. Thanks again!
