### ISSUE TITLE
Radeon RX 5700 XT OpenCL implementation is broken, do not use it for any Go engines

### ISSUE THREAD

**Issue by Apitheia** [lightvector/KataGo#199]
katago-v1.3.5-opencl-windows-x64

Windows 10 with a Radeon RX 5700 XT with Radeon Software Version 20.4.1 and OpenCL 2.0

Running benchmark or genconfig results in the following:

PS C:\Downloads\katago-v1.3.5-opencl-windows-x64> .\katago.exe benchmark -model .\g170e-b20c256x2-s3354994176-d716845198.bin.gz
2020-04-13 13:10:33-0600: Loading model and initializing benchmark...
2020-04-13 13:10:33-0600: nnRandSeed0 = 18415835870781179748
2020-04-13 13:10:33-0600: After dedups: nnModelFile0 = .\g170e-b20c256x2-s3354994176-d716845198.bin.gz useFP16 auto useNHWC auto
2020-04-13 13:10:33-0600: Found OpenCL Platform 0: AMD Accelerated Parallel Processing (Advanced Micro Devices, Inc.) (OpenCL 2.1 AMD-APP (3004.8))
2020-04-13 13:10:33-0600: Found 1 device(s) on platform 0 with type CPU or GPU or Accelerator
2020-04-13 13:10:33-0600: Found OpenCL Device 0: gfx1010 (Advanced Micro Devices, Inc.) (score 11000200)
2020-04-13 13:10:34-0600: Using OpenCL Device 0: gfx1010 (Advanced Micro Devices, Inc.) OpenCL 2.0 AMD-APP (3004.8)
2020-04-13 13:10:34-0600: No existing tuning parameters found or parseable or valid at: C:\Downloads\katago-v1.3.5-opencl-windows-x64/KataGoData/opencltuning/tune6_gpugfx1010_x19_y19_c256_mv8.txt
2020-04-13 13:10:34-0600: Performing autotuning
2020-04-13 13:10:34-0600: Found OpenCL Platform 0: AMD Accelerated Parallel Processing (Advanced Micro Devices, Inc.) (OpenCL 2.1 AMD-APP (3004.8))
2020-04-13 13:10:34-0600: Found 1 device(s) on platform 0 with type CPU or GPU or Accelerator
2020-04-13 13:10:34-0600: Found OpenCL Device 0: gfx1010 (Advanced Micro Devices, Inc.) (score 11000200)
2020-04-13 13:10:34-0600: Using OpenCL Device 0: gfx1010 (Advanced Micro Devices, Inc.) OpenCL 2.0 AMD-APP (3004.8)
Setting winograd3x3TileSize = 4
------------------------------------------------------
Tuning xGemmDirect for 1x1 convolutions and matrix mult
Testing 56 different configs
0x00007FFB1C4B6F29 (0x0000020504164560 0x000002057EEB76F0 0x0000020504164560 0x000000000000014B), amd_comgr_symbol_lookup() + 0x1305889 bytes(s)
0x00007FFB1C978BAF (0x000002057EAFC6A0 0x000000D171FEFB30 0x0000000000000001 0x0000000000000001), amd_comgr_symbol_lookup() + 0x17C750F bytes(s)
0x00007FFB1C979D74 (0x000002057EAFC610 0x000002057EEB76F0 0x000002057EA38F90 0x000002057ECDA2B8), amd_comgr_symbol_lookup() + 0x17C86D4 bytes(s)
0x00007FFB1C8CD628 (0x0000000000000000 0x0000000000000000 0x000000000000005F 0x0000000000000004), amd_comgr_symbol_lookup() + 0x171BF88 bytes(s)
0x00007FFB1D16C9D2 (0x000002057ED45330 0x0000020574F82B20 0x00000205041E2C01 0x0000020500000000), amd_comgr_symbol_lookup() + 0x1FBB332 bytes(s)
0x00007FFB1CE03EBF (0x000002057ED44FD0 0x0000000000000000 0x000002057ED45330 0x00007FFB00000000), amd_comgr_symbol_lookup() + 0x1C5281F bytes(s)
0x00007FFB1CE03B7B (0x00000205041E2F01 0x000000D171FF0360 0x0000000000000000 0x0000020574F82B28), amd_comgr_symbol_lookup() + 0x1C524DB bytes(s)
0x00007FFB1CE04A87 (0x0000020574F82C00 0x0000000000000000 0x000002057E932C70 0x000002057ED44FD0), amd_comgr_symbol_lookup() + 0x1C533E7 bytes(s)
0x00007FFB1D16CED1 (0x000002057F085300 0x000002057F084F00 0x00007FFB7F085300 0x0000000000000012), amd_comgr_symbol_lookup() + 0x1FBB831 bytes(s)
0x00007FFB1D16C6C0 (0x00007FFB1DE76638 0x000000D171FF06D0 0x0000000000000000 0x0000000000000000), amd_comgr_symbol_lookup() + 0x1FBB020 bytes(s)
0x00007FFB1B1FEC12 (0x000000D171FF09B0 0x0000000000000005 0x000000D171FF0B30 0x0000000000000000), amd_comgr_symbol_lookup() + 0x4D572 bytes(s)
0x00007FFB1B20150E (0x0000020574FB29D0 0x0000020574DB4110 0x000002056E742C30 0x0000020576CAC510), amd_comgr_symbol_lookup() + 0x4FE6E bytes(s)
0x00007FFB1B1C6028 (0x0000000000000000 0x000002056E820000 0x0000000000000000 0x0000000000000000), amd_comgr_symbol_lookup() + 0x14988 bytes(s)
0x00007FFB1B507CAF (0x0000020574D89AB0 0x000000D171FF0DE0 0x000002057ECC1020 0x0000020574D89AB0), amd_comgr_symbol_lookup() + 0x35660F bytes(s)
0x00007FFB1B4F6F0E (0x0000020574F0D770 0x000000D100000000 0x0000020574D89AB0 0x0000020574D89AB0), amd_comgr_symbol_lookup() + 0x34586E bytes(s)
0x00007FFB1B1C26ED (0x0000020574F0D770 0x0000020574D89AB0 0x000002057E91B748 0x0000020575036780), amd_comgr_symbol_lookup() + 0x1104D bytes(s)
0x00007FFB1B1A5145 (0x000000D171FF1AA8 0x000002057E91B6C0 0x0000020574DECD00 0x0000020574DECD00)
0x00007FFB1B1A7F86 (0x000002057ECC0060 0x000002057ECC37A0 0x000000D171FF21D0 0x00007FFB1D3C094C)
0x00007FFB1B1A835C (0x000002057ECC0060 0x0000020500000007 0x000000D171FF2538 0x000002057ECC0060)
0x00007FFB1B1A44CF (0x000002057EB47A70 0x000002057EB47A70 0x000002057ECBFCE0 0x0000020500000000)
0x00007FFB1B1B007E (0x0000020500000006 0x0000020574F72F10 0x000002057EB47A70 0x0000000000000000), amd_comgr_do_action() + 0x9DE bytes(s)
0x00007FFB3B079075 (0x0000000000000033 0x0000020576CAB5C0 0x000000D171FF2E00 0x000002057EB61101), clGetPipeInfo() + 0x28605 bytes(s)
0x00007FFB3B0811F3 (0x0000000000000000 0x0000020576CAB5C0 0x000002057EB47A70 0x0000000000000000), clGetPipeInfo() + 0x30783 bytes(s)
0x00007FFB3B077C60 (0x0000020500000000 0x000002057E8ED0F0 0x0000020576CCFE10 0x000002057E8ED0F8), clGetPipeInfo() + 0x271F0 bytes(s)
0x00007FFB3B06A072 (0x000002057504C460 0x000002056E69C9A8 0x0000020574FDE520 0x0000000000000000), clGetPipeInfo() + 0x19602 bytes(s)
0x00007FFB3B043FC9 (0x000000D171FF3650 0x000000D171FF3870 0x000000D171FF3870 0x000000D171FF3640), clBuildProgram() + 0xC9 bytes(s)
0x00007FF6B5CC1929 (0x000000000000000F 0x3D42444150442D00 0x000000D100310031 0x0000000000000000)
0x00007FF6B5CC606C (0x000002056E73C248 0x000000D171FF3A10 0x000000D171FF3A10 0x00007FFB753B8DE1)
0x00007FF6B5CC8262 (0x000002056E66FE90 0x00007FFB5C0210F0 0x00007FFB5C0210F0 0x00007FF6B5C53950)
0x00007FF6B5CC9A77 (0x00007FFB5C0210F0 0x000000D171FF3E00 0x0000000000000000 0x0000000000000000)
0x00007FF6B5CD4B3B (0x000002056E73C240 0x000000D171FF4220 0x000000D171FF3DF0 0x000000D171FF3BF0)
0x00007FF6B5CD677F (0x000000D171FF44A8 0x0000000000000000 0x000000D171FFF4E0 0x000000D171FF4680)
0x00007FF6B5CD2FA6 (0x000000D171FF46A0 0x0000000000000000 0x000000D171FF4810 0x0000000000000008)
0x00007FF6B5CBA473 (0x0000000000000013 0x0000000000000013 0x000000D171FF4870 0x000002057504D280)
0x00007FF6B5CB5E61 (0x000002056E69C7E0 0x000002056E69C7E0 0x000000D171FF4AA8 0x000000D171FF4AC8)
0x00007FF6B5CBC6AA (0x0000000000000000 0x000002056E69C8D0 0x0000000000000000 0x0000000000000014)
0x00007FF6B5CA813B (0x000000D171FFF420 0x0000000000000002 0x000000D171FF4CA0 0x0000000000000002)
0x00007FF6B5CF063E (0x000000D171FF4F58 0x000000D171FFF290 0x000000D171FF5400 0x0000000000000040)
0x00007FF6B5CED167 (0x000000D171FF5400 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF6B5D67C96 (0x000002056E652C70 0x00007FF6B5C5D0F3 0x000002056E69A6E0 0x0000000000000000)
0x00007FF6B5D646EC (0x000000000000003B 0x000002056E670B30 0x000002056E670B30 0x000002056E670B30)
0x00007FF6B5D6716E (0x000000D171FFFE90 0x0000000000000000 0x0000000000000004 0x00007FFB76E50000)
0x00007FF6B5DA3400 (0x00007FF6B5DC0B38 0x0000000000000004 0x0000000000000000 0x0000000000000004)
0x00007FF6B5DA3D51 (0x0000000000000000 0x0000000000000000 0x00007FFB7549B590 0x0000000000000000)
0x00007FF6B5DAAFDC (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FFB76E67BD4 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FFB77C0CED1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
PS C:\Downloads\katago-v1.3.5-opencl-windows-x64>

**Comment by lightvector** [comment]
AMD 5700 GPU series is buggy and their OpenCL implementation simply does not work for a lot of compute intensive applications. 

For example, see here where it also fails on a different distributed project:
https://www.reddit.com/r/Amd/comments/eblv26/psa_please_remove_your_amd_rx5700xt_from_setihome/

As far as I know, AMD hasn't released any fix, you simply can't rely on those GPUs for anything that uses OpenCL.

**Comment by lightvector** [comment]
See also this thread:
https://lifein19x19.com/viewtopic.php?f=18&t=17093

**Comment by lightvector** [comment]
I edited the title so that any future users seeing this thread will be warned, since this is a problem about this GPU that causes issues for not just KataGo, but also Leela Zero and also non-Go-related programs. It's been an open issue for many months - sadly if you bought such a GPU already, unless AMD suddenly comes out with a fix, it's probably only good for graphics and games, but not for neural nets or general numeric computation.

**Comment by Apitheia** [comment]
Well that sucks but thanks for letting me know.  I would have never thought to look for a problem with the driver.
