### ISSUE TITLE
Missing GTP command "undo"

### ISSUE THREAD

**Issue by kaorahi** [lightvector/KataGo#20]
The GTP command "undo" seems missing. It is widely used in GUIs (e.g. Lizzie).

~~~
$ git show --quiet --pretty=format:'%h%d'
fb23971 (HEAD -> opencl, origin/opencl)
$ git grep undo -- gtp.cpp
$ ./main gtp -model ../../g104-b6c96-s97778688-d23397744/model.txt.gz -config configs/gtp_example.cfg
play b d4
=

undo
? unknown command

~~~

**Comment by lightvector** [comment]
Thanks. The GTP spec indicated that the command was optional, but it makes sense that it would be very useful to have and heavily used. :)

Should be fixed:
https://github.com/lightvector/KataGo/commit/7c666db8031a5ae0d6449791174062e09a70c03b

Both opencl and master branches and the v1.1 release should now be updated. Poke me again if there are any problems.
