### ISSUE TITLE
Will KataGo be impacted by COVID-19

### ISSUE THREAD

**Issue by hydrogenpi** [lightvector/KataGo#202]
Not sure if this is asked before, but the understanding was that the KataGo was going to do a new run for a clean slate 40 block. Obviously this uses dozens if not hundreds of V100 GPU for a long time and a lot of resources. Given the macroeconomic effects and geopolitical implications of COVID-19, I'm not sure what the developer was relying on in order to train KataGo, if JaneStreet is sounds like a finance or FinTech firm? Could it be possible that the plans for KataGo in terms of the new runs will be put on hold or delayed or postponed due to the realities of COVID and the impeding economic doom of the world?  Or will KataGo still be able to achieve the new run and gain the strengths that it originally set out for itself pre-COVID?

**Comment by lightvector** [comment]
The current run is being paid for by me personally, and I already had a certain amount budgeted for it, and I have no plans to change that.

The next run, if it does actually happen, will be community-distributed, like LZ/SAI, so it will be up to people with their personal machines what they choose to contribute.
