### ISSUE TITLE
GPU performance improvement possibility (without CUDA)

### ISSUE THREAD

**Issue by 22nsuk** [lightvector/KataGo#204]
I checked the results in lc0 and found that using dx12 resulted in much faster results than opencl. Can this be applied to Katago?
If this is applicable, it will be of great help when distributed learning is implemented in the future.

**Comment by lightvector** [comment]
Not sure. I'm not excited about implementing an entire backend again myself - higher priority would certainly be to just get tensor cores working in OpenCL. But thanks for the heads up!

**Comment by 22nsuk** [comment]
Thank you for your reply. The way tensor cores are applied is also welcome. I always appreciate your quick feedback.
