### ISSUE TITLE
Does katago support the rules of Chinese ancient Go？

### ISSUE THREAD

**Issue by anchorite97** [lightvector/KataGo#206]
还棋头规则
My English is so poor that I have to use Chinese，sorry, thank you！

**Comment by lightvector** [comment]
KataGo does support penalizing every living group for 2 points ("group tax"), in combination with any other possible rules settings.
Choose `taxRule=ALL` in the config.

**Comment by anchorite97** [comment]
Thank you very much! Your great work！
