### ISSUE TITLE
Is it possible to support non-edge and non-corner boards?

### ISSUE THREAD

**Issue by llNoahll** [lightvector/KataGo#207]
Normal 19*19 board has edge and corner, which means:
       (0, 5) locate on a edge, so it connects to (0, 4), (0, 6), (1, 5)
       (0, 0) locate on a corner, so it connects to (0, 1), (1, 0)

a 19*19 cylinder shape board (non-corner board) behaves like this:
       (0, 5) connects to (0, 4), (0, 6), (1, 5)
       (0, 0) connects to (0, 1), (1, 0), (18, 0)

a 19*19 sphere shape board (non-edge board) behaves like this:
       (0, 5) connects to (0, 4), (0, 6), (1, 5), (18, 5)
       (0, 0) connects to (0, 1), (1, 0), (18, 0), (0, 18)

**Comment by lightvector** [comment]
Sure. Would require modifying the neural net GPU implementation (to use this boundary condition), making the minor tweak to implement this boundary condition also in the board logic, and then doing a new-self-play run to train the neural net. So, quite expensive, but doable.

By the way, you don't get a sphere when you wrap both the horizontal and vertical edges. You get a different shape. :P

https://simomaths.files.wordpress.com/2013/03/quotient_torus.png

**Comment by llNoahll** [comment]
Thanks!

**Comment by lightvector** [comment]
Just to be clear - I'm probably not going to be doing this myself - doing a whole new training run for a variant that only a few people play would be quite a bit of work. But if someone else wanted to try such an experiment, I think it would be cool. :)

**Comment by alreadydone** [comment]
This post (along with my two comments at the bottom) may be interesting to you: http://goplayerjuggler.blogspot.com/2017/06/an-introduction-to-toroidal-go.html?m=1
