### ISSUE TITLE
analysis engine hard crashing

### ISSUE THREAD

**Issue by sanderland** [lightvector/KataGo#208]
related to https://github.com/sanderland/katrain/issues/11
possibly affects the gtp version as well.

I suspect there are simply some checks missing when allocating gpu memory, and the program hard crashes without output.

reproduce: start too many KataGo instances, particularly a bs29 running a 40b network.
expected: either an "Uncaught Exception" output or a helpful message.

**Comment by lightvector** [comment]
On other uncaught exceptions, do you get a message on the command line on your system? Like, if you just immediately throw at the start of the program, what do you see? For my linux system, I see the exception's message, and for Windows, there's an explicit bit in the code (`main.cpp`) that ensures it gets printed.

If it's simply adding more cases to the top level to print the exception, then that's an easy fix. But there are also some systems where the GPU drivers just hard-terminate the program if something bad happens, and then there's nothing I can do in the C++ - the function call doesn't even make it back to my C++ code.

Are you OpenCL or CUDA?

**Comment by sanderland** [comment]
For windows I am using the OpenCL binaries as provided. On Linux I compile it myself wiith CUDA and get a lot more output when things go wrong. This may just be the hard-termination.

**Comment by sanderland** [comment]
@lightvector someone is reporting seeing the analysis engine crashing in cases where the GTP engine does fine.

**Comment by sanderland** [comment]
Confirmed due to differences in batch size, closing.
