### ISSUE TITLE
Compiled KG engine for Mac OS

### ISSUE THREAD

**Issue by SHKD13** [lightvector/KataGo#213]
Could someone who already compiled the engine for Mac share it?
Or help with the compilation process.

**Comment by isty2e** [comment]
Using Homebrew is probably the easiest way of building KataGo on mac.

**Comment by SHKD13** [comment]
I know about Homebrew, but the man who asked me to help can't get the clue how to use it in practice? What to start from? 
Is it possible to give some simple step by step instructions which doesn't require special programming skills?

**Comment by syys96** [comment]
I have successfully compiled it on macOS, but Homebrew is easier to install katago in case of no programming knowledge

**Comment by lightvector** [comment]
It sounds like "use Homebrew" is the solution, so if nobody around here is able to give more detailed steps, and not me either (I'm not a Mac user), it seems you should just start by searching on line? For example: https://www.google.com/search?&q=mac+what+is+homebrew

**Comment by lightvector** [comment]
Presumably the person who asked for help ran into trouble at some specific point when trying to install it or whatever, so help them out or find someone to help on that specific step? But without knowing the specific step, it's hard to help.

**Comment by syys96** [comment]
Step by step instructions, open the terminal:
1.   Install Homebrew on macOS
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" 
2.  Install pre-compiled binary directly (recommended)
       brew install katago 
3.  Or compile from source anyway
       brew install git make cmake zlib libzip boost
       git clone https://github.com/lightvector/KataGo.git
       cd KataGo/cpp
       cmake . -DBUILD_MCTS=1 -DUSE_BACKEND=OPENCL -DNO_GIT_REVISION=1
       make
       Now you can the katago executable file in KataGo/cpp directory

**Comment by raultm** [comment]
@syys96  thanks for share the steps to compile from source. A High Sierra user using now katago thanks to you
