### ISSUE TITLE
KataGo doesn't start within Lizzie interface

### ISSUE THREAD

**Issue by Taaqa** [lightvector/KataGo#215]
Latested version of Leela Zero run fine with Lizzie GPU, also KataGo delivered within Lizzie 0.7.2 GPU.

Katago since 1.3 - including the latetest one 1.3.5 (CUDA 10.1 resp. OpenCl) still showing 'Engine is loading'.

Abbility to run the brenchmarks, the command used for lizzie is according the suggestion 'whatever/path/to/katago gtp -model whatever/path/to/<NEURALNET>.gz -config /whatever/path/to/<GTP_CONFIG>.cfg'.

System:
Win 10 Home, Version 1903 (Build 18362.778)
Intel Core i7-9750H, 16 GB RAM; Geforce RTX 2060, 6GB DDR6
CUDA 10.1 and cuDNN v7.6.4 (tested it works fine)
Microsoft Visual C++ 2015-2019 Redistributed (x64) - 14.23.27820

**Comment by lightvector** [comment]
When you say "Abbility to run the brenchmarks" did you mean that you _did successfully run the benchmarks directly on command line_ and KataGo autotuned itself and displayed its performance stats and seemed to be working?

If so, then you are probably just mistyping some file paths or something in Lizzie. Try directly running the exact same command you are giving to Lizzie on the command line, from Lizzie's folder, and see what is wrong. If it is working, you should get a message like "GTP ready, beginning main protocol loop" and then it will be waiting for further input. (type "quit" to quit).

**Comment by lightvector** [comment]
Also if you are unfamiliar with how to specify file paths, please take a look at this link where it also describes how you can put the model and config into the same directory as KataGo and if you name them the correct thing, KataGo will use them automatically without any paths specified: https://github.com/lightvector/KataGo#how-to-use

**Comment by Mbr18** [comment]
To get Lizzie working with the latest version:
-Copy of b30.bin.gz and katago-gtp10.cfg in the Lizzie folder. 
-A copy of b30.bin.gz and katago-gtp10.cfg in the Lizzie/Katago folder.
-In the Lizzie settings/engine: "  ./katago/katago gtp -model b30.bin.gz -config katago-gtp10.cfg  "

See attachment GTP console output.
Maybe this also works for you.

[log gtp console 030520.txt](https://github.com/lightvector/KataGo/files/4570817/log.gtp.console.030520.txt)

**Comment by Taaqa** [comment]
Issue solved

Directly running the exact same command I'm giving to Lizzie on the command line showed me what was wrong: Networks must have the extension .txt, .bin, .txt.gz or .bin.gz. 
Unfortunately I had renamed the model file to .gz.

Thanks for your advice.

**Comment by Taaqa** [comment]
Hi lightvector,

 

impressive thing you provide with katago.
I'd like to honor your work a little. How can I do that?

 

Regards,

Dirk Michalowski

 

Gesendet: Sonntag, 03. Mai 2020 um 15:11 Uhr
Von: "lightvector" <notifications@github.com>
An: "lightvector/KataGo" <KataGo@noreply.github.com>
Cc: "Taaqa" <katagoo@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [lightvector/KataGo] KataGo doesn't start within Lizzie interface (#215)


 

Also if you are unfamiliar with how to specify file paths, please take a look at this link where it also describes how you can put the model and config into the same directory as KataGo and if you name them the correct thing, KataGo will use them automatically without any paths specified: https://github.com/lightvector/KataGo#how-to-use
