### ISSUE TITLE
Missing namespace

### ISSUE THREAD

**Issue by uduse** [lightvector/KataGo#218]
https://github.com/lightvector/KataGo/blob/1210b73426e8c9f5d01fff44766fa5111f383fbb/cpp/neuralnet/dummybackend.cpp#L53

Shouldn't it be `string NeuralNet::getModelName(const LoadedModel* loadedModel) {`?

**Comment by lightvector** [comment]
Yes, thanks for finding that! As you might guess, the "dummybackend" isn't compiled very often, which is why this went unnoticed. :)

I've made this fix locally and I will push and release soon.

**Comment by lightvector** [comment]
Fixed in v1.4.0. Thanks!
