### ISSUE TITLE
katago and centOS cloud GPU

### ISSUE THREAD

**Issue by zihevic** [lightvector/KataGo#220]
I recent got help from a cloud platform which contain a very strong gpu for trianning and testing AI. but the cloud environment is centOS, it does not contain any gui and cannot be installed since it related to other process. I would like to know, how could I use lizzie or any other analyse gui in my local computer and conncet with the cloud gpu in centOS to run katago for analysing game?

**Comment by lightvector** [comment]
Have you tried Google search? This is definitely not a KataGo-specific question, there are going to be many people who have asked before "how do I use such and such GUI with such and such cloud setup", so it shouldn't be hard to find detailed instructions and setups, which you can modify. Most revolve around wrapping a remote ssh command in a script and using it as the engine.
https://www.google.com/search?q=lizzie+remote+gpu

**Comment by lightvector** [comment]
Just checking back in - apologies, my previous reply wasn't as helpful/friendly as it could have been. Anyways, the way to do it is going to depend a bit on your OS, so it's hard to help without knowing your setup, but if you search online you should be able to find several results. Are there any particular issues you're running into when trying to get things set up?

**Comment by lightvector** [comment]
Going ahead and closing - but please feel free to reply back if you have any more specific questions or problems you run into when trying to start KataGo. Also, if it's more a question about Lizzie setup, https://github.com/featurecat/lizzie/issues probably has people who can help too.

**Comment by crsov** [comment]
You can configure lizzie to run katago over SSH
