### ISSUE TITLE
how to specify komi in config file?

### ISSUE THREAD

**Issue by lj739** [lightvector/KataGo#224]

**Comment by Friday9i** [comment]
It's defined by the gtp parameters or the GUI, not in the config file!
Eg in Sabaki, you define the komi, the board size and the opponents, and KataGo will play using the cfg file (hence, komi in cfg would be redundant)

**Comment by lj739** [comment]
In goban, there is no place to specify komi in GUI. I like the GUI of goban, if there is no way to write komi parameter in config file, it would be a very sad news.

**Comment by lightvector** [comment]
Can you request that the authors of that GUI add the ability to specify that the komi? KataGo is just like other engines here - it's pretty much universally true across all Go engines that if they support variable komi, then they accept komi through GTP, so all the GUI has to do is tell it to the engine.

**Comment by lj739** [comment]
The author hasn't renew this software one  year and more, it is the most beautiful GUI I've ever seen. https://hraj.si/goban/

**Comment by lightvector** [comment]
I took a peek at the source code <https://github.com/popojan/goban/search?q=komi&unscoped_q=komi> and it looks like it actually does tell the bot a komi, based on handicap game or not.

So on KataGo's side this makes it awkward. I could easily add a config parameter to set the initial komi on startup, assuming that GTP doesn't override it, but in this case your GUI deliberately overrides it to the value that it chooses. So KataGo would also need a hack to specifically *ignore* the komi that the GUI is telling it that the GUI wants to use! Seems pretty ugly.

How about you find out how to contact the author and see if you can get them to maintain it. If you like it so much maybe it will motivate them to work on it more. :)

**Comment by lj739** [comment]
Thanks for the quick reply. Katago is so strong that I must play with it on a very large komi. In sabaki lizgoban etc, specify any komi is a very easy case, but I can restrain my self from taking another bot to against it or telling me the next step. In goban, you have no way to  use another bot, so you must consider the next move very carefully, it makes the learning process very effective. At komi 6.5 or 7.5, it is very desperate for human players. I don't have  any code environment on my machine, and don't know how to make up a copy of goban with komi changed to -15(play as black) . If someone can help, thanks in advance.

**Comment by popojan** [comment]
Hello, @lj739, thank you for your feedback regarding goban. I opened an issue popojan/goban#17 and will see if we can find a better solution then recompiling with hardcoded komi -15. It is definitely lacking feature in goban, not katago.

**Comment by lightvector** [comment]
Looks like this is all handled. Great!
