### ISSUE TITLE
Linking error on Linux/CUDA version 

### ISSUE THREAD

**Issue by cleinias** [lightvector/KataGo#225]
When trying to build the CUDA version on Archlinux, I get a linking error in the early test phase. I can compile the Nvidia CUDA samples successfully, so it does not seem to be a CUDA  installation issue.   The linker seems unable to find the dl library, as far as I can tell. 

~~~~
Building 'katago' executable for GTP engine and other tools
 -DUSE_BACKEND=CUDA, using CUDA backend
 The CUDA compiler identification is NVIDIA 10.2.89
 Check for working CUDA compiler: /opt/cuda/bin/nvcc
 Check for working CUDA compiler: /opt/cuda/bin/nvcc - broken
 CMake Error at /usr/share/cmake-3.17/Modules/CMakeTestCUDACompiler.cmake:46 (message):
   The CUDA compiler

     "/opt/cuda/bin/nvcc"

   is not able to compile a simple test program.

   It fails with the following output:

     Change Dir: /home/stefano/builds/KataGo/cpp/CMakeFiles/CMakeTmp

     Run Build Command(s):/usr/bin/make cmTC_18138/fast && /usr/bin/make  -f CMakeFiles/cmTC_18138.dir/build.make
 CMakeFiles/cmTC_18138.dir/build
     make[1]: Entering directory '/home/stefano/builds/KataGo/cpp/CMakeFiles/CMakeTmp'
     Building CUDA object CMakeFiles/cmTC_18138.dir/main.cu.o
     /opt/cuda/bin/nvcc -forward-unknown-to-host-compiler   -cudart shared    -x cu -c
 /home/stefano/builds/KataGo/cpp/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_18138.dir/main.cu.o
     Linking CUDA executable cmTC_18138
     /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_18138.dir/link.txt --verbose=1
     /opt/cuda/bin/g++   CMakeFiles/cmTC_18138.dir/main.cu.o -o cmTC_18138  -lcudadevrt -lcudart_static
 -L"/opt/cuda/targets/x86_64-linux/lib/stubs" -L"/opt/cuda/targets/x86_64-linux/lib" -lcudadevrt -lcudart
     /usr/bin/ld: /opt/cuda/targets/x86_64-linux/lib/libcudart_static.a(libcudart_static.a.o): undefined reference to symbol
 'dlclose@@GLIBC_2.2.5'
     /usr/bin/ld: /usr/lib/libdl.so.2: error adding symbols: DSO missing from command line
     collect2: error: ld returned 1 exit status
     make[1]: *** [CMakeFiles/cmTC_18138.dir/build.make:107: cmTC_18138] Error 1
     make[1]: Leaving directory '/home/stefano/builds/KataGo/cpp/CMakeFiles/CMakeTmp'
     make: *** [Makefile:141: cmTC_18138/fast] Error 2
~~~~

**Comment by AlanVilaca** [comment]
Can you show your code?

**Comment by cleinias** [comment]
Sorry, I don't get the question. Which/whose code?
I simply tried to compile KataGo with the basic cmake command, i.e. cmake . from the cpp dir

**Comment by lightvector** [comment]
So apparently your cmake doesn't like your installation of CUDA and/or the versions of compilers and libraries you're trying to use. So even if you compiled the CUDA samples correctly, there may be a version mismatch between it and what cmake is expecting. When I google search online, I find this: https://gitlab.kitware.com/cmake/cmake/issues/16933 - does that help?

**Comment by cleinias** [comment]
As far as I can tell from cmake's output, the problem is with the CUDA static runtime library (that's what I'm guessing libcudart_static.a is). It requires the dl library and the linker can't find it. I tried adding   ${CMAKE_DL_LIBS} to the target_link_libraries in the CUDA section of CMakeLists but it did not help.

**Comment by lightvector** [comment]
Perhaps the important part is the "GLIBC_2.2.5"? Are you using a g++ version that is incompatible with the CUDA version, and therefore have also have incompatible glibc versions?

On my cloud machines, I currently am unable to upgrade from g++ 7 to g++ 8, for example, because CUDA on ubuntu does not support g++ 8, and bad things happen if you try to compile some stuff with g++8 and nvcc some things via g++ 7.

NVIDIA provides a table here for CUDA 10.2: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/

**Comment by isty2e** [comment]
I always compile KataGo with CUDA 10.2 and gcc-8 on Ubuntu 18.04, but no problem has ever happened. For the record, gcc-8 is installed via ppa:ubuntu-toolchain-r/test. I think you can try different versions of gcc, and if the problem is with glibc, things will get complicated.

**Comment by cleinias** [comment]
It might well be an issue with g++, but in that case I'm kind of stuck because my distribution (ArchLinux) is not among those listed on the nvidia page linked to.  In fact the issue may be with glibc---the g++ compiler cmake calls is v. 8.4.0 and comes from the CUDA installation itself, not from my distribution. So I assume nVidia put the correct version there.  But glibc comes from Archlinux (it is version .2.31) and it may not be what CUDA expects.

Even that line of reasoning may be wrong, though---the nvidia table lists  g++ 8.1 and glibc 2.28 for Red Hat, which is the closest to what Arch ships.

**Comment by lightvector** [comment]
When you build the samples, does it use something other than `/usr/bin/ld`, and/or does it pass other flags that point it to an appropriate place to find the libraries it's complaining about here?

**Comment by cleinias** [comment]
So, after wasting two hours on cmake/CUDA/g++ and so on and messing around with the CMakeLlist file (more or less at random, since I had never touched one such before), I managed to solve the problem by editing cpp/CMakeLists.txt as follows:
1. Adding  ${CMAKE_DL_LIBS} to the target_link_library instruction for the CUDA backend (line 210)

2. moving the line 48:  enable_language(CUDA)" instructions (the real culprit, as the initiator of the failed test), to immediately after the target_link_library instruction of point 1 above.

I am sure this is a hack and again, I don't know what I'm doing, but it finally compiled. Why this is happening on Arch and not on Ubuntu, I have no idea. Perhaps the newer versions of g++ changed  behavior.

**Comment by lightvector** [comment]
Thanks. I may investigate to see if this causes troubles for anyone else, if not, then maybe we can just modify the CMakeLists to have this for everyone. Glad you got it working.

**Comment by cleinias** [comment]
As far as I can tell, the issue is simply that that  cmake launches the test program too early---before being aware of the dl libs.  I' m sure it should be an easy fix for someone more conversant in cmake. Thanks for the help and for the fantastic program, I'm glad I can use it again.

**Comment by cleinias** [comment]
Apparently this is a problem introduced with cmake >= 3.17 ( I am running 3.17.2).  A fellow Arch user sent me this link that explain things (perhaps):
[https://github.com/microsoft/onnxruntime/issues/3355 ](url)

**Comment by OmnipotentEntity** [comment]
Per [CMake issue #20708](https://gitlab.kitware.com/cmake/cmake/-/issues/20708), a better workaround is to use `set(CMAKE_CUDA_RUNTIME_LIBRARY SHARED)` (instead of the code quoted later).  The error is caused by [CMake Merge Request 4178](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4178), which added some abstraction to the CUDA runtime detection/selection, which doesn't play nicely with this part of the CMakeLists:

```
# Ensure dynamic cuda linking
set(CMAKE_CUDA_FLAGS "" CACHE STRING "")
if(CMAKE_CUDA_FLAGS)
  list(REMOVE_ITEM CMAKE_CUDA_FLAGS "-cudart static")
endif()
string(APPEND CMAKE_CUDA_FLAGS "-cudart shared")
```

**Comment by robertmaynard** [comment]
The workaround that @OmnipotentEntity hopefully wont be needed. Brad King and I are working on a patch for 3.17.3:

https://gitlab.kitware.com/cmake/cmake/-/merge_requests/4762

**Comment by lightvector** [comment]
Given that this was updated for cmake, and KataGo went ahead and (belatedly) included @OmnipotentEntity 's fix later anyways for anyone who end up on the wrong version of cmake (thanks again!) I think this should be all handled now.
