### ISSUE TITLE
lcb in version 1.1

### ISSUE THREAD

**Issue by bvandenbon** [lightvector/KataGo#23]
The output that I get with version 1.1 is:

![afbeelding](https://user-images.githubusercontent.com/20482760/59806037-59094a00-92f3-11e9-9fdd-2178dc972745.png)

Shouldn't there be an `lcb` value in this format ?
Or is that something which is different from how LeeLa Zero works ?

Thank you in advance.

(PS: what is the utility value ?)

**Comment by lightvector** [comment]
You're right, I should add an "lcb" field as well. I implemented lz-analyze and kata-analyze originally *before* either KataGo or Leela Zero used LCB as of its latest release, way back several months ago. I'll add it shortly, thanks!

**Comment by lightvector** [comment]
The utility value is the value that KataGo *actually* cares about for performing the MCTS, rather than the winrate. Utility is a weighted combination of both winrate and score - so KataGo will play to some degree to maximize score in addition to simply trying to win.

**Comment by lightvector** [comment]
Implemented! :)
https://github.com/lightvector/KataGo/commit/57ebc392d81ad9e3b16a9d00ee668ecff4583e52
