### ISSUE TITLE
A problem of making with cuda

### ISSUE THREAD

**Issue by herogan2017** [lightvector/KataGo#230]
Hello, can anyone know the reason with the following problem?

I use cmake . -DUSE_BACKEND=CUDA -DNO_GIT_REVISION=1 and make

Scanning dependencies of target katago
[  1%] Building CXX object CMakeFiles/katago.dir/core/global.cpp.o
[  2%] Building CXX object CMakeFiles/katago.dir/core/bsearch.cpp.o
[  4%] Building CXX object CMakeFiles/katago.dir/core/config_parser.cpp.o
[  5%] Building CXX object CMakeFiles/katago.dir/core/datetime.cpp.o
[  6%] Building CXX object CMakeFiles/katago.dir/core/elo.cpp.o
[  8%] Building CXX object CMakeFiles/katago.dir/core/fancymath.cpp.o
[  9%] Building CXX object CMakeFiles/katago.dir/core/hash.cpp.o
[ 10%] Building CXX object CMakeFiles/katago.dir/core/logger.cpp.o
[ 12%] Building CXX object CMakeFiles/katago.dir/core/makedir.cpp.o
[ 13%] Building CXX object CMakeFiles/katago.dir/core/md5.cpp.o
[ 14%] Building CXX object CMakeFiles/katago.dir/core/multithread.cpp.o
[ 16%] Building CXX object CMakeFiles/katago.dir/core/rand.cpp.o
[ 17%] Building CXX object CMakeFiles/katago.dir/core/rand_helpers.cpp.o
[ 18%] Building CXX object CMakeFiles/katago.dir/core/sha2.cpp.o
[ 20%] Building CXX object CMakeFiles/katago.dir/core/test.cpp.o
[ 21%] Building CXX object CMakeFiles/katago.dir/core/threadsafequeue.cpp.o
[ 22%] Building CXX object CMakeFiles/katago.dir/core/timer.cpp.o
[ 24%] Building CXX object CMakeFiles/katago.dir/game/board.cpp.o
[ 25%] Building CXX object CMakeFiles/katago.dir/game/rules.cpp.o
[ 27%] Building CXX object CMakeFiles/katago.dir/game/boardhistory.cpp.o
[ 28%] Building CXX object CMakeFiles/katago.dir/dataio/sgf.cpp.o
[ 29%] Building CXX object CMakeFiles/katago.dir/dataio/numpywrite.cpp.o
[ 31%] Building CXX object CMakeFiles/katago.dir/dataio/trainingwrite.cpp.o
[ 32%] Building CXX object CMakeFiles/katago.dir/dataio/loadmodel.cpp.o
[ 33%] Building CXX object CMakeFiles/katago.dir/dataio/lzparse.cpp.o
[ 35%] Building CXX object CMakeFiles/katago.dir/dataio/homedata.cpp.o
[ 36%] Building CXX object CMakeFiles/katago.dir/neuralnet/nninputs.cpp.o
[ 37%] Building CXX object CMakeFiles/katago.dir/neuralnet/modelversion.cpp.o
[ 39%] Building CXX object CMakeFiles/katago.dir/neuralnet/nneval.cpp.o
[ 40%] Building CXX object CMakeFiles/katago.dir/neuralnet/desc.cpp.o
[ 41%] Building CXX object CMakeFiles/katago.dir/neuralnet/cudabackend.cpp.o
[ 43%] Building CUDA object CMakeFiles/katago.dir/neuralnet/cudahelpers.cu.o
In file included from <command-line>:0:0:
/usr/local/cuda-10.0/bin/../targets/x86_64-linux/include/cuda_runtime.h:83:10: fatal error: crt/host_config.h: No such file or directory
 #include "crt/host_config.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/katago.dir/build.make:465: recipe for target 'CMakeFiles/katago.dir/neuralnet/cudahelpers.cu.o' failed
make[2]: *** [CMakeFiles/katago.dir/neuralnet/cudahelpers.cu.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/katago.dir/all' failed
make[1]: *** [CMakeFiles/katago.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lightvector** [comment]
Oop, sorry, didn't see this issue earlier. Did you ever get this to work?

Anyways, if you read the error message you posted, you can see that the compiler is complaining  "cuda_runtime.h" in CUDA 10.0 attempts to include a different header that doesn't exist. So it seems like you haven't installed CUDA 10.0 correctly, or you are missing one of its dependencies, or CMake is failing to find it. You might first try following CUDA's instructions for compiling is runtime samples, to see if its either of the first two?
https://docs.nvidia.com/cuda/cuda-quick-start-guide/index.html#linux
And perhaps upgrade to a newer version of CUDA too, 10.0 is pretty out-of-date.

**Comment by lightvector** [comment]
Going ahead and closing this, since with CUDA 11 support and other things, quite a lot has changed since this point. Also, the recommended version for many casual users now is the OpenCL version, not the CUDA version, even on NVIDIA GPUs, so if you have issues with fixing your CUDA installation specifically, maybe you can try `-DUSE_BACKEND=OPENCL`?

Feel free to reply back or comment if you get back to this or if there are further issues.
