### ISSUE TITLE
KataGo uses an old version of libzip

### ISSUE THREAD

**Issue by iopq** [lightvector/KataGo#232]
caan't run it because I have libzip 5, not finding libzip 4, so precompiled binary doesn't run

**Comment by lightvector** [comment]
What OS?

**Comment by iopq** [comment]
Ubuntu, so I used apt to install the newest version that's available

**Comment by iopq** [comment]
Actually, I don't care about the libzip version, I just want the thing to work because I also have issues compiling it now.

Is it possible to release as an AppImage?

**Comment by trotro** [comment]
As a workaround you can create a symlink :
```shell
sudo ln -s /usr/lib/libzip.so /usr/lib/libzip.so.4
```

It works fine on manjaro.

**Comment by lightvector** [comment]
Precompiled new release 1.4.4 uses libzip5 now! https://github.com/lightvector/KataGo/releases

As for compiling it yourself, hard to help without more details. Presumably you're missing one or more of the dependencies, or you're trying to compile the CUDA version and using a version of g++ that is incompatible with NVIDIA's nvcc? NVIDIA has very specific tables on compatibility for different OSes, and anything outside of that is a tossup. (https://docs.nvidia.com/cuda/archive/10.2/cuda-installation-guide-linux/index.html)

**Comment by trotro** [comment]
Thanks for the update! Will try it later.

I’m using manjaro 18 with precompiled katago-v1.4.2-opencl-linux-x64.
Distributing katago as an AppImage could be a real plus, imho.

**Comment by lightvector** [comment]
I don't know much about AppImages, but if you think this would be a good idea, please open a new issue with more details, and if it's something that requires a code change, also feel free to submit a pull request. :)

libzip is updated, so this issue seems handed.

**Comment by SevenBlocks** [comment]
I have libzip4 on Ubuntu 18.04 and got this error:
`error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory`

If anyone else had the same issue I was able to fix it using @trotro's suggestion:

`sudo ln -s /usr/lib/x86_64-linux-gnu/libzip.so.4.0.0 /usr/lib/x86_64-linux-gnu/libzip.so.5`
