### ISSUE TITLE
Saved tuning parameters on Windows

### ISSUE THREAD

**Issue by kaorahi** [lightvector/KataGo#238]
I received a bug report
https://github.com/kaorahi/lizgoban/issues/53
and noticed that HomeData::getHomeDataDir was changed in f659e5df (v1.3.4).

In the all-in-one package
https://github.com/kaorahi/lizgoban/releases/tag/v0.5.0-pre1
of my GUI, katago.exe is extracted into a temporary directory that is removed after every run. This will cause the initial tuning of KataGo in every run, I guess. (I have no Windows machine and cannot test it by myself.)

For old getHomeDataDir, I set the current directory as a permanent place (the directory containing LizGoban*.exe itself) to avoid this problem. What can I do for new getHomeDataDir?

If possible, I would like to keep offering a single binary of my GUI that works without installation and additional downloads for those who are not familiar with computers.

**Comment by lightvector** [comment]
Would it be good if I added an option in the config to specify the directory? If so, I will do that for next release.

**Comment by kaorahi** [comment]
Yes. I would be happy if you would add that option in 1.4.3. I cannot fix this problem in GUI side and my package is practically unusable for CPU-only users until it.

**Comment by GopherAl** [comment]
> In the all-in-one package
https://github.com/kaorahi/lizgoban/releases/tag/v0.5.0-pre1
of my GUI, katago.exe is extracted into a temporary directory that is removed after every run. This will cause the initial tuning of KataGo in every run, I guess. (I have no Windows machine and cannot test it by myself.)

Yes, every time I select Preset/KataGo* it goes through the tuning process. I tried manually creating the folder _AppData\Local\Temp\1ccmWyFMOdGhvr5HFTlpN7fNPjm\resources\external\katago/KataGoData/opencltuning/_ and copying over the _tune6_... files that BadukMegapack created a few weeks ago. However it was immediately removed when I tried KataGo afterwards.

**Comment by lightvector** [comment]
Pushed to master:
https://github.com/lightvector/KataGo/commit/4a79cde56e81209ce4e2fd231b0f2cbee3a8354b
(if you can compile KataGo you can already use this, else wait for 1.4.3).

Adds `homeDataDir = DIRECTORY` as option for the config to set where to write the opencl tuning files. Also like other options in the config, it may be also specified/overridden inline on the command line via "-override-config".

**Comment by kaorahi** [comment]
Thanks for rapid implementation! I will wait for the official binary of 1.4.3 as I do not have Windows.

**Comment by GopherAl** [comment]
Thanks to both of you. I will wait for the release.

**Comment by kaorahi** [comment]
Can I use `-override-config "homeDataDir=."` to emulate the behavior of old getHomeDataDir before f659e5df on Windows?

**Comment by kaorahi** [comment]
Thanks. I will try it when 1.4.3 is released.

**Comment by kaorahi** [comment]
I've heard that `-override-config "homeDataDir=."` works well in 1.4.3. thx!
