### ISSUE TITLE
is these models useful? and how to use them

### ISSUE THREAD

**Issue by l1t1** [lightvector/KataGo#24]
i found them  in directoryl\cpp\models, and occupied most of size of source code.

**Comment by lightvector** [comment]
Those are some small 6 block models that are mostly used for testing and debugging. They vary in strength from very very very weak to human mid amateur dan. I don't think they're of particular interest, you should just use the models included in the release, or pick specific models from the full runs at https://d3dndmfyhecmj0.cloudfront.net/ if you want to see how it has progressed.
