### ISSUE TITLE
Could you provide some different human-level weights?

### ISSUE THREAD

**Issue by HandleCoding** [lightvector/KataGo#241]

**Comment by lightvector** [comment]
I'll upload more weights some time after the end of this run (there's just a tiny bit left). But the weaker ones are quite unlikely to play like a human of that level would play. For a much different approach, you should check out https://github.com/sanderland/katrain which makes more human-level players even using the current nets.

**Comment by HandleCoding** [comment]
I'm very glad to receive your reply. Your suggestions are very helpful。
