### ISSUE TITLE
Problem when compiling the program

### ISSUE THREAD

**Issue by wind23** [lightvector/KataGo#245]
I was trying to compile KataGo on CentOS 7.8. The G++ version I use is 7.3.1, and the cmake version is 3.16.2.

After I have set up all environments, when I run `cmake . -DUSE_BACKEND=CUDA`, everything seems all right. But when I run `make` after that, the following error message shows up:

	[  1%] Generating program/gitinfoupdated.h
	Scanning dependencies of target katago
	[  2%] Building CXX object CMakeFiles/katago.dir/core/global.cpp.o
	/home/test/KataGo/cpp/core/global.cpp: In function ‘void Global::collectFiles(const string&, std::function<bool(const std::basic_string<char>&)>, std::vector<std::basic_string<char> >&)’:
	/home/test/KataGo/cpp/core/global.cpp:684:85: error: ‘begin’ was not declared in this scope
		 for(const bfs::directory_entry& entry: bfs::recursive_directory_iterator(dirname)) {
																						 ^
	/home/test/KataGo/cpp/core/global.cpp:684:85: note: suggested alternatives:
	In file included from /opt/rh/devtoolset-7/root/usr/include/c++/7/string:51:0,
					 from /opt/rh/devtoolset-7/root/usr/include/c++/7/stdexcept:39,
					 from /opt/rh/devtoolset-7/root/usr/include/c++/7/array:39,
					 from /opt/rh/devtoolset-7/root/usr/include/c++/7/tuple:39,
					 from /opt/rh/devtoolset-7/root/usr/include/c++/7/functional:54,
					 from /home/test/KataGo/cpp/core/../core/global.h:13,
					 from /home/test/KataGo/cpp/core/global.cpp:1:
	/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/range_access.h:105:37: note:   ‘std::begin’
	   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&);
										 ^~~~~
	/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/range_access.h:105:37: note:   ‘std::begin’
	/home/test/KataGo/cpp/core/global.cpp:684:85: error: ‘end’ was not declared in this scope
		 for(const bfs::directory_entry& entry: bfs::recursive_directory_iterator(dirname)) {
																						 ^
	/home/test/KataGo/cpp/core/global.cpp:684:85: note: suggested alternatives:
	In file included from /opt/rh/devtoolset-7/root/usr/include/c++/7/string:51:0,
					 from /opt/rh/devtoolset-7/root/usr/include/c++/7/stdexcept:39,
					 from /opt/rh/devtoolset-7/root/usr/include/c++/7/array:39,
					 from /opt/rh/devtoolset-7/root/usr/include/c++/7/tuple:39,
					 from /opt/rh/devtoolset-7/root/usr/include/c++/7/functional:54,
					 from /home/test/KataGo/cpp/core/../core/global.h:13,
					 from /home/test/KataGo/cpp/core/global.cpp:1:
	/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/range_access.h:107:37: note:   ‘std::end’
	   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
										 ^~~
	/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/range_access.h:107:37: note:   ‘std::end’
	make[2]: *** [CMakeFiles/katago.dir/core/global.cpp.o] Error 1
	make[1]: *** [CMakeFiles/katago.dir/all] Error 2
	make: *** [all] Error 2

Does that mean there is something wrong in my compiling environment? Or there may be something other problems? Thank you!

**Comment by lightvector** [comment]
Are you using an outdated version of boost that does not support range for-loops in its directory iterator?

For reference, 1.65.1 is the version of boost I have on my system. And 1.73.0 is the latest, it seems.

**Comment by lightvector** [comment]
Alternatively, if that isn't the problem, what happens if you add:
` #include <iterator> `
to the list of includes near the top of the global.cpp file that was failing to compile?

**Comment by wind23** [comment]
The problem is solved by updating boost. Thanks!
