### ISSUE TITLE
[Error reporting] Generating new config file doesn't work.

### ISSUE THREAD

**Issue by wonsiks** [lightvector/KataGo#246]
I've tried to generate a new config file by "katago.exe genconfig -model KataGo20b.gz -output default_gtp.cfg" command but no file has been created.
During creation process I choosed OpenCL device 2 and it looked like using device 2 but it used device 0 actually.(Check the screenshot)
Maybe there's some error from the code.
Please check this problem.
Thanks.
![katago_genconfig_err](https://user-images.githubusercontent.com/37356450/84584979-73fa9580-ae45-11ea-93a5-d76ce917c9b6.png)

**Comment by wonsiks** [comment]
Oh, new KataGo 1.4.3 OpenCL version doesn't use device except id 0.
I have to roll-back to v1.4.2 for now.

**Comment by lightvector** [comment]
Thanks for the quick report. Try v1.4.4 and see if it works for you? Thanks!

**Comment by wonsiks** [comment]
It's working properly now.
Thank you so much.
