### ISSUE TITLE
Will Katago take part in the AI competition

### ISSUE THREAD

**Issue by jinghui22** [lightvector/KataGo#250]
Ask the author lightvector, if the ai contest is held in August, will Katago participate?

**Comment by lightvector** [comment]
Unfortunately, it doesn't appear that there was a major AI context this month?

**Comment by topmin** [comment]
福州市围棋协会第三届“吴清源杯”世界女子围棋赛暨2020世界人工智能围棋大赛，将于9月26日至9月30日在福州举行，只是不知道参赛 AI 是邀请制还是报名制。

**Comment by OmnipotentEntity** [comment]
> The 3rd "Wu Qingyuan Cup" World Women's Go Tournament of Fuzhou Go Association and the 2020 World Artificial Intelligence Go Tournament will be held in Fuzhou from September 26 to September 30, but I don't know whether the AI participation is by invitation or registration.

**Comment by lightvector** [comment]
For those who stumble on this thread later from Google search or whatever, see https://github.com/lightvector/KataGo/issues/320 for a more detailed thread.
