### ISSUE TITLE
release g170 selfplay games

### ISSUE THREAD

**Issue by StefanDing** [lightvector/KataGo#256]
g170 selfplay sgfs have not been uploaded in：
https://d3dndmfyhecmj0.cloudfront.net
can you release g170 selfgames?

**Comment by kennychenfs** [comment]
https://github.com/lightvector/KataGo/issues/127
explanation for why not release self play games.

**Comment by StefanDing** [comment]
> #127
> explanation for why not release self play games.

thanks,i know that the games will be released when this round is over
but the new networks released 2 days ago
so it's probably that it's end of the run now
that's only my opinion...

but the new

**Comment by StefanDing** [comment]
@lightvector
hi, will the selfplay of this round release？

**Comment by lightvector** [comment]
Yes, but please be patient.

**Comment by StefanDing** [comment]
> Yes, but please be patient.

thank you～

**Comment by lightvector** [comment]
Okay, should be available now!
https://d3dndmfyhecmj0.cloudfront.net/index.html

**Comment by StefanDing** [comment]
> Okay, should be available now!
> https://d3dndmfyhecmj0.cloudfront.net/index.html

i've seen it,thanks~
