### ISSUE TITLE
the latest katago's opencl version for linux 64bit can't work with Nvidia Geforce 940m

### ISSUE THREAD

**Issue by zzhmot** [lightvector/KataGo#264]
i wanted to use katago in my linux (ubuntu 20.04) computer, which have both intel integrated graphic card and Gefore 940M,  because 940M don't have tensor core, so i decide to choose opencl version of katago and l downloaded the version of katago-v1.4.5-opencl-linux-x64 
but when i run benchmark test with katago, the linux terminal tells:./katago: error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory
anyone can help me to solve the issue? many thanks!

**Comment by kennychenfs** [comment]
You have to install libzip5, I personally install 1.5.1.
Here is where I downloaded it.
https://launchpad.net/ubuntu/+source/libzip

**Comment by zzhmot** [comment]
> You have to install libzip5, I personally installed 1.5.1.
> Here is where I downloaded it.
> https://launchpad.net/ubuntu/+source/libzip

hello, kenny:   i have fixed the issu by following your suggestion,  thank you very much !

**Comment by lightvector** [comment]
Great.
