### ISSUE TITLE
(Question) What does it mean: "GAMELISTENTRY_PLAYER_REPLACED: channel 25262837 not found"?

### ISSUE THREAD

**Issue by sbbdms** [lightvector/KataGo#269]
Hi!
I just delivered KataGo to KGS and finished a game about 20 mins ago. I was monitoring KataGo's output and I occasionally noticed a line: "GAMELISTENTRY_PLAYER_REPLACED: channel 25262837 not found"
I never noticed such kind of outputs before, does it mean some kind of exception?
However the game finally finished without any fatal error. After the game finished, I went to check the saved gtp log but I found it disappeared from the log... It wasn't recorded in it.
So what does this line actually means?
![gamelistentry_player_replaced_ channel 25262837 not found 2](https://user-images.githubusercontent.com/19167292/86506228-1502bd80-be00-11ea-8110-84b046d6d19b.png)
![gamelistentry_player_replaced_ channel 25262837 not found 3](https://user-images.githubusercontent.com/19167292/86506230-17651780-be00-11ea-9faf-fc8ffbf909a7.png)

**Comment by lightvector** [comment]
This is definitely something on KGS's end, not KataGo. KataGo doesn't know anything about lists of games or players, all it knows is when it's asked to make a move. Please ask someone responsible for KGS. :)
