### ISSUE TITLE
Do you happen to plan to add a bit stronger weight?

### ISSUE THREAD

**Issue by mnemion** [lightvector/KataGo#27]
[difference.zip](https://github.com/lightvector/KataGo/files/3315076/difference.zip)
1, Do you happen to plan to add a bit stronger weight? I continued to lose the game by 1.5 points or 0.5 points to MiniGo in Block 20 this time. If weight is added, do I have to realize anew? I'm asking this question because I'm curious about it. 

2, I'm afraid the way of counting the total points acquired in both the website and HanQ Baduk is quite different. For example, when I lose by 0.5 points in HanQ Baduk, I win by 0.5 point in the website. I'm posting this because the problem must be solved and corrected soon.

![1](https://user-images.githubusercontent.com/52076991/59933927-52aad780-9485-11e9-8bf9-f1f149f5bd5e.PNG)

The opponent's win

![2](https://user-images.githubusercontent.com/52076991/59933939-56d6f500-9485-11e9-8906-ffd456074a0a.PNG)

https://online-go.com/game/18355480
my black win

**Comment by lightvector** [comment]
Hi there!
1. Yes, I'm planning to do a more research on possible ways to improve KataGo, and after that, I hope to do a third run which should produce something even stronger and better.
2. Are you trying to mirror moves between OGS and another website, pretending that you are a strong player by copying the moves played by your opponent on one website to play them on the other website? If this is the case, please do not do this any more. This is normally considered to be somewhat dishonest, and I'm not all that interested to try to help you. If the scoring system between OGS and another website differ, that is also not exactly the problem of KataGo.

I'm closing this issue for now. If I have greatly misunderstood you and this is not actually what you were trying to do, please feel free to reply back and let me know and I can re-open it.

**Comment by alreadydone** [comment]
okay I learned Fox is called HanQ in Korea. I guess KataGo on OGS was set up with 7.5 komi, while Fox uses 6.5. Though the OGS bot isn't set up in order to have moves transferred to Fox, you can certainly tell your own instance of KataGo to play with 6.5 komi.
