### ISSUE TITLE
User error or hardware/driver problem?

### ISSUE THREAD

**Issue by Xiaqi007** [lightvector/KataGo#271]
I'm trying to run OpenCL version 1.4.5. I run  
katago.exe benchmark -model g170e-b20c256x2-s5303129600-d1228401921.bin.gz
For two or three seconds it seems everything goes well, displaying a bunch of lines like this:

> 2020-07-08 22:06:43-0700: Loading model and initializing benchmark...
> 2020-07-08 22:06:43-0700: nnRandSeed0 = 3089971382280764449
> 2020-07-08 22:06:43-0700: After dedups: nnModelFile0 = .\g170e-b20c256x2-s5303129600-d1228401921.bin.gz useFP16 auto useNHWC auto
> 2020-07-08 22:06:44-0700: Found OpenCL Platform 0: Intel(R) OpenCL (Intel(R) Corporation) (OpenCL 1.2 )
> 2020-07-08 22:06:44-0700: Found 2 device(s) on platform 0 with type CPU or GPU or Accelerator

Etc.
But then after two or three seconds, this happens:

> Tuning xGemmDirect for 1x1 convolutions and matrix mult
> Testing 56 different configs
> 0x00007FFF9B89723D (0x0000000000000000 0x0000022380001537 0x0000000000000000 0x0000022311101408), Register() + 0x1DF40D bytes(s)

It prints out around 30 lines of hex like this, then exits.

Am I doing something incorrectly, or does this indicate that my hardware/driver isn't compatible with KataGo, or something else?

The KataGo engine doesn't start up within KaTrain either. Leela Zero runs on my system with no problem.

**Comment by Friday9i** [comment]
Which GPU do you use?

**Comment by leejingbo** [comment]
Your OpenCL driver version is 1.2, it seems too old. 

My GPU is Intel UHD Graphics 620 with  OpenCL version 2.1 , the katago.exe downloaded from the offical release works fine on my laptop.  I also build from the source code successfully and run it on my laptop.  

so, try to update the GPU driver .

**Comment by hope366** [comment]
>2020-07-09 18:30:51+0900: Loading model and initializing benchmark...
>2020-07-09 18:30:51+0900: nnRandSeed0 = 11255692583749100441
>2020-07-09 18:30:51+0900: After dedups: nnModelFile0 = KataGo20b-OpenCL.gz useFP16 auto useNHWC auto
>2020-07-09 18:30:52+0900: Found OpenCL Platform 0: NVIDIA CUDA (NVIDIA Corporation) (OpenCL 1.2 CUDA 11.0.186)
>2020-07-09 18:30:52+0900: Found 1 device(s) on platform 0 with type CPU or GPU or Accelerator
>2020-07-09 18:30:52+0900: Found OpenCL Device 0: GeForce RTX 2060 (NVIDIA Corporation) (score 11000102)
>2020-07-09 18:30:52+0900: Creating context for OpenCL Platform: NVIDIA CUDA (NVIDIA Corporation) (OpenCL 1.2 CUDA 11.0.186)
>2020-07-09 18:30:52+0900: Using OpenCL Device 0: GeForce RTX 2060 (NVIDIA Corporation) OpenCL 1.2 CUDA
>2020-07-09 18:30:52+0900: Loaded tuning parameters from: C:\Users\hiro7\Downloads\igo\Lizzie-v0.7.3\katago-v1.4.5-opencl/KataGoData/opencltuning/tune6_gpuGeForceRTX2060_x19_y19_c256_mv8.txt
>2020-07-09 18:30:52+0900: OpenCL backend: Model version 8
>2020-07-09 18:30:52+0900: OpenCL backend: Model name: g170-b20c256x2-s5303129600-d1228401921
It says OpenCL 1.2, but it works fine in my environment.
It may be because the GPU is RTX 2060.

**Comment by lightvector** [comment]
See: https://github.com/lightvector/KataGo#issues-with-specific-gpus-or-gpu-drivers

If you are using Intel integrated graphics, some versions of it may simply not work, due to being buggy. Besides the ones listed there, the same is often true for hardware that is many many years old. You might try updating your drivers, it may or may not be successful.

**Comment by lightvector** [comment]
Due to recent changes in v1.6.0 that reduced the amount of OpenCL code, it's possible that this may work again on Intel Integrated Graphics in some cases where it didn't before. It might not, but if you want to try it out again, there's a chance. https://github.com/lightvector/KataGo/releases

**Comment by Xiaqi007** [comment]
It works! The 1.6.0 eigen version runs on my machine. Many thanks!

**Comment by lightvector** [comment]
Cool! Also, you might want to check out the 1.6.1 release that just posted out today. It fixes a over-memory use bug of the 1.6.0 eigen version.
https://github.com/lightvector/KataGo/releases

Any other issues or questions?

**Comment by Xiaqi007** [comment]
OK, I've got 1.6.1. No other issues. Thanks again.
