### ISSUE TITLE
distance function

### ISSUE THREAD

**Issue by yffbit** [lightvector/KataGo#274]
https://github.com/lightvector/KataGo/blob/127cf2a51b1932ed7e69f89c7096f2871c4c66db/cpp/game/board.cpp#L1245-L1246
Should be dy = (loc1-loc0-dx) / (x_size+1) ?
It doesn't matter. It seems that these two functions, distance and euclideanDistanceSquared, are not really used.

**Comment by lightvector** [comment]
Thanks! Fixed.
https://github.com/lightvector/KataGo/commit/cdc213472af78f224dac36b6f86cd0d39728d416
