### ISSUE TITLE
gpuIdx device (nvidia GeForce) not found OpenCL (Clover) [distro: Slackware64-current]

### ISSUE THREAD

**Issue by wirelesstevmc** [lightvector/KataGo#277]
(Newbie alert)
I have been unable to get the pre-compiled or locally built katago binaries to run the benchmark either because my GPU is unsupported **or** I have not built it with the appropriate configuration or other needed packages. I'm looking for a little direction here with my hardware:
# lspci | grep -i nvidia
**26:00.0 VGA compatible controller: NVIDIA Corporation GP108 [GeForce GT 1030] (rev a1)**
I first tried the Cuda backend thinking surely this modern GPU was supported. Sigh...it is not.
So then I tried building with OpenCL backend. I read over the issue with buggy AMD GPU's on OpenCL (common-questions-and-issues) and it seems this is not applicable since there is no traceable seq fault and it is an nVidia GPU. Below is the output when running katago with the benchmark sub command. All the other sub commands seem to work. I sure would appreciate a pointer if the below output is useful. I'm happy to post any needed logs. Also this same video card runs with no issues in Windows 10 OS. Maybe I simply need to install another package /driver to support hardware detection??

**2020-07-19 15:17:06-0700: Loading model and initializing benchmark...
2020-07-19 15:17:06-0700: nnRandSeed0 = 3031223286744131279
2020-07-19 15:17:06-0700: After dedups: nnModelFile0 = /home/cahill/Downloads/github/KataGo/cpp/default_model.bin.gz useFP16 auto useNHWC auto
2020-07-19 15:17:09-0700: Found OpenCL Platform 0: Clover (Mesa) (OpenCL 1.1 Mesa 19.3.4)
2020-07-19 15:17:09-0700: Found 0 device(s) on platform 0 with type CPU or GPU or Accelerator, skipping
terminate called after throwing an instance of 'StringError'
  what():  Requested gpuIdx/device 0 was not found, valid devices range from 0 to -1
Abort
Exit 134**

**Comment by lightvector** [comment]
CUDA: As you found out yourself, whether your GPU supports CUDA or not is actually pretty borderline. See for example this post, which I found by googling around: https://medium.com%2F@medium.com/@samnco/using-the-nvidia-gt-1030-for-cuda-workloads-on-ubuntu-16-04-4eee72d56791

So it seems like CUDA support is sort of borderline for this lower-end GPU, there is some chance you may be able to make it work. But also, note that the above link is for CUDA 8.0, and KataGo requires at least 10.0, ideally 10.2.  (CUDA11 is out but has backwards-incompatible changes that I haven't ported through yet, see https://github.com/lightvector/KataGo/issues/244.

As for OpenCL, see https://github.com/lightvector/KataGo#issues-with-specific-gpus-or-gpu-drivers - your OpenCL GPU drivers are _exactly_ one of the ones known to have problems, as documented there, and you will need to install new drivers from a different source.

Hope that helps!

**Comment by lightvector** [comment]
Ah, you mentioned that you've already read over that issues section?

Yeah, that section is written from the perspective of AMD GPUs since that's the context that the OpenCL Mesa drivers came up in several times in past issues. But I'm not sure whether it's specifically the AMD GPU being problematic, or if it's generally the Mesa drivers. If it's generally the Mesa drivers (regardless of the actual underlying GPU), then it still might be the case that you need to install new drivers.

As far as KataGo is concerned, your Mesa platform appears to exist right now as an OpenCL platform but it advertises precisely zero usable GPU devices. So something is weird about the drivers' ability to expose your GPU through OpenCL, and given the other problems with Mesa on AMD, it seems possible that Mesa + OpenCL generally is just not a combo that works, so if there are other possible drivers you can try (maybe some Nvidia-specific ones?) that might have a chance.

**Comment by wirelesstevmc** [comment]
Wow! I'm very impressed and grateful for the the quick responses / comments. These are very useful. If I can get the engine running on windows (albeit OpenCL backend) I'm confident I can get it going on my Linux box. Since I spend most of the time booted in Linux with this particular machine (as well as an avid fan of Go)...well you know...where this is a will there is a way. Thanks again!

**Comment by wirelesstevmc** [comment]
Ok it turns out that my GPU is supported by CUDA. Although it is not a very powerful GPU (only 384 CUDA cores) it should in fact be detected by KataGo. I have the 10.2 CUDA Toolkit [**cudatoolkit-10.2.89-x86_64-1**] and the exact library [**cudnn-v7.6.5.32_10.2-x86_64-1**] that the KataGo is based on. The Cuda toolkit, library as well as KataGo (with Cuda backend) were all built locally on my Slackware 64_x86 machine. It is therefore inexplicable why KataGo does not detect my GPU as the OS and Cuda libraries do (See out below from nvidia-smi -q). This has to be something specific to the KataGo backend code. I am going to try recompiling KataGo to see if I can get a hint as to why. Perhaps just a minor mod to the backend code is needed?
---out from nvidia-smi query---
# nvidia-smi -q
==============NVSMI LOG==============

Timestamp                           : Tue Jul 21 07:14:08 2020
Driver Version                      : 440.44
CUDA Version                        : 10.2

Attached GPUs                       : 1
GPU 00000000:26:00.0
    Product Name                    : GeForce GT 1030
    Product Brand                   : GeForce
    Display Mode                    : Enabled
    Display Active                  : Enabled
    Persistence Mode                : Disabled
    Accounting Mode                 : Disabled
    Accounting Mode Buffer Size     : 4000
    Driver Model
        Current                     : N/A
        Pending                     : N/A
    Serial Number                   : N/A
    GPU UUID                        : GPU-7b0de5ef-916e-fac6-64c1-57502d77d167
    Minor Number                    : 0
    VBIOS Version                   : 86.08.24.00.30
    MultiGPU Board                  : No
    Board ID                        : 0x2600
    GPU Part Number                 : N/A
    Inforom Version
        Image Version               : G001.0000.01.04
        OEM Object                  : 1.1
        ECC Object                  : N/A
        Power Management Object     : N/A
    GPU Operation Mode
        Current                     : N/A
        Pending                     : N/A
    GPU Virtualization Mode
        Virtualization Mode         : None
        Host VGPU Mode              : N/A
    IBMNPU
        Relaxed Ordering Mode       : N/A
    PCI
        Bus                         : 0x26
        Device                      : 0x00
        Domain                      : 0x0000
        Device Id                   : 0x1D0110DE
        Bus Id                      : 00000000:26:00.0
        Sub System Id               : 0x63363842
        GPU Link Info
            PCIe Generation
                Max                 : 3
                Current             : 1
            Link Width
                Max                 : 4x
                Current             : 4x
        Bridge Chip
            Type                    : N/A
            Firmware                : N/A
        Replays Since Reset         : 0
        Replay Number Rollovers     : 0
        Tx Throughput               : 12000 KB/s
        Rx Throughput               : 144000 KB/s
    Fan Speed                       : 37 %
    Performance State               : P8
    Clocks Throttle Reasons
        Idle                        : Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Not Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
    FB Memory Usage
        Total                       : 1998 MiB
        Used                        : 613 MiB
        Free                        : 1385 MiB
    BAR1 Memory Usage
        Total                       : 256 MiB
        Used                        : 4 MiB
        Free                        : 252 MiB
    Compute Mode                    : Default
    Utilization
        Gpu                         : 0 %
        Memory                      : 10 %
        Encoder                     : N/A
        Decoder                     : 0 %
    Encoder Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    FBC Stats
        Active Sessions             : 0
        Average FPS                 : 0
        Average Latency             : 0
    Ecc Mode
        Current                     : N/A
        Pending                     : N/A
    ECC Errors
        Volatile
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
        Aggregate
            Single Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
            Double Bit            
                Device Memory       : N/A
                Register File       : N/A
                L1 Cache            : N/A
                L2 Cache            : N/A
                Texture Memory      : N/A
                Texture Shared      : N/A
                CBU                 : N/A
                Total               : N/A
    Retired Pages
        Single Bit ECC              : N/A
        Double Bit ECC              : N/A
        Pending Page Blacklist      : N/A
    Temperature
        GPU Current Temp            : 30 C
        GPU Shutdown Temp           : 102 C
        GPU Slowdown Temp           : 99 C
        GPU Max Operating Temp      : N/A
        Memory Current Temp         : N/A
        Memory Max Operating Temp   : N/A
    Power Readings
        Power Management            : Supported
        Power Draw                  : N/A
        Power Limit                 : 30.00 W
        Default Power Limit         : 30.00 W
        Enforced Power Limit        : 30.00 W
        Min Power Limit             : 25.50 W
        Max Power Limit             : 30.00 W
    Clocks
        Graphics                    : 139 MHz
        SM                          : 139 MHz
        Memory                      : 405 MHz
        Video                       : 544 MHz
    Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Default Applications Clocks
        Graphics                    : N/A
        Memory                      : N/A
    Max Clocks
        Graphics                    : 1974 MHz
        SM                          : 1974 MHz
        Memory                      : 3004 MHz
        Video                       : 1708 MHz
    Max Customer Boost Clocks
        Graphics                    : N/A
    Clock Policy
        Auto Boost                  : N/A
        Auto Boost Default          : N/A
    Processes
        Process ID                  : 1809
            Type                    : G
            Name                    : /usr/libexec/Xorg
            Used GPU Memory         : 349 MiB
        Process ID                  : 24718
            Type                    : G
            Name                    : /home/cahill/Downloads/Sabaki-master/node_modules/electron/dist/electron --type=gpu-process --field-trial-handle=9920150017661651186,18001959911070661482,131072 --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererForSitePerProcess --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --shared-files
            Used GPU Memory         : 25 MiB
        Process ID                  : 26319
            Type                    : G
            Name                    : kwin
            Used GPU Memory         : 24 MiB
        Process ID                  : 26675
            Type                    : G
            Name                    : /proc/self/exe
            Used GPU Memory         : 210 MiB

**Comment by lightvector** [comment]
I sometimes find on machines I have nvidia-smi available even without having installed CUDA + CUDNN, so that's not necessarily a test of whether you have CUDA actually installed in a successful way or not.

Does it work for you when building and running the CUDA 10.2 samples (as well as the CUDNN samples, like mnistCUDNN)?

**Comment by wirelesstevmc** [comment]
Sigh...Admittedly I am a newbie to the CUDA toolkit and libraries - so much to learn here. I have not taken a deep dive into the CUDA docs yet. How might I test this? i.e. try out a test build?

**Comment by wirelesstevmc** [comment]
Admittedly I can't really expect you to tutor me on the nuances of verifying my cuda installation :(
I found all the samples and Makefiles in /usr/share/cuda/samples and trying to build some of them. I already found some issues. Stay tuned...

**Comment by OmnipotentEntity** [comment]
Try doing `ldd $(which katago)` and see where the executable is expecting the libraries to be.

**Comment by wirelesstevmc** [comment]
Two response here. I'm staying chronological so this first response is for lightvector:
I was able to build and run one of the samples. Specifically the following fluidsGL executable was built and it ran. At first it wouldn't compile until I actually linked the libGL and libGLU libraries in the build directory! Apparently the nvcc compiler is too dumb to detect library paths.
**/usr/share/cuda/samples/5_Simulations/fluidsGL/fluidsGL**

Now OmnipotentEntity response - This (below) ldd out is from the latest KataGo recompiled with Cuda backend:
As you see the cuda libraries are definitely linked.
# ldd katago
        linux-vdso.so.1 (0x00007ffdaaea1000)
        **libcudnn.so.7 => /usr/lib64/libcudnn.so.7 (0x00007fc97d3e3000)
        libcublas.so.10 => /usr/lib64/libcublas.so.10 (0x00007fc97912d000)**
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc97910b000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fc979106000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fc9790fc000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fc978ee3000)
        libzip.so.5 => /usr/lib64/libzip.so.5 (0x00007fc978ec6000)
        libboost_filesystem.so.1.72.0 => /usr/lib64/libboost_filesystem.so.1.72.0 (0x00007fc978ea8000)
        libboost_system.so.1.72.0 => /usr/lib64/libboost_system.so.1.72.0 (0x00007fc978ea3000)
        libcudart.so.10.2 => /usr/lib64/libcudart.so.10.2 (0x00007fc978c25000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fc978a45000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fc9788f6000)
        libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007fc9788dc000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fc9786f7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc998d37000)
        libcublasLt.so.10 => /usr/lib64/libcublasLt.so.10 (0x00007fc976864000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007fc976851000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007fc97662b000)
        libgnutls.so.30 => /usr/lib64/libgnutls.so.30 (0x00007fc97644f000)
        libnettle.so.7 => /usr/lib64/libnettle.so.7 (0x00007fc976415000)
        libp11-kit.so.0 => /usr/lib64/libp11-kit.so.0 (0x00007fc9762e6000)
        libidn2.so.0 => /usr/lib64/libidn2.so.0 (0x00007fc9762c5000)
        libunistring.so.2 => /usr/lib64/libunistring.so.2 (0x00007fc975f43000)
        libhogweed.so.5 => /usr/lib64/libhogweed.so.5 (0x00007fc975f09000)
        libgmp.so.10 => /usr/lib64/libgmp.so.10 (0x00007fc975e8f000)
        libffi.so.7 => /usr/lib64/libffi.so.7 (0x00007fc975e83000)

**Comment by OmnipotentEntity** [comment]
Rather than pinging everyone subbed to this repo with back and forth about this problem.  Can you log onto the Discord?  http://discord.gg/5vacH5F

**Comment by wirelesstevmc** [comment]
So grateful for your help lightvector. Thank you! All I did was create a link from where the Slackware package put my cuda libs and bins in /usr/share/cuda to where the Nvidia says it should be in /usr/local/cuda and the benchmark is running now. And thanks to OmnipotentEntity for his help as well. On to get Leela Zero engine going and watch KataGo crush it :)
