### ISSUE TITLE
No Hash Comment in SGF files

### ISSUE THREAD

**Issue by Grant-Tao** [lightvector/KataGo#283]
First, big thanks to KataGo Team. The new released training data and selfplay games are just great.

But,  I found some lines in the readme.txt :
"
#C41-46: 128-bit hash identifying the game which should also be output in the SGF data as a comment. Split into chunks of 22, 22, 20, 22, 22, 20 bits, little-endian style (since floats have > 22 bits of precision). This allows matching up training rows with the sgf files.
"
And I found no hash comment in sgf files, and I cannot make a connection between sgf files and npz files. Maybe I omitted some thing?

**Comment by lightvector** [comment]
Oh, that's unfortunate. Yes, it seems that it was not written out, so you're going to have to simply live without this, sorry. I'll remove the part in the readme that suggests that this is possible.

**Comment by lightvector** [comment]
This is also fixed in the code as of the latest release, so whenever maybe we have the next run, we'll have this matching ability. Thanks for pointing this out!
