### ISSUE TITLE
katago under Ubuntu 20.04

### ISSUE THREAD

**Issue by adzweig** [lightvector/KataGo#284]
Hi 
I recently upgraded from Ubuntu 18.04 to 20.04. Now I can't get katago going.  
If I enter "./katago benchmark -model katanetwork.gz", I obtain the following error:
"./katago: error while loading shared libraries: libcudnn.so.7: cannot open shared object file: No such file or directory
"
This may have to do with the cuda version that I am using:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

Any help how to resolve this is greatly appreciated.

Thanks

Adrian

**Comment by adzweig** [comment]
After new installation of cuda 10.2 and cudnn7 things work fine!

**Comment by lightvector** [comment]
Yay!
