### ISSUE TITLE
Repeat tuning

### ISSUE THREAD

**Issue by kennychenfs** [lightvector/KataGo#285]
Katago 1.5.0 repeats tuning when it starts. The tuning parameter file actually exists, but it always says it's not exist.  
Linux OpenCL version.

**Comment by lightvector** [comment]
Sorry, it looks like I had a slightly older/buggy version checked out when I compiled. I checked versions and the only problematic one is linux opencl, which I have replaced with the correct version. Does it work now? (It should tune one more time with this updated version, and then work).

**Comment by kennychenfs** [comment]
Thanks for your fast reply! I will try it later.

**Comment by kennychenfs** [comment]
OK fixed.
