### ISSUE TITLE
Unable to run on Lizzie on Mac after compiling 1.5.0

### ISSUE THREAD

**Issue by trunterzx** [lightvector/KataGo#286]
I compiled the latest version of KataGo (1.5.0) on my Mac and tried to run it with Lizzie but it is not running.
The screen is simply stuck at the "Engine is loading" page.

This didn't happen for 1.4.5.
Any ideas?

**Comment by trunterzx** [comment]
Ah okay it is running now. It just took very long to load so I thought there was something wrong.

**Comment by lightvector** [comment]
Presumably it was running the tuning. It only needs to do this the first time. KataGo is outputting its progress as it does so, but Lizzie is pretty bad at communicating this to the user (by default, it hides all the output that would make it clear that it's not stuck).
