### ISSUE TITLE
Bad tag name for 1.5.0 release

### ISSUE THREAD

**Issue by apetresc** [lightvector/KataGo#297]
This is obviously incredibly minor, but still a pain for us package maintainers :)

Every other KataGo release before has used the 
`v#.#.#` naming scheme, but 1.5.0 dropped the `v` and is just `1.5.0`.

My recommended fix is just to add another tag to the same commit so nobody gets broken.

**Comment by OmnipotentEntity** [comment]
I noticed this as well when I was updating the NixOS package.  I just didn't think it was major enough bother about lol.

**Comment by lightvector** [comment]
Fixed, I think. Is it good now?

**Comment by apetresc** [comment]
:+1: Yup, working again. Thank you!
