### ISSUE TITLE
How to run multi katago?

### ISSUE THREAD

**Issue by xieren58** [lightvector/KataGo#300]
How to run multi katago for multi users in one server?
Thanks.

**Comment by lightvector** [comment]
Have you tried simply starting multiple instances?

Alternatively, if this is for some sort of analysis service, rather than simply playing games, have you looked at the analysis engine? https://github.com/lightvector/KataGo/blob/master/docs/Analysis_Engine.md

**Comment by xieren58** [comment]
Ok, I get it now, thanks！

**Comment by lightvector** [comment]
Great. :)
