### ISSUE TITLE
Questions on 1.1 release

### ISSUE THREAD

**Issue by ozymandias8** [lightvector/KataGo#32]
I had a couple question related to the 1.1 release. I am running the windows compile created by AlreadyDone over on the Leela git page.

I notice in Sabaki that the GPU load is high and TDP is at 80-90% when the engine is "idle", i.e. no gtp commands have been given. Leela Zero, by contrast, will not load the GPU until a command is given. Does that mean I have some setting configured incorrectly, or perhaps something related to how Sabaki is trying to interface with it?

My second question is related to variations displayed in Sabaki. I notice that they are appear to be capped at 10 moves. Is there a way to expand this?

If these are issues purely with Sabaki I wouldn't expect anyone here to know the answers, but I thought I would ask in case it's a configuration thing with Katago.

Great work on this project, seems to be much more flexible than other "zero" methods, such as Leela.

**Comment by lightvector** [comment]
Glad you like it.

If you have pondering enabled in the config, then you will probably observe this behavior of using the GPU even when idling. Additionally, it looks like when digging into the LZ source code to try to manually reverse-engineer how the GTP extension "lz-analyze" worked (ugh ^_^), I missed a subtle detail where "lz-analyze" will stop upon encountering a newline as input. Whereas KataGo's GTP parser only proceeds on whole GTP commands, and therefore cannot notice a newline to be able to stop analysis, until you explicitly give it some other command (like making a move). I'll see if I can fix that in a future release. I'm not aware of any other thing that should load the GPU.

Right now, KataGo doesn't report more than 9 or 10 PV moves, yes. I will see if I can make that a configurable parameter in the next version. Thanks for the feedback!

**Comment by ozymandias8** [comment]
Interesting, perhaps the GPU load is related to that somehow. I can play with it a bit to see what I can learn.

Ten moves gives the gist of the bot's current "thinking", so it's alright. Even with Leela I sometimes have to actually play out a sequence against it to understand why it thinks a particular move is good. Some of the reading is far deeper than I can understand.
