### ISSUE TITLE
Compiling error on windows

### ISSUE THREAD

**Issue by LZY2006** [lightvector/KataGo#327]
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
Building 'katago' executable for GTP engine and other tools
-DUSE_BACKEND=CUDA, using CUDA backend
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeDetermineCompilerId.cmake:367 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeDetermineCompilerId.cmake:32 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeDetermineCUDACompiler.cmake:243 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:51 (enable_language)

Configuring incomplete, errors occurred!
See also "C:/Users/zdwxx/Documents/Tencent Files/1182338055/FileRecv/windows-build/KataGo/cpp/build/CMakeFiles/CMakeOutput.log".

The log file doesn't show error information.

**Comment by Friday9i** [comment]
I'm not able to help you but I can share some elements: 
1) several people explained that compiling KataGo with Cuda is significantly harder than with OpenCL. Also, OpenCL version is now running about as fast (if not faster) than the Cuda version in most cases. So my advice would be to start to compile it with OpenCL.
2) On my side, I managed to compile it under OpenCL this week-end for the first time, after spending several hours (as I have little experience of modern tools such as git, cmake and visual studio...).
Retrospectively, just compiling KataGo without zlib and libzip (useful only for selfplay) was reasonably simple! But then, I had a quite hard time and was forced to make several "guesses" to try and eventually manage to set up zlib and libzip, and to use them for compiling KG.

**Comment by LZY2006** [comment]
I have solved the problem.
I found there's no CUDA 10.0.xml in C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations.
so I reinstalled CUDA10.0.Then the problem is solved.
