### ISSUE TITLE
What does x2 in the released weight files mean?

### ISSUE THREAD

**Issue by mega-optimus** [lightvector/KataGo#342]
Hi,
Just a simple question on file naming, take g170-b20c256x2-s668214784-d222255714 as example.
What does "x2" mean in the c256x2?
Thank you!

**Comment by lightvector** [comment]
Good question, yeah I agree that isn't obvious. It means it was trained with 2 GPUs instead of 1.

**Comment by mega-optimus** [comment]
Thanks for the prompt reply! The answer is unexpected :laughing:
