### ISSUE TITLE
Problems with Cuda 11 on RTX 3000 series

### ISSUE THREAD

**Issue by scaomath** [lightvector/KataGo#346]
Dear all, I have two problems. 

The first one is running the compiled CUDA 11 binary here (https://github.com/lightvector/KataGo/releases/tag/v1.7.0), I got an error of `libcudnn.so.8: cannot open shared object file: No such file or directory`.

So I compiled the CUDA version following the instructions using `cmake . -DUSE_BACKEND=CUDA`, using the cuda-compiled binary to run the `genconfig` I was able to get the following result:
<a href="https://imgur.com/7d19TqF"><img src="https://i.imgur.com/7d19TqF.png" title="source: imgur.com" /></a>

However, moving on using the config file generated for benchmark, katago will get stuck forever.  
```bash
(base) scao@scao-DL-desktop:~/Documents/Lizzie-0.7$ ./katago_cuda benchmark -model g170-b40c256x2.bin.gz -config gtp_cuda.cfg 
2020-11-12 16:10:56-0600: Loading model and initializing benchmark...
2020-11-12 16:10:56-0600: nnRandSeed0 = 11911038397205717008
2020-11-12 16:10:56-0600: After dedups: nnModelFile0 = g170-b40c256x2.bin.gz useFP16 auto useNHWC auto
2020-11-12 16:10:57-0600: Cuda backend thread 0: Found GPU GeForce RTX 3090 memory 25447170048 compute capability major 8 minor 6
2020-11-12 16:10:57-0600: Cuda backend thread 0: Model version 8 useFP16 = true useNHWC = true
2020-11-12 16:10:57-0600: Cuda backend thread 0: Model name: g170-b40c256x2-s5095420928-d1229425124
```
`nvidia-smi` says `katago` is run on GPU, however, the GPU usage is 0% always (I am using the integrated graphics for display so this is normal).

OpenCL version has no such problem. A caveat is that I found the visit per second is about 8-10 times slow than the CUDA genconfig shows. Therefore I suspect there is some sort of bug for the CUDA compiled binary.
<a href="https://imgur.com/AM9tyQV"><img src="https://i.imgur.com/AM9tyQV.png" title="source: imgur.com" /></a>

**Comment by lightvector** [comment]
Have you installed cudnn 8?

**Comment by scaomath** [comment]
> Have you installed cudnn 8?

My bad. I just checked and the cudnn is of version 7. I thought with CUDA 11.1 it is automatically 8. Do you think this is the reason why the CUDA-compiled version got stuck while openCL does not?

**Comment by lightvector** [comment]
Probably something like that. The number of visits per second you're getting on CUDA is also fairly implausible, so probably something is seriously broken when you try to use cuda 11 with cudnn 7 - I bet it's not actually doing the right computations and is instead just doing some sort of super-fast broken garbage, which includes possibly hanging when you try again later.

**Comment by scaomath** [comment]
Installing cudnn 8 solves the issue. Yet it seems the performance is slightly worse than the openCL version.
