### ISSUE TITLE
Intensive analysis of only certain movements

### ISSUE THREAD

**Issue by hope366** [lightvector/KataGo#358]
I have something to ask about related to #340.
In very difficult situations, KataGo often fails to find the best move.
The same phase diagram as the attached diagram of #340 is reprinted.
<img src="https://user-images.githubusercontent.com/63999713/100429087-2e224880-30d8-11eb-9ed2-062f85069cd9.png" width="60%">
In this situation, C-3 seems likely to be the best move. So I'd like to have KataGo analyze only C-3 intensively (using lizzie).
Is it possible for the user to specify any movement and let KataGo analyze only that movement?

**Comment by Friday9i** [comment]
Play the move and let it analyse the situation after it is played :-)

**Comment by hope366** [comment]
Thank you for answering.
I see, it certainly looks good that way ^^

**Comment by GopherAl** [comment]
That would have been my answer also. Wondered what I was missing. 

Maybe someone could help me - what do the numerals on each stone in the diagram mean? I know the middle one is the number of visits. What do the top and the bottom numeral signify? (I'm not familiar with lizzie.)

**Comment by Friday9i** [comment]
Above is the estimated winrate, below the estimated score

**Comment by GopherAl** [comment]
Thanks! So if Black plays C3, Black is assessed to have an ~18% chance of winning and is losing by ~5.1 pts? Is the 5.1 figure what is meant by "KataGo territory is displayed as the 3rd move suggestion statistic" (a fix in Lizzie Version 0.7)?

**Comment by hope366** [comment]
E-8 has the highest priority, followed by N-15, O-14, F-1, C-3, so I think C-3 is fifth.
If Black chose C-3, it would look like the screenshot below.
<img src="https://user-images.githubusercontent.com/63999713/100454509-6178cd80-3100-11eb-89b3-a1d0bcbfaec0.png" width=60%>
Of course, I realize that KataGo doesn't have absolute power, but it's a little surprising that you can't recognize it as the best move in the last phase that you can understand with just one modification.

**Comment by GopherAl** [comment]
> Of course, I realize that KataGo doesn't have absolute power, but it's a little surprising that you can't recognize it as the best move in the last phase that you can understand with just one modification.

I'm no authority but I will make this comment: in your first comment (& diagram) you think that C3 is the best move. However in the position shown KataGo has only made 13k visits to its 1st choice (E8) and the total number of visits on the goban is negligible. It can take over 100k visits to several top candidates before KG appears to settle on the top move. Even then if you ran it long enough some outlier may come through the pack to 1st place. Maybe you can have some kind of "certainty" that a move is the best if you have a really good GPU and analyse the position for "long enough" (whatever that means!).

> if Black plays C3, Black is assessed to have an ~18% chance of winning and is losing by ~5.1 pts? Is the 5.1 figure what is meant by "KataGo territory is displayed as the 3rd move suggestion statistic" (a fix in Lizzie Version 0.7)?

Most likely you can confirm or clarify or correct any misunderstanding of this for me. :)

**Comment by hope366** [comment]
Looking at the screenshot of #340, KataGo is not aware that the C-3 is the top move even after 100,000 playouts.
You may find C-3 by increasing the amount of analysis, but it will take a long time ...

**Comment by lightvector** [comment]
@hope366 - Have you tried setting `analysisWideRootNoise` to a larger value, like 0.05 or 0.1? You can force KataGo to search more widely in general if you use that setting - it may make it _weaker_, but the weakness will be due to more general small misevaluations instead of rare large misevaluations.

If you want to analyze one move 100%, then of course just play that move on the board first, then analyze.

> but it's a little surprising that you can't recognize it as the best move in the last phase that you can understand with just one modification.

This is not surprising at all. :)
We know that if a bot has not solved the game, it will _always_ be possible to find mistakes. So imagine we find a mistake. Now go forward one move at a time down the path that was misevaluated. At some point, it must be the case that the evaluation becomes correct, once you go far enough - so it should be quite frequent that there is a point where before, it is wrong, then afterwards, it is correct - that spot is where the real mistake is. Therefore, for any mistake, there is also a spot where one modification is enough to make it correct, so it should be very common to find spots where one move is sufficient to realize the mistake.

Okay, actually the above logic is not quite right. :). The other possibility is that the mistake is realized gradually over many moves. But this is much less for _tactical_ mistakes (rather than strategy mistakes). Because tactical mistakes in a fight are often sharp and have very immediate consequences - it would be surprising if most tactical mistakes were realized gradually instead of suddenly.

**Comment by lightvector** [comment]
Another way to think about it is - if you play the move on the board, and then analyze, you're asking for that move to get easily 10x or even 100x more analysis than that move had before.

If a move is possible for anyone (regardless of a bot, or a human) to realize to be correct - if the move is not simply completely beyond their ability - then it should be quite common for 10x or 100x to be enough to help them to realize it, because that's quite a big factor. Does that make it more intuitive and less surprising for you to think about it this way?

**Comment by michito744** [comment]
If you just want to discover it, it's not that difficult.

![2020-11-28 (1)](https://user-images.githubusercontent.com/53891655/100493181-e6eb9480-3177-11eb-8db5-f61ee290d3d6.png)

Results will vary significantly depending on the network files used, the settings and the calculation time.

**Comment by hope366** [comment]
@lightvector ,Thank you for the detailed explanation.
'analysisWideRootNoise = 0.5' I tried to analyze the same aspect with this setting. Last time it was commented out and disabled.
<img src="https://user-images.githubusercontent.com/63999713/100493134-662c9880-3177-11eb-8d54-9b9c04dd9f23.png" width="60%">
Unlike last time, KataGo seems to be focusing on movements that are likely to be correct. But as you say, we spend a lot of analysis on other trivial movements, so I think the total loss is greater. It may be better to use it only in very difficult situations.
> Therefore, for any mistake, there is also a spot where one modification is enough to make it correct, so it should be very common to find spots where one move is sufficient to realize the mistake.

Even for a series of movements where the winning percentage value does not change significantly, KataGo often slightly changes (improves) the assumed figure as it progresses step by step. It's not a big mistake like the theme diagram, but strictly speaking, it's a frequent mistake, and it looks like you're making fine adjustments as you move forward.

**Comment by hope366** [comment]
@michito744 ,Thank you for your verification.
I used the same neural network that you used. The amount of analysis is about the same. But the result is different as shown in the screenshot below. I set `analysisWideRootNoise = 0.1`, but you probably set a different number.
<img src="https://user-images.githubusercontent.com/63999713/100494678-3f765e00-3187-11eb-8ce1-89865bc6ba8e.png" width="60%">
Judging from the results so far, C-3, D-8, D-4, these three places show high numerical values, but I can not measure which is the correct answer with my strength. Maybe everything is wrong and even KataGo has a great move that you wouldn't expect. This depth is the interesting part of Go.

**Comment by michito744** [comment]
D8 is essentially the same progression, since the procedure for D8 is to be received by D9 and then hit C3.

**Comment by hope366** [comment]
Indeed, if White does not receive D-8, White is likely to lose a lot, so it seems not unnatural to assume that even if you hit D-8 first, the progress will be the same.
Using 40x384 and using the `analysisWideRootNoise = 0.1` setting, it seems that D-8 was discovered relatively early.
However, `analysisWideRootNoise = 0.1` may be more costly to disperse the analysis in many other aspects, so it should be used properly, but it is difficult to determine.

**Comment by michito744** [comment]
In fact, a fatal oversight will occur unless the network is further enhanced.
The above example can be found without losing power by adjusting the parameters, but the example below is extremely difficult.
![2020-11-28 (2)](https://user-images.githubusercontent.com/53891655/100506169-59786680-31b0-11eb-8cf7-6da01a23067b.png)

**Comment by hope366** [comment]
I'm not sure why the R-6's Blue Point is the best move in a very difficult situation.
Is this a professional vs. professional game?
I am interested, so I would be grateful if you could put SGF if possible.

**Comment by michito744** [comment]
Sorry for the lack of explanation.

In the actual game, Black S1 was played after this. This is the best move, harder to find in KataGo's analysis, and better than black R6(this is good move too).

The game record is the 1st game of the 44th Meijin-sen.

**Comment by hope366** [comment]
Thank you.
I found a game record and analyzed it a little.
![t](https://user-images.githubusercontent.com/63999713/100522019-0f60a680-31eb-11eb-93e3-90ac767aa21a.png)
If you put Kuroishi on S1, it is upside down and the winning percentage of black is about 97%, so it seems likely that S1 is the best move.
Is S1 a difficult move to find?

**Comment by michito744** [comment]
I think KataGo is very difficult to detect, because it strongly truncates moves that appear to be useless if it has short time.
In fact, it's easier to detect with humans.

**Comment by hope366** [comment]
>I think KataGo is very difficult to detect, because it strongly truncates moves that appear to be useless if it has short time.

That may be the reason why Go AI has been rapidly gaining strength recently.
It would have been more effective to improve the power of Go AI by continuing to choose good moves on average throughout the game, rather than finding the best move in a particular very difficult situation.

**Comment by michito744** [comment]
I think you're right.
And it looks like the performance of the network is directly related to the winner.
