### ISSUE TITLE
Forbidding many searches with Sabaki

### ISSUE THREAD

**Issue by smolendawid** [lightvector/KataGo#360]
I am often using KataGo with Sabaki on my Mac for the game analysis. After a minute my Mac is getting very hot and the fans are getting very noisy. 

Is there a way to stop searches after let's say 1000 searches?

**Comment by lightvector** [comment]
Sounds like that would be a feature request for Sabaki. KataGo is simple searching exactly when and what Sabaki tells it to search, so it would be entirely up to Sabaki to produce the behavior you're asking for. Try opening an issue here: https://github.com/SabakiHQ/Sabaki and adding as much more detail as you can about exactly what you'd like changed and/or perhaps if there is a simple UI interface you'd like to see to accomplish it.

**Comment by HackYardo** [comment]
@smolendawid 
Several gtp commands can pause analyzing. I use  'final_score' to pause.

**Comment by smolendawid** [comment]
Thank you for the support, I understand. The "hack" with final_score is somehow useful.
