### ISSUE TITLE
Support World Mind Sports Game 2008 Go Rule

### ISSUE THREAD

**Issue by thynson** [lightvector/KataGo#37]
Ruleset detailed commentary: http://home.snafu.de/jasiek/wmsgc.pdf
Through not accepted by majors players, this rule is worth to implement because it make Chinese-style score system compatible to 6.5 komi, which shall be more balanced for black and white accordding to stats.

**Comment by lightvector** [comment]
This is basically the same as [button Go](https://senseis.xmp.net/?ButtonGo), which is now [implemented](https://lightvector.github.io/KataGo/rules.html) as of [v1.3 release](https://github.com/lightvector/KataGo/releases/tag/v1.3). Enjoy!
