### ISSUE TITLE
SYMMETRY or symmetry in kata-raw-nn output

### ISSUE THREAD

**Issue by kaorahi** [lightvector/KataGo#382]
`docs/GTP_Extensions.md` says that the output of `kata-raw-nn` is `SYMMETRY ...`. But it is lowercase `symmetry ...` actually.

    $ echo "kata-raw-nn 0" | ./katago-cpu gtp -model net/kata_128x10.bin.gz -config gtp_my.cfg 2> /dev/null | grep '='
    = symmetry 0

Is this correct?

**Comment by lightvector** [comment]
Thanks, I have pushed a fix to master to adjust the documentation to match the actual output.
Additionally, the push to master adds a new field also print the policy probability for passing, which due to an oversight, was missing before.

**Comment by kaorahi** [comment]
Thanks for the immediate fix!
