### ISSUE TITLE
Newest version of katago network from https://katagotraining.org/ is not supported by even Katago 1.7.0

### ISSUE THREAD

**Issue by SGQuek** [lightvector/KataGo#386]
I have downloaded the newest version of the neural network from
https://katagotraining.org/ 

upon starting, this is the error message:

Uncaught exception: Error loading or parsing model file katanetwork_b34N.bin.gz: kata1-b40c256-s5600995072-d1348643660: model found unsupported version 10

Please help.

**Comment by kennychenfs** [comment]
https://github.com/lightvector/KataGo/issues/372#issuecomment-750762248

**Comment by OmnipotentEntity** [comment]
You will need to compile your own client from head, and ask lightvector to manually enable you for contribution if you want to contribute before the official release of 1.8.0.

**Comment by Friday9i** [comment]
Version 1.8 is now released :-)

**Comment by SGQuek** [comment]
This is to inform that I have already tested version 1.8.0 CUDA11.2, on my Ryzen 3970X + Galax 2080 Ti Hall of Fame.
For my particular brand of GPU, CUDA11.2 turns out to be 5% faster than CUDA10.2 , maybe because it is a special version of
2080 Ti.

I have also tested the newest network, looks significantly stronger indeed.
