### ISSUE TITLE
Compiling lasted master source with errors 

### ISSUE THREAD

**Issue by qiqiguaitm** [lightvector/KataGo#387]
Using Ubuntu18.04  install CUDA 10.2 and cudnn7.6.5.32

cmake . -DUSE_BACKEND=CUDA
make with errors:
CMakeFiles/katago.dir/build.make:459: recipe for target 'CMakeFiles/katago.dir/neuralnet/cudahelpers.cu.o' failed
make[2]: *** [CMakeFiles/katago.dir/neuralnet/cudahelpers.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /root/explore/KataGo/cpp/neuralnet/cudabackend.cpp:12:0:
/root/explore/KataGo/cpp/neuralnet/../external/half-2.1.0/include/half.hpp: In function ‘unsigned int half_float::detail::float2half_impl(float, std::true_type)’:
/root/explore/KataGo/cpp/neuralnet/../external/half-2.1.0/include/half.hpp:912:42: warning: there are no arguments to ‘_mm_set_ss’ that depend on a template parameter, so a declaration of ‘_mm_set_ss’ must be available [-fpermissive]
    return _mm_cvtsi128_si32(_mm_cvtps_ph(_mm_set_ss(value),
                                          ^~~~~~~~~~
/root/explore/KataGo/cpp/neuralnet/../external/half-2.1.0/include/half.hpp:913:34: error: ‘_MM_FROUND_TO_NEAREST_INT’ was not declared in this scope
     (R==std::round_to_nearest) ? _MM_FROUND_TO_NEAREST_INT :
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~
/root/explore/KataGo/cpp/neuralnet/../external/half-2.1.0/include/half.hpp:914:35: error: ‘_MM_FROUND_TO_ZERO’ was not declared in this scope
     (R==std::round_toward_zero) ? _MM_FROUND_TO_ZERO :
                                   ^~~~~~~~~~~~~~~~~~
/root/explore/KataGo/cpp/neuralnet/../external/half-2.1.0/include/half.hpp:914:35: note: suggested alternative: ‘__FD_ZERO’
     (R==std::round_toward_zero) ? _MM_FROUND_TO_ZERO :
                                   ^~~~~~~~~~~~~~~~~~
                                   __FD_ZERO
/root/explore/KataGo/cpp/neuralnet/../external/half-2.1.0/include/half.hpp:915:39: error: ‘_MM_FROUND_TO_POS_INF’ was not declared in this scope
     (R==std::round_toward_infinity) ? _MM_FROUND_TO_POS_INF :
                                       ^~~~~~~~~~~~~~~~~~~~~
/root/explore/KataGo/cpp/neuralnet/../external/half-2.1.0/include/half.hpp:916:43: error: ‘_MM_FROUND_TO_NEG_INF’ was not declared in this scope
     (R==std::round_toward_neg_infinity) ? _MM_FROUND_TO_NEG_INF :
                                           ^~~~~~~~~~~~~~~~~~~~~
/root/explore/KataGo/cpp/neuralnet/../external/half-2.1.0/include/half.hpp:917:5: error: ‘_MM_FROUND_CUR_DIRECTION’ was not declared in this scope
     _MM_FROUND_CUR_DIRECTION));

**Comment by lightvector** [comment]
What version of g++ or other compiler are you using?

And also, if you `make VERBOSE=1` and, what is the command line being invoked? Do you have any unusual environment variables or compiler definitions?

Some context: your compiler seems to be disliking some of the FP16-related intrinsics or something of that sort from the "half-2.1.0" library, which KataGo depends on. According to the comments, these intrinsics are enabled by this piece of code if your compiler advertises that it has support by defining `__F16C__`, or if somehow `HALF_ENABLE_F16C_INTRINSICS` is already defined:
https://github.com/lightvector/KataGo/blob/master/cpp/external/half-2.1.0/include/half.hpp#L276

And then, with these intrinsics enabled, this is the part of the code that your compiler is sad about, since it seems it actually does not recognize those intrinsics.
https://github.com/lightvector/KataGo/blob/master/cpp/external/half-2.1.0/include/half.hpp#L911

**Comment by qiqiguaitm** [comment]
make VERBOSE=1, and get :

[ 39%] Building CXX object CMakeFiles/katago.dir/neuralnet/cudabackend.cpp.o
/usr/bin/c++  -DBUILD_DISTRIBUTED -DCUDA_TARGET_VERSION=10.2.89 -DUSE_AVX2 -DUSE_CUDA_BACKEND -I/root/explore/KataGo/cpp/external -I/root/explore/KataGo/cpp/external/tclap-1.2.2/include -I/root/explore/KataGo/cpp/external/httplib -I/root/explore/KataGo/cpp -isystem /root/explore/KataGo/cpp/external/filesystem-1.3.6/include -isystem /usr/local/cuda/include  -march=native -mfpmath=sse -mavx2 -mfma -g -O2 -pedantic -Wall -Wextra -Wno-sign-compare -Wcast-align -Wcast-qual -Wctor-dtor-privacy -Wdisabled-optimization -Wformat=2 -Wlogical-op -Wmissing-declarations -Wmissing-include-dirs -Wnoexcept -Woverloaded-virtual -Wredundant-decls -Wshadow -Wstrict-null-sentinel -Wstrict-overflow=1 -Wswitch-default -Wfloat-conversion -Wnull-dereference -Wunused -Walloc-zero -Wduplicated-branches -Wduplicated-cond -Wdangling-else -Wrestrict -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free   -std=gnu++14 -o CMakeFiles/katago.dir/neuralnet/cudabackend.cpp.o -c /root/explore/KataGo/cpp/neuralnet/cudabackend.cpp
In file included from /root/explore/KataGo/cpp/neuralnet/cudabackend.cpp:12:0:
/root/explore/KataGo/cpp/neuralnet/../external/half-2.1.0/include/half.hpp: In function ‘unsigned int half_float::detail::float2half_impl(float, std::true_type)’:
/root/explore/KataGo/cpp/neuralnet/../external/half-2.1.0/include/half.hpp:912:42: error: there are no arguments to ‘_mm_set_ss’ that depend on a template parameter, so a declaration of ‘_mm_set_ss’ must be available [-fpermissive]
    return _mm_cvtsi128_si32(_mm_cvtps_ph(_mm_set_ss(value),

**Comment by qiqiguaitm** [comment]
And g++ version: g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by qiqiguaitm** [comment]
And it compile sucessfully  with  -DUSE_BACKEND=EIGEN or -DUSE_BACKEND=OPENCL
