### ISSUE TITLE
v1.8.0 cuda11.2 windows default configuration always pass

### ISSUE THREAD

**Issue by walge-laine** [lightvector/KataGo#392]
The bot always plays pass in gtp.
Console output:
=
C:\Katago-v1.8.0>katago.exe gtp
KataGo v1.8.0
Using TrompTaylor rules initially, unless GTP/GUI overrides this
Loaded config C:\Katago-v1.8.0/default_gtp.cfg
Loaded model C:\Katago-v1.8.0/default_model.bin.gz
Model name: kata1-b40c256-s5725361408-d1378743195
GTP ready, beginning main protocol loop
kata-genmove_analyze B 50
\=
info move pass visits 499 utility -1.10447 winrate 0.00141883 scoreMean -7.48061 scoreStdev 0.724498 scoreLead -7.48061 scoreSelfplay -7.4856 prior 0.982312 lcb -0.00407998 utilityLcb -1.11987 order 0 pv pass pass info move A19 visits 1 utility 1.18141 winrate 1 scoreMean 23.4952 scoreStdev 13.8598 scoreLead 23.4952 scoreSelfplay 20.0718 prior 4.89979e-05 lcb -6.92997e-09 utilityLcb -2.8 order 1 pv A19 info move B19 visits 1 utility 1.18141 winrate 1 scoreMean 23.4952 scoreStdev 13.8598 scoreLead 23.4952 scoreSelfplay 20.0718 prior 4.89979e-05 lcb -6.92997e-09 utilityLcb -2.8 order 2 pv B19 info move C19 visits 1 utility 1.18141 winrate 1 scoreMean 23.4952 scoreStdev 13.8598 scoreLead 23.4952 scoreSelfplay 20.0718 prior 4.89979e-05 lcb -6.92997e-09 utilityLcb -2.8 order 3 pv C19 info move D19 visits 1 utility 1.18141 winrate 1 scoreMean 23.4952 scoreStdev 13.8598 scoreLead 23.4952 scoreSelfplay 20.0718 prior 4.89979e-05 lcb -6.92997e-09 utilityLcb -2.8 order 4 pv D19 info move E19 visits 1 utility 1.18141 winrate 1 scoreMean 23.4952 scoreStdev 13.8598 scoreLead 23.4952 scoreSelfplay 20.0718 prior 4.89979e-05 lcb -6.92997e-09 utilityLcb -2.8 order 5 pv E19
play pass

kata-genmove_analyze W 50
\=
info move pass visits 249 utility 1.10045 winrate 0.998827 scoreMean 7.47861 scoreStdev 1.04358 scoreLead 7.47861 scoreSelfplay 7.46862 prior 0.982312 lcb 0.995524 utilityLcb 1.0912 order 0 pv pass pass info move A19 visits 1 utility 1.18141 winrate 1 scoreMean 23.4952 scoreStdev 13.8598 scoreLead 23.4952 scoreSelfplay 20.0718 prior 4.89979e-05 lcb 0 utilityLcb -2.8 order 1 pv A19 info move B19 visits 1 utility 1.18141 winrate 1 scoreMean 23.4952 scoreStdev 13.8598 scoreLead 23.4952 scoreSelfplay 20.0718 prior 4.89979e-05 lcb 0 utilityLcb -2.8 order 2 pv B19 info move C19 visits 1 utility 1.18141 winrate 1 scoreMean 23.4952 scoreStdev 13.8598 scoreLead 23.4952 scoreSelfplay 20.0718 prior 4.89979e-05 lcb 0 utilityLcb -2.8 order 3 pv C19 info move D19 visits 1 utility 1.18141 winrate 1 scoreMean 23.4952 scoreStdev 13.8598 scoreLead 23.4952 scoreSelfplay 20.0718 prior 4.89979e-05 lcb 0 utilityLcb -2.8 order 4 pv D19 info move E19 visits 1 utility 1.18141 winrate 1 scoreMean 23.4952 scoreStdev 13.8598 scoreLead 23.4952 scoreSelfplay 20.0718 prior 4.89979e-05 lcb 0 utilityLcb -2.8 order 5 pv E19
play pass

quit
\=

GTP log:
=
2021-01-21 22:56:46+0800: GTP Engine starting...
2021-01-21 22:56:46+0800: KataGo v1.8.0
2021-01-21 22:56:46+0800: Using TrompTaylor rules initially, unless GTP/GUI overrides this
2021-01-21 22:56:46+0800: Using 6 CPU thread(s) for search
2021-01-21 22:56:46+0800: nnRandSeed0 = 2490211870391232407
2021-01-21 22:56:46+0800: After dedups: nnModelFile0 = C:\Katago-v1.8.0/default_model.bin.gz useFP16 auto useNHWC auto
2021-01-21 22:56:47+0800: Cuda backend thread 0: Found GPU GeForce GTX 1660 Ti memory 6442450944 compute capability major 7 minor 5
2021-01-21 22:56:47+0800: Cuda backend thread 0: Model version 10 useFP16 = true useNHWC = true
2021-01-21 22:56:47+0800: Cuda backend thread 0: Model name: kata1-b40c256-s5725361408-d1378743195
2021-01-21 22:56:51+0800: Loaded neural net with nnXLen 19 nnYLen 19
2021-01-21 22:56:51+0800: Loaded config C:\Katago-v1.8.0/default_gtp.cfg
2021-01-21 22:56:51+0800: Loaded model C:\Katago-v1.8.0/default_model.bin.gz
2021-01-21 22:56:51+0800: Model name: kata1-b40c256-s5725361408-d1378743195
2021-01-21 22:56:51+0800: GTP ready, beginning main protocol loop
2021-01-21 22:56:56+0800: Controller: kata-genmove_analyze B 50
2021-01-21 22:56:58+0800: MoveNum: 0 HASH: CDCBC1F514D7E680FACD226074256633
   A B C D E F G H J K L M N O P Q R S T
19 . . . . . . . . . . . . . . . . . . .
18 . . . . . . . . . . . . . . . . . . .
17 . . . . . . . . . . . . . . . . . . .
16 . . . . . . . . . . . . . . . . . . .
15 . . . . . . . . . . . . . . . . . . .
14 . . . . . . . . . . . . . . . . . . .
13 . . . . . . . . . . . . . . . . . . .
12 . . . . . . . . . . . . . . . . . . .
11 . . . . . . . . . . . . . . . . . . .
10 . . . . . . . . . . . . . . . . . . .
 9 . . . . . . . . . . . . . . . . . . .
 8 . . . . . . . . . . . . . . . . . . .
 7 . . . . . . . . . . . . . . . . . . .
 6 . . . . . . . . . . . . . . . . . . .
 5 . . . . . . . . . . . . . . . . . . .
 4 . . . . . . . . . . . . . . . . . . .
 3 . . . . . . . . . . . . . . . . . . .
 2 . . . . . . . . . . . . . . . . . . .
 1 . . . . . . . . . . . . . . . . . . .

koPOSITIONALscoreAREAtaxNONEsui1komi7.5
Time taken: 2.032
Root visits: 505
New playouts: 505
NN rows: 7
NN batches: 3
NN avg batch size: 2.33333
PV: pass pass
Tree:
: T -107.02c W -96.72c S -10.29c ( -7.1 L  -7.0) N     505  --  pass pass
---Black(^)---
pss : T -110.45c W -99.72c S -10.73c ( -7.5 L  -7.5) LCB -111.99c P 98.23% WF  8.56% PSV     499 N     499  --  pass pass
A19 : T 118.14c W 100.00c S  18.14c (+20.1 L +23.5) LCB -280.00c P  0.00% WF 18.29% PSV       1 N       1  --  A19
B19 : T 118.14c W 100.00c S  18.14c (+20.1 L +23.5) LCB -280.00c P  0.00% WF 18.29% PSV       1 N       1  --  B19
C19 : T 118.14c W 100.00c S  18.14c (+20.1 L +23.5) LCB -280.00c P  0.00% WF 18.29% PSV       1 N       1  --  C19
D19 : T 118.14c W 100.00c S  18.14c (+20.1 L +23.5) LCB -280.00c P  0.00% WF 18.29% PSV       1 N       1  --  D19
E19 : T 118.14c W 100.00c S  18.14c (+20.1 L +23.5) LCB -280.00c P  0.00% WF 18.29% PSV       1 N       1  --  E19

2021-01-21 22:56:58+0800: = play pass
2021-01-21 22:57:19+0800: Controller: kata-genmove_analyze W 50
2021-01-21 22:57:19+0800: MoveNum: 1 HASH: CDCBC1F514D7E680FACD226074256633
   A B C D E F G H J K L M N O P Q R S T
19 . . . . . . . . . . . . . . . . . . .
18 . . . . . . . . . . . . . . . . . . .
17 . . . . . . . . . . . . . . . . . . .
16 . . . . . . . . . . . . . . . . . . .
15 . . . . . . . . . . . . . . . . . . .
14 . . . . . . . . . . . . . . . . . . .
13 . . . . . . . . . . . . . . . . . . .
12 . . . . . . . . . . . . . . . . . . .
11 . . . . . . . . . . . . . . . . . . .
10 . . . . . . . . . . . . . . . . . . .
 9 . . . . . . . . . . . . . . . . . . .
 8 . . . . . . . . . . . . . . . . . . .
 7 . . . . . . . . . . . . . . . . . . .
 6 . . . . . . . . . . . . . . . . . . .
 5 . . . . . . . . . . . . . . . . . . .
 4 . . . . . . . . . . . . . . . . . . .
 3 . . . . . . . . . . . . . . . . . . .
 2 . . . . . . . . . . . . . . . . . . .
 1 . . . . . . . . . . . . . . . . . . .

koPOSITIONALscoreAREAtaxNONEsui1komi7.5
Time taken: 0.359
Root visits: 255
New playouts: 255
NN rows: 7
NN batches: 3
NN avg batch size: 2.33333
PV: pass pass
Tree:
: T 109.62c W  99.22c S  10.40c ( +7.7 L  +7.8) N     255  --  pass pass
---White(^)---
pss : T 110.04c W  99.77c S  10.28c ( +7.5 L  +7.5) LCB  109.12c P 98.23% WF 15.66% PSV     249 N     249  --  pass pass
A19 : T 118.14c W 100.00c S  18.14c (+20.1 L +23.5) LCB -280.00c P  0.00% WF 16.87% PSV       1 N       1  --  A19
B19 : T 118.14c W 100.00c S  18.14c (+20.1 L +23.5) LCB -280.00c P  0.00% WF 16.87% PSV       1 N       1  --  B19
C19 : T 118.14c W 100.00c S  18.14c (+20.1 L +23.5) LCB -280.00c P  0.00% WF 16.87% PSV       1 N       1  --  C19
D19 : T 118.14c W 100.00c S  18.14c (+20.1 L +23.5) LCB -280.00c P  0.00% WF 16.87% PSV       1 N       1  --  D19
E19 : T 118.14c W 100.00c S  18.14c (+20.1 L +23.5) LCB -280.00c P  0.00% WF 16.87% PSV       1 N       1  --  E19

2021-01-21 22:57:19+0800: = play pass
2021-01-21 22:57:23+0800: Controller: quit
2021-01-21 22:57:23+0800: Quit requested by controller
2021-01-21 22:57:23+0800: = 
2021-01-21 22:57:23+0800: All cleaned up, quitting

My GPU info:
=
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 461.09       Driver Version: 461.09       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 166... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   38C    P8     2W /  N/A |    540MiB /  6144MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by lightvector** [comment]
That's definitely very confusing.  It seems like probably something is indeed broken with how KataGo is interfacing with your GPU, and it's simply computing the wrong results. Do smaller neural nets work for you, or did older KataGo versions work for you before?

**Comment by walge-laine** [comment]
> That's definitely very confusing.  It seems like probably something is indeed broken with how KataGo is interfacing with your GPU, and it's simply computing the wrong results. Do smaller neural nets work for you, or did older KataGo versions work for you before?

v1.3.5 and cuda 10.1 works with the same neural network.

**Comment by lightvector** [comment]
If you try using the OpenCL version, does it work for you?

**Comment by walge-laine** [comment]
> If you try using the OpenCL version, does it work for you?

Yes, the OpenCL version works fine.

**Comment by walge-laine** [comment]
I feel confused what is the correct cudnn version, because I cannot find a version for cuda 11.2 on https://developer.nvidia.com/cudnn, where the latest one is for 11.1.
Is this possibly related with the issue?

**Comment by lightvector** [comment]
Yeah, there's a chance this is the issue. KataGo for now is compiled to use cuda 11.2, but CUDNN 8 for cuda 11.1, because NVIDIA has not released a more recent cudnn.

If you are still having trouble, I recommend just using the OpenCL version for now. In a future release, KataGo may be able to set up more automated builds to build a wider variety of versions to hopefully offer more options/changes for compatibility.

**Comment by walge-laine** [comment]
Thank you for your reply.
