### ISSUE TITLE
is there a config entry of this function?

### ISSUE THREAD

**Issue by l1t1** [lightvector/KataGo#41]
https://tieba.baidu.com/p/6177996350

**Comment by lightvector** [comment]
Not in the 1.1 release, but not too long after that I added it to the gtp config, and this has since been pushed to master:

    # Configure the maximum length of analysis printed out by lz-analyze and other places.
    # analysisPVLen = 9

**Comment by l1t1** [comment]
thanks

**Comment by l1t1** [comment]
i set `analysisPVLen = 19` in, seems nothing changed, still saw 10 lines of analysis

**Comment by lightvector** [comment]
You are probably accidentally still compiling and running an old version, have mistyped the parameter or the config, or are not running enough playouts for the PV to actually be longer? As help for you to debug, KataGo will complain about "WARNING: Unused key" on startup if you have mistyped things or it doesn't recognize a parameter.

**Comment by l1t1** [comment]
i am sure i used the latest(https://github.com/lightvector/KataGo/commit/faf6c4bbd2a72f08469fa055ee4ab132ec3987fc) version.
and no warning shows at gtp.log
```
the config file attached
2019-07-16 13:24:30+0800: All cleaned up, quitting
2019-07-16 13:27:32+0800: GTP Engine starting...
2019-07-16 13:27:32+0800: Using 2 CPU thread(s) for search
2019-07-16 13:27:32+0800: nnRandSeed0 = 17696671081867057718
2019-07-16 13:27:32+0800: After dedups: nnModelFile0 = d:\model.txt useFP16 false useNHWC false
2019-07-16 13:27:51+0800: Loaded neural net with nnXLen 19 nnYLen 19
2019-07-16 13:27:51+0800: KataGo v1.2-alpha
2019-07-16 13:27:51+0800: Loaded model d:\model.txt
2019-07-16 13:27:51+0800: GTP ready, beginning main protocol loop
2019-07-16 13:27:51+0800: Controller: protocol_version
2019-07-16 13:27:51+0800: = 2
2019-07-16 13:27:51+0800: Controller: name
2019-07-16 13:27:51+0800: = KataGo
2019-07-16 13:27:51+0800: Controller: version
2019-07-16 13:27:51+0800: = 1.2-alpha
2019-07-16 13:27:51+0800: Controller: list_commands
2019-07-16 13:27:51+0800: = protocol_version
```
config file used
[gtp_example.cfg.zip](https://github.com/lightvector/KataGo/files/3395842/gtp_example.cfg.zip)

**Comment by lightvector** [comment]
Can you try what happens if run KataGo manually on the command line and type in `kata-analyze 500`? In the output, for the "pv", after running for a while, how long is the "pv" for the top move?

If you don't get enough visits per second for it to be searching deep enough to have PV of more than 9 moves, try running the 6-block 96 channel net, it should be much faster. Or you could reverse the test and instead set analysisPVLen to something tiny like "3" and verify that the PVs never get longer.

**Comment by l1t1** [comment]
after input kata-analyze 500,
it kept outputing large number of info, such as 
```
3 prior 0.000282001 lcb 0.366824 utilityLcb -0.360437 order 284 pv S10 Q17 Q3 info move pass visits 1 utility -1.09369 r
adius 2.8 winrate 0.0386608 scoreMean -30.9585 scoreStdev 27.7136 prior 0.000320932 lcb -0.961339 utilityLcb -2.8 order
285 pv pass
```

**Comment by lightvector** [comment]
Yes, and you notice how it's giving you moves for the "pv" in that output? Those are the variations that get shown by a GUI. You should check the moves that have large numbers of visits and see how long the "pv" is for them. `analysisPVLen` should very much affect them, if it doesn't then you have a strange bug that doesn't happen for me.

**Comment by l1t1** [comment]
i didnt use gui. if i genmove b, i saw 10 lines in gtp.log, are there other ways let me saw 20 lines?
btw,  a 96x6 model and `numSearchThreads =4` results to `NN avg batch size: 2.03423`, is it normal?
