### ISSUE TITLE
ERROR: Async bot thread failed: resource unavailable try again: resource unavailable try again

### ISSUE THREAD

**Issue by sbbdms** [lightvector/KataGo#414]
I connected KataGo to KGS and it played 3 games in a row.
In the last (handicap) game, KataGo was losing. After all the dames have been filled, KataGo didn't pass and then try to fill in opponent's territory, and suddenly crashed with the information: 
ERROR: Async bot thread failed: resource unavailable try again: resource unavailable try again

KataGo version: katago-v1.8.0-cuda11.2-windows-x64
weight: kata1-b40c256-s6046032896-d1456262172
RAM: 96GB

log file (including all the 3 games):
[20210206-193625-4EE0CDFA.log](https://github.com/lightvector/KataGo/files/5937123/20210206-193625-4EE0CDFA.log)

config file:
[default_gtp_japanese.zip](https://github.com/lightvector/KataGo/files/5937126/default_gtp_japanese.zip)

demo:
[KataGo3090-rsun-2.zip](https://github.com/lightvector/KataGo/files/5937148/KataGo3090-rsun-2.zip)

screenshots:
![1](https://user-images.githubusercontent.com/19167292/107123209-361c1700-68d7-11eb-8d0d-d84c3b765887.png)

![2](https://user-images.githubusercontent.com/19167292/107123211-3caa8e80-68d7-11eb-89da-3c9da23c2714.png)

**Comment by petgo3** [comment]
your config includes:
 nnCacheSizePowerOfTwo = 32
this is 256 times more than me (with a 2080TI and 32 GB Ram)
i think you should reduce it.
 
 my config:
# Cache up to 2 ** this many neural net evaluations in case of transpositions in the tree.
nnCacheSizePowerOfTwo = 24
# Size of mutex pool for nnCache is 2 ** this
nnMutexPoolSizePowerOfTwo = 20

**Comment by sbbdms** [comment]
> your config includes:
> nnCacheSizePowerOfTwo = 32
> this is 256 times more than me (with a 2080TI and 32 GB Ram)
> i think you should reduce it.
> 
> my config:
> 
> nnCacheSizePowerOfTwo = 24
> 
> nnMutexPoolSizePowerOfTwo = 20

KataGo only uses ~75GB RAM under nnCacheSizePowerOfTwo = 32, and 24 is the maximum value of nnMutexPoolSizePowerOfTwo. I still have plenty idle RAM. Is it the reason that causes this crash?

**Comment by petgo3** [comment]
Memory consumtion is growing. nnCacheSizePowerOfTwo = 24 leads to nearly 4 GB comsumption, if running constantly many games. So 32 would lead roughly to 1TB ...

**Comment by sbbdms** [comment]
Thanks, I will try to reduce the values and observe with my task manager open.

**Comment by petgo3** [comment]
Hint: Taskmanager is not to trustable (there might be timeshift e.g.)

**Comment by sbbdms** [comment]
What's the maximum proper value to fit my RAM... nnCacheSizePowerOfTwo = 24 seems to use <500MB RAM when launching KataGo. Is it enough under ~200000 visits?

**Comment by petgo3** [comment]
Cache is growing slowly, so wait until some games done ...

**Comment by lightvector** [comment]
@sbbdms - No matter what cache size you set, it still only uses memory proportional to how much of the cache is filled. So the memory use at launch time tells you nothing about how big you should set the cache. The data structure for the cache itself does also take some memory even when not filled, but almost all of the memory usage only happens once filled.

Instead you should just multiply according to the documentation.
https://github.com/lightvector/KataGo/blob/master/cpp/configs/gtp_example.cfg#L24

The doc says 1.5kb per entry if you have ownership off, which should be the case when just playing games, unless you've done something special to turn it on. If you want to be conservative and account for other overhead, round up to 2kb/entry. So then just do the math. 24 means the cache has 2**24 entries, 32 means the cache has 2**32 entries, multiply to find out the peak memory usage of the cache (and the rest of KataGo's memory usage beyond the cache should not be more than a few GB).

**Comment by sbbdms** [comment]
> @sbbdms - No matter what cache size you set, it still only uses memory proportional to how much of the cache is filled. So the memory use at launch time tells you nothing about how big you should set the cache. The data structure for the cache itself does also take some memory even when not filled, but almost all of the memory usage only happens once filled.
> 
> Instead you should just multiply according to the documentation.
> https://github.com/lightvector/KataGo/blob/master/cpp/configs/gtp_example.cfg#L24
> 
> The doc says 1.5kb per entry if you have ownership off, which should be the case when just playing games, unless you've done something special to turn it on. If you want to be conservative and account for other overhead, round up to 2kb/entry. So then just do the math. 24 means the cache has 2^24 entries, 32 means the cache has 2^32 entries, multiply to find out the peak memory usage of the cache (and the rest of KataGo's memory usage beyond the cache should not be more than a few GB).

Thanks very much for explaining...
2^25*2kb=64GB, so i am going to adjust that value to 25.
