### ISSUE TITLE
Prompt error, unable to download training network 

### ISSUE THREAD

**Issue by kppomzh** [lightvector/KataGo#421]
Windows 10 20H2

---RESPONSE---------------------
Status Code: 403
Header: allow: POST, OPTIONS
Header: CF-Cache-Status: DYNAMIC
Header: CF-RAY: 621ea3b5dae1ed3b-SJC
Header: cf-request-id: 084704a5a20000ed3bd72fc000000001
Header: Connection: close
Header: content-language: en
Header: Content-Length: 63
Header: Content-Type: application/json
Header: Date: Mon, 15 Feb 2021 11:20:25 GMT
Header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Header: NEL: {"report_to":"cf-nel","max_age":604800}
Header: Report-To: {"max_age":604800,"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=GTC5QThMFLBDJg3htS0HqAE9lqUHoefg5RVHKnPF9nX4D8QhJVrJImpZW1dnN9yI8noW9AOwwSFfcrm8RP7J+TM0CeZBz6F+nNaJi8AGPwlhNDQ="}]}
Header: Server: cloudflare
Header: Set-Cookie: __cfduid=df56d959fa37104ef17009eab02d8ae7b1613388025; expires=Wed, 17-Mar-21 11:20:25 GMT; path=/; domain=.katagotraining.org; HttpOnly; SameSite=Lax
Header: strict-transport-security: max-age=15552000; includeSubDomains; preload
Header: vary: Accept, Accept-Language
Header: Via: 1.1 google
Header: x-content-type-options: nosniff
Header: x-frame-options: DENY
Header: x-xss-protection: 1; mode=block
Body:
{"detail":"You do not have permission to perform this action."}

**Comment by Friday9i** [comment]
Did you check the process and especially the login & password to be included in the config file?

**Comment by kppomzh** [comment]
@Friday9i 
Such output can be considered that the training program has been running normally, but the network file cannot be downloaded correctly from the server. I don't think there is any problem with my configuration, unless the server address which given in the example configuration file is wrong. 
Otherwise, that following output should not be printed: 
Body:
{"detail":"You do not have permission to perform this action."}

2021-02-15 20:54:45+0800: Downloaded 4712762 / 173527854 bytes for model: https://media.katagotraining.org/uploaded/netw
orks/models/kata1/kata1-b40c256-s6371201536-d1545042795.bin.gz

**Comment by lightvector** [comment]
Yes, that message means you have successfully typed the server address, but it does not mean you have successfully used your username and password. Generally it means either:

* Maybe you mistyped your username or your password (which would cause you to not have permission, because your client can contact the server but not log in).
* You forgot to complete the registration process by verifying your email address. (which would cause you to not have permission, because your account would not actually be fully created and active yet).

It's on the todo list to make the error message clearer.

**Comment by lightvector** [comment]
And the reason you might see a download still proceeding is because downloading networks doesn't require permission or login - all networks are public. So don't be confused by that.

**Comment by kppomzh** [comment]
@lightvector Thank you,I don't notice the register email.Now it works normally.
