### ISSUE TITLE
I have a question！

### ISSUE THREAD

**Issue by egBean** [lightvector/KataGo#436]
I thought if I do not set param dynamicPlayoutDoublingAdvantageCapPerOppLead,the default value is 0.045.and when katago engine start,param playoutDoublingAdvantage would be calculate by param dynamicPlayoutDoublingAdvantageCapPerOppLead?
But how can I get param playoutDoublingAdvantage's value  when game start? I use kata-get-param playoutDoublingAdvantage   but return zero,is this because of analysis mode?
你好，即使我直接使用默认设置开始让子棋游戏，是不是pda的值也是会被计算出来而不是默认0呢？我看可以根据dynamicPlayoutDoublingAdvantageCapPerOppLead这个参数来计算，最大值是2.75。但是我使用kata-get-param playoutDoublingAdvantage 命令返回的却是0.是因为是分析模式的原因吗？我怎么拿到游戏进行时的pda数值呢？

**Comment by lightvector** [comment]
Sorry, I think there is no nice programmatic way to current value value out of KataGo right now, other than to replicate the formula by yourself based on the reported score difference that kata-analyze or the analysis engine would return to you. If it is necessary, we could try finding a way to expose it.

The reason it always returns 0 is that user parameter `dynamicPlayoutDoublingAdvantageCapPerOppLead` does NOT operate by setting the user parameter `playoutDoublingAdvantage`. Instead, it directly sets the internal `playoutDoublingAdvantage` value. When you use kata-get-param, it reports the user parameter setting, which yes, also applies to analysis, whereas the dynamic one does not. It's all a little messy here right now, sorry. Let me know if you have a particular use case.

**Comment by egBean** [comment]
Thanks,I just want to know if there is a pda param which calculated by dynamicPlayoutDoublingAdvantageCapPerOppLead when I play with katago with default settings in handicap game.
