### ISSUE TITLE
Wishlist: Support traditional Chinese (scoring) rule?

### ISSUE THREAD

**Issue by Iey4iej3** [lightvector/KataGo#44]
In the abstract of an [article](https://www.cs.cmu.edu/~wjh/go/rules/Chinese.html), the author sketched the traditional Chinese (scoring) rule, and the difference between the traditional one and the modern one:

> Under the traditional Chinese rules, a player's score was the maximum number of stones he could in theory play on the board. Since every groups needs two liberties to live, this rule created a two-point group tax: the player with the more separate groups lost two points for evey excess group. (In practice, one point per excess group was subtracted from the player's score and added to his opponent's score so that the total remained 361. {This does not compute; it could convert a clear winner into a loser. Only by adding two points per group could the total be made 361. --wjh}) Modern Chinese rules avoid this by counting both stones and surrounded points.

I wonder whether we would support this. It could be used to analyze traditional Chinese games, and to understand differences of good strategies between the traditional one and the modern one.

**Comment by Iey4iej3** [comment]
Sorry, this is mentioned in the ReadMe. Feel free to close it.

**Comment by lightvector** [comment]
KataGo now actually does support this, with the v1.3 release! See a description of the supported rules here:
https://lightvector.github.io/KataGo/rules.html

Set "taxRule" to the appropriate thing in your configs. Enjoy!
