### ISSUE TITLE
README.txt

### ISSUE THREAD

**Issue by tedthegypsy** [lightvector/KataGo#447]
Thanks for all your KataGo.

README.txt inside  lizzie folder hasn't been updated for a longtime.
Showing,
KataGo v1.6.0
https://github.com/lightvector/KataGo

It's not so important, but this texist is the only way to confirm 
the KataGo version for me.

Will you update README.txt as well when you update KataGo next time please.

**Comment by lightvector** [comment]
Presumably the readme is correct and NOT out of date. Lizzie probably is actually using an old version of KataGo.
I don't maintain Lizzie and have nothing to do with updating it. It sounds like you should open this issue at Lizzie's github: https://github.com/featurecat/lizzie

**Comment by tedthegypsy** [comment]
Thank you for your prompt reply.

It seems that I have confused Lizzie with KataGo.
I close this issue.
