### ISSUE TITLE
Mismatch? The default value of conservativePass

### ISSUE THREAD

**Issue by sbbdms** [lightvector/KataGo#458]
Code in setup.cpp:

>     if(cfg.contains("conservativePass"+idxStr)) params.conservativePass = cfg.getBool("conservativePass"+idxStr);
    else if(cfg.contains("conservativePass"))   params.conservativePass = cfg.getBool("conservativePass");
    else                                        params.conservativePass = false;

Description in gtp_example.cfg:

> \# Make the bot never assume that its pass will end the game, even if passing would end and "win" under Tromp-Taylor rules.
\# Usually this is a good idea when using it for analysis or playing on servers where scoring may be implemented non-tromp-taylorly.
\# Defaults to true! Uncomment and set to false to disable this.
\# conservativePass = true

**Comment by lightvector** [comment]
Thanks. I think there is no bug, just some more confusing-than-necessary code. This parameter is specifically overridden to another default for gtp:
https://github.com/lightvector/KataGo/blob/master/cpp/command/gtp.cpp#L1484

**Comment by sbbdms** [comment]
Thanks for pointing out, this "issue" is invalid...
