### ISSUE TITLE
Making a "Pass" in the beginning of a game, abnormal search result in the log

### ISSUE THREAD

**Issue by sbbdms** [lightvector/KataGo#473]
Brief description:
I was testing a pair of new parameters of the highthreads2 branch (https://github.com/lightvector/KataGo/pull/449).
I opened a new game against HiraBot (6d) on KGS, where KataGo played as white, gave 6 stones and afforded 9.5 reverse komi (http://files.gokgs.com/games/2021/4/28/KataGo3090-HiraBot41.sgf).

Unexpectedly KataGo played a "Pass" for its 2nd move...
The corresponding log of the move:

> 2021-04-29 04:48:22+0800: MoveNum: 2 HASH: 5289C1362E2F7B0E6905B7EE3B6492A6
   A B C D E F G H J K L M N O P Q R S T
19 . . . . . . . . . . . . . . . . . . .
18 . . . . . . . . . . . . . . . . . . .
17 . . . . . . . . . . . . . . . . . . .
16 . . . X . . . . . . . . . . . X . . .
15 . . X . . . . . . . . . . . . . . . .
14 . . O . . . . . . . . . . . . . . . .
13 . . . . . . . . . . . . . . . . . . .
12 . . . . . . . . . . . . . . . . . . .
11 . . . . . . . . . . . . . . . . . . .
10 . . . X . . . . . . . . . . . X . . .
 9 . . . . . . . . . . . . . . . . . . .
 8 . . . . . . . . . . . . . . . . . . .
 7 . . . . . . . . . . . . . . . . . . .
 6 . . . . . . . . . . . . . . . . . . .
 5 . . . . . . . . . . . . . . . . . . .
 4 . . . X . . . . . . . . . . . X . . .
 3 . . . . . . . . . . . . . . . . . . .
 2 . . . . . . . . . . . . . . . . . . .
 1 . . . . . . . . . . . . . . . . . . .

> koPOSITIONALscoreAREAtaxNONEsui0whbNfpok1komi-9.5
> Time taken: 12.047
> Root visits: 26234
> New playouts: 25506
> NN rows: 20165
> NN batches: 381
> NN avg batch size: 52.9265
> PlayoutDoublingAdvantage: 2.75
> PV: pass pass
> Tree:
> : T -117.92c W -99.99c S -17.93c (-61.7 L -57.8) N   26234  --  pass pass
> ---White(^)---
> pss : T -103.46c W -100.00c S  -3.46c (-51.0 L -47.9) LCB -108.06c P  0.06% WF 42436.0 PSV 1832453 N    3396  --  pass pass
> D14 : T -126.76c W -99.99c S -26.77c (-68.3 L -63.9) LCB -126.82c P 30.09% WF 56840.1 PSV   75265 N   20104  --  D14 F16 G14 G11 C6 J16 O17 G4
> F3  : T -127.63c W -99.99c S -27.65c (-68.9 L -64.5) LCB -128.16c P  6.40% WF 1236.3 PSV    1205 N     317  --  F3 D14 O3 F4 G4 F5 R6
> O17 : T -127.59c W -99.99c S -27.60c (-68.9 L -64.6) LCB -128.15c P  5.53% WF 1127.3 PSV    1091 N     292  --  O17 D14 R14 O16 N16 O15 R17
> C6  : T -127.73c W -99.99c S -27.74c (-68.8 L -64.5) LCB -128.34c P  5.62% WF 980.6 PSV     947 N     251  --  C6 D14 F3 D6 D13 C13 B14
> O3  : T -127.70c W -99.99c S -27.71c (-68.9 L -64.5) LCB -128.26c P  5.25% WF 954.8 PSV     920 N     242  --  O3 D14 F3 F4 G4 F5
> R14 : T -127.17c W -99.99c S -27.18c (-68.5 L -64.2) LCB -127.72c P  1.98% WF 838.2 PSV     789 N     212  --  R14 D14 R6 R5 Q6 O4
> F17 : T -127.73c W -99.99c S -27.74c (-68.8 L -64.5) LCB -128.50c P  3.92% WF 734.6 PSV     700 N     185  --  F17 D14 E15 C13 O17 H17
> C17 : T -128.22c W -99.99c S -28.23c (-69.2 L -65.0) LCB -129.29c P  4.45% WF 538.4 PSV     513 N     142  --  C17 D14 F18 D17 D18 F17 G17
> R6  : T -127.60c W -99.99c S -27.61c (-68.8 L -64.3) LCB -128.46c P  1.96% WF 407.7 PSV     378 N     100  --  R6 D14 F3 F4 O3
> 
> 2021-04-29 04:48:22+0800: = pass
> 2021-04-29 04:48:22+0800: Controller: time_left w 158 0
> 2021-04-29 04:48:22+0800: = 

Which seems to be extremely strange.

However the situation is a bit complicated --- I modified some code from the highthreads2 branch (For playing on KGS, not for generating games to assess parameters). The modification is a bit amateur and I am not sure if it implement bugs.

In general I am not sure which part caused the move. It may be caused by my modification, and it is also possible caused by initial code, or parameters in the config file.

My log records the nnRandSeed and the time (exact to second) I launched KataGo. However I cannot reproduce the situation with the fixed nnRandSeed and the system time --- I think it also needs to find the exact searchRandSeed, which wasn't recorded in the log, and I don't know if it can be conjectured by the nnRandSeed and the time I launched.

I will record more information, with some attach below.

**Comment by sbbdms** [comment]
Network: b40s785

Tree of KataGo: https://github.com/lightvector/KataGo/tree/b412243d72693c81c5e23a9dd926435044863548 (I compiled it on 2021-03-27, 2644 commits in total)

The part I modified:

(1) nneval.cpp: Changing the initial hard-coded dagger pattern from MYT's to another:
![1 nneval cpp](https://user-images.githubusercontent.com/19167292/116641913-473d6700-a9a0-11eb-9cb1-fcfdabb6ac93.png)

(2) gtp.cpp: Trying to change avoidMYTDaggerHack and dynamicScoreUtilityFactor between different handicaps:
![2-1 gtp cpp](https://user-images.githubusercontent.com/19167292/116641987-6fc56100-a9a0-11eb-9b16-727c6e969895.png)

![2-2 gtp cpp](https://user-images.githubusercontent.com/19167292/116641995-73f17e80-a9a0-11eb-901a-84f49e001bfb.png)

(3) main.cpp: The version of KataGo
![3 main cpp](https://user-images.githubusercontent.com/19167292/116642019-823f9a80-a9a0-11eb-9861-d7cd4701cf2e.png)

Log and the config file:
[20210429-044747-B34E0778.log](https://github.com/lightvector/KataGo/files/6402727/20210429-044747-B34E0778.log)
[default_gtp_japanese.zip](https://github.com/lightvector/KataGo/files/6402728/default_gtp_japanese.zip)

PS: The config file is set to use Japanese rule, but the actual game is in Chinese-ogs rule, so KataGo automatically changed the rule to Chinese-ogs, regardless of the config file.

**Comment by lightvector** [comment]
I'm not sure what the cause is, but at least your way of setting parameters looks unsafe, especially given that you have pondering enabled so that there might be a search ongoing at the same time. You are not supposed to reach inside the engine and directly modify the parameters, you are supposed to use the setParams method.

**Comment by lightvector** [comment]
If the changes you screenshotted are truly the only changes, then I still don't see how this is possible, even given the unsafe way of setting parameters. So I'm also not sure how to reproduce this. :)

**Comment by sbbdms** [comment]
If I have both nnRandSeed and searchRandSeed, is it more possible to reproduce this situation?

**Comment by lightvector** [comment]
If you use only 1 search thread, and you fix the seeds, then yes, it should be deterministic for a particular computer and GPU.

**Comment by sbbdms** [comment]
Thanks for your answer!
It seems that nothing could do to this situation...
I am going to close this issue, and try to find another safe way to modify the code.
If the situation happen again (Hopes so), I will reopen it.

**Comment by sbbdms** [comment]
I guess I have found out the situation that can trigger this. It's extremely lucky, I just thought it might never happen again...

Though I notice your comment that PDA value which higher than 2.75 may result in worse performance because of the lack of well training, I want to have a validation today. So I modified:

(1) Unlimit the maximum PDA from 2.75 (I set it to 10)
(2) Make PDA a high value like 5.0~6.0, by changing dynamicPlayoutDoublingAdvantageCapPerOppLead to a higher value, or letting KataGo afford a huge handicap.
(3) chinese-ogs rule

If the PDA is around 4.5, you will probably see the "Pass" move in the move selection list, and it would be possibly chosen. For example:

> ---White(^)---
Q6  : T -121.69c W -99.89c S -21.80c (-52.8 L -49.5) LCB -121.80c P 43.98% WF 31485.0 PSV   31739 N   11140  --  Q6 O4 N6 L4 R14 R12 P14 N16
R3  : T -121.54c W -99.91c S -21.63c (-52.6 L -49.4) LCB -121.81c P 19.20% WF 15782.0 PSV   15789 N    5806  --  R3 Q3 S5 R4 S4 S3 Q7 R8
C4  : T -123.55c W -99.90c S -23.65c (-54.0 L -50.6) LCB -124.33c P  5.21% WF 1263.4 PSV    1308 N     463  --  C4 C3 C5 D5 B3 D3 C7 Q6
R14 : T -123.34c W -99.90c S -23.44c (-53.7 L -50.2) LCB -123.99c P  2.70% WF 720.7 PSV     732 N     258  --  R14 Q6 O17 O16 N16 P17 O15
pss : T -120.81c W -87.32c S -33.49c (-62.4 L -58.8) LCB -130.05c P  0.11% WF 19016.8 PSV     706 N    2902  --  pass Q6 R14 R15 Q14 O16 M17
F3  : T -123.15c W -99.90c S -23.25c (-53.9 L -50.4) LCB -124.02c P  2.13% WF 618.6 PSV     623 N     222  --  F3 Q6 C6 F4 Q7 P6 G4
O17 : T -123.35c W -99.90c S -23.44c (-53.9 L -50.4) LCB -124.07c P  1.98% WF 529.2 PSV     535 N     187  --  O17 Q6 F17 O16 N16 O15
C6  : T -122.79c W -99.89c S -22.90c (-53.5 L -50.1) LCB -123.52c P  1.45% WF 503.5 PSV     497 N     182  --  C6 Q6 C14 C15 D14 F16 F3
F17 : T -123.40c W -99.89c S -23.51c (-54.0 L -50.5) LCB -124.46c P  1.76% WF 461.7 PSV     465 N     169  --  F17 Q6 F3 K3 C6 D6
R16 : T -124.97c W -99.90c S -25.07c (-54.9 L -51.4) LCB -126.18c P  2.72% WF 428.8 PSV     455 N     158  --  R16 R17 R15 Q15 R14 Q17 Q6

If the PDA is high as 5 or 6, then the "Pass" move is very likely to be chosen.

I think it is far out of my expectation and is probably abnormal. Below is my reason:

(1) Though I know that PDA value which is higher than 2.75 may result in worse performance because of the lack of well training, it shouldn't be such bad that generate a "Pass" move in the beginning. Actually if KataGo doesn't select "Pass" move, it can still give 7 handicap stones to a 6D bot on KGS with ~4.5 PDA.

(2) It happens in chinese-ogs rule, but not in japanese rule.

(3) Its output is very strange: If the komi is a positive number, then if the "Pass" move appears, then it is with a very high winrate but a very low score. If the komi is a negative number, then the "Pass" move is with a very low winrate but a very high score.

(4) It may be the reason of the issue happened 2 days ago, because the phenomenon matches the description above (If the komi is a negative number, then the "Pass" move is with a very low winrate but a very high score). If so, then it means it might not only happen with high PDA, but also some low PDA like 2.75.

I am not sure if it only happens in Highthreads2 branch, may do some validation later.

What do you think of this phenomenon? Is it normal?

**Comment by lightvector** [comment]
It is not merely "lack of well training", it is **no training at all**. PDA values above 3 are invalid input, because they do not occur in training at all. Specifying a PDA value above 3 may to some degree be sort of like telling KataGo that an illegal move was played, or that a stone is both black and white at the same time. In these situations, it is quite expected that the output will not make sense, because the input is invalid.

Or you could get lucky and the neural net extrapolates anyways, the same way it extrapolates to board sizes that it has never seen before. But there is no guarantee. This means you should not also expect PDA > 3 to be better at playing handicap games unless you have run the necessary dozens or hundreds of games to validate that it actually does help, and if you do validate it, you should also not expect it to be consistent across different neural networks because again - there is *no training at all* for PDA > 3, a network can say absolutely anything it wants for PDA > 3 and it would be equally correct and valid.

So any conclusions you make with PDA above 3 are untrustworthy and should not be used to make any conclusions. Can you instead try to reproduce with PDA <= 3?

**Comment by lightvector** [comment]
By the way, the real mystery here I'm still be curious about in your original log, is **why did black pass in response in the principal variation**?

In that log, it shows that white knows that passing is 100% losing, but it believes it is preferred because it loses by fewer points than playing out the game. However, the only reason it loses by fewer points is because black has a large chance to pass in response, and therefore wins only by the area-scoring value of the stones on the board because nobody has any territory. Indeed, passing in response is the principle variation in the log you put in.

But why does black want to pass in response, if black believes that leads to an even worse score? Black should take advantage of the free move and be even farther ahead, and then this would let white realize that passing is bad.

That's the thing I'm curious about. I've played with it a few times, but am having some trouble reproducing the result, and understanding what parameters can cause it. It's an interesting bug to figure out, if it's real. :)

**Comment by lightvector** [comment]
It might be possible to investigate by seeing what kind of configuration causes black to be highly likely to pass *in response to white's pass*, rather than by looking for configurations that cause white to pass in the first place. Does that make sense?

**Comment by sbbdms** [comment]
I reset the maximum PDA to 3.0. I can hardly reproduce the situation directly. However I found another example that might explain.

With these setting below:

(1) chinese-ogs rule
(2) conservativePass = false
(3) KataGo plays as white, affords >=4 handicap stones, and a few reverse komi (like -10 or -20)

Then if opponent plays a "Pass" in the beginning, KataGo will very likely to follow a "Pass" and the game will be scored, KataGo will lose directly.

A test log for example:

> 2021-05-03 01:05:18+0800: Controller: play b pass
2021-05-03 01:05:18+0800: = 
2021-05-03 01:05:18+0800: Controller: genmove w
2021-05-03 01:05:21+0800: MoveNum: 4 HASH: 2A57ED4CA03BD85E48E5F6264E5D62A6
   A B C D E F G H J K L M N O P Q R S T
19 . . . . . . . . . . . . . . . . . . .
18 . . . . . . . . . . . . . . . . . . .
17 . . . . . . . . . . . . . . . . . . .
16 . . . X . . . . . . . . . . . X . . .
15 . . . . . . . . . . . . . . . . . . .
14 . . O2. . . . . . . . . . . . . . . .
13 . . . . . . . . . . . . . . . . . . .
12 . . . . . . . . . . . . . . . . . . .
11 . . . . . . . . . . . . . . . . . . .
10 . . . . . . . . . . . . . . . . . . .
 9 . . . . . . . . . . . . . . . . . . .
 8 . . . . . . . . . . . . . . . . . . .
 7 . . . . . . . . . . . . . . . . . . .
 6 . . O . . . . . . . . . . . . . . . .
 5 . . . . . . . . . . . . . . . . . . .
 4 . . . X . . . . . . . . . . . X . . .
 3 . . . . . X1. . . . . . . . . . . . .
 2 . . . . . . . . . . . . . . . . . . .
 1 . . . . . . . . . . . . . . . . . . .

koPOSITIONALscoreAREAtaxNONEsui0whbNfpok1komi-20
Time taken: 3.625
Root visits: 311417
New playouts: 281904
NN rows: 390
NN batches: 371
NN avg batch size: 1.05121
PlayoutDoublingAdvantage: 3
PV: pass
Tree:
: T -107.89c W -100.00c S  -7.89c (-19.0 L -19.0) N  311417  --  pass
---White(^)---
pss : T -107.87c W -100.00c S  -7.87c (-19.0 L -19.0) LCB -107.87c P 95.89% WF 310995.8 PSV  310939 N  310939  --  pass
R17 : T -120.21c W -99.73c S -20.48c (-38.2 L -35.6) LCB -120.54c P  0.69% WF  83.0 PSV     102 N     102  --  R17 R16 Q17 O17 O18 N17 F17
Q17 : T -120.53c W -99.72c S -20.81c (-38.8 L -36.2) LCB -121.57c P  0.18% WF  22.5 PSV      26 N      26  --  Q17 R17 P17 P16 R18 R16
R18 : T -121.21c W -99.75c S -21.46c (-39.9 L -37.2) LCB -121.97c P  0.16% WF  19.0 PSV      22 N      22  --  R18 P17 F17 F16 G16
B4  : T -119.74c W -99.69c S -20.05c (-37.4 L -34.7) LCB -120.77c P  0.15% WF  19.3 PSV      22 N      22  --  B4 F17 O3 J3
Q18 : T -120.53c W -99.72c S -20.81c (-38.8 L -36.1) LCB -121.20c P  0.15% WF  18.3 PSV      21 N      21  --  Q18 P17 F17 F16 G16
P18 : T -120.62c W -99.73c S -20.89c (-38.8 L -36.2) LCB -121.95c P  0.13% WF  16.6 PSV      19 N      19  --  P18 O17 F17 F16 G16
C17 : T -120.23c W -99.72c S -20.51c (-38.4 L -35.8) LCB -121.18c P  0.13% WF  15.8 PSV      18 N      18  --  C17 C16 D17 E16 F18 C12 E14
B16 : T -120.27c W -99.72c S -20.55c (-38.1 L -35.4) LCB -121.37c P  0.12% WF  15.8 PSV      18 N      18  --  B16 H17 F17 F16 E17
R16 : T -120.49c W -99.71c S -20.77c (-38.8 L -36.2) LCB -122.04c P  0.11% WF  14.1 PSV      15 N      16  --  R16 R17 R15 Q15 R14 Q17

2021-05-03 01:05:21+0800: = pass
2021-05-03 01:05:22+0800: Controller: time_left w 152 0
2021-05-03 01:05:22+0800: = 
2021-05-03 01:05:22+0800: Controller: final_status_list dead
2021-05-03 01:05:23+0800: = 
2021-05-03 01:05:31+0800: All cleaned up, quitting

It seems that, with the setting above, if KataGo affords some handicap stones (Usually >=4) and a reverse komi (like -10 or -20), and opponent plays a "Pass" in the beginning, then KataGo will think:

(1) Following a "Pass" move has a very high probability (95.89% in the log above)
(2) The winrate doesn't differ much between a "Pass" move (-100.00c) and a non-pass move (~-99.70c)
(3) The score differs much. A "Pass" move leads to a much smaller loss (-19.0) than a non-pass move (~-38.0)

So KataGo follows a "Pass".

I think it might explain the issue happened 3 days ago. In that game KataGo affords 6 handicap stones and a reverse komi (-9.5). When KataGo analyses its next move, there's a chance where it think about the double-pass sequence and find it is the "Best" choice (Similar winrate as non-pass sequence but much better score), then plays a "Pass".

What do you think about this phenomenon? Is it normal?

**Comment by sbbdms** [comment]
> It might be possible to investigate by seeing what kind of configuration causes black to be highly likely to pass in response to white's pass, rather than by looking for configurations that cause white to pass in the first place. Does that make sense?

According to the network lists above, if the opponent plays a "Pass" move first, then KataGo thinks that, following a "Pass" move has a very high probability (95.89% in the log above)

So that might be the reason why KataGo thinks about the double-pass sequence?

**Comment by sbbdms** [comment]
> It might be possible to investigate by seeing what kind of configuration causes black to be highly likely to pass in response to white's pass, rather than by looking for configurations that cause white to pass in the first place. Does that make sense?

I am not sure about that...

According to the log above, if KataGo is the side that is far BEHIND, and its opponent plays a "Pass" in the first place, then KataGo thinks that it has a very high probability (95.89% in the log above) to follow a "Pass".

It's also strange because KataGo should take advantage to the free move and lessen the gap, right? But the probability in the log is indeed 95.89%...

I am not sure, if KataGo is the side that is far AHEAD, and its opponent plays a "Pass" in the first place, then what's the probability that KataGo follow a "Pass"?

I can't validate for now because I am generating games for highthreads2 branch. Will have a validate later.

**Comment by lightvector** [comment]
> According to the log above, if KataGo is the side that is far BEHIND, and its opponent plays a "Pass" in the first place, then KataGo thinks that it has a very high probability (95.89% in the log above) to follow a "Pass".

> It's also strange because KataGo should take advantage to the free move and lessen the gap, right? But the probability of following a "Pass" in the log is indeed 95.89%...

Good observation. I think this is correct and makes perfect sense. If you are playing without conservativePass=true, which means that the game is being played under strict Tromp-Taylor-style scoring, and you are trying to maximize your score, and you are far BEHIND, then passing to end the game is the optimal action because you lose by far fewer points than if you were to continue playing. This is completely reasonable.

> So if KataGo is the side that is far AHEAD, and its opponent plays a "Pass" in the first place, then what's the probability that KataGo thinks itself to follow a "Pass"?

Right, so the critical thing is what happens when are you ahead. The side that is ahead should not want to pass and end the game, they should want to take a free move to extend their score further.

**Comment by sbbdms** [comment]
I have validated.

If KataGo plays as black, the opponent affords 6 handicap stones and a -9.5 reverse komi, then if opponent plays a "Pass" on its 2nd move, KataGo thinks that following a "Pass" has a 81.54% probability in a game, so KataGo follows a "Pass" and the game is scored.

If the komi is 0.5 (KataGo will lose by 0.5 if it follows a "Pass"), KataGo still thinks the probability is 68.14% (However it doesn't follow because of the huge difference of winrate though)

So, if KataGo is the side that is far AHEAD, and its opponent plays a "Pass" in the first place, there's still a very high probability that KataGo thinks itself to follow a "Pass".

I think that's the reason why KataGo considers about a double-pass sequence 3 days ago.

Two logs below:

(1) Komi=-9.5

> 2021-05-03 09:30:30+0800: Controller: play w pass
2021-05-03 09:30:31+0800: = 
2021-05-03 09:30:31+0800: Controller: genmove b
2021-05-03 09:30:34+0800: MoveNum: 3 HASH: 6BD0A4E90B446003988A41B44EE62505
   A B C D E F G H J K L M N O P Q R S T
19 . . . . . . . . . . . . . . . . . . .
18 . . . . . . . . . . . . . . . . . . .
17 . . . . . O1. . . . . . . . . . . . .
16 . . . X . . . . . X . . . . X . X . .
15 . . . . . . . . . . . . . . . . . . .
14 . . . . . . . . . . . . . . . . . . .
13 . . . . . . . . . . . . . . . . . . .
12 . . . . . . . . . . . . . . . . . . .
11 . . . . . . . . . . . . . . . . . . .
10 . . . . . . . . . . . . . . . X2. . .
 9 . . . . . . . . . . . . . . . . . . .
 8 . . . . . . . . . . . . . . . . . . .
 7 . . . . . . . . . . . . . . . . . . .
 6 . . . . . . . . . . . . . . . . . . .
 5 . . . . . . . . . . . . . . . . . . .
 4 . . . X . . . . . . . . . . . X . . .
 3 . . . . . . . . . . . . . . . . . . .
 2 . . . . . . . . . . . . . . . . . . .
 1 . . . . . . . . . . . . . . . . . . .

> koPOSITIONALscoreAREAtaxNONEsui0whbNfpok1komi-9.5
> Time taken: 3.703
> Root visits: 13829
> New playouts: 5416
> NN rows: 5482
> NN batches: 104
> NN avg batch size: 52.7115
> PlayoutDoublingAdvantage: -3
> PV: pass
> Tree:
> : T 121.48c W 100.00c S  21.48c (+56.6 L +53.0) N   13829  --  pass
> ---Black(^)---
> pss : T 100.32c W 100.00c S   0.32c ( +9.5 L  +9.5) LCB  100.32c P 81.54% WF 4883.5 PSV    8097 N    8097  --  pass
> L4  : T 133.09c W 100.00c S  33.09c (+83.1 L +77.3) LCB  132.99c P  0.27% WF  89.1 PSV      57 N      57  --  L4 F3 E17 F16 D14
> J4  : T 133.12c W 100.00c S  33.12c (+83.3 L +77.5) LCB  133.02c P  0.24% WF  89.2 PSV      57 N      57  --  J4 C14 E15 C17 D17 C16
> D14 : T 133.03c W 100.00c S  33.03c (+82.0 L +76.4) LCB  132.95c P  0.23% WF  89.1 PSV      57 N      57  --  D14 O3 O4 E15 D15
> M4  : T 133.06c W 100.00c S  33.06c (+82.6 L +76.9) LCB  132.97c P  0.22% WF  89.1 PSV      57 N      57  --  M4 F3 E17 F16 D14 C6
> K4  : T 133.13c W 100.00c S  33.14c (+83.3 L +77.5) LCB  133.06c P  0.28% WF  87.6 PSV      56 N      56  --  K4 C14 E15 C17 D17 C16
> D6  : T 132.99c W 100.00c S  32.99c (+81.6 L +76.0) LCB  132.88c P  0.27% WF  87.5 PSV      56 N      56  --  D6 C14 E15 C17 D17 C16
> N4  : T 133.04c W 100.00c S  33.04c (+82.4 L +76.9) LCB  132.94c P  0.22% WF  87.5 PSV      56 N      56  --  N4 C14 D14 D15 E15
> D13 : T 133.08c W 100.00c S  33.09c (+82.9 L +77.2) LCB  133.00c P  0.18% WF  87.5 PSV      56 N      56  --  D13 F3 J3 C6 D6
> M6  : T 133.04c W 100.00c S  33.05c (+82.7 L +77.0) LCB  132.95c P  0.13% WF  87.5 PSV      56 N      56  --  M6 C6 E17 F16 D14 F3
> 
> 2021-05-03 09:30:34+0800: = pass
> 2021-05-03 09:30:35+0800: Controller: time_left b 157 0
> 2021-05-03 09:30:35+0800: = 
> 2021-05-03 09:30:35+0800: Controller: final_status_list dead
> 2021-05-03 09:30:36+0800: = 
> 2021-05-03 09:30:54+0800: All cleaned up, quitting

(2) Komi=0.5

2021-05-03 09:32:07+0800: Controller: play w pass
2021-05-03 09:32:07+0800: = 
2021-05-03 09:32:07+0800: Controller: genmove b
2021-05-03 09:32:10+0800: MoveNum: 3 HASH: B475076300C6E1BF933AE10DB6906ECA
   A B C D E F G H J K L M N O P Q R S T
19 . . . . . . . . . . . . . . . . . . .
18 . . . . . . . . . . . . . . . . . . .
17 . . . . @ O1. . . . . . . . . . . . .
16 . . . X . X2. . . . . . . X . . X . .
15 . . . . . . . . . . . . . . . . . . .
14 . . . . . . . . . . . . . . . . . . .
13 . . . . . . . . . . . . . . . . . . .
12 . . . . . . . . . . . . . . . . . . .
11 . . . . . . . . . . . . . . . . . . .
10 . . . . . . . . . . . . . . . X . . .
 9 . . . . . . . . . . . . . . . . . . .
 8 . . . . . . . . . . . . . . . . . . .
 7 . . . . . . . . . . . . . . . . . . .
 6 . . . . . . . . . . . . . . . . . . .
 5 . . . . . . . . . . . . . . . . . . .
 4 . . . X . . . . . . . . . . . X . . .
 3 . . . . . . . . . . . . . . . . . . .
 2 . . . . . . . . . . . . . . . . . . .
 1 . . . . . . . . . . . . . . . . . . .

> koPOSITIONALscoreAREAtaxNONEsui0whbNfpok1komi0.5
> Time taken: 3.671
> Root visits: 5485
> New playouts: 5485
> NN rows: 5432
> NN batches: 104
> NN avg batch size: 52.2308
> PlayoutDoublingAdvantage: -3
> PV: E17 C6 C10 F3
> Tree:
> : T 130.64c W  99.89c S  30.75c (+72.8 L +67.7) N    5485  --  E17 C6 C10 F3
> ---Black(^)---
> E17 : T 131.11c W  99.99c S  31.12c (+74.5 L +69.2) LCB  130.90c P  1.36% WF  52.6 PSV     925 N      52  --  E17 C6 C10 F3
> G17 : T 131.08c W  99.99c S  31.09c (+74.5 L +69.1) LCB  130.85c P  1.14% WF  53.6 PSV      53 N      53  --  G17 R6 R5 Q6 O4 F3
> pss : T -118.66c W -100.00c S -18.66c ( -0.5 L  -0.5) LCB -118.67c P 68.14% WF   2.6 PSV      37 N      37  --  pass
> G16 : T 130.96c W  99.99c S  30.97c (+73.7 L +68.4) LCB  130.80c P  0.76% WF  52.5 PSV      34 N      52  --  G16 M17 D10 J17 G17
> K4  : T 131.02c W  99.99c S  31.03c (+74.4 L +69.1) LCB  130.75c P  0.39% WF  53.5 PSV      18 N      53  --  K4 G16 F15 D17 C17 E17
> R3  : T 130.67c W  99.99c S  30.68c (+71.7 L +66.8) LCB  130.39c P  0.44% WF  52.3 PSV      18 N      52  --  R3 G16 F15 E18 C17 D17
> L4  : T 130.94c W  99.99c S  30.95c (+73.9 L +68.6) LCB  130.68c P  0.41% WF  52.5 PSV      18 N      52  --  L4 G16 F15 E18 C17 G15 G14
> P3  : T 130.74c W  99.99c S  30.75c (+72.3 L +67.3) LCB  130.49c P  0.42% WF  53.4 PSV      17 N      53  --  P3 G16 F15 D17 C17 E17
> O4  : T 130.76c W  99.99c S  30.77c (+72.6 L +67.5) LCB  130.47c P  0.41% WF  52.4 PSV      17 N      52  --  O4 G16 F15 E18 C17 G15
> M4  : T 130.92c W  99.99c S  30.93c (+73.7 L +68.4) LCB  130.65c P  0.36% WF  52.5 PSV      16 N      52  --  M4 G16 F15 E18 C17 D17
> 
> 2021-05-03 09:32:11+0800: = E17
> 2021-05-03 09:32:12+0800: Controller: time_left b 152 0
> 2021-05-03 09:32:12+0800: = 
> 2021-05-03 09:32:26+0800: All cleaned up, quitting

**Comment by lightvector** [comment]
Thanks. Yeah, so it looks like the neural net has some convergence issues here where it does put a significant amount of mass on passing. However, I think this is fine, it should not be a problem, not at this level. It normally should be the case that the search fixes this easily - even if the net puts 80% mass on pass, the search should *extremely* rapidly discover that the 20% mass on normal moves leads to higher score than the 80% pass, and then the 80% pass should get relatively few playouts.

And your own logs indicate that there is something weird going on that is NOT due to the neural net, but rather that there is some bug in the search.

Here is an excerpt from your log:
```
Root visits: 13829
New playouts: 5416
...
PlayoutDoublingAdvantage: -3
PV: pass
Tree:
: T 121.48c W 100.00c S 21.48c (+56.6 L +53.0) N 13829 -- pass
---Black(^)---
pss : T 100.32c W 100.00c S 0.32c ( +9.5 L +9.5) LCB 100.32c P 81.54% WF 4883.5 PSV 8097 N 8097 -- pass
L4 : T 133.09c W 100.00c S 33.09c (+83.1 L +77.3) LCB 132.99c P 0.27% WF 89.1 PSV 57 N 57 -- L4 F3 E17 F16 D14
J4 : T 133.12c W 100.00c S 33.12c (+83.3 L +77.5) LCB 133.02c P 0.24% WF 89.2 PSV 57 N 57 -- J4 C14 E15 C17 D17 C16
D14 : T 133.03c W 100.00c S 33.03c (+82.0 L +76.4) LCB 132.95c P 0.23% WF 89.1 PSV 57 N 57 -- D14 O3 O4 E15 D15
M4 : T 133.06c W 100.00c S 33.06c (+82.6 L +76.9) LCB 132.97c P 0.22% WF 89.1 PSV 57 N 57 -- M4 F3 E17 F16 D14 C6
```

This search output is absurd and buggy in a way that is not explained by the net. The pass move is evaluated as 100.32c whereas the other moves are 133.09c - so this is about a 30 centi-utility difference, or the equivalent of about 15% winrate. Under normal circumstances, it should not matter that a move has 81% policy, if its winrate is seen to be 15% worse than other moves, it should rapidly stop being searched and the other moves, no matter how low their policy is, should start being searched.

Indeed, this happens all the time in games. The neural net is mistaken, because it is not perfect, but the search should realize rapidly that the 80% preferred move is actually worse than some other move, so the other move gets the most playouts and is chosen instead.

But somehow, here the pass move still has the majority of the visits. So the problem is not the neural net, the problem is that the search is completely failing to do its job somehow.

Can you send me the config and the *exact* commands you are using to produce this situation? I would like to see if I can reproduce it. Also, does this result also happen for you with numSearchThreads = 1, or does it require a large numSearchThreads?

**Comment by sbbdms** [comment]
Editing

[default_gtp_japanese.zip](https://github.com/lightvector/KataGo/files/6412683/default_gtp_japanese.zip)
[20210503-093009-5929AFC4.zip](https://github.com/lightvector/KataGo/files/6412684/20210503-093009-5929AFC4.zip)

**Comment by sbbdms** [comment]
I think it is related by numSearchThreads and searchFactorAfterOnePass.

higher numSearchThreads, and lower searchFactorAfterOnePass, could reproduce the situation easier.

With default setting (searchFactorAfterOnePass=0.50), then setting numSearchThreads at around 75 is probably to reproduce the situation.

**Comment by lightvector** [comment]
(1) is not a problem. This is correct behavior because it minimizes score loss. If you prefer to avoid this behavior, don't change the default of conservativePass = true
(3) is caused by (2).

So there is only one problem here.

> Any plan to prevent these, or just remain original?

> (2) If KataGo is far AHEAD, and ... then ... **due to unknown reason.**

(emphasis mine)

Well, obviously, I'm not going to just say "I plan to do nothing, all of this is normal" when there is an **_unknown reason_** for one of the behaviors - I'm going to find out the reason. :)

I think I have an idea what's going on, and it's basically a bug due to threads. I have to test and find a way to try to fix it though.

**Comment by lightvector** [comment]
If you would like to test, I think #478 will fix this.

**Comment by sbbdms** [comment]
Thanks for your hard work, I will have a test at ~11 hours later.
I have done selecting parameters in https://github.com/lightvector/KataGo/pull/449. A very brief test shows it might be better than the UEC version. I am running games to test how much it is better than the original version (3 ideas disabled), so I can't run your fix right now.

**Comment by sbbdms** [comment]
Seems it is fixed by https://github.com/lightvector/KataGo/pull/478. Closing this issue.
Again, thanks very much!
