### ISSUE TITLE
Giving up on game which appears stuck, finding a new one

### ISSUE THREAD

**Issue by kotenok2000** [lightvector/KataGo#476]
what does "Giving up on game 6F4614DDD358B516 which appears stuck, finding a new one" mean?

**Comment by lightvector** [comment]
I don't know, are you on some weird version of KataGo or are you using some other script or program? The phrase "appears stuck" does not occur anywhere in all of KataGo's source code on any of version 1.8.0, 1.8.1, 1.8.2 as far as I can tell.

**Comment by kotenok2000** [comment]
I think i should have asked it in katrain issues.
