### ISSUE TITLE
why the time cost  of opencl version is less than cuda version

### ISSUE THREAD

**Issue by l1t1** [lightvector/KataGo#48]
D:\KataGo-1.1\katago12bc = 1.2beta cuda
D:\KataGo12b\katago =1.2beta opencl
```
# Black: KataGo
# BlackCommand: D:\KataGo-1.1\katago12bc gtp -model d:\model696.txt -config D:\KataGo12b\gtp_example.cfg
# BlackLabel: KataGo:1.2-beta
# BlackVersion: 1.2-beta
# Date: July 19, 2019 1:33:24 PM CST
# Host: PC
# Komi: 7.5
# Referee: -
# Size: 19
# White: KataGo
# WhiteCommand: D:\KataGo12b\katago gtp -model d:\model696.txt -config D:\KataGo12b\gtp_example.cfg
# WhiteLabel: KataGo:1.2-beta
# WhiteVersion: 1.2-beta
# Xml: 0
#
#GAME	RES_B	RES_W	RES_R	ALT	DUP	LEN	TIME_B	TIME_W	CPU_B	CPU_W	ERR	ERR_MSG
0	W+R	W+R	W+R	0	-	302	654	522	0	0	0	
1	B+R	B+R	B+R	0	-	247	523.1	438	0	0	0	
2	B+R	B+R	B+R	0	-	175	485.8	390	0	0	0	
3	B+R	B+R	B+R	0	-	281	689.5	557.9	0	0	0	
4	B+R	B+R	B+R	0	-	225	488.8	398.5	0	0	0	
5	B+R	B+R	B+R	0	-	253	586.4	514.7	0	0	0	
6	B+R	B+R	B+R	0	-	215	472.5	395.5	0	0	0	
7	W+R	W+R	W+R	0	-	208	431.5	374.8	0	0	0	
8	W+R	W+R	W+R	0	-	218	524.6	426.9	0	0	0	
9	W+R	W+R	W+R	0	-	156	305.7	258	0	0	0
```

**Comment by l1t1** [comment]
`D:\tool\go_gui\gogui-twogtp -white "D:\KataGo12b\katago gtp -model d:\model696.txt -config D:\KataGo12b\gtp_example.cfg" -black "D:\KataGo-1.1\katago12bc gtp -model d:\model696.txt -config D:\KataGo12b\gtp_example.cfg"  -games 20 -sgffile katagocl_cuda -auto -komi 7.5`

**Comment by lightvector** [comment]
How many searchThreads are you using for each?

**Comment by l1t1** [comment]
they shared one config, both 1000  searchThreads

**Comment by lightvector** [comment]
Ummm... that's a pretty absurd number of search threads. I would not expect good play using that many threads, nor do I have any idea how to think about how performance behaves with that many threads....

**Comment by l1t1** [comment]
my fault, it was 1 thread. max visits was 1000

**Comment by lightvector** [comment]
Well, 1 thread is probably too few. You can get much better performance on both increasing threads (the best number of threads for each one may be different)

It's possible that OpenCL will be faster than CUDA, or it's possible that CUDA will be faster than OpenCL, but 1 thread is too few to find out for sure.

**Comment by l1t1** [comment]
I am testing the 1.2 final version with searchThreads 3( my cpu has 4 threads)
`D:\tool\go_gui\gogui-twogtp -white "D:\KataGo-1.1\katago12_cuda gtp -model d:\model696.txt -config D:\gtp_example.cfg" -black "D:\KataGo-1.1\katago12_opencl gtp -model d:\model696.txt -config D:\gtp_example.cfg"  -games 20 -sgffile katago12_cuda_opencl -auto -komi 7.5`

**Comment by l1t1** [comment]
it seems no speedup when Threads >2, maybe it limited by my cpu?

**Comment by l1t1** [comment]
cuda version is faster with 20x256 model

**Comment by lightvector** [comment]
Going ahead and closing this due to lack of new activity, feel free to comment back if you think there's anything to add or reopen. I don't think its too surprising that OpenCL can be faster than CUDA. I might spend some time optimizing one or both a little more before next release. Thanks for posting your stats and results!
