### ISSUE TITLE
Can I ignore it?

### ISSUE THREAD

**Issue by jaewoo1120** [lightvector/KataGo#481]
These days, when I train katago with Google Collab, these things come out often.

*Error connecting to server, possibly an internet blip, or possibly the server is down or temporarily misconfigured, waiting about 5 seconds and trying again.

*Error was: No response from server

*Server returned 400 with 'already exist', data is probably uploaded already or has a key conflict, so skipping, response was: {"kg_game_uid":["Training game with this KG game uid already exists."]}

*uploadTrainingGameAndDataConnection to server is back!

Can I ignore it?
It doesn't matter to train katago, but it does come out quite often, so it bothers me.
This article can be awkward because it is written in a translator.

**Comment by OmnipotentEntity** [comment]
Yes.  It just means that the connection between you and the server was temporarily severed, but it has been restored.  It's something you can expect to happen from time to time, and there isn't much you can do to prevent it.  It's just how the internet works, (ie, it sometimes sorta doesn't).

**Comment by jaewoo1120** [comment]
Thank you for your answer! :)
