### ISSUE TITLE
Is it true: if you run 60 block model, you need a fast computer?

### ISSUE THREAD

**Issue by HackYardo** [lightvector/KataGo#489]
I download software at:
40: https://media.katagotraining.org/uploaded/networks/models/kata1/kata1-b40c256-s8303739392-d2019960373.bin.gz
60: https://media.katagotraining.org/uploaded/networks/models/kata1-extra/kata1-b60c320-s3075277568-d1985975170.bin.gz
release: https://github.com/lightvector/KataGo/releases/download/v1.8.2/katago-v1.8.2-opencl-windows-x64.zip
My laptop can run 40, but can not run 60. Is my laptop too slow? It shut down processes sometimes if it can't run them quickly.
The information:
```
PS E:\Program Files\Sabaki\kata1\60> ./katago.exe gtp -model m2.bin.gz -config c.cfg
KataGo v1.8.2
Using TrompTaylor rules initially, unless GTP/GUI overrides this
Creating context for OpenCL Platform: NVIDIA CUDA (NVIDIA Corporation) (OpenCL 1.2 CUDA 11.1.114)
Using OpenCL Device 1: GeForce MX110 (NVIDIA Corporation) OpenCL 1.2 CUDA (Extensions: cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid)
Loaded tuning parameters from: E:\Program Files\Sabaki\kata1\60/KataGoData/opencltuning/tune8_gpuGeForceMX110_x19_y19_c320_mv10.txt
Loaded config c.cfg
Loaded model m2.bin.gz
Model name: kata1-b60c320-s3075277568-d1985975170
GTP ready, beginning main protocol loop
genmove
? Expected one argument for genmove but got ''

genmove B
PS E:\Program Files\Sabaki\kata1\60>
```

**Comment by HackYardo** [comment]
As far as I know, MX110's cuda is true in name and false in fact🤣

**Comment by sbbdms** [comment]
Seems this 60b network could be run on my computer, with a 30 series GPU and CUDA backend.
BTW, how could users find the information of the latest 60b network? I check the official training site and could find any information...

**Comment by HackYardo** [comment]
**I can run now, by closing MX110 and using Intel gpu.**
 
@sbbdms 

As far as I know, 60 is not open to the public, and I get this 60 model from:  https://www.bilibili.com/video/BV1wU4y1b7sD

**Comment by HackYardo** [comment]
**I can run now, by closing MX110 and using Intel gpu.**
 
@sbbdms 

As far as I know, 60 is not open to the public, and I get this 60 model from:  bilibili.com 673147202
