### ISSUE TITLE
Compiling issue when VS 2019 is updated to 16.10.0

### ISSUE THREAD

**Issue by sbbdms** [lightvector/KataGo#490]
KataGo backend: CUDA
Compiler: Microsoft Visual Studio 2019

I have no problem when the previous version of comiler is 16.9.6.
Today my compiler is updated to 16.10.0. When I recompile KataGo it reports error.

Log:
[log.txt](https://github.com/lightvector/KataGo/files/6562658/log.txt)

Screenshots:
![Screenshot1](https://user-images.githubusercontent.com/19167292/120024541-f6ae3d80-c021-11eb-9758-bc2560ee80f8.png)
![Screenshot2](https://user-images.githubusercontent.com/19167292/120024546-f9109780-c021-11eb-9fd6-b95bc99d66cf.png)

**Comment by lightvector** [comment]
Given that other projects are also running into this (see the above issue that referenced this one), maybe this is a problem with Visual Studio that is independent of KataGo?

I don't know what else would be a problem, all the errors you report seem to be related to CUDA and VS having some compatibility issues.

**Comment by sbbdms** [comment]
Yes, it seems to be a compatibility issue, as I compile exactly the same code in both versions.

I am leaving this issue open to:

(1) Seek for a solution. I couldn't find a way to demote my VS 2019 version back to 16.9.6 with CMake usable. Changing C++ Standard setting of the project, from C++14 to C++17 (As the above issue that referenced this issue suggests), couldn't solve this problem either. Now I have to compile KataGo with OPENCL backend, where KataGo runs slightly slower than CUDA backend.

(2) Remind other users not to update their VS 2019 to 16.10.0, until there's a solution coming out. After that I will close this issue.

**Comment by mickeyandkaka** [comment]
I have the same issue and successfully get rid of it.
The only way now seems that there's

**Comment by sbbdms** [comment]
Thanks! Now I can compile it with CUDA backend with your solution.
Closing the issue. Anyone who meets this issue can refer to the solution mentioned above (The latest VS2019 version, 16.10.1, still has this issue).
