### ISSUE TITLE
Please call the Independent GPU by default in OpenCL version.

### ISSUE THREAD

**Issue by ivysrono** [lightvector/KataGo#50]
1.2 beta OpenCL use the Core GPU as GPU0 by default, it's confusing.

**Comment by lightvector** [comment]
Given that the platforms and devices could be given by OpenCL in arbitrary order, do you know a good heuristic to determine which one is the "Independent GPU"? How do other projects solve this problem?

**Comment by ivysrono** [comment]
I do not know C++.
It seems that core GPU always be GPU0, so could you set default that: use GPU1 if there are more than one GPUs, and use GPU0 if there is only one GPU.
In my opinion, this is not the best choise, but better than now.

**Comment by lightvector** [comment]
What happens for a user with a system where they are the other way around? I don't think the order is guaranteed. :)

Anyways, it looks like Leela Zero uses some heuristic scoring method: https://github.com/leela-zero/leela-zero/blob/3f297889563bcbec671982c655996ccff63fa253/src/OpenCL.cpp#L773

I implemented something similar for KataGo now: https://github.com/lightvector/KataGo/commit/26d990cda17b1a8f6906636ab70f5d2546deb4b0

Release v1.2-beta has been updated to v1.2 now including this change, so I think we're all good: https://github.com/lightvector/KataGo/releases

**Comment by lightvector** [comment]
And of course, feel free to reply back if this scoring method here is not working for you.
