### ISSUE TITLE
Does not run on Linux CL_PLATFORM_NOT_FOUND_KHR

### ISSUE THREAD

**Issue by vidfamn** [lightvector/KataGo#517]
Error running KataGo on Linux Mint 20.1 Cinnamon. The prebuilt KataGo in KaTrain app crashes with the same error.

Version: 1.9.1

Error:
```
2021-07-04 02:23:25+0200: Loading model and initializing benchmark...
2021-07-04 02:23:25+0200: nnRandSeed0 = 18290286760873974004
2021-07-04 02:23:25+0200: After dedups: nnModelFile0 = g170-b30c320x2-s4824661760-d1229536699.bin.gz useFP16 auto useNHWC auto
terminate called after throwing an instance of 'StringError'
  what():  OpenCL error at /home/sonny/repos/KataGo/cpp/neuralnet/openclhelpers.cpp, func err, line 263, error CL_PLATFORM_NOT_FOUND_KHR
[1]    211896 abort (core dumped)  ./katago benchmark -config configs/gtp_example.cfg -model
```

Steps to reproduce:
1. `cmake . -DUSE_BACKEND=OPENCL`
2. `make`
3. `./katago benchmark -config configs/gtp_example.cfg -model g170-b30c320x2-s4824661760-d1229536699.bin.gz`

**Comment by vidfamn** [comment]
I got it running, not quite sure what solved it but I removed my Cuda installation and installed the latest version from nvidias page. I don't have the knowledge to why this affects OpenCL or why I could build with OpenCL but not run it.

**Comment by lightvector** [comment]
Right, OpenCL in general is an interface to GPUs that must be provided by the software for your GPU. Whatever GPU you *actually* have (NVIDIA, AMD, Intel, etc) that vendor is responsible for providing OpenCL as well. So for example, NVIDIA implements the OpenCL interface using the same drivers and software it uses to implement CUDA, so changing one affects the other.

**Comment by lightvector** [comment]
Try updating your drivers and CUDA installation to the latest that your GPU supports? That error normally just indicates that OpenCL is not currently installed or available on your system - whatever nvidia drivers and libraries you have installed right now don't expose OpenCL as an available thing for other programs to use.

**Comment by tasuki** [comment]
Thank you, indeed that was the case! All the things related to GPUs are so confusing to me...
