### ISSUE TITLE
What is the "right" way of fine-tuning existing KataGo weights?

### ISSUE THREAD

**Issue by kmdanielduan** [lightvector/KataGo#526]
I'm trying to load existing model weights downloaded from [katagotraining](https://katagotraining.org/networks/) and do fine-tuning. What is the "right" way of loading the weights? 

My current way is relying on `train.py` to load the model weights by creating an `initial_weights_dir` in the `traindir`. Let's say I'm loading the raw TF weights 
 from `https://media.katagotraining.org/uploaded/networks/zips/kata1/kata1-b40c256-s9645747200-d2348848859.zip`. What I do is first unzip the file, then move the model weight from `kata1-b40c256-s9226359552-d2246551327/saved_model` to `os.path.join(traindir,"initial_weights")`.

When I load the model, it seems like the assignment_mapping doesn't match between the initial model built in `train.py` and the loaded model.

```
variables_to_restore = tf.compat.v1.global_variables()
assignment_mapping = {}
for v in variables_to_restore:
    name = v.name.split(":")[0] # drop the ":0" at the end of each var
    if name in varname_in_checkpoint:
        assignment_mapping[name] = v

tf.compat.v1.train.init_from_checkpoint(checkpoint_path, assignment_mapping)
initial_weights_already_loaded = True
```

Specifically, the loaded model tensor names have a prefix of `swa_model`, so it's `('swa_model/conv1/w', [5, 5, 22, 96])` for the first layer, while the newly initialized model has a tensor name without a prefix: `conv1/w:0`.

Of course, this problem can be dodged by changing the specification of the assignment_mapping, but I wonder if I find the correct way of loading existing model weights, or is there a better way of doing it?

**Comment by lightvector** [comment]
Sorry, yes, that's bit messy, in past cases where I've used that feature myself, it was before the swa (stochastic weight averaging) of models happened. 

Given that "swa_model" is common for KataGo's exported models, that code probably should just hardcodedly check for both possibilities. Something like this:
```
for v in variables_to_restore:
    name = v.name.split(":")[0] # drop the ":0" at the end of each var
    if name in varname_in_checkpoint:
        assignment_mapping[name] = v
    elif ("swa_model/"+name) in varname_in_checkpoint:
        assignment_mapping[("swa_model/"+name)] = v
```

If you try this, does it work for you?

**Comment by kmdanielduan** [comment]
Thanks! That works! Just created a pull request for this.

**Comment by lightvector** [comment]
Thanks for the PR, looks good to me. Let me know if I can help with anything else that you run into that needs to be fixed.
