### ISSUE TITLE
Is it feasible to encourage a larger scoreStdev in handicap games?

### ISSUE THREAD

**Issue by sbbdms** [lightvector/KataGo#529]
According to the games and experience concluded by some human players, a quite good tactic for weaker players to play against stronger players in handicap games, is playing moves which might "lost" points, but can "simplify" the situation.

Correspondingly, stronger players tend to play moves which can make situation messy and complicated. However, those moves may not "gain" points. If the weaker player follows correctly, those moves could cause an even more loss than other moves --- Obviously this is not what the stronger player expects.

So, my idea is: Could we encourage a larger scoreStdev in handicap games, as scoreStdev is an index which describes the total uncertainty (in points) of the game?

For example, if there are some moves in the selection lists, and they have similar scoreMean, then we may consider selecting the move which has a larger scoreStdev.

I would like to put into practice but I have two questions:
(1) Given a fixed situation, is scoreStdev the same for both Black and White sides? If not, how to get the scoreStdev respectively of two different players?
(2) Could it implement the idea above by simply changing getScoreUtility function like this:
![screenshot](https://user-images.githubusercontent.com/19167292/126257985-70371e7e-d835-4a60-a028-023a876174a5.png)

The idea above might be quite humble... I would like to know your opinion. Thanks!

**Comment by lightvector** [comment]
I have never tried it, but it sounds like a plausible thing to try. I would encourage you test out whatever you feel is appropriate, and see how it actually behaves in some test positions, compared to baseline, in several positions where you think there is a clear difference between two possible moves but KataGo chooses the "wrong" one for making it hard for the weaker player. 

You may find it difficult to get something working effectively, or you may find it easy - I have no idea, an idea like this needs experimentation and is hard to predict in advance. If you do find have something promising, then of course the next step is to test in real games. :)

For 1, scoreStdev is the same for both sides, yes. For 2, the place in the code you are looking is a reasonable place to put the code.

**Comment by sbbdms** [comment]
Thanks for your reply!

Actually... I have been trying this idea for a while. Currently I am using the function below, where 0.25 is used as a factor because it is slightly smaller than the default value of dynamicScoreUtility:
![screenshot](https://user-images.githubusercontent.com/19167292/126261278-3843a3c2-ae84-45a1-a4ac-d28a060b2830.png)

What I have observed is, after the modification, KataGo is very likely to play 3-3 in the middle game or even early game, which is not regarded as a good tactic in handicap games, and is supposed to make scoreStdev smaller because it gives opponent a strong influence outside:
![screenshot2](https://user-images.githubusercontent.com/19167292/126261584-3d1b5fb4-aa71-4097-81bf-471e2545a463.png)

This is the problem I didn't expect. I have to ban 3-3 when no other stones are around the handicap stone, via avoidMYTDaggerHack method.

Currently I still have no idea if it becomes better/worse in handicap games, because it is hard to find an index to measure.

When playing against some human players which are good at simplifing situation, KataGo still lets them to gain a solid territory quite early (May not in corner), without any complicated semeai which is supposed to make scoreStdev larger.

In general, I think it doesn't become much better in handicap games with the current modification.

I would like to make sure that my modification is correct, because I am not familar with the whole code in KataGo.
Are there any other parts which should be modified?

**Comment by sbbdms** [comment]
The previous function is not good to attach scoreStdev to dynamicScoreValue.
I am now changing to another function, which seems to be better for now, but always needs more games to test.

**Comment by sbbdms** [comment]
The modification above is totally a mistake... Closing this issue.
