### ISSUE TITLE
OpenCL problem with Windows on Intel integrated CPU

### ISSUE THREAD

**Issue by iopq** [lightvector/KataGo#54]
I first waited for the tuning to finish then whenever I launch it it spits out

```
KataGo v1.2
Using OpenCL Device 0: Intel(R) HD Graphics 5500 (Intel(R) Corporation) OpenCL 2
.0
Loaded tuning parameters from: ./KataGoData/opencltuning/tune_gpuIntelRHDGraphic
s5500_x19_y19_c96_mv5.txt
Uncaught exception: CL_BUILD_PROGRAM_FAILURE
BUILD LOG FOR xgemmDirectProgram ON DEVICE 0
fcl build 1 succeeded.
```

and then it quits

**Comment by lightvector** [comment]
@Naphthalin posted a very similar error to yours with Intel HD Graphics 4600, where it tuned successfully, then failed to build when actually using the parameters (despite building successfully when tuning). "fcl build 1 succeeded" is supposed to be the error message when building, which strangely sounds like a success!

I think the answer might be that Intel HD Graphics OpenCL is simply buggy. At least, I'm not sure there's much I can do here. See https://github.com/CNugteren/CLBlast/issues/280

**Comment by l1t1** [comment]
try 32bit version, my 4400 works on it

**Comment by iopq** [comment]
32bit didn't work, LeelaZero works fine for some reason

**Comment by iopq** [comment]
I did the tuning again to see what happened

```
Tuning xGemmDirect for convolutions
Testing 56 different configs
WARNING: Reference implementation failed: CL_BUILD_PROGRAM_FAILURE
Tuning 20/56 ...
Tuning 40/56 ...
ERROR: Could not find any configuration that worked
Done tuning
------------------------------------------------------
Uncaught exception: CL_BUILD_PROGRAM_FAILURE
BUILD LOG FOR xgemmDirectProgram ON DEVICE 0
fcl build 1 succeeded.
```

**Comment by portkata** [comment]
Does the current 1.3.2 engine work with intel graphics for anyone? if so, which intel graphics generation do you have?

**Comment by lightvector** [comment]
Seems basically the same as https://github.com/lightvector/KataGo/issues/78, and also a pretty old issue so closing this issue and just leaving the other one open for user visiblity.
