### ISSUE TITLE
suggest to improve the speed of katago

### ISSUE THREAD

**Issue by l1t1** [lightvector/KataGo#56]
as test in https://github.com/leela-zero/leela-zero/issues/2452 and https://github.com/lightvector/KataGo/issues/48 , the speed of katago i about 33% of that of leelaz, so it's weaker in time parity match.

**Comment by lightvector** [comment]
As mentioned in one of the linked threads, will work on it as I get more time.

**Comment by l1t1** [comment]
thanks
