### ISSUE TITLE
Suggestion to make readme more consistent for older branches. 

### ISSUE THREAD

**Issue by kiatchun** [lightvector/KataGo#571]
Some of the older/stale branches do not state TensorRT or Eigen as one of the options, and the "se" branch in particular still states that 20b networks are still the latest. I think it is a good idea to update the readme.md in these branches for consistency.

**Comment by lightvector** [comment]
I don't see why anyone would be looking at those branches rather than the main site, but maybe I should just close them. I'm not going to update all branches any time anything changes.
