### ISSUE TITLE
About 3 Ko 

### ISSUE THREAD

**Issue by hope366** [lightvector/KataGo#575]
Please tell me how KataGo handles 3 Ko. 

>In the game between KataGo of lizziyzy, 3 Kos occurred and it was a draw. I've never seen a draw in GoGuiTool. 

There is a report. Does KataGo have different processing methods such as 3 Ko depending on the GUI used?

**Comment by michito744** [comment]
I think lizziyzy is not using kata-analyze.

**Comment by lightvector** [comment]
See https://lightvector.github.io/KataGo/rules.html - the ko rule in KataGo is configurable. If you have a question about how a specific GUI chooses to configure it, that is a question that should be posted in the github/forum/discord/etc. for that GUI.

**Comment by hope366** [comment]
Thank you for your comment.
Contact the GUI developer to understand the problem.
