### ISSUE TITLE
Difference between "kata-analyze prior" and "kata-raw-nn policy" 

### ISSUE THREAD

**Issue by hope366** [lightvector/KataGo#578]
windows10
katago-1.10.0-opencl
kata1-s1038 
Rule: Japanese rule komi 6.5
Items related to analysis of default_gtp.cfg are left as default values 

I launched KataGo from the command line and ran `kata-analyze 100` on an empty board. A lot of data was output, but it stopped immediately. If you look at the top, you can see the following information. This is information about the point of "Q16". 
`info move Q16 visits 27 utility -0.0423148 winrate 0.479952 scoreMean -0.232691 scoreStdev 16.5836 scoreLead -0.232691 scoreSelfplay -0.271399 prior 0.0703739 lcb 0.47516 utilityLcb -0.0557313 order 0 pv Q16 D4 Q4 D16 F17`

Then I ran `kata-raw-nn 0`. The following is output. Is "Q16" the 16th from the left and the 4th from the top (the star in the upper right corner)? If so, "0.067926" is displayed in the place of "Q16". Similar to "prior 0.0703739" above. Are these two parameters with similar meanings? What are the specific differences that are subtly different? 
Also, there are 8 types of `kata-raw-nn ##` from 0 to 7 (or all), and I think that symmetry is related. What is the difference between them? 
I'm sorry if the question is duplicated with the one already mentioned. Thank you. 
![raw-0](https://user-images.githubusercontent.com/63999713/142348901-84087870-49aa-4c42-88a6-da7a088d6d95.png)

**Comment by lightvector** [comment]
The neural net evaluates every board position with a random symmetry (or a mix of symmetries at the root, or a fixed symmetry, depending on how your config is set).  You can sort of think of each symmetry like a neural net that was independently trained on the same millions of games but that used a different random sampling of what moves it learned from those games. So they may return different answers.

**Comment by hope366** [comment]
Thank you for your prompt response. It can be a little difficult to understand your statement accurately because I don't have much expertise. 
I understand these two as "the evaluation that KataGo intuitively felt in any aspect", but do they generally match?
Also, do you mean that even if these two are in the same situation, they will be slightly different at the timing of execution?

**Comment by lightvector** [comment]
There are 8 possible orientations of the board (reflections and rotations). The neural net learns the value of every orientation independently (sort of like 8 different neural nets), and when we evaluate a board, we randomly choose one of the 8 to produce the evaluation, as a way of averaging them all together. So every time you evaluate the board via the neural net, you can get 8 different answers.

**Comment by hope366** [comment]
Thank you. I learned a lot.
