### ISSUE TITLE
(Question) Does the standard deviation of utility keeps unchanged after utilityAvg is changed by adding bonus from pattern?

### ISSUE THREAD

**Issue by sbbdms** [lightvector/KataGo#581]
https://github.com/lightvector/KataGo/blob/9c79faaf299a37af38982181fdfec2a642d50d9b/cpp/search/search.cpp#L3115
https://github.com/lightvector/KataGo/blob/9c79faaf299a37af38982181fdfec2a642d50d9b/cpp/search/search.cpp#L3116
https://github.com/lightvector/KataGo/blob/9c79faaf299a37af38982181fdfec2a642d50d9b/cpp/search/search.cpp#L3117

I am a bit confused by the formula in the 3rd line of code above.
It seems that it is concluded by asserting that the standard deviation of utility keeps unchanged after utilityAvg is changed.

Assuming there're three utility values u[0], u[1] and u[2], utilityAvg = a1 = (u[0] + u[1] + u[2]) / 3.
Assuming utilityAvg2 = a2 = utilityAvg + getPatternBonus(node.patternBonusHash,getOpp(node.nextPla)).
So the proportion of two utilities is a2 / a1.

My question is, after adding bonus from pattern, can we regard the three utility values, u[0], u[1] and u[2], are changed by multiplying the same proportion (a2 / a1)?
That means, after adding bonus from pattern, their values are changed to u[0] * a2 / a1, u[1] * a2 / a1, and u[2] * a2 / a1.
If so, then the utilityStdev should not be unchanged, it should be multiplied by the proportion (a2 / a1) too, and the code of the 3rd line should be: _utilitySqAvg = utilitySqAvg * utilityAvg * utilityAvg / oldUtilityAvg / oldUtilityAvg;_

Please point out if there're mistakes in the thought, since I am not quite familar to the internal logic of the search...

**Comment by lightvector** [comment]
The intention is to change them by adding the same amount to each, not by multiplying them by the same proportion.

**Comment by sbbdms** [comment]
I see... Thanks for your answer!
