### ISSUE TITLE
Could I use part of KaraGo/docs/rules.html to interpret Go game rules to users?

### ISSUE THREAD

**Issue by HackYardo** [lightvector/KataGo#589]
I'm sorry, I'm not major in computer science or law, so I don't understand licenses of software even after reading them. I just open a Go app project, and the KataGo rules page is clear to explain Go game rules.

**Comment by lightvector** [comment]
Informally speaking, the MIT license lets you do most things you could want to do so long as you provide the original copyright notice and license along with any copies you distribute, making it clear who the authors of the material are, or if you modify it, who the original authors were before your modifications.

Not all of the stuff in this repo is under the same license, so check https://github.com/lightvector/KataGo/blob/master/LICENSE for details. If you have difficulty understanding, please try finding someone who is more knowledgeable about software licenses who can help explain to you.

**Comment by lightvector** [comment]
Also, I recommend you be a little bit careful if you want to use the KataGo rules page for beginners to understanding things like Japanese rules. They are written so as to try to be mathematically rigorous, but the way they implement things (in particular the cleanup phases) is only one particular choice of approximation and is not universal, and the extra rigorous language might also be confusing to some people.. KataGo tries to provide enough rules options to be able to very closely replicate most rulesets of interest, but doesn't claim that it replaces them exactly.

**Comment by merlinpan** [comment]
In general, the computer rules (TT) is too rigorous to be used in real life, and japanese rules have so many exceptions/eccentricities (seki, leaving ko at the end, etc.) so make it very hard to deal with.

In general, chinese-like rules are the easiest to deal with. The AGA ruleset https://www.usgo.org/aga-concise-rules-go is chinese-equivalent (but provided japanese-like territory counting) would be where I would start with for a beginner.

Also note that even though most rule sets state "previous board are not to be repeated", most human games only forbid a repetition cycle of 2 (simple kos), and treat any multi-ko-based repetitions are draw.

**Comment by HackYardo** [comment]
Thank you very much! I add a [ThirdParty.md](https://github.com/HackYardo/VastGo/blob/master/THIRDPARTY.md) besides [License.md](https://github.com/HackYardo/VastGo/blob/master/LICENSE.md) to list the links of dependencies and their licenses. Does it make sense?

**Comment by lightvector** [comment]
Okay with me. I personally have no complaints your approach of having your license cover the code that is yours and providing a link in the end for info about third party dependencies, including KataGo or other software you're building on top of. As far as I'm concerned it's fine, as long as you're honest about what is your work versus what work is from others that you are building on top of.

Right now, briefly at a glance it seems you're not directly modifying or redistributing KataGo or most of your dependencies, but instead just providing scripts that use them, and all the code that is within of your repo is yours alone. If you ever took the step of including and/or modifying parts of KataGo directly to be part of your repo it would be nice if you make sure that your license or documentation also distinguishes which specific files or parts were directly copied and modified, but at the moment if all the code in your repo is your own, as far as I'm concerned it seems perfectly good as-is.

Seems like you have an ambitious and interesting project, thanks for sharing.

**Comment by HackYardo** [comment]
Thank you for explaining such a basic point to me. I will clarify which files or parts and devide them into copied, modified, redistributed, in the repo's developing.
