### ISSUE TITLE
Cheap visits should be a ratio rather than a pre-set number

### ISSUE THREAD

**Issue by iopq** [lightvector/KataGo#60]
I just had visits set at 60 and cheap visits at 100 for the last week. :joy:

**Comment by iopq** [comment]
So furthermore, visits should be a ratio of board sizes. 19x19 requires something like 5x more visits to actually learn anything than 9x9. So when you add the smaller boards into the training, they should be at lower visits

**Comment by lightvector** [comment]
I added a guard in the latest release where it should error out at some point if it notices cheap visits less than normal visits -thanks.
I think I'm not going to implement the the ratio of board sizes for now - although it shouldn't be *too* hard to hack the code yourself if you want to do that in a custom version. Feel free to leave this issue open, or close it if you're satisfied, or whatever.

**Comment by iopq** [comment]
Good enough for me. I was just thinking smaller boards could be stronger at a higher amount of games/lower visits. But that's only tangentially related, so I'm closing this issue
