### ISSUE TITLE
pvVisits in graphsearch

### ISSUE THREAD

**Issue by kaorahi** [lightvector/KataGo#605]
I have used pvVisits in kata-analyze for guessing whether the principal variation is an inevitable straight road in KataGo's thought. Let v(1), v(2), ... be pvVisits for the moves m(1), m(2), ... in pv. If v(n) / v(n-1) is small, I regard m(n) as just an example of several considerable candidates.

In the following screenshot, v(n) / v(n-1) is displayed as the font size of the move number. So I can notice that the move 3 is very unsure. (v(n) / v(1) is also indicated as the height of the number n on the right edge of the board. I watch their motions for observing the convergence of the analysis.)

![pvvisits](https://user-images.githubusercontent.com/38910552/155969590-4544444a-06e8-4b8a-b4fa-c8131ef0a28b.png)

In graphsearch, pvVisits seems unsuitable for the above purpose as v(n) can be greater than v(n-1). I would appreciate it if KataGo provides the visits of the edges (node1, node2), (node2, node3), ... in addition to the visits of node1, node2, ...

**Comment by lightvector** [comment]
Okay, I will add this.

**Comment by kaorahi** [comment]
Thanks for f0a3e294!

**Comment by lightvector** [comment]
No problem!

Note: pushed a followup in 0d30fab9 to master making it so that for GTP, you need to request pvEdgeVisits true separately, so as to avoid surprising any clients that aren't expecting another field there for the next release.
