### ISSUE TITLE
Could kata-analyze output ownership for each candidates

### ISSUE THREAD

**Issue by yzyray** [lightvector/KataGo#608]
I have seen such a cool video, showing different ownership by mouse hover.
https://discord.com/channels/417022162348802048/629446365688365067/948682158283821117
I think this is based on analysis engine,and use includeMovesOwnership tag in analysis engine's queries.
I want to add this feature in my own GUI,but my GUI is based on GTP engine,could `kata-analyze` also output ownership for each candidates? Thanks in advance.

**Comment by HackYardo** [comment]
Hi, @yzyray :
I think it is very cool too, but it maybe done by a gui, just put each **candidates** into several **positions**, then send those positions to KataGo for multiple **ownership matrices**.
BTW, I can't link to `disord`, I wonder what gui and which engine are used in the cool video, do you know their names? Who make the video?

**Comment by yzyray** [comment]
The movie is from https://github.com/rooklift/ogatak

https://user-images.githubusercontent.com/49384584/157219262-5d7712d7-c9aa-47d2-808c-048d85406590.mov

**Comment by HackYardo** [comment]
Ohh, thank you very much, I knew this project last year. It use KataGo Parallel Analysis Protocol instead of GTP, it KataGo's GTP support it, it will be very nice!
