### ISSUE TITLE
would you mind to develop a command that can pause contribution?

### ISSUE THREAD

**Issue by 1067511899** [lightvector/KataGo#613]
The 60 block is 50% slower  than 40 block,so the contribute will cost hours to finish.
I read the issue before that you will not develop a function to save contribute games so that can continue contribution from saved games,so,would you mind to develop a command that can pause contribution and release the usage of video card or CPU，so that we can do some work that needs  video card or CPU,and after the work,we can continue the contribution?
for sometimes we really need full function of the computer,and shutdown half finished contribution is really a kind of waste.

apologize for my poor English.

Thank you.

**Comment by lightvector** [comment]
Thanks for the reminder, some other users have asked for this before too. I am happy to work on this for the upcoming release within a couple weeks.

It should be relatively easy to entirely halt the computational usage of the CPU and GPU, as well as some of the RAM. It will be much more difficult to release GPU memory - how much do you care about GPU memory?

**Comment by 1067511899** [comment]
Well,I really not care much about the GPU memory,because when I'm training with 12 threads,It only used 1.7~1.8G GPU memory,and my video card has 6G memory.so,just halt the CPU and GPU is enough.

Thank you.

![image](https://user-images.githubusercontent.com/21253207/157698163-4bb1a15c-5a8c-4d4d-ac34-372f2fc1b3ce.png)

**Comment by 1067511899** [comment]
new version,pause contribution function works fine.thank you.
