### ISSUE TITLE
Question: Analyse mode only giving the best variaton

### ISSUE THREAD

**Issue by SukramD** [lightvector/KataGo#624]
Hi everyone,

First, sorry if I missed the answer to the question somewhere in the documentation.

I would like the Parallel Analysis Engine to write only the best variation of a position into the response without affecting the search itself. Is that possible?

**Comment by lightvector** [comment]
Just feed the input into a json parser and then just ignore everything other than the fields with the info you want? It sounds like you probably only care about the move with order 0.

**Comment by SukramD** [comment]
Yes that would be my second option. I just thought that it would be more effective if it is possible to configure that directly in the engine.
Thanks for the answer!
