### ISSUE TITLE
Test the model under ELF framework

### ISSUE THREAD

**Issue by zwcolin** [lightvector/KataGo#625]
We would like to take your model as a baseline to test our Go AI, and our model is developed based on ELF's framework. I saw that in the documentation you had competitions between KataGo and ELF Go. We are wondering if you have a pipeline that can easily run your network as an AI agent player in ELF with pytorch? Thank you!

**Comment by lightvector** [comment]
The universal protocol that all Go bots speak for competitions and tournaments is GTP: https://www.lysator.liu.se/~gunnar/gtp/

Almost every major Go bot in the last couple of decades that isn't deliberately limited and restricted to its own built-in app or graphical interface (e.g. for commercial reasons) implements GTP, whether it's KataGo, Leela Zero, or even much older bots like Pachi or GnuGo. 
Almost every computer Go tournament, or computer Go league such as CGOS (http://www.yss-aya.com/cgos/) uses client software that expects your program to speak GTP. 
If you implement GTP, you also get the ability to run your bot on Go servers like KGS or OGS so you can test it in games against human players in real time.
Also if you implement GTP, you can connect your bot to lot of nice user interfaces like q5go (https://github.com/bernds/q5Go) or Sabaki (https://sabaki.yichuanshen.de/).

So you should just implement GTP. 

Some examples of match software for running a pair of GTP agents against one another would be a library called ringmaster that is part of a python2 library gomillhttps://mjw.woodcraft.me.uk/gomill/doc/0.8/ringmaster.html, also gogui-twogtp in https://github.com/Remi-Coulom/gogui can do it. Applications like q5go can also do it, although they probably aren't so suited for running a large number of games - more that if you like you can connect two bots and watch graphically as they play one game against each other.

**Comment by lightvector** [comment]
And of course, as an addendum, to run KataGo as a gtp agent, the command line would look something like `./katago gtp -config <CONFIG>.cfg -model <NEURAL MODEL FILE>.bin.gz`.

**Comment by zwcolin** [comment]
That sounds perfect - thank you for the clarification!
