### ISSUE TITLE
How to play with katago in text interface?

### ISSUE THREAD

**Issue by NelloHo** [lightvector/KataGo#626]
Hello everyone:
I used to play Go before I'm visually impaired, and I really want to enjoy the game again. 
Is there a pure text interface to play with katago? I ask so because the  screen reader can only read text, so normal GUI will not work in my case.

**Comment by ParmuzinAlexander** [comment]
You can run KataGo in the terminal
`katago.exe gtp`
and use commands
```
play b q16
play w q16
genmove b
genmove w
showboard
undo
```

**Comment by NelloHo** [comment]
thank you !

**Comment by HackYardo** [comment]
@NelloHo  You can use a Go GUI named [Sabaki](https://github.com/SabakiHQ/Sabaki) to learn `GoTextProtocol`, so that you have a GUI besides a TUI/TI.
And if your question has been solved, you need to **CLOSE** the issue.
