### ISSUE TITLE
Automatic SGF review

### ISSUE THREAD

**Issue by lukaszlew** [lightvector/KataGo#64]
I'd like to implement a following logic:
- read SGF file
- analyze every position in SGF tree and expand SGF tree with principal variation at a subset of nodes
- add some comments 
- save SGF

This best would be done through GTP, but I'm not eager to parse the output of *-analyze commands. Would it be possible to use JSON there?

**Comment by lightvector** [comment]
Are you asking for KataGo to do the SGF reading and comments and saving part, or are you doing all of that yourself and are happy providing the moves via GTP and it's just that you want a better analysis output format?

If you just want a better format (and possibly a slightly better interface for providing a game or a set of positions to analyze all together) but not the SGF commenting and saving part, then your request is very similar to something someone else has also wanted and that I'm currently sketching out how best to do. :)

**Comment by lukaszlew** [comment]
I did once all-through-gtp in the past. But then I got bitten many times by a changing output format. 
I'm only asking Kata for a dump of it's internal state in JSON through GTP.
Maybe the JSON fields could be standardized in the future across engines.

**Comment by bvandenbon** [comment]
Lucaszlew if you have a clear idea of what it should look like, I am willing to develop it for ZBaduk (which interfaces with KataGo). The question is "how configurable" should it be?

I would be tempted to say, that you only want these branches for the worst x moves of the game.
or when there is an alternative for a move that has an advantage of at least x percentage.

Does that sound reasonable ?

**Comment by lukaszlew** [comment]
This request is more about getting the data from KataGo into an sgf (say overnight analysis).
Displaying it is a different matter.

My favorite way to review games of good players is to use [Go Dojo](https://play.google.com/store/apps/details?id=pl.happydroid.goess&hl=en_US).
There you have to guess moves so if you want to get a good score you have to focus and analyze.

It would be great if we could use arbitrary game but guess and get scored for what KataGo is suggesting.

**Comment by lightvector** [comment]
Just browsing over old issues.
In case this is useful, as of recent releases, there is a JSON analysis engine with a protocol documented here:
https://github.com/lightvector/KataGo/blob/master/docs/Analysis_Engine.md

Enjoy!

Closing this issue as it is very old and possibly handled by this JSON engine now existing, if there are more questions please reply back or open a new issue, happy to answer further.
