### ISSUE TITLE
Is it possible to intentionally change the length of the change diagram?

### ISSUE THREAD

**Issue by hope366** [lightvector/KataGo#654]
I usually use Lizzieyzy for analysis on KataGo.
Let KataGo analyze and the candidate moves will be displayed. At this time, if you hover the mouse cursor over the candidate hand, the change diagram that KataGo envisions will be displayed.
The length of the change diagram is 10 or less when it is short, and 30 or more when it is long.

When I showed an acquaintance who did not use Go AI at all the game record analyzed by KataGo,we received the opinion that the length of the change diagram is too short to be helpful.
I tried increasing the amount of analysis a little to increase the depth of the change diagram, but it seems that there is not much change.

Is it possible to intentionally increase the length of the change diagram by tweaking some settings? Or is the length of the change diagram dependent on the placement of the stones, and is it impossible to intentionally lengthen it with the settings and the amount of analysis?

**Comment by hope366** [comment]
Thank you for your prompt and courteous guidance.
I've been using Go AI since the Leela Zero project started, so I'm sure I understand to some extent that the deeper parts of the change diagram will be fairly unreliable. I explained that to my acquaintances and told them that if they wanted to get even better analysis results, they should build a Go AI on their personal computer. However, unfortunately things haven't seemed to move forward because I'm so scared of the warnings from antivirus software.
I can't guarantee them that the warnings from antivirus software are completely misleading, so I can't do anything so far.
I think they're probably afraid of Java or KataGo.
If you have useful advice to relieve their fears, I would be grateful for whatever it is.

**Comment by hope366** [comment]
`analysisPVLen = 50` I usually use KataGo with this setting.
Even with this setting, in certain situations, there are quite a few times when the length of the change diagram is around 5 even after performing thousands of searches.
In other words, this number "5" does not mean that it was intentionally shortened due to the influence of the above settings, right?

**Comment by hope366** [comment]
Thank you for the detailed guidance.
Anyway, the important thing is that variation is just one indicator, and if you want to get the best movement at the moment, move to that position and then search for it.

**Comment by michito744** [comment]
It is not uncommon for it to take several minutes to get the same result with KataGo compared to FineArt's 10-move  diagram.

KataGo's 50-move diagram requires more than 500k to 1M searches under the proper settings to be usable. The 50-move diagram displayed after a few seconds of searching is garbage.

**Comment by hope366** [comment]
>It is not uncommon for it to take several minutes to get the same result with KataGo compared to FineArt's 10-move diagram.

The reason for this could be the difference in algorithms and the amount of computational resources, but which one is expected to have the greater impact?
>KataGo's 50-move diagram requires more than 500k to 1M searches under the proper settings to be usable. The 50-move diagram displayed after a few seconds of searching is garbage.

Searching 100,000 times per move is likely to take a considerable amount of time, depending on the performance of the GPU.
Assuming that 100,000 searches yield a change diagram that includes 50 moves, how much is the "number of searches for each move" required to obtain the same level of reliability as each move? Is expected?
If the latter can find better moves with fewer searches, then you don't have to do a lot of searches in one part, right?

**Comment by michito744** [comment]
> The reason for this could be the difference in algorithms and the amount of computational resources, but which one is expected to have the greater impact?
 
I think the accuracy of the NN is the biggest factor.
Even if there were 10 times more computing power, there is a level of difference that cannot be explained.

> Searching 100,000 times per move is likely to take a considerable amount of time, depending on the performance of the GPU. Assuming that 100,000 searches yield a change diagram that includes 50 moves, how much is the "number of searches for each move" required to obtain the same level of reliability as each move? Is expected? If the latter can find better moves with fewer searches, then you don't have to do a lot of searches in one part, right?

It is not possible to search about 100,000 times. It is an order of magnitude short.

Under KataGo's NN, it is not uncommon for the weighting of obvious best moves to be less than 5% (or in the worst case, less than 1%).
In such cases, it is impossible to even discover the best procedure in the first place without mixing in noise and increasing the number of searches considerably, so most of the computation time is wasted.

Therefore, I don't think there is a clear guideline.

**Comment by hope366** [comment]
Well, in other words, in order to find the best movement after the second move, it is currently best to move to that position and then search.

**Comment by michito744** [comment]
> Well, in other words, in order to find the best movement after the second move, it is currently best to move to that position and then search.

If there is a choke point that is very difficult to find after 10 moves, moving forward one move to search for it will only make it very difficult after 9 moves and will not solve anything fundamentally.
