### ISSUE TITLE
Does any powerful tool to download the SGF file from KataGo server?

### ISSUE THREAD

**Issue by CGLemon** [lightvector/KataGo#658]
I want a tool that can download the specific SGF file, like game type, board size, score rule.... Does anyone recommend one.

**Comment by lightvector** [comment]
It does not exist, and please do not write or share code online to automatedly scrape it. Could you take down your script? That part of the webserver is not designed to handle the load if people try to do this.

The answer would be for the server itself to provide a zip-compressed daily SGF download from the server itself, where there is a job that runs daily and compresses the previous day's SGF files, and then exposes a webpage listing each day's data for bulk downloading those files: https://github.com/katago/katago-server. Nobody has yet written the code to do that however. If you have web dev experience or you know someone who does who would like to contribute to that repo and implement something like that, it would be welcome.
