### ISSUE TITLE
Estimated score wrong in handicap 5 game. Does score include handicap?

### ISSUE THREAD

**Issue by petgo3** [lightvector/KataGo#66]
In this game (http://kgs.gosquares.net/index.rhtml.en?id=petgo&id2=Minitaxi&r=0) black lost by 6.5 points. Interesting is a passing by black at move 261 (instead of taking last neutral field, chinese counting).
But in the gtp.log you can see this:

1) Move 260:
koPOSITIONALscoreAREAsui1komi0.5
Time taken: 19.625
Root visits: 48186
NN rows: 15456
NN batches: 3882
NN avg batch size: 3.98145
PV: F17 Q6 H18 H19 F16 B10 S17 G18 R18
Tree:
: T **-98.30c W -98.15c S  -0.15c ( -0.8)** N   48186  --  F17 Q6 H18 H19 F16 B10 S17
---White(^)---
F17 : T -98.30c W -98.17c S  -0.14c ( -0.8) LCB  -98.48c P 92.14% WF 33.15% PSV   46959 N   46959  --  F17 Q6 H18 H19 F16 B10 S17 G18
F8  : T -97.90c W -97.38c S  -0.52c ( -1.0) LCB -100.16c P  2.44% WF 33.83% PSV     944 N     944  --  F8 F9 F17 Q6 F16 E8 T8 P1
A11 : T -98.43c W -97.44c S  -0.99c ( -1.4) LCB -101.41c P  1.25% WF 33.02% PSV     282 N     282  --  A11 A14 F17 Q6 F16 B10 R15 A10

2019-08-11 20:13:21+0200: = F17

2) Move 262:
koPOSITIONALscoreAREAsui1komi0.5
Time taken: 1.985
Root visits: 2097
NN rows: 1564
NN batches: 393
NN avg batch size: 3.97964
PV: Q6 F16 F8 S17 F17 S18 R19 F16 G7 Q19 T17 G8 F17 G7 F16
Tree:
: T  **92.88c W  91.34c S   1.54c ( +2.0)** N    2097  --  Q6 F16 F8 S17 F17 S18 R19
---White(^)---
Q6  : T  93.62c W  92.05c S   1.57c ( +2.0) LCB   90.55c P  3.10% WF 51.95% PSV    2050 N    2050  --  Q6 F16 F8 S17 F17 S18 R19 F16
pss : T -118.82c W -100.00c S -18.82c (-11.5) LCB -118.82c P 93.41% WF  0.49% PSV      22 N      22  --  pass
F8  : T -61.91c W -59.54c S  -2.37c ( -0.4) LCB -713.60c P  0.03% WF  2.90% PSV       5 N       5  --  F8 G7 Q6 F16
A11 : T -70.78c W -67.87c S  -2.90c ( -0.8) LCB -367.73c P  0.02% WF  2.54% PSV       5 N       5  --  A11 A14 Q6 F16 F8
R19 : T -71.03c W -69.03c S  -2.01c ( -0.2) LCB -3985.95c P  0.01% WF  3.39% PSV       3 N       3  --  R19 F16
S17 : T -94.83c W -92.28c S  -2.56c ( -0.5) LCB -320.00c P  0.02% WF  3.12% PSV       2 N       2  --  S17 Q6
S19 : T -92.93c W -90.41c S  -2.52c ( -0.5) LCB -320.00c P  0.01% WF  3.20% PSV       2 N       2  --  S19 Q6
F16 : T -101.32c W -98.20c S  -3.13c ( -0.9) LCB -320.00c P  2.95% WF  4.24% PSV       1 N       1  --  F16
S18 : T -89.61c W -87.27c S  -2.34c ( -0.4) LCB -320.00c P  0.04% WF  4.84% PSV       1 N       1  --  S18
G18 : T -93.60c W -90.29c S  -3.31c ( -1.0) LCB -320.00c P  0.03% WF  4.62% PSV       1 N       1  --  G18

Actually the game was won by 6.5 points for w, but kata realized this at move 262 (after the passing "mistake"). Kata should have been sure of the result a lot earlier, since the one point at move 261 shouldn't matter for the winning (only for the points).

Or did it get something wrong?

**Comment by lightvector** [comment]
See `whiteBonusPerHandicapStone` parameter in the gtp config.

If the server you are running on has such a score adjustment and does not already provide this adjustment in the "komi" input to GTP, then you need to provide this argument in the config.

**Comment by lightvector** [comment]
Also, side note: **If you are going to try to run KataGo in matches or on a server, in general, I'd recommend reading through the gtp config carefully!**

There are a lot of parameters in there, but the relevant ones are commented and explained, and they might well be relevant to you, such as the above parameter!

If you have not already, you probably should also determine carefully whether the server you are running on uses positional or situational superko, or allows suicide, and configure those aspects of the rules correctly as well. (If the server doesn't use superko at all, then unfortunately there isn't quite support yet with the latest neural net, but future training runs should have nets that support that too).

**Comment by lightvector** [comment]
Followup: according to https://www.britgo.org/rules/compare.html among the various rulesets that do add handicap points as a separate factor from Komi, they aren't even consistent about whether it's N points or N-1. Yuck. I'd imagine it's also inconsistent between servers. I wonder if there are also servers that do have this adjustment but differ in whether they pre-adjust the reported komi or not in GTP.

Makes me sad as a programmer - ideally the GTP komi should have from the start always literally meant "points to add in addition to the regular on-the-board score". I guess I'll add support for an N vs N-1 adjustment too in the next release. If you need an "N-1" adjustment rather than an "N" adjustment you'll be off by one point - feel free to hack the code to do this yourself for the moment, or add a wrapper around GTP to adjust the komi properly.

Otherwise, let me know if this takes care of the issue, thanks!

**Comment by petgo3** [comment]
Thx a lot, so I did it get something wrong.
I just use the config now properly ...
