### ISSUE TITLE
Strange output from a game

### ISSUE THREAD

**Issue by sbbdms** [lightvector/KataGo#663]
SGF:

> (;GM[1]FF[4]  SZ[19]  GN[]  DT[2022-07-23]  PB[忘与冉]  PW[小狼の让子]  BR[4段]  WR[9段]  KM[0]HA[8]RU[Chinese]AP[GNU Go:3.8]RE[B+17.00]TM[60]TC[10]TT[40]AP[foxwq]RL[0]  AB[pd][dp][dd][pp][dj][pj][jd][jp];W[cq];B[dq];W[cp];B[do];W[bn];B[cm];W[nq];B[qn];W[qc];B[qd];W[pc];B[od];W[nb];B[mc];W[oj];B[pi];W[ol];B[lq];W[fc];B[cf];W[pk];B[np];W[qq];B[oq];W[jo];B[ip];W[df];B[ce];W[cn];B[dn];W[kp];B[kq];W[oi];B[ph];W[mp];B[mq];W[db];B[nk];W[ok];B[hc];W[di];B[ci];W[oh];B[pg];W[ch];B[dh];W[ei];B[cj];W[rd];B[re];W[cg];B[ec];W[eb];B[fd];W[ej];B[fb];W[gf];B[dl];W[cc];B[io];W[ro];B[qo];W[rn];B[rm];W[qm];B[rp];W[rl];B[qp];W[sp];B[sq];W[cr];B[dr];W[ds];B[es];W[cs];B[fr];W[no];B[nr];W[fs];B[gs];W[rc];B[mb];W[rf];B[qe];W[nc];B[nd];W[md];B[kc];W[ld];B[oc];W[ob];B[na];W[pa];B[rg];W[bb];B[jf];W[jg];B[kg];W[hl];B[im];W[if];B[jh];W[ig];B[kf];W[fl];B[mm];W[mg];B[mf];W[nf];B[me];W[kh];B[so];W[id];B[ic];W[il];B[jm];W[jl];B[kl];W[kk];B[ll];W[nm];B[on];W[nn];B[lk];W[lg];B[je];W[kj];B[lh];W[ki];B[mh];W[ee];B[fe];W[ff];B[gc];W[nh];B[lf];W[ng];B[mj];W[sm];B[mi];W[bm];B[qk];W[rk];B[rj];W[ql];B[sk];W[qj];B[ri];W[pm];B[gm];W[lc];B[lb];W[cl];B[dm];W[fm];B[ek];W[fk];B[bl];W[ln];B[mn];W[mo];B[bd];W[bf];B[be];W[hm];B[hn];W[bc];B[ca];W[jn];B[in];W[ba];B[lm];W[al];B[bk];W[fn];B[fo];W[gn];B[go];W[qf];B[pf];W[se];B[qg];W[sf];B[sd];W[sc];B[sg];W[sd];B[am];W[co];B[bg];W[bh];B[af];W[oo];B[op];W[lp];B[ie];W[kn];B[km];W[oe];B[ne];W[of];B[pe];W[he];B[hd];W[ge];B[bi];W[ma];B[kb];W[ah];B[ag];W[dg];B[la];W[ra];B[ak];W[an];B[al];W[pn];B[ac];W[ab];B[ad];W[ea];B[nl];W[sl];B[sj];W[de];B[el];W[ed];B[fc];W[ai];B[aj];W[en];B[eo];W[dc];B[cd];W[qi];B[qh];W[fa];B[ga];W[qk];B[sp];W[sn];B[ma];W[oa];B[gd];W[nj];B[lj];W[po];B[em];W[og];B[ni];W[li])

At the end of the game, black plays O11, white plays M11. Then the game is counted, its result is B+17.0.
However, after my bot (plays as white) plays M11, its output from log is like below:

> 2022-07-23 19:21:06+0800: Controller: genmove w
> 2022-07-23 19:21:16+0800: MoveNum: 250 HASH: 8935FDA4E733C4E2AE7763DFBC55F44C
> A B C D E F G H J K L M N O P Q R S T
> 19 . O X . O O X . . . . X X X O O . O .
> 18 O O . O O X . . . . X X X O O . . . .
> 17 X O O O X X X X X . X O X O X O O O O
> 16 X X X X O X X X . X . O O X X X X O O
> 15 . X X O O X O O X X . . X X O X X X O
> 14 X . X O . O O . O X X X X O O X O O O

> 13 X X O O . . . . O O X O O O O2X X X X
> 12 O O O X . . . . . X O X X O O X X . .
> 11 O X X O O . . . . . O @ X X3O X O X .
> 10 X . X X O . . . . . O X X O O X O X X
> 9 X X . . X O . . . . O X . X O O O O X
> 8 X X O X X O . O O O X X . X O . O O O
> 7 X O X X X1O X O X X X X X O . O O . O
> 6 O O O X O O O X X O O O X O X O X O O
> 5 . . O X X X X . X O . . O O O O X O X
> 4 . . O X . . . . X X O O O X X X X X X
> 3 . . O X . . . . . . X X X . X . O . X
> 2 . . O X . X . . . . . . . X . . . . .
> 1 . . O O X . X . . . . . . . . . . . .
> 
> koPOSITIONALscoreAREAtaxNONEsui0whbNfpok1komi0
> Time taken: 10.032
> Root visits: 40839
> New playouts: 40428
> NN rows: 25750
> NN batches: 537
> NN avg batch size: 47.9516
> PlayoutDoublingAdvantage: 2.75
> PV: M11 K9 K10 A2 A4 F10 F11 F13 E12 J12 G10 H12 H14 J9
> Tree:
> : T -107.70c W -99.88c S  -7.83c (-19.5 L -19.1) N   40839  --  M11 K9 K10 A2 A4 F10 F11
> ---White(^)---
> M11 : T -107.61c W -99.88c S  -7.78c (-19.5 L -19.1) LCB -107.72c P 39.08% WF 144452.2 PSV  144268 N   37438  --  M11 K9 K10 A2 A4 F10 F11 F13
> N9  : T -108.37c W -99.80c S  -8.23c (-19.5 L -19.1) LCB -109.65c P  5.11% WF 1264.2 PSV    1266 N     300  --  N9 N8 S12 T12 M11 K9 K11 J12
> H18 : T -108.30c W -99.81c S  -8.00c (-19.4 L -18.9) LCB -109.52c P  4.05% WF 1028.1 PSV    1030 N     257  --  H18 J18 M11 K9 K11 J12 J10 F13
> S12 : T -108.25c W -99.82c S  -8.14c (-19.3 L -18.9) LCB -109.51c P  3.95% WF 1021.6 PSV    1021 N     225  --  S12 T12 K11 M11 E12 C9
> C9  : T -108.49c W -99.80c S  -8.27c (-19.7 L -19.2) LCB -109.94c P  4.24% WF 981.7 PSV     947 N     258  --  C9 D9 N9 N8 M11 K9 K11 J12
> N8  : T -108.59c W -99.78c S  -8.47c (-19.8 L -19.4) LCB -110.07c P  4.34% WF 959.7 PSV     941 N     242  --  N8 N9 T11 S12 M11 K9 K11 J12
> H19 : T -108.45c W -99.76c S  -8.39c (-19.7 L -19.3) LCB -109.91c P  4.01% WF 946.8 PSV     927 N     240  --  H19 G18 K11 M11 E12
> T11 : T -108.46c W -99.83c S  -8.24c (-19.4 L -19.1) LCB -109.54c P  3.99% WF 946.7 PSV     898 N     220  --  T11 T12 K11 M11 E12 C9
> E2  : T -108.31c W -99.84c S  -8.20c (-19.2 L -18.9) LCB -109.36c P  3.58% WF 876.9 PSV     877 N     193  --  E2 M11 K9 F1 E12
> K9  : T -108.62c W -99.95c S  -8.54c (-19.3 L -19.2) LCB -109.13c P  2.59% WF 799.7 PSV     806 N     143  --  K9 M11 E12 C9 P7
> 
> = M11
> 
> 2022-07-23 19:21:16+0800: = M11

The score shows at least 2 points less than the actual result for white.
After black plays "pass", white follows a "pass" and the output is like:

> 2022-07-23 19:21:18+0800: Controller: play b pass
> =
> 
> time_left w 580 3
> 2022-07-23 19:21:18+0800: =
> 2022-07-23 19:21:18+0800: Controller: time_left w 580 3
> =
> 
> genmove w
> 2022-07-23 19:21:18+0800: =
> 2022-07-23 19:21:18+0800: Controller: genmove w
> 2022-07-23 19:21:20+0800: MoveNum: 252 HASH: 6FDDE01C2DACFB86BC5B8949108E6123
> A B C D E F G H J K L M N O P Q R S T
> 19 . O X . O O X . . . . X X X O O . O .
> 18 O O . O O X . . . . X X X O O . . . .
> 17 X O O O X X X X X . X O X O X O O O O
> 16 X X X X O X X X . X . O O X X X X O O
> 15 . X X O O X O O X X . . X X O X X X O
> 14 X . X O . O O . O X X X X O O X O O O
> 13 X X O O . . . . O O X O O O O X X X X
> 12 O O O X . . . . . X O X X O O X X . .
> 11 O X X O O . . . . . O O2X X1O X O X .
> 10 X . X X O . . . . . O X X O O X O X X
> 9 X X . . X O . . . . O X . X O O O O X
> 8 X X O X X O . O O O X X . X O . O O O
> 7 X O X X X O X O X X X X X O . O O . O
> 6 O O O X O O O X X O O O X O X O X O O
> 5 . . O X X X X . X O . . O O O O X O X
> 4 . . O X . . . . X X O O O X X X X X X
> 3 . . O X . . . . . . X X X . X . O . X
> 2 . . O X . X . . . . . . . X . . . . .
> 1 . . O O X . X . . . . . . . . . . . .
> 
> koPOSITIONALscoreAREAtaxNONEsui0whbNfpok1komi0
> Time taken: 2.016
> Root visits: 1429957
> New playouts: 1413947
> NN rows: 73
> NN batches: 22
> NN avg batch size: 3.31818
> PlayoutDoublingAdvantage: 2.75
> PV: pass
> Tree:
> : T 101.73c W 100.00c S   1.74c ( +4.0 L  +4.0) N 1429957  --  pass
> ---White(^)---
> pss : T 101.74c W 100.00c S   1.74c ( +4.0 L  +4.0) LCB  101.74c P 98.04% WF 11439153.4 PSV 11438832 N 1429854  --  pass
> J12 : T -121.23c W -99.98c S -21.25c (-17.5 L -17.3) LCB -280.00c P  0.35% WF   2.7 PSV       5 N       1  --  J12
> E12 : T -121.27c W -99.99c S -21.28c (-17.6 L -17.3) LCB -280.00c P  0.34% WF   2.7 PSV       4 N       1  --  E12
> K11 : T -121.23c W -99.97c S -21.26c (-17.6 L -17.3) LCB -280.00c P  0.20% WF   2.7 PSV       2 N       1  --  K11
> Q2  : T -121.34c W -99.90c S -21.44c (-18.0 L -17.6) LCB -280.00c P  0.09% WF   2.4 PSV       1 N       1  --  Q2
> G8  : T -121.27c W -99.98c S -21.29c (-17.6 L -17.3) LCB -280.00c P  0.09% WF   2.7 PSV       1 N       1  --  G8
> C9  : T -119.79c W -98.96c S -20.83c (-16.9 L -16.7) LCB -280.00c P  0.06% WF   2.0 PSV       0 N       1  --  C9
> H19 : T -120.60c W -99.54c S -21.06c (-17.3 L -16.9) LCB -280.00c P  0.04% WF   2.2 PSV       0 N       1  --  H19
> K9  : T -121.27c W -99.98c S -21.29c (-17.6 L -17.3) LCB -280.00c P  0.04% WF   2.7 PSV       0 N       1  --  K9
> S2  : T -121.39c W -99.87c S -21.52c (-18.2 L -17.7) LCB -280.00c P  0.04% WF   2.4 PSV       0 N       1  --  S2
> 
> = pass
> 
> final_score
> 2022-07-23 19:21:20+0800: = pass
> 2022-07-23 19:21:22+0800: Controller: final_score
> = B+17.0
> 
> final_status_list dead
> 2022-07-23 19:21:25+0800: = B+17.0
> 2022-07-23 19:21:25+0800: Controller: final_status_list dead
> = C19 M17 M16 N16 D12 K12 C8 G7 P6 R3

I think there are something strange from the log:
(1) Why white gets back the "lost" 2 points after black's "pass"?
(2) Why the log shows white has 100% winrate and will be won by 4.0 after it follows a "pass"? (Is it the whiteHandicapBonus, as it is an 8-stone handicap game?)
(3) The visits are about 1.4M in 2 seconds. This is probably an abnormal output, as my hardware configuration usually plays about 4000 playouts per move with the 40b weight. (Can also be found in the previous visits)

Do you have any idea what causes this output?
(I think it may be similar as the previous issue https://github.com/lightvector/KataGo/issues/473, however it was previously fixed and I have no idea if it still makes this issue)

**Comment by lightvector** [comment]
1. Because KataGo is thinking black may be able to cut at K9 and K12 and start some difficult tactics inside to win some more points. You can see it in your own log that these moves are being considered in the variation of that search. In fact nothing works, but there are some tactics that *almost* work, and if white makes a small mistake black will gain a lot. For example, here is a sequence where white makes a mistake and black wins a lot:
![image](https://user-images.githubusercontent.com/11942395/181267533-1c3428c8-055b-49b2-83d6-91ac8ce22fa6.png)

So the reading of these variations biases the MCTS score to be slightly lower than normal because there is some aji. This is why it's only 2 points on average instead of more. The average of "very nothing works and so white loses nothing" and "very small chance that white loses 30 points" turns out to be on average 2 points. When black passes, they forfeit the chance to try these variations and have a small chance of white messing up and losing everything.

2. White has 100% winrate after a pass because under strict Tromp-Taylor-like rules (https://senseis.xmp.net/?TrompTaylorRules), there is no such thing as "dead" stones, you must either remove them from the board or else they will be scored as points for the opponent. The white stone at R3 needs to be captured before passing or else it it is scored as white's points and therefore black's entire territory on the bottom is not counted because R3 is alive inside it.

So black passing is a huge blunder. Black should capture all the stones, or else white can pass and end the game prematurely and win.

By default KataGo assumes that its pass can never end the game prematurely, https://github.com/lightvector/KataGo/blob/master/cpp/configs/gtp_example.cfg#L166-L169 - so either there is a bug or you may have changed this option at some point without understanding what it did, or you are using a very outdated version of KataGo.

3. 1.4 million visits seems normal. Searching is extremely fast if 99% of the visits are "pass, score game", because then it never needs to call the neural net. It just keeps repeating "pass, score game" in a tight loop.

**Comment by sbbdms** [comment]
Thanks very much for your detailed explaination! Indeed that option was changed and it probably caused the phenomenon.
Now I am clear about the 3 questions and there should be no potential issues. Closing this issue.
