### ISSUE TITLE
KataGo on Browser

### ISSUE THREAD

**Issue by y-ich** [lightvector/KataGo#67]
Hi.

I succeeded to run KataGo on browsers (though I am sorry that I do not test it well yet^^;)
.
https://github.com/y-ich/KataGo

If you use the latest Chrome, you can utilize WebGL in Web Workers thanks to TensorFlow.js.

If you want to try it, please read https://github.com/y-ich/KataGo/blob/browser/README_WASM.md
(Sorry for no demo pages because I must implement UI from now^^)

@lightvector san,
Thank you for your great project!

**Comment by lightvector** [comment]
Neat!

**Comment by y-ich** [comment]
Now I implemented a simple Lizzie-like UI.

https://github.com/new3Rs/react-lizzie
(Google Chrome is required)

Enjoy!

**Comment by kaorahi** [comment]
typo?

~~~
--- a/tfjs/save_graph.py
+++ b/tfjs/save_graph.py
@@ -56,7 +56,7 @@ if __name__ == '__main__':
                 'swa_model/policy_output': model.policy_output,
                 'swa_model/value_output': model.value_output,
                 'swa_model/miscvalues_output': model.miscvalues_output,
-                'sswa_model/corebelief_output': model.scorebelief_output,
+                'swa_model/scorebelief_output': model.scorebelief_output,
                 'swa_model/bonusbelief_output': model.bonusbelief_output,
                 'swa_model/ownership_output': model.ownership_output,
             }
~~~

~~~
$ git log --oneline -n 1
82a8028 (HEAD, y-ich/browser) bugfix: wrong copy for ownership
~~~

**Comment by y-ich** [comment]
Yes, thank you!

**Comment by adamreisnz** [comment]
Are there any updates to this project @y-ich? Do you think you would be able to update it to the latest version of this repository?

**Comment by y-ich** [comment]
@adamreisnz san,

The latest version of KataGo uses PyTorch. So the workflow is different from TensorFlow version.
I am not sure if it is possible.
Before that, I think that the weights for the latest KataGo might be too large for browsers.

**Comment by adamreisnz** [comment]
市川ゆちさん　ありがとうございます。

Yes I was thinking that might be the case. All good, I will look into another solution.
It's for a new project I am working on, https://letsplaygo.com/ja

おやすみなさい

**Comment by y-ich** [comment]
@adamreisnz san,

I successfully updated KataGo on Browser for KataGo v1.14.0, though it does not support weight version 12 and later yet.
Only TensorFlow model can be converted and its instructions are a little bothered since you need to checkout back the previous branch "browser_v1.8.0".

I hope that it will be useful for you.
