### ISSUE TITLE
can't get kata go running in smartgo

### ISSUE THREAD

**Issue by s482** [lightvector/KataGo#671]
system: windows 11
program: smart go windows
CPU version
katago eigen and other

I intended on using katago to analyze my game and to play with

using process monitor I saw this report is it an error?
 Name not found in windows registry in a couple of directories eg.
 REGOPENKEY NOT FOUND
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\...
I tried to write the keys that were being looked for but that did not work

**Comment by HackYardo** [comment]
Sounds like a issue of SmartGo. You can try KaTrain, Sabaki, or run KataGo in your terminal `./katago -h`, if everything works fine except SmartGo, it is a SmartGo issue for sure. And if you pay for SmartGo, you can tele their user support for help.

**Comment by s482** [comment]
The problem is the GTP command. I was using `katago gtp` which worked in windows 10 but in windows 11 the default terminal was changed from command prompt to Powershell. the command must be `./katago gtp`

Hackyardo I am not familiar with -h I will read the GTP reference thanks
