### ISSUE TITLE
Does not run on ubuntu 22.04

### ISSUE THREAD

**Issue by kylebakerio** [lightvector/KataGo#672]
At first, got errors in console from not having xsel and xclip. So I installed those. Then the app would launch, but I see:

```
ERROR:
/home/kyle/.local/lib/python3.10/site-packages/KataGo/katago: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

(Sometimes I just get an error 127, instead, but this is the more verbose one.)

libssl is now 3 instead of 1.1 in the repos for 22.04.

Advice for getting this to run?

EDIT: sorry, meant this for katrain, not for katago, my bad!

**Comment by tsutton** [comment]
I think this is a katago issue, not a katrain issue, at least in as far as the latest official release binaries (v1.11.0) downloaded from this repo have the same issue. I can reproduce by downloading the latest Linux release (tried CUDA and OpenCL). Manjaro just started defaulting to OpenSSL 3.0 recently, which is where I'm having the issue.

FWIW, I have for-now worked around this by downloading the OpenSSL 1.1.1s source from https://www.openssl.org/source/ , building with `./configure`, `make`, then copying the produced `libssl.so.1.1` and `libcrypto.so.1.1` to `/usr/lib`
