### ISSUE TITLE
Huawei launches Ascend 910, the world's most powerful AI processor, and MindSpore, an all-scenario AI computing framework

### ISSUE THREAD

**Issue by hydrogenpi** [lightvector/KataGo#68]
https://www.huawei.com/en/press-events/news/2019/8/Huawei-Ascend-910-most-powerful-AI-processor

**Comment by alreadydone** [comment]
They claim more than 2x V100's fp16 inference and 2x that for int8. Hopefully the computing power can be easily utilized through OpenCL with possibly some tweaks similar to what ihavnoid did for LZ to utilize tensor cores, or through some platform hopefully more lightweight than CUDA. They said it will not be more expensive than V100 or TPUv3. If LZ/KataGo is able to run on it, and if they make it available on Huawei Cloud at a price lower than V100 on the cloud, Fox will soon be filled with Ascend 910s.

**Comment by lightvector** [comment]
(just combing through old issues) 
Closing this for now as it seems there are no recent updates here and not much to do. Let me know if there is!
