### ISSUE TITLE
OpenCL backend KataGo fails to start from C:\Program Files.

### ISSUE THREAD

**Issue by MAOmao000** [lightvector/KataGo#687]
Is it possible to create a tuning file in a folder that contains blank spaces?
The following is the result of the run.
```
C:\Program Files\KataGo-1.11>katago.exe analysis -config analysis_example.cfg -model kata1-b40c256-s11840935168-d2898845681.bin.gz

If "KataGoData/opencltuning/tune8_gpu..." exists:
2022-10-09 03:51:57+0900: Started, ready to begin handling requests

If "KataGoData" does not exist:
2022-10-09 03:53:08+0900: Creating context for OpenCL Platform: ...
Uncaught exception:

If only "KataGoData" exists:
2022-10-09 04:01:34+0900: Creating context for OpenCL Platform: ...
Uncaught exception:

If "KataGoData/opencltuning" exists:
(Tuning messages)
Done tuning
------------------------------------------------------
Uncaught exception: Could not write to file C:\Program Files\KataGo-1.11/KataGoData/opencltuning/tune8_gpuNVIDIAGeForceGTX1050_x19_y19_c256_mv10.txt - invalid path or permissions?
```

**Comment by HackYardo** [comment]
Look at the path, there are many "/" and "\", so there is a "invalid path exception"... 
"/" and "\" are not the same one symbol...
```
Done tuning
------------------------------------------------------
Uncaught exception: Could not write to file C:\Program Files\KataGo-1.11/KataGoData/opencltuning/tune8_gpuNVIDIAGeForceGTX1050_x19_y19_c256_mv10.txt - invalid path or permissions?
```

**Comment by MAOmao000** [comment]
That's right, but this pathname is not what you specified in the arguments or configuration file.
It's made by KataGo.
Is it difficult to handle with KataGo?

**Comment by MAOmao000** [comment]
I am sorry.
This was permissions issue, not a pathname.
The tuning file can be generated when run with administrator privileges.
This may be an impossible order, but is it possible to create a tuning file in C:\Program Files as an ordinary user?

**Comment by HackYardo** [comment]
Oh, I know what you mean.
You set a dir where the OpenCL cfg in, you can try **'path'**:
```
# Optionally override where KataGo will attempt to save things like openCLTuner files and other cached data.
homeDataDir = c:\'Program File'\KataGoOpenCL\
```

**Comment by MAOmao000** [comment]
@HackYardo
In my case, I copied the directory (KataGo-1.11) containing katago.exe to C:\Program Files on Explorer and performed the above startup.
In this case, the write attribute of the destination directory (KataGo-1.11) seems to have been rewritten by Windows to prohibit general users from writing to it.
In this case, I was able to confirm that if I give write permission to the directory (KataGo-1.11) containing katago.exe, it will work.
Please close the issue.
Thank you for your response.

**Comment by HackYardo** [comment]
Oh, I see. But I have no chance to close issues, you open the issue, you close it.
