### ISSUE TITLE
[Question] Is v1.1 weight saturated?

### ISSUE THREAD

**Issue by y-ich** [lightvector/KataGo#69]
Hi.

I have a technical question.

When I read AlphaGo Zero paper, I understood that 20b AGZ could not beat AlphaGo Master, which consists of 20b with more input features, and 40b AGZ beaten her barely.
So I thought that putting more input features brings large strength boost.

 Is v1.1 weight saturated? Or was the training stopped when it exceeded ELFv2?

I guess that v1.1 weight may become much stronger by more training.

Thank you.

**Comment by lightvector** [comment]
Although I haven't trained it more, I think it's not saturated. It probably has at least another couple hundred Elo to improve (maybe more). I don't actually plan to train this particular run further though, instead I want to try to make some more fundamental improvements, if possible, and do a new run with better architecture and more things (for example, maybe direct support in the neural net for understanding Japanese scoring).

**Comment by y-ich** [comment]
Thank you for your answer!

I just want to know whether saturated or not.

Cheers for your great project!
