### ISSUE TITLE
How can I run katago(version 1.11.0) using eigenavx2 backend in Katrain on my macos(intel)

### ISSUE THREAD

**Issue by GlareL** [lightvector/KataGo#692]
I install katago via homebrew ,but when I use KaTrain to invoke katago it tells 'ERROR: Engine died unexpectedly without sending output status -6'.It's Ok when I use Sabaki to invoke katago.
Maybe the reason is my katago is using OpenCL backend ,so I want to install katago which is using eigenavx2 backend.
It's esay to install katago whose default backend is OpenCL via homebrew ,but how can I install katago which is using eigenavx2 backend?
I download 'katago-v1.11.0-eigenavx2-linux-x64.zip' and try to use it to config katrain but it tells 'cannot execute binary file', Maybe I should compile it ,but how to do?

**Comment by ChinChangYang** [comment]
If you can use Sabaki to invoke KataGo, then I believe KaTrain should be able to invoke KataGo. Did you install KaTrain via [Homebrew](https://formulae.brew.sh/cask/katrain)?

```
brew install --cask katrain
```

**Comment by GlareL** [comment]
> 

I reinstall KataGo via Homebrew, and use default config of KaTrain to run KataGo, it still tells _ERROR: Engine died unexpectedly without sending output: status -6_.
Then I use my config which can run KataGo normally in Sabaki, it tells the same error.
Finally I fill the path of _match_example.cfg_ of configs of KataGo instead of _analysis_example.cfg_ of that, amazingly, it can run successfully.
So one of solutions of this problem is that filling the path of _match_example.cfg_ of configs of KataGo instead of _analysis_example.cfg_ of that in the blank of **Path of KataGo config file**.
As for why I filled in the path of _analysis_example.cfg_ at the beginning, because the default setting is _katrain/KataGo/analysis_config.cfg_.
Last but not least, thank you for giving me the confidence that KataGo can also run normally on KaTrain.

**Comment by GlareL** [comment]
> If you can use Sabaki to invoke KataGo, then I believe KaTrain should be able to invoke KataGo. Did you install KaTrain via [Homebrew](https://formulae.brew.sh/cask/katrain)?
> 
> ```
> brew install --cask katrain
> ```

I reinstall KataGo via Homebrew, and use default config of KaTrain to run KataGo, it still tells ERROR: Engine died unexpectedly without sending output: status -6.
Then I use my config which can run KataGo normally in Sabaki, it tells the same error.
Finally I fill the path of match_example.cfg of configs of KataGo instead of analysis_example.cfg of that, amazingly, it can run successfully.
So one of solutions of this problem is that filling the path of match_example.cfg of configs of KataGo instead of analysis_example.cfg of that in the blank of Path of KataGo config file.
As for why I filled in the path of analysis_example.cfg at the beginning, because the default setting is katrain/KataGo/analysis_config.cfg.
Last but not least, thank you for giving me the confidence that KataGo can also run normally on KaTrain.
