### ISSUE TITLE
how to change opencltuning file loaction in opencl version

### ISSUE THREAD

**Issue by songshizhao** [lightvector/KataGo#702]
opencl version write KataGoData/opencltuning/***.txt in katago work directory
can i change the location of this file？
like -override-config logDir=** in cpu version command
and I found katago will reload opencltuning result dircetly next time，how to indicate katago to specify file generated last time？

**Comment by lightvector** [comment]
If you want to control the directory where KataGo saves things like this, set `homeDataDir` to a directory in the config. If you want to specify the exact fiel, try `openclTunerFile`.

**Comment by songshizhao** [comment]
Perfect answer, thank you
