### ISSUE TITLE
Real-time display of area counts

### ISSUE THREAD

**Issue by kaorahi** [lightvector/KataGo#72]
I'm trying real-time display of area counts by KataGo. Isn't this fun?
![area_count](https://user-images.githubusercontent.com/38910552/64700036-106fc000-d4e1-11e9-88d2-aef78b79834e.gif)

**Comment by lightvector** [comment]
Woah...

**Comment by lukaszlew** [comment]
Woah indeed!
Amazing.

How are the areas calculated? Is it number of intersections above threshold or is it sum of probabilities (expected value)?

**Comment by kaorahi** [comment]
Interesting. Instead of this phi, we can use the correlation of the estimated ownerships that are directly obtained as the output of the neural network in KataGo. We need to modify KataGo to get "correlations" anyway if we use your algorithm.

My current problem is rather psychological. In this screenshot, it is said that black has 81 points as the sum of the right-top corner and the bottom edge. They are surely "connected". But people may prefer separate counting of these two areas.
![cluster](https://user-images.githubusercontent.com/38910552/64862491-9de01b00-d66d-11e9-934e-848eefa21dc9.png)

**Comment by lukaszlew** [comment]
Yes indeed it would require KataGo modifications. 
Here is an alternative then:

Initialize with 19*19 clusters.
For each cluster track their size, sum of score, sum of squared score, mean location on board (x and y) and squared location coordinates. Squares are for variance and stddev calculation. 
Map cluster_id -> (n, s_sum, s2_sum, x_sum, x2_sum, y_sum, y2_sum)
When you merge clusters just add all the components. Initialize sums with small epsilon.
For each cluster you can compute stddev of score and location. E.g. for score:
sqrt(s2_sum / n - (s_sum / n)^2)

Intuitively we want to have clusters that are:
  - small stddev of score - user intuitively assigns equal score to intersections in the cluster 
  - small stddev of location - user want blobs (your current goal)

Linear combination of these should be a measurement of a cluster quality.
Some thresholds on these values should do the job.

**Comment by kaorahi** [comment]
I implemented a naive method based on classic "morphological transformations" (erosion & dilation). I'll check its feasibility for a while.

https://github.com/kaorahi/lizgoban/commit/4b2af31ba3b9951d44d7607e2c58963493c05a5a
![morph](https://user-images.githubusercontent.com/38910552/64907890-9125fa80-d733-11e9-8977-66a1d76b17ea.png)

**Comment by lukaszlew** [comment]
Please consider displaying boundaries between territories.

**Comment by kaorahi** [comment]
Done :)

(We may be better to change the place of discussion if we talk about GUI implementations too long.)

![boundary](https://user-images.githubusercontent.com/38910552/64922195-4ecded80-d807-11e9-8fc9-004d9d71a7e2.png)

**Comment by lukaszlew** [comment]
Please direct me to a better place :)
Here's another idea. For at-a-glance perception point of view, lot's of numbers are distracting. Observing myself observing the board I realize I do the mental work of separating the numbers into intersections where there is approximately white full-point, white half point, dame, black half-point or black full-point.
Perhaps it would be beneficial that computer does it for the user and displays it in the language the user already is accustomed to - display translucent stones and half-stones (perhaps even quarter points) on the owned intersections. What do you think?
The natual

**Comment by kaorahi** [comment]
Then shall we use https://github.com/kaorahi/lizgoban/issues/33 for GUI-side topics?
