### ISSUE TITLE
Can't compile OPENCL on branch gpu-backend-cleanup  VS2019 error

### ISSUE THREAD

**Issue by jun63cn** [lightvector/KataGo#722]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2026	字符串太大，已截断尾部字符	katago	C:\Users\jun\Downloads\KataGo\cpp\neuralnet\hgemm_wmma_nchw.opencl	454

**Comment by lightvector** [comment]
Thanks, yes, I suspected this would be the case, it was a work in progress. Visual Studio has a very low length limit on the length of strings that they will accept in the code. I merged gpu-backend-cleanup into master, and additionally pushed this commit 103dc043 which should fix it. Can you check if the master branch works for you now?

**Comment by jun63cn** [comment]
Thanks, It‘s OK now.
