### ISSUE TITLE
Why not replace cnn residual blocks with transformers?

### ISSUE THREAD

**Issue by NeverLandFly** [lightvector/KataGo#724]
Go have more associations between each move than images and natural language, so using the transformer structure should also achieve better results, right? Just a hunch.

**Comment by Ishinoshita** [comment]
IMHO, "Why not" style questions might be better suited for [#katago](https://discord.com/channels/417022162348802048/583775968804732928) channel of the Computer Go Community discord, than as an 'issue' on github. At least, you may get quicker answers there, where someone can easily redirect you to previous discussions. For example,  see [here](https://discord.com/channels/417022162348802048/583775968804732928/979054019731410974)

**Comment by NeverLandFly** [comment]
Ok, thanks
