### ISSUE TITLE
Terminate all queries in analysis engine

### ISSUE THREAD

**Issue by kaorahi** [lightvector/KataGo#726]
In the analysis engine, I would like to terminate all queries without explicitly specifying their ids. Is this possible?

Background:

I am writing a wrapper script for `katago analysis` so that I can use it casually on the command line like this:

```sh
$ ls *.sgf | katawrap.py ... | jq ...
```

To save the startup time of katago (5-10 sec) when I run the wrapper repeatedly, I use netcat to make local katago server easily:

(server)

```sh
$ mkfifo /tmp/f
$ cat /tmp/f \
  | ./katago analysis -config analysis.cfg -model model.bin.gz \
  | nc -klv localhost 1234 > /tmp/f
```

(client)

```sh
$ ls /foo/*.sgf \
  | ./katawrap.py \
      -default '{"maxVisits": 1, "analyzeTurnsEvery": 100}' \
      nc localhost 1234 \
  | jq -r '[.sgfFile, .turnNumber, (.winrate*100|round)] | @csv'
```

When I start a heavy analysis and terminate the client with Ctrl-C...

* I tried to trap Ctrl-C in the wrapper and send termination requests `{..., "action":"terminate",...}` to katago (and sleep 10 sec), but I got BrokenPipeError immediately before sleeping and katago keeps searching.
* I can start another client and resume communication with katago, but the new client cannot cancel the queries since their ids are unknown.
* I can stop the server and restart katago, but this operation is a little annoying.

I will be happy if I can tell katago "Terminate all queries" at the beginning of my wrapper.

**Comment by kaorahi** [comment]
* This may be a python side problem? [ref](https://stackoverflow.com/questions/48449653/capture-ctrl-c-signal-and-wait-for-subprocess) [ref](https://stackoverflow.com/questions/5045771/python-how-to-prevent-subprocesses-from-receiving-ctrl-c-control-c-sigint)
* I should write another wrapper for the server that records all unfinished queries and send termination requests when it receives `{"action":"terminateAll"}`?
* BTW, can katago read termination requests soon if they are sent after 30000 analysis queries?

**Comment by lightvector** [comment]
Thanks for the feedback! I pushed a possible implementation here: https://github.com/lightvector/KataGo/pull/727 - does this do what you wanted?

**Comment by kaorahi** [comment]
Yes. `terminate_all` makes things much simpler. Thanks for the implementation! It works.

**Comment by kaorahi** [comment]
(Note for future readers)
In my trials on Linux, it seems that the most reliable way for Ctrl-C is...

1. Catch KeyboardInterrupt.
2. Kill the existing client nc.
3. Then start another client nc and send terminate_all to it.
