### ISSUE TITLE
what is the result of GTP cmd genmove

### ISSUE THREAD

**Issue by songshizhao** [lightvector/KataGo#736]
genmove usually return position coordinates, like "= E4"

but sometimes return "= pass" or "= resign"

Is there any other return value ?

**Comment by CGLemon** [comment]
The ```pass```, ```resign``` and coordinates are all. Lower case and upper case are legal. For example, may output  ```= E4```, ```= e4```.  ```= PASS``` or ```= pass```.

**Comment by songshizhao** [comment]
> The `pass`, `resign` and coordinates are all. Lower case and upper case are legal. For example, may output `= E4`, `= e4`. `= PASS` or `= pass`.

thank you
