### ISSUE TITLE
TensorRT backend performance regression between v1.12.1 and v1.12.2

### ISSUE THREAD

**Issue by OmnipotentEntity** [lightvector/KataGo#739]
I am experiencing a performance regression of about 10% on my computer (Ti2080).  It might have something to do with the timing cache being unused due to an error:

```
2023-01-11 13:19:51-0600: Using existing timing cache at /home/omnipotententity/.katago/trtcache/trt-8502_gpu-2a25d4df_tune-4bb5666e2ab6_exact19x19_batch32_fp16
2023-01-11 13:19:51-0600: TensorRT backend: 1: [myelinCache.h::deserializeFromBuffer::52] Error Code 1: Myelin (Myelin error from unknown graph)
2023-01-11 13:19:51-0600: TensorRT backend: 4: The timing cache will not be used!
```

Benchmark log for v.1.12.2: [tensorrt-1.12.2.txt](https://github.com/lightvector/KataGo/files/10395659/tensorrt-1.12.2.txt)

Benchmark log for v.1.12.1: [tensorrt-1.12.1.txt](https://github.com/lightvector/KataGo/files/10395660/tensorrt-1.12.1.txt)

**Comment by matolv** [comment]
> Still having this issue on my setup. Using version 1.12.3. Running without a saved timing cache will make a new one which works for that session but problem arises when trying to reuse the cache.
> 
> ```
> 2023-02-03 12:20:28+0200: Running with following config:
> allowResignation = true
> conservativePass = false
> lagBuffer = 0.0
> logAllGTPCommunication = false
> logDir = gtp_logs
> logSearchInfo = true
> logToStderr = true
> maxTimePondering = 60
> nnCacheSizePowerOfTwo = 22
> numSearchThreads = 96
> ponderingEnabled = false
> resignConsecTurns = 6
> resignThreshold = -0.93
> rules = japanese
> searchFactorAfterOnePass = 0.50
> searchFactorAfterTwoPass = 0.30
> searchFactorWhenWinning = 0.30
> searchFactorWhenWinningThreshold = 0.95
> 
> 2023-02-03 12:20:28+0200: Loading model and initializing benchmark...
> 2023-02-03 12:20:28+0200: Testing with default positions for board size: 19
> 2023-02-03 12:20:28+0200: nnRandSeed0 = 6778924738224897138
> 2023-02-03 12:20:28+0200: After dedups: nnModelFile0 = kata1-b60c320-s6908673792-d3104143025.bin.gz useFP16 auto useNHWC auto
> 2023-02-03 12:20:28+0200: Initializing neural net buffer to be size 19 * 19 exactly
> 2023-02-03 12:20:30+0200: TensorRT backend thread 0: Found GPU NVIDIA GeForce RTX 4090 memory 25756696576 compute capability major 8 minor 9
> 2023-02-03 12:20:30+0200: TensorRT backend thread 0: Initializing (may take a long time)
> 2023-02-03 12:20:32+0200: Using existing timing cache at C:\Users\user\Desktop\katago/KataGoData/trtcache/trt-8502_gpu-e7d86226_tune-85cbab2735d3_exact19x19_batch96_fp16
> 2023-02-03 12:20:32+0200: TensorRT backend: 1: [myelinCache.h::nvinfer1::builder::MyelinCache::deserializeFromBuffer::52] Error Code 1: Myelin (Myelin error from unknown graph)
> 2023-02-03 12:20:32+0200: TensorRT backend: 4: The timing cache will not be used!
> ```

Temporary solution:
Delete the cache file before you start the program each time. The file should be ~/katagodata/trtcache/trt-8502_gpu_xxx

I complied katago on debian11. It works normal without this issue so there should be no issue in the source code. I think they just released a wrong binary file for win x64.

**Comment by hyln9** [comment]
@tterava @matolv The performance regression bug has been fixed. As for the error message, it's known to be unrelated and harmless. You can safely ignore it and keep the cache file.
