### ISSUE TITLE
How to config to enable multi-gpu?

### ISSUE THREAD

**Issue by pangafu** [lightvector/KataGo#75]
I only found 
cudaDeviceToUse = 0
openclDeviceToUse = 0

to make which number gpu enable, how to make multi-gpu enable?

**Comment by trunterzx** [comment]
Hi I want to ask this as well... How can I configure such that KataGo will make use of multiple GPUs?

**Comment by lightvector** [comment]
@trunterzx - you will want to look at the notes about performance in the gtp_example.cfg
https://github.com/lightvector/KataGo/blob/master/cpp/configs/gtp_example.cfg

Basic setup is to specify numNNServerThreadsPerModel equal to the number of gpus, which gives you threads indexed (0,1,2,...N-1) and then in the CUDA or OpenCL-specific sections to specify that for model 0 thread K for each different index K you specify the GPU device number for that thread to use. (For GTP, model 0 is the only model, so they should all be model 0 but different thread indices).
