### ISSUE TITLE
sabaki: the selected engine does not support analysis

### ISSUE THREAD

**Issue by kurokoleung** [lightvector/KataGo#750]
An error occurred when using sabaki set the katago engine as analyzer
but i used the command "./katago analysis -config analysis_example.cfg" it seems work

os: macOS Ventura 13.1
architect:apple-m1
katago-version:1.12.3
sabaki-version:0.52.2

<img width="149" alt="image" src="https://user-images.githubusercontent.com/44601069/214866367-55844914-bca8-4090-a290-3f7bfba50e37.png">

**Comment by lightvector** [comment]
This sounds like a question you might want to ask to the github or help for Sabaki, rather than KataGo. Note that Sabaki probably uses GTP rather than analysis, if I recall right.

**Comment by kurokoleung** [comment]
ok,thanks
