### ISSUE TITLE
Unable to open test website

### ISSUE THREAD

**Issue by Chenvincentkevin** [lightvector/KataGo#772]
unable to open https://test.katagodistributed.org/, I want to try rectangular versions of katago

**Comment by OmnipotentEntity** [comment]
You do not need a specific version of katago to use rectangular boards.  You just need to specify a rectangular board size using the appropriate gtp or analyze command.

**Comment by Chenvincentkevin** [comment]
Thanks for your response. The issue is closed

**Comment by Chenvincentkevin** [comment]
Thanks for your response. The issue is closed
