### ISSUE TITLE
v1.13.1 build failure on Linux & test failure on macOS 13 for Homebrew

### ISSUE THREAD

**Issue by p-linnane** [lightvector/KataGo#794]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v1.13.0, and subsequently v1.13.1, we are running into a couple failures. Linux fails to build with the following error:

```
  /usr/bin/ld: CMakeFiles/katago.dir/neuralnet/nneval.cpp.o: in function `NNEvaluator::NNEvaluator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Logger*, int, int, int, int, bool, bool, int, int, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, enabled_t, enabled_t, int, std::vector<int, std::allocator<int> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, int)':
  nneval.cpp:(.text+0x1dd4): undefined reference to `NeuralNet::getPostProcessParams(LoadedModel const*)'
  collect2: error: ld returned 1 exit status
  make[2]: *** [CMakeFiles/katago.dir/build.make:1846: katago] Error 1
  make[2]: Leaving directory '/tmp/katago-20230524-7050-1wm7yk8/KataGo-1.13.1/cpp'
  make[1]: *** [CMakeFiles/Makefile2:86: CMakeFiles/katago.dir/all] Error 2
  make[1]: Leaving directory '/tmp/katago-20230524-7050-1wm7yk8/KataGo-1.13.1/cpp'
  make: *** [Makefile:94: all] Error 2
```

macOS 13 (both arm64 & x86_64) fail the the test suite:

```
==> /usr/local/Cellar/katago/1.13.1/bin/katago runtests
  Running rng and hash tests
  Running fancy math tests
  
  FATAL ERROR:
  Failed approx equal: normToTApprox(2,10000) 2.00025003104416443
  file: /tmp/katago-20230524-7433-1qxgmom/KataGo-1.13.1/cpp/core/fancymath.cpp
  line: 188
  Values: 2.00025003104437582 2.00025003104416443
```

The relevant GitHub Actions run can be found [here](https://github.com/Homebrew/homebrew-core/actions/runs/5070804110).

Relates to https://github.com/Homebrew/homebrew-core/pull/131793

**Comment by lightvector** [comment]
Thanks for reporting! The first one looks like it's because I forgot to add the relevant function `NeuralNet::getPostProcessParams` to the dummy backend for the neural net. Oops! The dummy backend is a backend that has only stub implementations for the neural net and means you can't actually run anything meaningful so it isn't used in practice, which is why I missed it not compiling in testing.

The second one indicates some more tests that we should be adding some leniency in floating point tolerance for the tests. I can fix that too!

But I'm also interested to know - did this floating point error emerge with v1.13.x or was it also broken on earlier releases? Or maybe some underlying system libraries or compiler versions updated on the relevant systems for the build? Because I'm not remembering or seeing there being a modification to that math code in KataGo between the last release and now.

**Comment by p-linnane** [comment]
It emerged in v1.13.x. macOS 13 uses Xcode 14.3 now, but that's the only thing I can think of.

**Comment by lightvector** [comment]
I pushed some fixes to master branch! Is this enough for you to test whether the errors are resolved? If so, then I can add and tag out a new release with the fixes.

**Comment by lightvector** [comment]
Thanks, pushed another commit, and tested that it works across both of my Windows and Linux personal setups with and without AVX2 (which toggling that did earlier break some tests for me). Hopefully this does the trick now?

**Comment by lightvector** [comment]
The additional commit on master added just now to try to further fix those betapdf tests: https://github.com/lightvector/KataGo/commit/64bc4563e098cc5613828e6056b30252645578d3

**Comment by p-linnane** [comment]
Here is the output after also adding that commit:
```
==> /opt/homebrew/Cellar/katago/1.13.1/bin/katago runtests
Running rng and hash tests
Running fancy math tests

FATAL ERROR:
Failed approx equal: betapdf(1-1e-8,.5e10,.5e2) 281620447.51994127035140991
file: /tmp/katago-20230525-86400-vb80gr/KataGo-1.13.1/cpp/core/fancymath.cpp
line: 269
Values: 281624744.73973077535629272 281620447.51994127035140991
```

**Comment by p-linnane** [comment]
> (Sorry for the back and forth, thanks for working with me through this!)

No problem at all! I really appreciate your willingness to work through htis for Homebrew 😄 

Happy to say that the test suite is now passing with those 5 commits applied to the formula! If you can cut a new releae I will push it to our CI.

**Comment by lightvector** [comment]
Great! Okay v1.13.2 is up: https://github.com/lightvector/KataGo/releases/tag/v1.13.2

**Comment by p-linnane** [comment]
Confirming that all builds for v1.13.2 succeeded! Thank so much for all your help here!
