### ISSUE TITLE
Is it possible to use 8-bit Inference with TensorRT?

### ISSUE THREAD

**Issue by zhufl0811** [lightvector/KataGo#799]
I try to use 8-bit Inference with TensorRT, but the winrates is a lot different from fp16. The data I used to quantization was generated from selfplay command.
First I want to ask if it is possible? If it is possible, do you have any demo to do the quantization, and where should I get the data for  quantization.

**Comment by yehu3d** [comment]
per-channel quantization,don't per-layer

**Comment by zhufl0811** [comment]
s
