### ISSUE TITLE
Speeding up runs even faster?

### ISSUE THREAD

**Issue by iopq** [lightvector/KataGo#8]
https://github.com/leela-zero/leela-zero/issues/2282

this patch lets you select moves with very few playouts, as long as they have a good winrate with SOME visits (10% and maximum lowest confidence bound)

But on higher visits it seems like a wash because Leela Zero prefers the higher winrate move to visit anyway. But on lower visits it lets you find a good move quickly! That means you can go up to a bigger network size faster - before you'd need to learn on say 1600 visits, but now maybe 300 visits can do the job while still incrementally getting stronger

**Comment by l1t1** [comment]
is the method common for each engine?

**Comment by lightvector** [comment]
Thanks! Yep, something like this is on my list for future testing, and I should be able to do a real comparison on how it affects the actual selfplay training improvement, rather than just the match strength.

**Comment by lightvector** [comment]
Just going back through old issues and cleaning things up. LCB is implemented for match games as of tip of master (it actually has been for a little while). Definitely it is a big improvement in final match strength.

As for using it in the selfplay training... well that's a bit more unclear: https://github.com/leela-zero/leela-zero/issues/2411
