### ISSUE TITLE
what does genmove-debug output mean?

### ISSUE THREAD

**Issue by kennychenfs** [lightvector/KataGo#81]
I use genmove-debug for winrate and something else, but I don't know what they mean.

```
koPOSITIONALscoreAREAsui1komi7.5
Time taken: 10.0348
Root visits: 4802
NN rows: 3484
NN batches: 442
NN avg batch size: 7.88235
PV: K4 D10 C11 D4 C10 K10 D3 K3 L3 J3 J4 E3 C3 H4 E2
Tree:
: T -23.11c W -22.31c S  -0.80c ( -1.5) N    4802  --  K4 D10 C11 D4 C10 K10 D3
---Black(^)---
K4  : T -22.90c W -22.12c S  -0.77c ( -1.5) LCB  -23.82c P 21.95% WF  6.36% PSV    1794 N    1170  --  K4 D10 C11 D4 C10 K10 D3 K3
...
```
I want to know what T, W, S mean.

**Comment by lightvector** [comment]
T is the total utility, W is the utility due to win/loss, s is the utility due to score.

This output isn't entirely meant for consumption by "casual" users, so yeah, I haven't really documented it. Hence "debug". :)

**Comment by lightvector** [comment]
Closing this issue for now, let me know if you have further questions.

**Comment by kennychenfs** [comment]
ok

**Comment by pnprog** [comment]
Hi @lightvector , thanks for the information!

I just started adding support for Katago in goreviewpartner, so I am also looking at the logs.

What is the meaning of "utility" exactly?
I have been leaving under a rock this year (in term of Go related activities, and following latest developement) so maybe my question is stupid but I am trying to catch up now.

`R16 : T  -3.10c W  -2.69c S  -0.41c ( -1.0) LCB   -3.37c P 23.27% WF  8.38% PSV    2644 N    2644  --  R16 D3 P4 D15 P16 D5 R10 C10`

In the example above, I guess `2644 N    2644` is the number of visits, both numbers seems to be always identical, is there a posibility they could be different?
What are the meanings of `23.27% WF` and `8.38% PSV` ? I cannot find how they would relate to win rate (48.63% for this exemple), maybe it is policy network value?

**Comment by kennychenfs** [comment]
@pnprog Besides, you can get ownership by "kata-analyze" and a argument, ownership true.
I think it could be useful for you

**Comment by kennychenfs** [comment]
The utilities is from -1 to 1, while the winrate is from 0~1, you can also get the winrate by kata-analyze

**Comment by pnprog** [comment]
@kennychenfs thank for the answer!

So here is a more complete exemle:
```
genmove w
2019-12-15 15:39:23+0800: Controller: genmove w
CHAT:Visits 1003 Winrate 51.22% ScoreMean 0.8 ScoreStdev 32.1 PV C4 C16 Q3 E16 Q5 P16 E4
2019-12-15 15:39:25+0800: MoveNum: 1 HASH: 51CF5E56175121BF0FF1A841E89DD3FB
   A B C D E F G H J K L M N O P Q R S T
19 . . . . . . . . . . . . . . . . . . .
18 . . . . . . . . . . . . . . . . . . .
17 . . . . . . . . . . . . . . . . . . .
16 . . . . . . . . . . . . . . . . X . .
15 . . . . . . . . . . . . . . . . . . .
14 . . . . . . . . . . . . . . . . . . .
13 . . . . . . . . . . . . . . . . . . .
12 . . . . . . . . . . . . . . . . . . .
11 . . . . . . . . . . . . . . . . . . .
10 . . . . . . . . . . . . . . . . . . .
 9 . . . . . . . . . . . . . . . . . . .
 8 . . . . . . . . . . . . . . . . . . .
 7 . . . . . . . . . . . . . . . . . . .
 6 . . . . . . . . . . . . . . . . . . .
 5 . . . . . . . . . . . . . . . . . . .
 4 . . @ . . . . . . . . . . . . . . . .
 3 . . . . . . . . . . . . . . . . . . .
 2 . . . . . . . . . . . . . . . . . . .
 1 . . . . . . . . . . . . . . . . . . .

koPOSITIONALscoreAREAsui1komi7.5
Time taken: 1.563
Root visits: 1003
NN rows: 449
NN batches: 225
NN avg batch size: 1.99556
PV: R4 C4 D17 E4 P4 P16
Tree:
: T   2.69c W   2.43c S   0.26c ( +0.8) N    1003  --  R4 C4 D17 E4 P4 P16
---White(^)---
R4  : T   2.88c W   2.59c S   0.29c ( +0.9) LCB    2.18c P 13.38% WF  7.81% PSV     161 N     161  --  R4 C4 D17 E4 P4 P16
Q3  : T   2.88c W   2.58c S   0.30c ( +0.9) LCB    2.17c P 12.85% WF  7.81% PSV     155 N     155  --  Q3 C4 D17 P16 Q5 E4
C4  : T   2.80c W   2.52c S   0.28c ( +0.9) LCB    2.08c P 12.62% WF  7.79% PSV     149 N     149  --  C4 C16 Q3 E16 Q5 P16 E4
D17 : T   2.69c W   2.43c S   0.27c ( +0.8) LCB    2.00c P 12.16% WF  7.77% PSV     139 N     139  --  D17 Q3 C4 P16 D15 Q5
D3  : T   2.83c W   2.55c S   0.29c ( +0.9) LCB    2.12c P 11.36% WF  7.80% PSV     135 N     135  --  D3 D17 R4 D15 P4 C5
C16 : T   2.83c W   2.54c S   0.29c ( +0.9) LCB    2.03c P 11.29% WF  7.80% PSV     135 N     135  --  C16 Q3 C4 P16 E4 Q5
D4  : T   2.23c W   2.09c S   0.14c ( +0.6) LCB    0.56c P  3.97% WF  7.69% PSV      39 N      39  --  D4 C16 R4 E16 P4
Q4  : T   1.81c W   1.73c S   0.09c ( +0.5) LCB    0.49c P  3.49% WF  7.62% PSV      30 N      30  --  Q4 C16 C4 P16
D16 : T   1.81c W   1.74c S   0.07c ( +0.5) LCB    0.13c P  3.48% WF  7.62% PSV      30 N      30  --  D16 C4 Q3 E4
Q16 : T   2.06c W   1.97c S   0.09c ( +0.5) LCB   -5.73c P  0.95% WF  7.69% PSV       8 N       8  --  Q16 Q17 R15 R17 D3

= C4
```
The "chat comment" says `CHAT:Visits 1003 Winrate 51.22% ScoreMean 0.8 ScoreStdev 32.1 PV C4 C16 Q3 E16 Q5 P16 E4` so I understand that `C4` has a 51.22% winrate.
Then there is this line for C4: `C4  : T   2.80c W   2.52c S   0.28c ( +0.9) LCB    2.08c P 12.62% WF  7.79% PSV     149 N     149  --  C4 C16 Q3 E16 Q5 P16 E4` so an utility of 2.80, when adusted to a 0~100% should be `2.80/2+50=41.40%` am I right? or is my calculation wrong @lightvector  ? it is not exactly the same value as above.

**Comment by kennychenfs** [comment]
The chat comment shows the root's utilities and R4 is one of the node, so they are surely a little different.

**Comment by pnprog** [comment]
@kennychenfs that was a fast reply :)

**Comment by pnprog** [comment]
So after a look at the code, here is what I can find:

+ T: utility * 100
+ W: resultUtility * 100
+ S: scoreUtility * 100 ( in parenthesis: scoreMean )
+ LCB: lcb * 100 <- cannot find what this lcb is about
+ P: policyPrior * 100
+ WF: weightFactor * 100
+ PSV: playSelectionValue
+ N: numVisits

Also, I am not sure why in the exemple above, Katago would play C4 when R4 seems a better move.
