### ISSUE TITLE
为什么卡塔狗和绝艺，针对胜负的判定不同？

### ISSUE THREAD

**Issue by 1067511899** [lightvector/KataGo#816]
![image](https://github.com/lightvector/KataGo/assets/21253207/c3ffd81b-b254-4682-bda9-893e034bfde3)
![image](https://github.com/lightvector/KataGo/assets/21253207/6687882b-ee22-4839-8b25-f0e14d0007a1)
![image](https://github.com/lightvector/KataGo/assets/21253207/8ac30df3-5464-4403-93d0-d6827517c614)
![image](https://github.com/lightvector/KataGo/assets/21253207/e4b102b9-88f8-4d9b-add0-4fda2e3065ed)

您好，这是今天下午举行的昌棋杯比赛，王星昊vs柯洁。最后的局面，按照绝艺的判定是白好，但是使用卡塔狗分析，结果却是黑好，请问这个是不是我的电脑的计算力不够的原因？还是配置文件的问题？谢谢。
[[柯洁]vs[王星昊]16891489820100014901.zip](https://github.com/lightvector/KataGo/files/12026062/vs.16891489820100014901.zip)

**Comment by jianghaochen14** [comment]
这个比赛采用的是应氏规则黑棋贴8点柯洁还被延时罚点了，而且你的计算量太低了！

**Comment by 1067511899** [comment]
> 这个比赛采用的是应氏规则黑棋贴8点柯洁还被延时罚点了，而且你的计算量太低了！

我用lizzieyzy或者katrain（最新版exe文件）摆一下看看，都是五五开的样子，个人觉得8点和7.5目差别不大。另外，这个和罚点没有关系，而是最后黑大龙死了。我按照推荐走了几步以后，胜率就急转直下，黑死了几十目。就是说，按照推荐，怎么走怎么死，但是只有走了之后才能计算到，而没走之前胜率基本五五开，走了几步一选之后，胜率就崩了。
另外，您可以看到，野狐用的也是中国规则，贴7.5目。当然我不确定绝艺在计算的时候是否也是用中国规则，贴7.5目。

最主要的是，这种情况我从未遇到过，以前胜率虽然有差别（和绝艺以及其他AI从来没有一样过——这可以理解），但是胜负没有差别。但是现在胜负都有差别了。有意思的是，我在看棋的时候，看到有人说，他使用星阵，最后也是黑优。

所以提个issue，想看看是否哪里不对？如果您有高性能GPU，能摆一下后续嘛？谢谢。

**Comment by 1067511899** [comment]
![image](https://github.com/lightvector/KataGo/assets/21253207/33d62bf3-9ba7-4b20-837d-8ba24f453f63)
好吧，看来是我的计算量不够，不过这个计算量也太夸张了吧？

**Comment by 1067511899** [comment]
![image](https://github.com/lightvector/KataGo/assets/21253207/fcb3965d-6d5a-4126-8ed6-b3a686c7a75f)
好吧，看来是我的计算量不够，不过这个计算量也太夸张了吧。

**Comment by 1067511899** [comment]
![QQ图片20230714001745](https://github.com/lightvector/KataGo/assets/21253207/87114fbe-8b59-4ae5-ad37-6b9b32707796)
![Sabaki_6Ctyp17UEz](https://github.com/lightvector/KataGo/assets/21253207/ea54219a-4f5e-4e59-be3d-dacb902d26a9)
![QQͼƬ20230713212754](https://github.com/lightvector/KataGo/assets/21253207/9113dd9d-2eb8-41aa-b2f8-23071f98e5eb)
![QQͼƬ20230713221053](https://github.com/lightvector/KataGo/assets/21253207/e6965c63-e62c-4392-8963-71ca6abc6140)
我请了其他网友做了对比，发现18b权重需要极大的计算量，才能判断出黑不行了。而60b的权重，需要很少的计算量就可以判断出来。
具体到底什么情况就不知道了。

**Comment by michito744** [comment]
To begin with, 8 points is not an accurate final score prediction.

If we play correctly from the first diagram, the 17 white stones on the right side will eventually be taken by black, and all the black stones in the center will be taken by white instead. It will take more than 30 moves to reach that situation, and it is assumed that white will win the ko.

What FineArt shows is a midway report of the likelihood of convergence to that phase, and it is only an average score with a mixture of positions where White plays correctly and wins by 40 points or more and other positions.

Still, it is far better than the prediction that KataGo-18b shows with the same amount of time spent, so the average score and evaluation values are heavily biased in favor of White.

* The black M3 is simply a horizon effect and is completely meaningless.

**Comment by 1067511899** [comment]
> To begin with, 8 points is not an accurate final score prediction.
> 
> If we play correctly from the first diagram, the 17 white stones on the right side will eventually be taken by black, and all the black stones in the center will be taken by white instead. It will take more than 30 moves to reach that situation, and it is assumed that white will win the ko.
> 
> What FineArt shows is a midway report of the likelihood of convergence to that phase, and it is only an average score with a mixture of positions where White plays correctly and wins by 40 points or more and other positions.
> 
> Still, it is far better than the prediction that KataGo-18b shows with the same amount of time spent, so the average score and evaluation values are heavily biased in favor of White.
> 
> * The black M3 is simply a horizon effect and is completely meaningless.

You are right,and even the 60b is better than 18b,so I go back and use 60b again.
