### ISSUE TITLE
Data format in SGF files?

### ISSUE THREAD

**Issue by jiacheng-ye** [lightvector/KataGo#834]
Hi, thanks for the great work.
I have two questions related to the SGF files and self-play training.

First, I'm wondering what's the values means after each move in the SGF files from https://katagoarchive.org/kata1/traininggames/index.html. 

For example, what is `C[0.10 0.90 0.00 -12.9 v=1500 weight=1.20]`  means for the move [jp]:
```
B[jp]C[0.10 0.90 0.00 -12.9 v=1500 weight=1.20];W[hp]C[0.08 0.92 0.00 -13.8 v=1109 weight=0.59];B[lq]C[0.09 0.91 0.00 -13.5 v=813 weight=0.46];W[lp]C[0.08 0.92 0.00 -14.3 v=421 weight=0.00];B[iq]C[0.10 0.90 0.00 -12.9 v=250 weight=0.15];W[hq]C[0.09 0.91 0.00 -13.5 v=250 weight=0.00]
```

Second, in my views, one should use the whole mcts distribution over all the moves in the self-play process, which seems not reflected in this game data, e.g., we only have a single top-1 label for each move here.
So how can `C[0.10 0.90 0.00 -12.9 v=1500 weight=1.20]` be used in the policy network training?

Thanks for your help in advance.

**Comment by lightvector** [comment]
Thanks good question, I've updated the README at https://katagoarchive.org/kata1/index.html to be more clear, please take a look! :)
The first four unlabeled values are predicted white win prob, black win prob, no-result prob, expected score. 
The SGF files are only for convenient human viewing, you're supposed to look at the trainingdata folder if you want the detailed training data.

**Comment by jiacheng-ye** [comment]
Thanks a lot!
