### ISSUE TITLE
Draw game with x.5 komi?

### ISSUE THREAD

**Issue by akdtg** [lightvector/KataGo#838]
I wonder why the results of rating games like these are counted as draws although komi isn't an integer?

https://katagotraining.org/sgfplayer/rating-games/1046078/
https://katagotraining.org/sgfplayer/rating-games/1047513/
https://katagotraining.org/sgfplayer/rating-games/1046622/

**Comment by OmnipotentEntity** [comment]
They are button games.

>  Button: Whether a half-point is awarded to the first player to be able to pass. (e.g. slightly rewarding endgame efficiency, partially reconciling area and territory scoring).

**Comment by akdtg** [comment]
I've never heard about such rule, thank you for the explanation.
