### ISSUE TITLE
KataGov1.2 do not support CUDA 10.2

### ISSUE THREAD

**Issue by ivysrono** [lightvector/KataGo#84]
10.1 is 🆗

**Comment by l1t1** [comment]
what is the error message

**Comment by lightvector** [comment]
There is also nothing tricky or special that KataGo does with CUDA - it only calls pretty standard and basic functions that are unlikely to change between versions. I have KataGo working on CUDA 10.2 perfectly fine on Ubuntu Linux on a cloud machine. Perhaps you did not install or upgrade CUDA correctly?

**Comment by ivysrono** [comment]
Windows 10 x64

**Comment by lightvector** [comment]
Hmmm. And what's the error message?

Possibly the pre-built executables would have to be recompiled, although I expect that they would work directly after a recompile without any changes to the source. If that's the case, then I'll do it next release closer to the end of this year.

**Comment by lightvector** [comment]
Oh, wait, I'm not actually providing any CUDA executables for Windows, only OpenCL. So I assume you're building from source yourself? In that case, yes, what error messages are you getting? Does it work if you do a full clean and rebuild?

**Comment by petgo3** [comment]
As far as i know kata runs for me on win 10 cuda.

**Comment by ivysrono** [comment]
![图片](https://user-images.githubusercontent.com/2649544/69495647-31eb2000-0f04-11ea-91ad-7e7e9825c99c.png)
` I'm not actually providing any CUDA executables for Windows`???

**Comment by lightvector** [comment]
Oh, I am. Haha, sorry, yeah I added that one later separately from the others at someone else's request. Yes, okay then it might not work until a recompile, which I'll handle next release.

**Comment by ivysrono** [comment]
![图片](https://user-images.githubusercontent.com/2649544/69495831-5647fc00-0f06-11ea-824a-e61b5e784aa6.png)
![图片](https://user-images.githubusercontent.com/2649544/69495833-5ba54680-0f06-11ea-8309-cd4ce63fdfad.png)
cuda_10.2.89_win10 + cudnn-10.2-windows10-x64-v7.6.5.32

**Comment by lightvector** [comment]
What happens if you run it directly on the command line? _None_ of the GUI engines gives any reliable error messages compared to running it directly.

**Comment by ivysrono** [comment]
I have back to 10.1……

**Comment by lightvector** [comment]
Sure, no problem. You can notice how none of the GUI programs tell you what the error is, right? They just say that they could not run the engine, but they do NOT actually say what error exactly they encountered when they attempted to run the engine. Please just keep in mind for the future.

**Comment by apetresc** [comment]
I can confirm that KataGo 1.3+ works just fine with CUDA 10.2 and cuDNN 7.6.5. Just used the latest binary release directly without any issues.

Perhaps the README can be updated to reflect that.

**Comment by ivysrono** [comment]
win10 + 1.3.1 
confirm this issue.

**Comment by apetresc** [comment]
> win10 + 1.3.1
> confirm this issue.

Are you saying you still experience the issue even with 1.3.1? Or you're confirming my experience that it does work now?

**Comment by ivysrono** [comment]
> 
> 
> > win10 + 1.3.1
> > confirm this issue.
> 
I still experience the issue even with 1.3.1

**Comment by apetresc** [comment]
Ah, strange. Then I suspect it's related to something specific to your setup, not broad KataGo incompatibility with CUDA 10.2, seeing as several of us have it running that way successfully without any changes.

Can you try running katago.exe from the command line and pasting the error you get? As @lightvector suggested earlier, this will give a much more informative diagnostic message than what Sabaki shows.

**Comment by ivysrono** [comment]
10.1：working
![图片](https://user-images.githubusercontent.com/2649544/73934082-b4d32280-4918-11ea-8e00-ee0403ead3ab.png)
10.2：end itself.
![图片](https://user-images.githubusercontent.com/2649544/73934715-f9ab8900-4919-11ea-8d8a-e85443ef405a.png)

**Comment by ivysrono** [comment]
Sorry, my stupid mistake, KataGo support 10.2.
