### ISSUE TITLE
I want to train a katago starting from 0, specifying rules such as 2 moves in a row, and training mainly 11 way boards. Is there any introductory tutorial for newbies（我想训练一个从0开始的katago，指定规则，比如连下2步，主要训练11路棋盘。有没有适合新手的入门教程）

### ISSUE THREAD

**Issue by awsjgy** [lightvector/KataGo#846]
我是一个入门编程新手，没看到从0训练katago的视频，谁能做一个手把手的炼丹从0训练katago ai的教程，对新手友好的
我想训练一个连下2步的katago，在11路棋盘上。因为中国野狐围棋平台，有个飞刀游戏，支持连下2步，他虽然有运气成分，但是实力是关键。因为我看到很多人会玩的，可以连胜一二十盘
对此这个飞刀游戏，还有升降级，比如最高等级刀神>刀仙>刀圣，我最高能打到刀仙，站不稳，很快就掉了。

希望能有人能帮我教我如何训练一个从0开始的katago，vx：wsjgya

I'm a newbie to introductory programming and haven't seen any videos on training katago from 0. Can someone do a hands on alchemy training katago ai from 0 tutorial that's newbie friendly!
I want to train a katago that plays 2 moves in a row, on an 11 way board. Because the Chinese Wildfox Go platform, has a flying dagger game that supports 2 moves in a row, he has luck involved, but strength is key. Because I see a lot of people who can play, can win 20 games in a row!
To this flying dagger game, there is a rise and fall, for example, the highest level of knife God > knife immortal > knife saint, I can hit the highest knife immortal, stand unsteady, quickly fell.

**Comment by awsjgy** [comment]
katago is strong and more applicable to home use than alphago. But katago is no longer as strong and no longer as helpful to humans. How about not being able to outperform katago or come close.
From the time katago surpassed humans, the help to humans was already maximized

What I'm thinking about is if we can really gear katago towards the average hobbyist or novice programmer. Like come out with a tutorial to train katago from 0 onwards

The Chinese Wildfox Go platform has the most Go players in the world and at the highest level, with tens of thousands of people online every day. There are tens of thousands of people online every day, including China, Japan, and Korea.
Many people outside of China don't realize that there is another way to play Go, called the Flying Dagger Game. This game was developed by Tencent in China in January of the previous year and has been around for almost 3 years. If it wasn't fun, it wouldn't be for professional players, and the game has been iterated and updated until now. The game has been updated from a 9-way board at the beginning to an 11-way board now. And it already supports elevated play. This game is also not purely just luck, otherwise there could not be elevation, and someone who can play can win more than 10 to 20 games in a row. Even people with a high rank can achieve this win rate.
I myself have played this game, I was not very good at first and always lost, but later on I was able to play and started to get stronger. This game is fun and skillful. It requires calculation, and although there is an element of luck, there is a certain range of luck that can be controlled and predicted by a player with a certain level of skill and experience. People outside of China are less likely to play it, and laymen may think it's pure luck, but only insiders know it has something to do with calculation.

I'm new to programming, and I can't even train katago from 0, let alone train katago in 2 moves. I've tried to get programmers to take orders and pay for this game, but at 10,000 RMB, it's unnecessarily expensive. Algorithms are needed. But I know this game can be realized by modifying the code algorithm. Because someone in China has done katago under different rules before, I think it's interesting, in order to study the game? And it can also develop intelligence. https://zhuanlan.zhihu.com/p/476301916可以参考这个链接 train a katago with different rules to reach beyond human chess power. hzyhhzy's project There is open source on github, made a lot of katago with different rules. project address https://github.com/hzyhhzy/KataGo/tree/LifeGo2



katago很强，比alphago更加适用于家用。但是katago再强，对人类帮助已经没有那么大。怎么样都不可能超越katago或接近。
从katago超越人类的时候开始，对人类帮助就已经最大化了

我想的是能不能把katago真正面向普通爱好者或者编程新手。比如出一个从0开始训练katago的教程

中国野狐围棋平台是世界上围棋棋手最多，而且水平最高的平台，每天有几万人在线。包括中国、日本、韩国。
除中国以外很多人不知道围棋还有个玩法，叫做飞刀游戏。这个游戏是由中国腾讯公司开发，于前年一月份到现在，已经将近3年，经久不衰。这个游戏要是不好玩，不至于职业棋手，这个玩法不断迭代更新到现在。从一开始的9路棋盘，到现在的11路棋盘。而且已经支持升降级的玩法。这个游戏也不纯粹只是运气，否则不可能出现升降级，而且有人会玩的可以连胜10多盘到20盘。哪怕等级高的人也可以达到这个胜率。
我本人也玩过这个游戏，一开始不太会玩，总是输，到后面会玩，开始变强。这个游戏的趣味性很强，而且很有技巧。需要计算，虽然有运气成分，但是这个运气成分一定范围能被有一定棋力和经验的棋手所控制和预测。除中国以外的人，不太会玩，外行人可能觉得纯粹是运气，但是内行人才知道这个跟计算有关系。

本人是编程新手，连从0训练katago都不会，更别说训练2步的katago了。我也曾经想让程序员接单，付费这个游戏，但是要万把元人民币，没必要划不来。需要算法。但是我知道这个游戏可以通过修改代码算法来实现。因为之前中国有人做过不同规则下的katago，我觉得这很有趣，为了研究游戏吗，而且也能开发智力。https://zhuanlan.zhihu.com/p/476301916可以参考这个链接，训练一个不同规则的katago达到超越人类的棋力。hzyhhzy的项目在github上有开源，做了很多不同规则的katago。项目地址https://github.com/hzyhhzy/KataGo/tree/LifeGo2

**Comment by awsjgy** [comment]
This flying dagger game is played by people every day, and he plays it more easily than the normal 19-way board. To make an analogy, this 11-way flying dagger game, the user can play one or two dozen consecutive games at a time without feeling tired, this is not just by luck, he has the strength of the calculation of the ingredients in it!

So than the normal rules of Go sometimes fun, you can relieve boredom, the kind of game can be like a flying dagger game can grasp the luck just right to control the gameplay is not much. Many games are unplayable because they are too random and completely random. But this one can be manually interfered with to

This flying dagger game is played by people every day, and he plays it more easily than the normal 19-way board. To make an analogy, this 11-way flying dagger game, the user can play one or two dozen consecutive games at a time without feeling tired, this is not just by luck, he has the strength of the calculation of the ingredients in it!

So than the normal rules of Go sometimes fun, you can relieve boredom, the kind of game can be like a flying dagger game can grasp the luck just right to control the gameplay is not much. Many games are unplayable because they are too random and completely random. But this one can be manually interfered with to

This flying dagger ai is not hard to say, not easy to say. Difficult in that it requires algorithms and involves luck. Easy is as long as the design to the algorithm and rules. You don't need to do a lot of math like normal go rules to reach a level beyond human, not to mention 11 ways. I'm sure with good training it would be hard for a human to win a game even with bad luck.
这个飞刀游戏天天有人玩，他比正常的19路棋盘玩起来更轻松。打个比方，这种11路飞刀游戏，用户一次可以连续玩一二十盘，都不感觉到累，这不是仅仅靠运气，他是有实力的计算成分在里面的

所以比正常规则的围棋有时候好玩，可以解解闷，那种能像飞刀游戏一样能把握运气恰如其分到可以控制的玩法不多了。很多游戏因为随机性太强，而无法玩下去，完全随机。但是这个可以人工干预到

这个飞刀ai说难不难，说容易不容易。难在要算法，而且涉及到运气。容易在于只要设计到了算法和规则。不需要像正常围棋规则一样算很多计算量就可以达到一个超越人类的水平，何况是11路。我相信如果训练的好，哪怕运气再差，人类也很难赢一盘。

**Comment by lightvector** [comment]
I think you already have two open issues at https://github.com/lightvector/KataGo/issues/839 and https://github.com/lightvector/KataGo/issues/844 that discusses the same topic. Please don't keep opening more issues about the exact same topic, you can just post in the same issues you already had open. I'll go ahead and close this one since it redundant.

**Comment by awsjgy** [comment]
> 我认为您在 #[839](https://github.com/lightvector/KataGo/issues/839) 和 #844 中已经有两个讨论同一主题的未决问题。请不要继续打开有关完全相同主题的更多问题，您可以只发布您已经打开的相同问题。我会继续关闭这个，因为它是多余的。

Okay. Okay.
好的，好的
