### ISSUE TITLE
Probably) Fatal overfitting

### ISSUE THREAD

**Issue by michito744** [lightvector/KataGo#87]
This phenomenon is presumed to be overfitting.

The g104-b20c256 network is beautiful and practical,
 but it often causes false searches due to inaccurate policies.

1_CompletelyMissed
![1_CompletelyMissed_2019-12-05](https://user-images.githubusercontent.com/53891655/70226988-282fab00-1795-11ea-99d9-b9228c3e8dab.png)
2_TooLowToOpenCorrectNode
![2_TooLowToOpenCorrectNode_2019-12-05](https://user-images.githubusercontent.com/53891655/70227003-2ebe2280-1795-11ea-97b3-925c224c5bf3.png)
3_IfRootThenRight
![3_IfRootThenRight_2019-12-05](https://user-images.githubusercontent.com/53891655/70227014-32ea4000-1795-11ea-8cf1-fa74caab9e1b.png)
4_B2isCompletelyRight
![4_B2IsCompletelyRight_2019-12-05](https://user-images.githubusercontent.com/53891655/70227018-37165d80-1795-11ea-8b9a-f1096c36795b.png)
5_ResultofOpeningNode
![5_ResultOfOpeningNode_2019-12-05](https://user-images.githubusercontent.com/53891655/70227025-3aa9e480-1795-11ea-97fd-0d5ed4269bc2.png)
6_PolicyisPerfectlyBad
![6_PolicyIsPerfectlyBad_2019-12-05](https://user-images.githubusercontent.com/53891655/70227040-41385c00-1795-11ea-9cf7-a23a6fcf7c56.png)

**Comment by lightvector** [comment]
Thanks.

Keep in mind: if you take two different similar-strength bots and play them against each other, in *every* game one of them will win, due to the other's mistakes - they can't both win! And a decent fraction of the time, it will be also because one of them missed a move that the other one saw that caused a sudden change in evaluation - so the general kind of situation is not actually that rare for any bot, unfortunately, although the exact positions may vary between bot. It's a continued thing being worked on.

**Comment by michito744** [comment]
Thank you very much.

When testing Hatsuyoron120, I found a clear improvement in overfitting.
It is unstable to use for games(*), but I expect future development.

*When Hatsuyoron120 was played against LZ254, the stone shape of katago collapsed.

1_Hatsuyoron120 succeeded correct search. (Compare with the above)
![SuccessfulSearch_2019-12-11](https://user-images.githubusercontent.com/53891655/70621543-31b98700-1c5d-11ea-8c3d-0ea979bd35f2.png)
2_Hatsuyoron120 discovered correct move. (Not found in the official version)
![DiscoveredCorrectMove_2019-12-11](https://user-images.githubusercontent.com/53891655/70621684-7f35f400-1c5d-11ea-9298-2e3cb2f7c87e.png)
3_Hatsuyoron120 can find correct move faster than official version. (I think that further improvements are needed)
![CanFindCorrectMoveThanOfficialVer_2019-12-11](https://user-images.githubusercontent.com/53891655/70621734-970d7800-1c5d-11ea-9591-b5b267e4a6b4.png)

**Comment by lightvector** [comment]
I've noted this test position. I don't think there's much to do here but train a network much more. Closing this for now, but if you would like to send me an SGF file, I'll include it in my personal set of test positions to that I test from time to time on KataGo versions as I develop them.
