### ISSUE TITLE
katago 1.14.0 TRT plan cache boots significantly slower than 1.13.2

### ISSUE THREAD

**Issue by kinfkong** [lightvector/KataGo#879]
Here is the testing environments for comparing the booting time for 1.13.2 and 1.14.0 when hitting the plan cache (That means the plan cache files already exist).

For 1.13.2: using TensorRT 8.5.2
For 1.14.0: using TensorRT 8.6.1
The  loading weight is: 18b

In a 5 cards of RTX3080 machine, it takes **40 seconds** for 1.14.0 to boot to GTP ready, while 1.13.2 just need **17 seconds**
In a 8 cards of RTX4070 machine, it takes **63 seconds** for 1.14.0 to boot to GTP ready, while 1.13.2 just need **26 seconds**.

I also try with different weights and different machines, 1.14.0 is generally boots much slower than 1.13.2

Have you @lightvector or @hyln9 observed this? Thanks!

**Comment by hyln9** [comment]
I do not currently have access to these GPUs.

Could you please try commenting out [this line](https://github.com/lightvector/KataGo/blob/c6de1bbda837a0717eaeca46102f7326ed0da0d4/cpp/neuralnet/trtbackend.cpp#L999) and see if it makes a difference?

Otherwise it might be a bug in TensorRT itself.

**Comment by kinfkong** [comment]
[1.13-trt8.5-benchmark.txt](https://github.com/lightvector/KataGo/files/13805262/1.13-trt8.5-benchmark.txt)
[1.14-trt8.6-benchmark.txt](https://github.com/lightvector/KataGo/files/13805263/1.14-trt8.6-benchmark.txt)

@hyln9 
1. Commenting out that line does not help. Commenting that line out or not ,does not affect the boot time, they are the same.
2. I attached the benchmark log for katago1.13+trt8.5 and katago1.14+trt8.6. benchmark log shows more details, and you can check the timestamps in the log to check if there are any hints? thanks.
3. The benchmark also shows there is a about 10% performance drop in 1.14.

Maybe the trt 8.6 itself causes that: 1). cost more time to start katago. 2). katago benchmark is worse in trt 8.6.

cc: @lightvector

**Comment by kinfkong** [comment]
[1.14-trt8.5-benchmark.txt](https://github.com/lightvector/KataGo/files/13805445/1.14-trt8.5-benchmark.txt)
I slightly modify the code to make 1.14 to comapitable with trt 8.5. Here is the benchmark log. 
Everything seems fine running katago 1.14 in trt 8.5

I am not sure if trt 8.5's issue, or my environment causes. if anyone else can observer that the bechmark or boot time becomes slower, I suggest we should make 1.14 can run in trt 8.5

so, I make a pr for this purpose: 
https://github.com/lightvector/KataGo/pull/880

**Comment by hyln9** [comment]
Do you have single GPU performance numbers? And what's your CUDA version?

Anyway I'll submit a proper patch for TensorRT 8.5 compatibility very soon.

**Comment by kinfkong** [comment]
[1.14-trt-8.5-single-RTX3060Laptop-benchmark.txt](https://github.com/lightvector/KataGo/files/13805987/1.14-trt-8.5-single-RTX3060Laptop-benchmark.txt)
[1.14-trt-8.6-single-RTX3060Laptop-benchmark.txt](https://github.com/lightvector/KataGo/files/13805989/1.14-trt-8.6-single-RTX3060Laptop-benchmark.txt)

Now I use a much weaker machine which has only a single RTX 3060 Laptop GPU.

The benchmark shows v/s or nn/s are almost close, but the loading time, trt 8.6 still slower than 8.5 (7 seconds vs 4 seconds)

The environment is:
ubuntu 22.04
cuda 12.1 (both for running and compiling)

**Comment by hyln9** [comment]
I've submitted the patch.

In the meantime, you can build KataGo with TensorRT 9.2 (available [here](https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/9.2.0/tensorrt-9.2.0.5.linux.x86_64-gnu.cuda-12.2.tar.gz) instead of the website), which fixes the problem and improves performance and compatibility.

**Comment by TTXS123OK** [comment]
> Here is the testing environments for comparing the booting time for 1.13.2 and 1.14.0 when hitting the plan cache (That means the plan cache files already exist).
> 
> For 1.13.2: using TensorRT 8.5.2 For 1.14.0: using TensorRT 8.6.1 The loading weight is: 18b
> 
> In a 5 cards of RTX3080 machine, it takes **40 seconds** for 1.14.0 to boot to GTP ready, while 1.13.2 just need **17 seconds** In a 8 cards of RTX4070 machine, it takes **63 seconds** for 1.14.0 to boot to GTP ready, while 1.13.2 just need **26 seconds**.
> 
> I also try with different weights and different machines, 1.14.0 is generally boots much slower than 1.13.2
> 
> Have you @lightvector or @hyln9 observed this? Thanks!

I also tested katago-1.13.2 and katago-1.14 on trt-8.6.1 in my environment. However, I found no significant difference between 1.13.2 and 1.14. They both take about 18-20 seconds from boot to GTP ready.

Anyway, thanks to @hyln9 for the pr compating trt-8.5 for current main branch.  #[https://github.com/lightvector/KataGo/pull/882](url)

My environment:
1 card 2080Ti
ubuntu 20.04
cuda 12.0

loading weight:18b
katago-1.13.2 git version: 48ec6e7769a4f4992a06edb8af46b4e91f142b72
katago-1.14.2 git version: 4334a0f77ba4a42caf16a3848acef6041540f3e9
using katago config generated by `./katago genconfig -model 18b.bin.gz' with default options

**Comment by kinfkong** [comment]
@TTXS123OK are you testing using plan cache or timing cache?
