### ISSUE TITLE
error CL_PLATFORM_NOT_FOUND_KHR

### ISSUE THREAD

**Issue by HeibaiPanda** [lightvector/KataGo#89]
KataGo doesn't work on my computer.Please,I need help.

KataGo v1.2
terminate called after throwing an instance of 'StringError'
  what():  OpenCL error at /home/dwugcloud/data/kata/cpp/neuralnet/openclhelpers.cpp, func err, line 188, error CL_PLATFORM_NOT_FOUND_KHR

My CPU is AMD A8-7650K.It contains an integrated GPU Radeon R7

**Comment by lightvector** [comment]
It sounds like you don't have OpenCL support on your integrated GPU. If you've Googled online and your GPU is supposed to support OpenCL, then you will need to try updating your drivers, and figure out if you need to specially install something to get support. Try making sure other OpenCL demos work, that or Leela Zero OpenCL GPU version works for you first. Comment back if you've tried all those things and you are sure that OpenCL is working properly but are still getting this error.

**Comment by HeibaiPanda** [comment]
Thanks for your response.
You are right.After installing mesa-opencl-icd it works.
Now I can learn Go by using this fantastic tool.
Thank your work on this project.It really helps me a lot.
