### ISSUE TITLE
Question about mapping between moveInfo and analyzeTurns

### ISSUE THREAD

**Issue by zhongwang97** [lightvector/KataGo#893]
Not sure I'm getting meaning of `analyzeTurns` wrong.
If I specify more than one value in the `analyzeTurns` in the request, how can I know which turn corresponds to each moveInfo in the response?
It looks like each moveinfo should contain a `turnNumber` field indicating that it is the analyzing result of a certain turn, but right now there is only one `turnNumber` in the whole response.
Thank you

**Comment by lightvector** [comment]
There will be more than one whole response, one for each turn.

**Comment by zhongwang97** [comment]
OK got it thank you
