### ISSUE TITLE
Question of compatability

### ISSUE THREAD

**Issue by Lecale** [lightvector/KataGo#9]
Perhaps it is already explained somewhere, so I apologise if I missed it. Is it possible to use KataGo with something like Lizzie, by transporting the weights file over to the installation folder?
I find your project interesting, but I don't have a c++ compiler.

**Comment by alreadydone** [comment]
KataGo weights file can only be read by the KataGo engine, not by the Leela Zero engine. The KataGo engine now also supports Lizzie. If you are on Windows, use the compile binaries at https://github.com/lightvector/KataGo/issues/2.

**Comment by lightvector** [comment]
Leaving #2 open as sort of documentation on Windows usage until I can get all-around better usability and support implemented, but going ahead and closing this, as this seems handled.

Seems MinGW for compiling to Windows can work with OpenCL, so once we also expand greatly what GPUs are supported via OpenCL and drop the necessity of dependence on CUDA, having precompiled binaries should suddenly become a lot easier too.
