### ISSUE TITLE
Lower CMake version requirement

### ISSUE THREAD

**Issue by gslin** [lightvector/KataGo#92]
I tried to build KataGo on Ubuntu 18.04, and CMake in the official apt repository is 3.10.2 (ref: https://packages.ubuntu.com/search?keywords=cmake) so KataGo will refuse to start building.

I just decrease version number requirement inside `CMakeLists.txt` from:

    cmake_minimum_required(VERSION 3.12.3)

to:

    cmake_minimum_required(VERSION 3.10.2)

And it works fine, so maybe we can lower requirement of CMake, which will help Linux users to build it much easier.

**Comment by lightvector** [comment]
Thank you. I'll make this change.

**Comment by JBX2010** [comment]
This would be very helpful for a lot people. I have spent a lot time on upgrading the CMake everytime.

**Comment by lightvector** [comment]
Done. https://github.com/lightvector/KataGo/pull/96/commits/bf7e414a0257bbeaa253470e25ef86c98bfaec9c
Which is part of the new 1.3 release.
