### ISSUE TITLE
A question about moves not being buffed by LCB

### ISSUE THREAD

**Issue by sbbdms** [lightvector/KataGo#920]
Hi.

I observed a strange output when running KataGo with little modification:
B9  : LCB  -23.32c P  7.72% WF 96117.8 PSV  212360 N  456337  --  B9 B10 C8 C7 L13 M12 B7 C9
B8  : LCB   -5.79c P  8.86% WF 36150.3 PSV   29430 N   59962  --  B8 B9 A9 B10 L13 M12 L14 S16
L13 : LCB  -55.93c P 19.19% WF 1109.4 PSV    1966 N    3533  --  L13 M12 B9 B10 J5 F5 C8 C7
J5  : LCB  -52.61c P  5.08% WF 444.2 PSV     621 N    1046  --  J5 F5 B8 B9 A9 B10 L13 M12
N10 : LCB -117.57c P 13.34% WF 167.5 PSV     457 N     691  --  N10 N11 J5 F5 L13 M12 B7 G17
G17 : LCB -108.96c P  8.29% WF 135.6 PSV     322 N     490  --  G17 G18 L13 M12 L14 H17 P13 O13
S17 : LCB -134.94c P  6.76% WF  78.5 PSV     205 N     272  --  S17 R17 J5 H6 S19 R19 G5 F5
S16 : LCB  -98.79c P  4.30% WF  99.9 PSV     198 N     300  --  S16 S17 J5 F5 S15 R17 L13 M12
E17 : LCB -167.36c P  5.74% WF  44.5 PSV     130 N     168  --  E17 G17 L13 M12 D18 M18 L14 S16
B7  : LCB  -82.58c P  1.92% WF  79.1 PSV     125 N     200  --  B7 G17 B9 B10 B13 C13 A10 B11

I was using the default value of minVisitPropForLCB and lcbStdevs.
It seems that B8 has a better LCB utility than B9, and B8's weight is more than 0.15 times of B9's (Which is threshold by the default minVisitPropForLCB). However B8 isn't buffed by LCB, on the contrary, its playSelectionValue gets lower, meanwhile other moves get higher playSelectionValues.
I checked the code of the function getPlaySelectionValues(), and I couldn't find out what caused this result.

Could you give analysis that what caused it?
Thanks!

**Comment by lightvector** [comment]
Hi @sbbdms - I looked at this and I also find this result surprising. I'm not sure how it would happen - do have the game position that this occurred on, and can you send it to me? If you repeatedly run the search a few times on this position, do you ever observe this happening again?

**Comment by sbbdms** [comment]
@lightvector 

Hi.
Recently I read the code again and I might found the reason.
The formula in the code is:

> weight >= searchParams.minVisitPropForLCB * nonLCBBestChildWeight

It is _nonLCBBestChildWeight_ that multiplies minVisitPropForLCB.
However, after _nonLCBBestChildWeight_ is set, the value in _weight_ (For other indexes which are not nonLCBBestIdx) will be reduced by getReducedPlaySelectionWeight(). After that it is stored in _playSelectionValues[]_ array but not the _weight_ variable. So that might be the case, I should refer the PSV output to judge which move should be buffed by LCB, but not the WF.
