### ISSUE TITLE
throwing an instance of 'StringError'

### ISSUE THREAD

**Issue by wave2006** [lightvector/KataGo#93]
i had downloaded the neural nets,but the error occured when i tried to start KataGo.

terminate called after throwing an instance of 'StringError'
what():  Dummy neural net backend: NeuralNet::loadModelFile unimplemented

**Comment by lightvector** [comment]
You've compiled without specifying whether to use CUDA or OpenCL. The cmakefile should have output a big warning message to this effect when you first configured the project for building.

**Comment by lightvector** [comment]
Basically, you have to pick one of the backends to use. Otherwise you get a dummy backend that supports some testing, but cannot actually run a neural net or load the model file.

**Comment by wave2006** [comment]
> Basically, you have to pick one of the backends to use. Otherwise you get a dummy backend that supports some testing, but cannot actually run a neural net or load the model file.

Thank  you@lightvector  very much for your reply. After recompilation, I have solved this problem perfectly. And wish you a happy new year!
