### ISSUE TITLE
Where can I see the latest achievements of katago

### ISSUE THREAD

**Issue by luckyangman** [lightvector/KataGo#95]
I am very concerned about the progress of katago. I don't know where to see it. I don't know where to download the latest weight?

**Comment by lightvector** [comment]
I'm working on a new run and a new release. But for the latest release so far:
https://github.com/lightvector/KataGo/releases/tag/v1.2

It contains a link to where to download some neural nets (scroll to the middle). For the full training history of the run in June, which is the latest official run, you can see here. https://d3dndmfyhecmj0.cloudfront.net/g104/index.html

**Comment by petgo3** [comment]
As far as i understood you can watch katabot with some sigificant improvements on ogs live.😁

**Comment by luckyangman** [comment]
Thank you! I've bThank you! I've been following the progress of katago. I already know the link you sent. I want to know the latest development and test the latest weight.

**Comment by lightvector** [comment]
New release! https://github.com/lightvector/KataGo/releases/tag/v1.3

**Comment by luckyangman** [comment]
Thank you!  I've been following at Diacord

**Comment by lightvector** [comment]
I'll continue to update the main README, and post on L19 and LZ Discord as I push out new releases. Maybe a reddit post too as appropriate. Hopefully that's enough ways of broadcasting updates. Thanks!
