### ISSUE TITLE
How to set rules to "twisted cross and eating" for beginner

### ISSUE THREAD

**Issue by BobDLA** [lightvector/KataGo#953]
Is that possible to set the rules to "twisted cross and eating" for beginner?  That is to put each 2 stones as cross inside the center. And the winner will  firstly eat defined stones.
This rule is useful for the beginner to practice.

Is that possible?

Thanks
![go](https://github.com/lightvector/KataGo/assets/3804610/4cd49566-3ee5-4a75-8206-e9da1b7a2a45)

**Comment by lightvector** [comment]
Sorry, there is no way to set the rules to this right now. KataGo has no implementation or training for these rules.
