### ISSUE TITLE
Throwback

### ISSUE THREAD

**Issue by michito744** [lightvector/KataGo#954]
There is a example of cases where a wrong conclusion is reached by choosing a clearly ludicrous progression in 28b, when it could  resolve in 18b.

#796

![2024-06-29](https://github.com/lightvector/KataGo/assets/53891655/9f46a1fa-cf8f-4e3d-9d0c-7268171eb97b)
![2024-06-29 (2)](https://github.com/lightvector/KataGo/assets/53891655/d99c3f56-8204-4db7-aa54-cb22f4561f5c)

This is the effect of 28b's clearly incorrect conclusion reflected in the policy, since KataGo itself discovers the correct conclusion when it is allowed to search deeper in a slightly further phase.

**Comment by lightvector** [comment]
Thanks! As with the previous cases, can you attach an SGF?

**Comment by michito744** [comment]
@lightvector 

I placed the SGF in https://github.com/lightvector/KataGo/issues/796 .
