### ISSUE TITLE
allowResignation affects humanSL strength??

### ISSUE THREAD

**Issue by kaorahi** [lightvector/KataGo#959]
Though I don't have definitive proof yet, it seems that `kata-set-param allowResignation true` makes `kata-search_analyze_cancellable` much stronger in `katago gtp -human-model ...`. Is this possible?? (KataGo 1.15.1)

Here's a command sequence from a game between a human (black) and katago (white). If the (*2) line is included, katago seems to play much more reasonably even with `rank_9k` in the next line. Without (*2), I can easily capture many stones and destroy territories.

I also noticed that if I replace the (*1) line with `rank_20k`, katago plays like a 20k.

```
play b L5
name
name
kata-set-param humanSLProfile rank_1d   <=== (*1)
kata-raw-human-nn 0
time_settings 0 3 1
kata-set-param allowResignation true   <=== (*2)
kata-set-param humanSLProfile rank_9k
kata-search_analyze_cancellable w interval 20 ownership true ownershipStdev true minmoves 30 pvVisits true pvEdgeVisits true movesOwnership true rootInfo true
play w E6
```

I'll send another report if I identify my bug or find clear steps to reproduce the issue.

**Comment by kaorahi** [comment]
I've tried more variations.

(OK = suitable for 9k, NG = too strong for 9k, in my impression)

* Remove `kata-raw-human-nn`: OK
* Insert `name` command just before `kata-search_analyze_cancellable`: OK
* Use `genmove` instead of `kata-search_analyze_cancellable`: NG
* Change the backend from OpenCL to Eigen: OK? (I may need to adjust time_settings further for a fair comparison.)

Here are the policy spectra for games that I found easy (*1 = rank_20k) and hard (*1 = rank_9d), but I haven't been able to reproduced the issue without my GUI...

![easy](https://github.com/user-attachments/assets/82fa9446-e91a-4df2-8acb-4d15a4eac8e5)
![hard](https://github.com/user-attachments/assets/15de6a92-e2ce-4733-92a0-2bd94875fd8d)

**Comment by kaorahi** [comment]
I'll close this issue since things are unclear. Sorry for bothering you.

**Comment by lightvector** [comment]
@kaorahi If there's a major bug in KataGo here with silently using the wrong profile despite having set another one, I'd like to fix it. In these cases you should be able to see from KataGo's own log file (with logAllGTPCommunication=true) what sequence of commands it perceived, to verify that it received all the commands you expected your GUI to send, in the expected order. Additionally, you can try using ranks that are much further separated than 1d and 9k, such as using 9d and 20k, to get a far sharper distinction so that your testing is less unclear.

Do you think there's a bug here?

**Comment by kaorahi** [comment]
No, I'm starting to doubt the issue itself now.

Thank you for caring.

At a glance, KataGo's GTP log looks as expected. I'm beginning to think that the issue of being "too strong" might just be a coincidence or a preconception. I wasn't able to reproduce the issue in matches between the two 9k KataGo engines with the GUI settings that I considered "OK" and "NG". They are running on different machines to avoid any mutual interference.
