### ISSUE TITLE
Do you have a plan to create a GUI?

### ISSUE THREAD

**Issue by 1067511899** [lightvector/KataGo#962]
The GUI you recommand:
katrain:not updated for 1 year,not support human-like play(I tried,but failed,have to log out windows to kill the program).
lizzie:    not updated for nearly 4 years,but support human-like play,not very good to use.
ogatak:  updated recently,but not support human-like play,and quite possible will not support later.
the other two are also old.
so, do you have a plan to create a GUI?make an all in one package?

Thank you .

**Comment by sente361** [comment]
Sabaki is an excellent GUI in which you can attach and run any version of KataGo or any other go engine

**Comment by 1067511899** [comment]
> Sabaki is an excellent GUI in which you can attach and run any version of KataGo or any other go engine

thanks,I will try to use it.

**Comment by 1067511899** [comment]
The sabaki works great,so I close the issue.
