### ISSUE TITLE
katago-v1.15.3-opencl-windows-x64 Server returned error 400: This version of KataGo is not enabled for distributed.

### ISSUE THREAD

**Issue by peterwernerulm** [lightvector/KataGo#968]
Hi, 
distributed training is not working with the latest release. is this to be expected?

ERROR: task loop loop thread failed: Server returned error 400: This version of KataGo is not enabled for distributed. If this exact version was working previously, then changes in the run require a newer version - please update KataGo to the latest version or release. But if this is already the official newest version of KataGo, or you think that not enabling this version is an oversight, please ask server admins to enable the following version hash: cd0ed6c0712088ddb901be68189ba7fa1439a9e7-opencl
---RESPONSE---------------------
Status Code: 400
Header: allow: POST, OPTIONS
Header: CF-Cache-Status: DYNAMIC
Header: CF-RAY: 8af09abf8ccf915c-FRA
Header: Connection: close
Header: content-language: en
Header: Content-Length: 451
Header: Content-Type: application/json
Header: Date: Tue, 06 Aug 2024 17:04:10 GMT
Header: NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Header: Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=fVMM0f8uWsUK/TD20jrhA8A4g6P03IpNeNqm03+4NskA35e6m9YcCyXDQhFscFYDilM8q/5ZCKIRFGWQ7D8oVa06HV0rNnXlEv2hCt9+gKlXCUPEw54xEzpA3YdlhsdhZPOvfw=="}],"group":"cf-nel","max_age":604800}
Header: Server: cloudflare
Header: strict-transport-security: max-age=15552000; includeSubDomains; preload
Header: vary: Accept, Accept-Language
Header: via: 1.1 google
Header: x-content-type-options: nosniff
Header: x-frame-options: DENY
Header: x-xss-protection: 1; mode=block
Body:
{"error":"This version of KataGo is not enabled for distributed. If this exact version was working previously, then changes in the run require a newer version - please update KataGo to the latest version or release. But if this is already the official newest version of KataGo, or you think that not enabling this version is an oversight, please ask server admins to enable the following version hash: cd0ed6c0712088ddb901be68189ba7fa1439a9e7-opencl"}

Regards,
Peter

**Comment by lightvector** [comment]
Thank you for the report! I messed up this step when preparing this release, it should now be fixed and it should work for contribute now. Let me know if you encounter further issues.

**Comment by peterwernerulm** [comment]
it works now. thank you.
