### ISSUE TITLE
Can I access checkpoint files of g170?

### ISSUE THREAD

**Issue by y-ich** [lightvector/KataGo#97]
Congratulations for new v1.3 release!
Many Korean and Japanese players must be glad for Japanese rule feature.

Can I access checkpoint files of g170?
I want to convert the weights for my app and it needs checkpoint files or pb files to do it.
I checked https://d3dndmfyhecmj0.cloudfront.net/g170/index.html but there seems be no checkpoints.

Thank you!

**Comment by lightvector** [comment]
Thanks, I'll get those uploaded within a few days. The same overall format as the ones for g104 are fine?
Note that if you were basing off of the tensorflow python code, the tensorflow code has changed and also upgraded to TF1.5

**Comment by y-ich** [comment]
The same one as g104 is fine for me.
I will update TensorFlow, too.

Thank you!

**Comment by lightvector** [comment]
These should be there now in https://d3dndmfyhecmj0.cloudfront.net/g170/neuralnets/index.html

**Comment by y-ich** [comment]
Thank you!
