### ISSUE TITLE
The Homebrew version is still 1.14.1

### ISSUE THREAD

**Issue by RomanGoEmpire** [lightvector/KataGo#972]
Hi,

Is there a date when version 1.15 or later will be released on Homebrew?
If not, I would try to update it using the tar.gz file, but I'm not sure how to do that.

**Comment by lightvector** [comment]
Thanks, I don't manage the homebrew version but you might be able to reach out to the people who have managed it in the past?

There was a hiccup where v1.15.1 had an issue (https://github.com/lightvector/KataGo/issues/961) that prevented the homebrew build, but as far as I know v1.15.2 and v1.15.3 should not share that issue. So if someone were to skip v1.15.1 and try the build again there's a good chance it works.

**Comment by lightvector** [comment]
(@chenrui333 @dwt)

**Comment by dwt** [comment]
@RomanGoEmpire Give it a go, you should be able to start with `brew edit katago` and go from there.

**Comment by RomanGoEmpire** [comment]
> @RomanGoEmpire Give it a go, you should be able to start with `brew edit katago` and go from there.

Unfortunately, I don't know how to do it. I have tried to edit the katago.rb file of Homebrew and run it, but it didn't work. Probably because I don't know what I'm doing.

**Comment by dwt** [comment]
@RomanGoEmpire Why don't you share what you tried, and what error you are getting? I am quite strapped for time these days, but I might be able to help?

**Comment by RomanGoEmpire** [comment]
@dwt 
I have changed the version of the tar.gz from 1.14.1 to 1.15.3 in `katago.rb`:

```
url "https://github.com/lightvector/KataGo/archive/refs/tags/v1.15.3.tar.gz"
```

The problem I'm facing is that it is still pulling the 1.14.1.gz. I don't know much about this, but it may be because the sha256 checksum needs to be updated as well.

![image](https://github.com/user-attachments/assets/bb941d47-2b15-4169-ae5e-9a0806b3571c)

**Comment by dwt** [comment]
Could you show the changed the recipe as well? The shasums most definitely need to change as well.

**Comment by RomanGoEmpire** [comment]
```rb
class Katago < Formula
  desc "Neural Network Go engine with no human-provided knowledge"
  homepage "https://github.com/lightvector/KataGo"
  url "https://github.com/lightvector/KataGo/archive/refs/tags/v1.15.3.tar.gz"
  sha256 "1a80d7fbd2b3a2684049afe61407d2276f6faf1dd1ca3f886cdb07c170c08e65"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  bottle do
    sha256 cellar: :any,                 arm64_sonoma:   "e2b7df163de75c2d1ffc03a2a3cd8a458fc7108e01b6dfcefbdc6517302cd191"
    sha256 cellar: :any,                 arm64_ventura:  "45ae58e3412cadde15bc46e89225b9b259b44e81f5c0304aa9490872feec5790"
    sha256 cellar: :any,                 arm64_monterey: "218cd81826671227870bb65317bb42d9b7b1742103582f42e30b9b365b7932b6"
    sha256 cellar: :any,                 sonoma:         "30d97d287876702216d97d59e32a3df21c1586134458be069ff52aea48253e02"
    sha256 cellar: :any,                 ventura:        "9df9faaab88d83c002dc0c0733ce4e61d100a40abf72f0f94ce3e03162b09de1"
    sha256 cellar: :any,                 monterey:       "009315fcc87bd9b85391c3d94d4716b9da8dd1b0f2e88b0b8c34a7a8600bd337"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "bf856497d4397a8c46c27d44cbf37fe675f031e25aed4ca43e10d386a2e7fde5"
  end

  depends_on "cmake" => :build
  depends_on "boost"
  depends_on "libzip"
  depends_on macos: :mojave

  resource "20b-network" do
    url "https://github.com/lightvector/KataGo/releases/download/v1.4.5/g170e-b20c256x2-s5303129600-d1228401921.bin.gz", using: :nounzip
    sha256 "7c8a84ed9ee737e9c7e741a08bf242d63db37b648e7f64942f3a8b1b5101e7c2"
  end

  resource "30b-network" do
    url "https://github.com/lightvector/KataGo/releases/download/v1.4.5/g170-b30c320x2-s4824661760-d1229536699.bin.gz", using: :nounzip
    sha256 "1e601446c870228932d44c8ad25fd527cb7dbf0cf13c3536f5c37cff1993fee6"
  end

  resource "40b-network" do
    url "https://github.com/lightvector/KataGo/releases/download/v1.4.5/g170-b40c256x2-s5095420928-d1229425124.bin.gz", using: :nounzip
    sha256 "2b3a78981d2b6b5fae1cf8972e01bf3e48d2b291bc5e52ef41c9b65c53d59a71"
  end

  def install
    cd "cpp" do
      args = %w[-DBUILD_MCTS=1 -DNO_GIT_REVISION=1]
      if OS.mac?
        args << "-DUSE_BACKEND=OPENCL"
        args << "-DCMAKE_OSX_SYSROOT=#{MacOS.sdk_path}"
      end
      system "cmake", ".", *args, *std_cmake_args
      system "make"
      bin.install "katago"
      pkgshare.install "configs"
    end
    pkgshare.install resource("20b-network")
    pkgshare.install resource("30b-network")
    pkgshare.install resource("40b-network")
  end

  test do
    system bin/"katago", "version"
    assert_match(/All tests passed$/, shell_output("#{bin}/katago runtests").strip)
  end
end

```

**Comment by dwt** [comment]
Did you follow the steps [in the FAQ](https://docs.brew.sh/FAQ#can-i-edit-formulae-myself) so you have your own tap of the home-brew repo?

**Comment by RomanGoEmpire** [comment]
Ah not. I just did brew edit katago. I wll take a look

**Comment by dwt** [comment]
I would also hand download the tgz first to generate the shasums for homebrew

**Comment by RomanGoEmpire** [comment]
96a1ef3d12eb30a950164f203b012b5f2257ef796b9bd15163d9ba3b79a32a1b

Worked for me.

**Comment by dwt** [comment]
Come back if you have more questions. I'll try give you some pointers.

Next steps I see are:

1. Update the linked neural networks
2. Create a pull request against homebrew/core

**Comment by RomanGoEmpire** [comment]
i will take a look. Thanks for the help
You might see a new brew version soon 😛

**Comment by RomanGoEmpire** [comment]
just one question.  the neural network links should still work?
What should be changed there?

**Comment by RomanGoEmpire** [comment]
So the changes where merged.

https://github.com/Homebrew/homebrew-core/pull/181381

i assume that it will be available soon :)

**Comment by RomanGoEmpire** [comment]
Was updated :)

**Comment by dwt** [comment]
@RomanGoEmpire The Neural network links probably still work, but I haven't followed the development of KataGo as of late. In the past, almost every release also provided new and better neural networks, so this might be worth a second pull request to update them too if available. @lightvector the networks are currently not he ones from release 1.4.5 - is this worth an update?

```
  resource "20b-network" do
    url "https://github.com/lightvector/KataGo/releases/download/v1.4.5/g170e-b20c256x2-s5303129600-d1228401921.bin.gz", using: :nounzip
    sha256 "7c8a84ed9ee737e9c7e741a08bf242d63db37b648e7f64942f3a8b1b5101e7c2"
  end

  resource "30b-network" do
    url "https://github.com/lightvector/KataGo/releases/download/v1.4.5/g170-b30c320x2-s4824661760-d1229536699.bin.gz", using: :nounzip
    sha256 "1e601446c870228932d44c8ad25fd527cb7dbf0cf13c3536f5c37cff1993fee6"
  end

  resource "40b-network" do
    url "https://github.com/lightvector/KataGo/releases/download/v1.4.5/g170-b40c256x2-s5095420928-d1229425124.bin.gz", using: :nounzip
    sha256 "2b3a78981d2b6b5fae1cf8972e01bf3e48d2b291bc5e52ef41c9b65c53d59a71"
  end
```

**Comment by dwt** [comment]
@RomanGoEmpire Nice work!
