### ISSUE TITLE
Human-like mode may be too strong.

### ISSUE THREAD

**Issue by ArchNew** [lightvector/KataGo#985]
I won against StarMatrix (星阵) semi 7-dan (准7段) by half a point (半目) using human-like configurations and weights, along with one kata1-b18 weight. Two conclusions can be drawn from this result. First, your 5k likely corresponds to an amateur 5-dan level. Second, the human-like mode is still far from being fully usable.

**Comment by HackYardo** [comment]
As far as I know, the bots of Golaxy have many **ladder** and **large-scale war** bugs, I ever won Golaxy-5dan in half of hour when I was 9kyu. So the human-like mode is not that strong actually.

**Comment by ArchNew** [comment]
Your Weiqi skill is considerably strong! May I ask how did you know you were 9kyu back then? Wildfox(野狐围棋) platform?

**Comment by HackYardo** [comment]
It's `Online-Go.com`. The key is the **bugs** of Golaxy bots, not my skill.

**Comment by ArchNew** [comment]
Thanks a lot! The reason that I'm interested in the human-like weights and configurations, especially the 5k config file, is that I want a practice partner at my level who can play with me at my convenience. Clearly, the Online-Go.com is a better alternative.

**Comment by ArchNew** [comment]
Thanks a lot! The reason that I'm interested in the human-like weights and configurations, especially the 5k config file, is that I want a practice partner at my level who can play with me at my convenience. Clearly, the Online-Go.com is a better alternative.
