### ISSUE TITLE
After extensive training, is it possible for the B4C32 model to reach superhuman world champion level?

### ISSUE THREAD

**Issue by Garbage123King** [lightvector/KataGo#999]
I notice B4C32 has very less params num, only 80,000.

I ran for 6 days, use R5 3600 and RX5700 (OpenCL + ROCm), get s24256896-d3517290, I tested it with some AI. found that it is weak.

any hardware upgrade recommand? CPU or GPU?

**Comment by OmnipotentEntity** [comment]
B4C32 is far too small to play effectively, unfortunately.

**Comment by Garbage123King** [comment]
> B4C32 is far too small to play effectively, unfortunately.

and B6C96 is a much better choice, right?

**Comment by lightvector** [comment]
Very roughly, with reasonable amounts of compute and playouts:
b6c96 is capable of reaching mid to strong amateur dan level, but 6 blocks is too small to view the whole board at once so it will have serious flaws in perceiving large dragons
b10c128 can reach somewhere around human professional level, but also 10 blocks is only barely enough to see the whole board so it will also have flaws in perceiving large dragons, although not as bad as b6c96
b15c192 can reach superhuman level in most normal positions but will be far weaker than other AI bots
b20c256 is the smaller of the two sizes that AlphaZero used and reaches much stronger than b15c192 
b10c384nbt (new "nbt" architecture) should be similar speed but better than b20c256 
b40c256 is the larger of the two sizes that AlphaGoZero used
b18c384nbt should (new "nbt" architecture) should be similar speed but better than b40c256 
b28c512nbt is KataGo's current network and is also the strongest for most purposes even taking into account that the larger neural net is slower and makes the search less deep.

It's currently unknown if going to an even larger size would be even better or if the additional compute cost would result in a weaker bot.
